News UAT/force-app/main/default/objects/Contact/fields/NewsXtend_My_Account_Access__c.field-meta.xml
<CustomField>
    <fullName>NewsXtend_My_Account_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to enable access to the My Account Community</description>
    <inlineHelpText>Used to enable access to the My Account Community</inlineHelpText>
    <label>NewsXtend My Account Access</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Contact_Role__c/Contact_Role__c.object-meta.xml
<CustomObject>
    <description>Created to replace the Account/ Contact Roles object.
Standard object does not allow adding additional fields or help texts.</description>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CTC{00000000}</displayFormat>
        <label>Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Contact_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>•	Agency Contact – e.g. Media Agency Contact, Creative Agency Contact, PR Agency Contact
•	Is Employed by Multiple Businesses – is an employee of more than one business e.g. Employed Mon-Fri by Telstra and on weekends/ after-hours runs own accountancy firm
•	Other Association – Consultant for the Business e.g. Graphic Designer, Financial Services etc</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency Contact</fullName>
            </value>
            <value>
                <fullName>Other Association</fullName>
            </value>
            <value>
                <fullName>Is Employed by Multiple Businesses</fullName>
            </value>
            <value>
                <fullName>NewsXtend Agency</fullName>
            </value>
            <value>
                <fullName>NewsXtend Customer - Mgmt</fullName>
            </value>
            <value>
                <fullName>NewsXtend Customer - Non Mgmt</fullName>
            </value>
            <value>
                <fullName>NewsXtend Web Developer</fullName>
            </value>
            <value>
                <fullName>NewsXtend NRM Sales Rep</fullName>
            </value>
            <value>
                <fullName>NewsXtend CNG Sales Rep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Role_Access__c/Customer_Role_Access__c.object-meta.xml
<CustomObject>
    <description>Defines the Access granted to community users with a contact role to My Account</description>
    <label>Customer Role Access</label>
    <nameField>
        <displayFormat>CRA-{0000}</displayFormat>
        <label>Customer Role Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Role Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Customer_Role_Access__c/fields/Account_Access__c.field-meta.xml
<CustomField>
    <fullName>Account_Access__c</fullName>
    <description>Level of access granted to Contact for the Account Object</description>
    <inlineHelpText>Level of access granted to Contact for the Account Object</inlineHelpText>
    <label>Account Access</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Public Read</fullName>
            </value>
            <value>
                <fullName>Public Read/Write</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Role_Access__c/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <description>Role corresponding to Contact Role in the Contact Roles Object</description>
    <inlineHelpText>Select role corresponding to Contact Role in the Contact Roles Object</inlineHelpText>
    <label>Contact Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NewsXtend Agency</fullName>
            </value>
            <value>
                <fullName>NewsXtend Customer - Mgmt</fullName>
            </value>
            <value>
                <fullName>NewsXtend Customer - Non Mgmt</fullName>
            </value>
            <value>
                <fullName>NewsXtend Web Developer</fullName>
            </value>
            <value>
                <fullName>NewsXtend NRM Sales Rep</fullName>
            </value>
            <value>
                <fullName>NewsXtend CNG Sales Rep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/Customer_Task__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Customer Activity</label>
    <nameField>
        <displayFormat>CAN-{YYMMDD}-{0000}</displayFormat>
        <label>Customer Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will contain the reference of Product Order for Approve Display Ad Proof Task</description>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Payer_Account__c.field-meta.xml
<CustomField>
    <fullName>Payer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payer Account</relationshipLabel>
    <relationshipName>Opportunities_Payer</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Product Orders</relationshipLabel>
    <relationshipName>Product_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/SocialCampaign__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Proof</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proofs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/SocialCampaign__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipName>Social_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/classes/NXX2_ShareRecordUtilityTest.cls
@isTest
public class NXX2_ShareRecordUtilityTest{
    public static testMethod void testTriggerHandler() {
        NXX2_TestUtility.disableAllTriggerDuringTesting();
        User currentUser = TestDataFactory.createUser('System Administrator','Test','Demo',null,false,false);
        System.runAs(currentUser){
            Test.startTest();
            UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
            Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
            User portalAccountOwner1 = new User(
                UserRoleId = portalRole.Id,
                ProfileId = profile1.Id,
                Username = System.now().millisecond() + 'test2@test.com',
                Alias = 'batman',
                Email='test@testSalesforce.com',
                EmailEncodingKey='UTF-8',
                Firstname='Bruce',
                Lastname='Wayne',
                LanguageLocaleKey='en_US',
                LocaleSidKey='en_US',
                TimeZoneSidKey='America/Chicago'
            );
            insert portalAccountOwner1;
            List<Account> accounts = TestDataFactory.createAccounts(3,false);
            accounts[0].ownerId = portalAccountOwner1.Id;
            accounts[1].ownerId = portalAccountOwner1.Id;
            accounts[2].ownerId = portalAccountOwner1.Id;
            insert accounts;
            List<Contact> contacts = TestDataFactory.createContacts(2,accounts[0]);
            contacts[0].Email = 'NXX2Test123@News.com';
            contacts[0].NewsXtend_My_Account_Access__c = true;
            insert contacts;
            List<Opportunity> opportunities = TestDataFactory.createOpportunities_withContact(2,Test.getStandardPricebookId(),accounts[0],contacts[0]);
            opportunities[0].Payer_Account__c = accounts[1].Id;
            opportunities[1].Payer_Account__c = accounts[2].Id;
            insert opportunities;
            List<String> roles = new List<String>();
            Schema.DescribeFieldResult fieldResult = Contact_Role__c.Role__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for( Schema.PicklistEntry f : ple){
                roles.add(f.getValue());
            }       
            List<Customer_Role_Access__c> roleAccess = NXX2_TestUtility.createCustomerRoleAccess(roles);
            roleAccess[1].Account_Access__c = 'Public Read/Write';
            insert roleAccess;
            List<Contact_Role__c> contactRoles = NXX2_TestUtility.createContactRole(contacts[0].Id,accounts,roleAccess[0].Contact_Role__c);
            Order__c campaignOrder = NXX2_TestUtility.createCampaignOrder(opportunities[0].Id, contacts[0].Id, accounts[0].Id);
            List<Product_Order__c> pos = NXX2_TestUtility.createProductOrder(1, campaignOrder.Id);
            SocialCampaign__c proof = NXX2_TestUtility.createProof(pos[0].Id);
            List<Customer_Task__c> activityForCO = NXX2_TestUtility.createCustomerActivityForCampaignOrder(new List<Order__c>{campaignOrder});
            List<Customer_Task__c> activityForPO = NXX2_TestUtility.createCustomerActivityForProductOrder(pos);
            List<Customer_Task__c> activityForProof = NXX2_TestUtility.createCustomerActivity(new List<SocialCampaign__c>{proof});
            
            Test.stopTest();
            NXX2_Contact_Role_TriggerHandler handler = new  NXX2_Contact_Role_TriggerHandler();
            Map<Id, Contact_Role__c> newItems = new Map<Id, Contact_Role__c>();
            Map<Id, Contact_Role__c> oldItems = new Map<Id, Contact_Role__c>();
            newItems.put(contactRoles[0].Id, contactRoles[0]);
            oldItems.put(contactRoles[0].Id, contactRoles[1]);
            handler.AfterDelete(oldItems);
            handler.AfterInsert(newItems);
            handler.AfterUpdate(newItems, oldItems);
            handler.BeforeInsert(newItems.values());
            
            NXX2_AccountTriggerHandler handler1 = new  NXX2_AccountTriggerHandler();
            Map<Id, Account> newItems1 = new Map<Id, Account>();
            Map<Id, Account> oldItems1 = new Map<Id, Account>();
            newItems1.put(accounts[0].Id, accounts[0]);
            oldItems1.put(accounts[0].Id, accounts[2]);
            handler1.AfterUpdate(newItems1, oldItems1);
            
            NXX2_Contact_TriggerHandler handler2 = new NXX2_Contact_TriggerHandler();
            Map<Id, Contact> newItems2 = new Map<Id, Contact>();
            Map<Id, Contact> oldItems2 = new Map<Id, Contact>();
            newItems2.put(contacts[0].Id, contacts[0]);
            oldItems2.put(contacts[0].Id, contacts[1]);
            newItems2.put(contacts[1].Id, contacts[1]);
            oldItems2.put(contacts[1].Id, contacts[0]);
            handler2.AfterUpdate(newItems2, oldItems2);
            NXX2_ShareRecordUtility nXX2_ShareRecordUtility =  new NXX2_ShareRecordUtility(new Set<Id>{contacts[0].Id,contacts[1].Id},newItems2);
        	System.enqueueJob(nXX2_ShareRecordUtility);
            
            Map<Id, Contact> contactItems = new Map<Id, Contact>();
            contactItems.put(contacts[0].Id, contacts[0]);
            NXX2_ShareRecordUtility utility = new NXX2_ShareRecordUtility(new Set<Id>{contacts[0].Id},contactItems);
            List<AccountShare> accountShareList = [SELECT Id From AccountShare];
            List<Customer_Task__Share> customerTaskShareList = [SELECT Id From Customer_Task__Share];
            List<SocialCampaign__Share> socialCampaignShareList = [SELECT Id From SocialCampaign__Share];
            
            utility.deleteAccountShareRecords(accountShareList);
            utility.deleteCustomerTaskShareRecords(customerTaskShareList);
            utility.deleteProofShareRecords(socialCampaignShareList);
        }
    }
}