News UAT/force-app/main/default/objects/Briefing_Form__c/Briefing_Form__c.object-meta.xml
<CustomObject>
    <label>Briefing Form</label>
    <nameField>
        <label>Briefing Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Briefing Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Briefing_Form__c/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <label>Campaign</label>
</RecordType>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Briefing_Form__c.field-meta.xml
<CustomField>
    <fullName>Briefing_Form__c</fullName>
    <formula>Order__r.Briefing_Form__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Briefing Form</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>Order__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/View_Briefing_Form_ctrl.cls
public class View_Briefing_Form_ctrl {
    
    public View_Briefing_Form_ctrl(ApexPages.StandardController controller) {
    }
    
    Public pagereference View_Briefing_mthd(){
        Id ProductOrderId =  ApexPages.currentPage().getParameters().get('id');
        Product_order__c Porder = [Select Briefing_Form__c, Opportunity__c from Product_order__c where id =: ProductOrderId] ;
        id Briefingform = Porder.Briefing_Form__c;
        id opportuid = Porder.Opportunity__c;
        If (Porder.Briefing_Form__c == null ){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.info, 'Campaign Order does not have a Briefing Form created'));
            return null;
            
        }
        else{
            
            string URL = '/apex/CS_ViewBriefingForm?bfId='+Briefingform+ '&oppId='+opportuid ;   
            
            pagereference p = new pagereference(URL);
            p.setRedirect(true);
            return p;              
        }
        
    }
}