News UAT/force-app/main/default/objects/Activity/fields/Campaign_Order__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>@NXRIII-75</description>
    <label>Campaign Order Name</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Activity/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>@NXRIII-75</description>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Contact_Role__c/Contact_Role__c.object-meta.xml
<CustomObject>
    <description>Created to replace the Account/ Contact Roles object.
Standard object does not allow adding additional fields or help texts.</description>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CTC{00000000}</displayFormat>
        <label>Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Roles</relationshipLabel>
    <relationshipName>Contact_Roles_Contact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Contact_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>•	Agency Contact – e.g. Media Agency Contact, Creative Agency Contact, PR Agency Contact
•	Is Employed by Multiple Businesses – is an employee of more than one business e.g. Employed Mon-Fri by Telstra and on weekends/ after-hours runs own accountancy firm
•	Other Association – Consultant for the Business e.g. Graphic Designer, Financial Services etc</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency Contact</fullName>
            </value>
            <value>
                <fullName>Other Association</fullName>
            </value>
            <value>
                <fullName>Is Employed by Multiple Businesses</fullName>
            </value>
            <value>
                <fullName>NewsXtend Agency</fullName>
            </value>
            <value>
                <fullName>NewsXtend Customer - Mgmt</fullName>
            </value>
            <value>
                <fullName>NewsXtend Customer - Non Mgmt</fullName>
            </value>
            <value>
                <fullName>NewsXtend Web Developer</fullName>
            </value>
            <value>
                <fullName>NewsXtend NRM Sales Rep</fullName>
            </value>
            <value>
                <fullName>NewsXtend CNG Sales Rep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Role_Access__c/Customer_Role_Access__c.object-meta.xml
<CustomObject>
    <description>Defines the Access granted to community users with a contact role to My Account</description>
    <label>Customer Role Access</label>
    <nameField>
        <displayFormat>CRA-{0000}</displayFormat>
        <label>Customer Role Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Role Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Customer_Role_Access__c/fields/Account_Access__c.field-meta.xml
<CustomField>
    <fullName>Account_Access__c</fullName>
    <description>Level of access granted to Contact for the Account Object</description>
    <inlineHelpText>Level of access granted to Contact for the Account Object</inlineHelpText>
    <label>Account Access</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Public Read</fullName>
            </value>
            <value>
                <fullName>Public Read/Write</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Role_Access__c/fields/Community_User_Profile__c.field-meta.xml
<CustomField>
    <fullName>Community_User_Profile__c</fullName>
    <description>Profile to be used for the corresponding Contact Role</description>
    <inlineHelpText>Profile to be used for the corresponding Contact Role</inlineHelpText>
    <label>Community User Profile</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NewsXtend My Account Community Read Only</fullName>
            </value>
            <value>
                <fullName>NewsXtend My Account Community Read Only Login</fullName>
            </value>
            <value>
                <fullName>Partner Community Login Read Only</fullName>
                <isActive>false</isActive>
                <label>Partner Community Login Read Only</label>
            </value>
            <value>
                <fullName>Partner Community User Custom</fullName>
                <isActive>false</isActive>
                <label>Partner Community User Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Role_Access__c/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <description>Role corresponding to Contact Role in the Contact Roles Object</description>
    <inlineHelpText>Select role corresponding to Contact Role in the Contact Roles Object</inlineHelpText>
    <label>Contact Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NewsXtend Agency</fullName>
            </value>
            <value>
                <fullName>NewsXtend Customer - Mgmt</fullName>
            </value>
            <value>
                <fullName>NewsXtend Customer - Non Mgmt</fullName>
            </value>
            <value>
                <fullName>NewsXtend Web Developer</fullName>
            </value>
            <value>
                <fullName>NewsXtend NRM Sales Rep</fullName>
            </value>
            <value>
                <fullName>NewsXtend CNG Sales Rep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Role_Access__c/fields/Customer_Activity_Access__c.field-meta.xml
<CustomField>
    <fullName>Customer_Activity_Access__c</fullName>
    <description>Level of access granted to Contact for the Customer Object</description>
    <inlineHelpText>Level of access granted to Contact for the Customer Object</inlineHelpText>
    <label>Customer Activity Access</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Public Read</fullName>
            </value>
            <value>
                <fullName>Public Read/Write</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Role_Access__c/fields/Proof_Access__c.field-meta.xml
<CustomField>
    <fullName>Proof_Access__c</fullName>
    <description>Level of access granted to Contact for the Proof Object</description>
    <inlineHelpText>Level of access granted to Contact for the Proof Object</inlineHelpText>
    <label>Proof Access</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Public Read</fullName>
            </value>
            <value>
                <fullName>Public Read/Write</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/Customer_Task__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Customer Activity</label>
    <nameField>
        <displayFormat>CAN-{YYMMDD}-{0000}</displayFormat>
        <label>Customer Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Campaign_Order__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will contain the reference of Product Order for Approve Display Ad Proof Task</description>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Social_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Social_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This relationship to link social campaign to a customer task to get &quot;Campaign Tasks&quot;</description>
    <label>Social Campaign</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_TriggerSettings__c/NXX2_TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This will be used to disable trigger</description>
    <label>NXX2 TriggerSettings</label>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_TriggerSettings__c/fields/CustomerRoleAccessTriggerDisabled__c.field-meta.xml
<CustomField>
    <fullName>CustomerRoleAccessTriggerDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CustomerRoleAccessTriggerDisabled</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>Order__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Product Orders</relationshipLabel>
    <relationshipName>Product_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <label>Other</label>
</RecordType>

News UAT/force-app/main/default/objects/SocialCampaign__c/SocialCampaign__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Proof</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proofs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/SocialCampaign__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipName>Social_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/fields/Visible_To_Customer__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be used to share record with customer</description>
    <label>Visible To Customer</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/classes/NXX2_CustomerRoleAccessTriggerHandler.cls
/**
* @author       Kamal Sharma
* @date         2019-01-02
* @className	NXX2_CustomerRoleAccessTriggerHandler
* @description  This is the handler class for proof trigger.
*/
public class NXX2_CustomerRoleAccessTriggerHandler extends NXX2_TriggerHandler_Utility implements NXX2_TriggerHandler
{
    // Allows unit tests (or other code) to disable this trigger for the transaction
    public static Boolean TriggerDisabled = false;
 
    /**
    * @author       Kamal Sharma
    * @date         2019-01-02
    * @description  Checks to see if the trigger has been disabled either by custom setting or by running code
    * @param        NA
    * @return       Boolean
    */
    public Boolean IsDisabled()
    {
        NXX2_TriggerSettings__c triggerSettings = NXX2_TriggerSettings__c.getInstance();
        if (triggerSettings.CustomerRoleAccessTriggerDisabled__c)
            return true;
        else
            return TriggerDisabled;
    }
 
    public void BeforeInsert(List<SObject> newItems) {}
 
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {}
 
    public void BeforeDelete(Map<Id, SObject> oldItems) {}
    
    /**
    * @author       Kamal Sharma
    * @date         2019-01-02
    * @description  This method will initiate sharing of records with portal users 
    * 				on insertion of new customer role access record.
    * @param        Map<Id, SObject> newItems
    * @return       void
    */
    public void AfterInsert(Map<Id, SObject> newItems) {
        Customer_Role_Access__c newCustomerRoleAccess;
        //This variable is declaired in NXX2_TriggerHandler_Utility class
    	customerRoleAccessMap = new Map<String,Customer_Role_Access__c>();
        //This variable is declaired in NXX2_TriggerHandler_Utility class
        contactRoleAccessCommunityUserProfiles = new Set<String>();
        for(Id customerRoleAccessId : newItems.keySet()){
            newCustomerRoleAccess = ((Map<Id, Customer_Role_Access__c>)newItems).get(customerRoleAccessId);
            if(newCustomerRoleAccess.Account_Access__c != 'None'){
                customerRoleAccessMap.put(newCustomerRoleAccess.Contact_Role__c,newCustomerRoleAccess);
                contactRoleAccessCommunityUserProfiles.add(newCustomerRoleAccess.Community_User_Profile__c);
            }
        }
        //This method is declaired in NXX2_TriggerHandler_Utility class
        //This method will populate all contact roles with the role related to new customer role access record.
        populateContactRoleDataForTheRoles(customerRoleAccessMap.keySet());
        //This method is declaired in NXX2_TriggerHandler_Utility class
        //This method will populate all users for the contacts related to contact roles fetched earlier.
        populateContactUserMap();
        //This method will start sharing of records for new customer role access.
        accountSharingOnCustomerRoleAccessChange();
    }
    
 	/**
    * @author       Kamal Sharma
    * @date         2019-01-02
    * @description  This method will initiate sharing of records with portal users 
    * 				on updation of customer role access record.
    * @param        Map<Id, SObject> newItems, Map<Id, SObject> oldItems
    * @return       void
    */
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        Customer_Role_Access__c newCustomerRoleAccess;
        Customer_Role_Access__c oldCustomerRoleAccess;
        //This variable is declaired in NXX2_TriggerHandler_Utility class
    	customerRoleAccessMap = new Map<String,Customer_Role_Access__c>();
        //This variable is declaired in NXX2_TriggerHandler_Utility class
        contactRoleAccessCommunityUserProfiles = new Set<String>();
        for(Id customerRoleAccessId : newItems.keySet()){
            newCustomerRoleAccess = ((Map<Id, Customer_Role_Access__c>)newItems).get(customerRoleAccessId);
            oldCustomerRoleAccess = ((Map<Id, Customer_Role_Access__c>)oldItems).get(customerRoleAccessId);
            if(newCustomerRoleAccess.Account_Access__c != newCustomerRoleAccess.Account_Access__c ||
               newCustomerRoleAccess.Proof_Access__c != newCustomerRoleAccess.Proof_Access__c ||
               newCustomerRoleAccess.Customer_Activity_Access__c != newCustomerRoleAccess.Customer_Activity_Access__c){
                customerRoleAccessMap.put(newCustomerRoleAccess.Contact_Role__c,newCustomerRoleAccess);
            	contactRoleAccessCommunityUserProfiles.add(newCustomerRoleAccess.Community_User_Profile__c);
            }
        }
        //This method is declaired in NXX2_TriggerHandler_Utility class
        //This method will populate all contact roles with the role related to new customer role access record.
        populateContactRoleDataForTheRoles(customerRoleAccessMap.keySet());
        //This method is declaired in NXX2_TriggerHandler_Utility class
        //This method will populate all users for the contacts related to contact roles fetched earlier.
        populateContactUserMap();
        //This method will delete all existing share records for the updated customer role access
        deleteExisitngSharing();
        //This method will start sharing of records for new customer role access.
        accountSharingOnCustomerRoleAccessChange();
    }
 
    public void AfterDelete(Map<Id, SObject> oldItems) {}
 
    public void AfterUndelete(Map<Id, SObject> oldItems) {}
    /**
    * @author       Kamal Sharma
    * @date         2019-01-02
    * @description  This method will share the accounts,proofs and customer activities with related users.
    * @param        NA
    * @return       void
    */
    private void accountSharingOnCustomerRoleAccessChange(){
        try{
            //This method is declaired in NXX2_TriggerHandler_Utility class
            //Get opportunties related to contact roles
            Set<Id> opportunityIds = populateAccountsToPrimaryAccountsMap(null,accountContactRoleMap.keySet());
            //Remove contacts having active portal user already.
            contactIds.removeAll(contactUserMap.keySet());
            //This method is declaired in NXX2_TriggerHandler_Utility class
            //Create portal user for rest of the contacts.
            createCommunityUserForContacts();
            //Populate Account,Proof and Customer Activity share list to insert
            initializeSharing(opportunityIds,true);
            if(accountShareList.size() > 0){
            	insert accountShareList;
            }
            if(proofShareList.size() > 0){
            	insert proofShareList;
            }
            if(customerActivityShareList.size() > 0){
            	insert customerActivityShareList;
            }
        }catch(Exception e){
            system.debug('Class NXX2_ShareRecordUtility, Method recalculateAccountSharing');
            system.debug('Exception: '+ e.getStackTraceString());
        }
    }
    /**
    * @author       Kamal Sharma
    * @date         2019-01-02
    * @description  This method will share the accounts,proofs and customer activities with related users.
    * @param        Set<Id> opportunityIds,Boolean updateAll
    * @return       void
    */
    private void initializeSharing(Set<Id> opportunityIds,Boolean updateAll){
        Map<Id,SocialCampaign__c> proofs;
        Map<Id,Customer_Task__c> customerActivities;
        if(updateAll){
            proofs = new Map<Id,SocialCampaign__c>([SELECT Id FROM SocialCampaign__c 
                      WHERE Product_Order__r.Order__r.Opportunity__c IN : opportunityIds AND Visible_To_Customer__c = true]);
            customerActivities = new Map<Id,Customer_Task__c>([SELECT Id FROM Customer_Task__c WHERE Product_Order__r.Order__r.Opportunity__c IN :opportunityIds 
                                  OR Campaign_Order__r.Opportunity__c IN :opportunityIds 
                                  OR Social_Campaign__r.Product_Order__r.Order__r.Opportunity__c IN :opportunityIds]);
        }
        //This variable belongs to NXX2_TriggerHandler_Utility class
        accountShareList = new List<AccountShare>();
        //This variable belongs to NXX2_TriggerHandler_Utility class
        proofShareList = new List<SocialCampaign__Share>();
        //This variable belongs to NXX2_TriggerHandler_Utility class
        customerActivityShareList = new List<Customer_Task__Share>();
        for(Id accountId : accountContactRoleMap.keySet()){
            List<Contact_Role__c> contactRoles = accountContactRoleMap.get(accountId);
            for(Contact_Role__c contactRole : contactRoles){
                Customer_Role_Access__c customerRoleAccess = customerRoleAccessMap.get(contactRole.Role__c);
                if(customerRoleAccess.Account_Access__c != 'None'){
                    //This method belongs to NXX2_TriggerHandler_Utility Class and will create account share record
                    populateAccountShareList(contactRole.Contact__c,accountId,customerRoleAccess);
                    if(updateAll && customerRoleAccess.Proof_Access__c != 'None'){
                        //This method belongs to NXX2_TriggerHandler_Utility Class and will create account share record
                        populateProofShareList(contactRole.Contact__c,proofs.keySet(),customerRoleAccess);
                    }
                    if(updateAll && customerRoleAccess.Customer_Activity_Access__c != 'None'){
                    	//This method belongs to NXX2_TriggerHandler_Utility Class 
                        //and will create customer activity share record
                        populateCustomerActivityShareList(contactRole.Contact__c,customerActivities.keySet(),customerRoleAccess);
                    }
                }
            }
        }
    }
    /**
    * @author       Kamal Sharma
    * @date         2019-01-02
    * @description  This method will delete existing share records related portal users
    * @param        NA
    * @return       void
    */
    private void deleteExisitngSharing(){
        List<AccountShare> accountShareList = [SELECT Id FROM AccountShare 
                                               WHERE UserOrGroupId IN :userIds 
                                               AND RowCause = 'Manual'];
        List<SocialCampaign__Share> proofShareList = [SELECT Id FROM SocialCampaign__Share 
                                               WHERE UserOrGroupId IN :userIds 
                                               AND RowCause = 'Manual'];
        List<Customer_Task__Share> customeActivityShareList = [SELECT Id FROM Customer_Task__Share 
                                               WHERE UserOrGroupId IN :userIds 
                                               AND RowCause = 'Manual'];
        delete accountShareList;
        delete proofShareList;
        delete customeActivityShareList;
    }
}