News UAT/force-app/main/default/objects/Activity/fields/Campaign_Order__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>@NXRIII-75</description>
    <label>Campaign Order Name</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Activity/fields/CSPOFA__Orchestration_Step__c.field-meta.xml
<CustomField>
    <fullName>CSPOFA__Orchestration_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orchestration Step</label>
    <referenceTo>CSPOFA__Orchestration_Step__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Activity/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>@NXRIII-75</description>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Contact_Role__c/Contact_Role__c.object-meta.xml
<CustomObject>
    <description>Created to replace the Account/ Contact Roles object.
Standard object does not allow adding additional fields or help texts.</description>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CTC{00000000}</displayFormat>
        <label>Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Roles</relationshipLabel>
    <relationshipName>Contact_Roles_Contact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Contact_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>•	Agency Contact – e.g. Media Agency Contact, Creative Agency Contact, PR Agency Contact
•	Is Employed by Multiple Businesses – is an employee of more than one business e.g. Employed Mon-Fri by Telstra and on weekends/ after-hours runs own accountancy firm
•	Other Association – Consultant for the Business e.g. Graphic Designer, Financial Services etc</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency Contact</fullName>
            </value>
            <value>
                <fullName>Other Association</fullName>
            </value>
            <value>
                <fullName>Is Employed by Multiple Businesses</fullName>
            </value>
            <value>
                <fullName>NewsXtend Agency</fullName>
            </value>
            <value>
                <fullName>NewsXtend Customer - Mgmt</fullName>
            </value>
            <value>
                <fullName>NewsXtend Customer - Non Mgmt</fullName>
            </value>
            <value>
                <fullName>NewsXtend Web Developer</fullName>
            </value>
            <value>
                <fullName>NewsXtend NRM Sales Rep</fullName>
            </value>
            <value>
                <fullName>NewsXtend CNG Sales Rep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Role_Access__c/Customer_Role_Access__c.object-meta.xml
<CustomObject>
    <description>Defines the Access granted to community users with a contact role to My Account</description>
    <label>Customer Role Access</label>
    <nameField>
        <displayFormat>CRA-{0000}</displayFormat>
        <label>Customer Role Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Role Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Customer_Role_Access__c/fields/Account_Access__c.field-meta.xml
<CustomField>
    <fullName>Account_Access__c</fullName>
    <description>Level of access granted to Contact for the Account Object</description>
    <inlineHelpText>Level of access granted to Contact for the Account Object</inlineHelpText>
    <label>Account Access</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Public Read</fullName>
            </value>
            <value>
                <fullName>Public Read/Write</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Role_Access__c/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <description>Role corresponding to Contact Role in the Contact Roles Object</description>
    <inlineHelpText>Select role corresponding to Contact Role in the Contact Roles Object</inlineHelpText>
    <label>Contact Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NewsXtend Agency</fullName>
            </value>
            <value>
                <fullName>NewsXtend Customer - Mgmt</fullName>
            </value>
            <value>
                <fullName>NewsXtend Customer - Non Mgmt</fullName>
            </value>
            <value>
                <fullName>NewsXtend Web Developer</fullName>
            </value>
            <value>
                <fullName>NewsXtend NRM Sales Rep</fullName>
            </value>
            <value>
                <fullName>NewsXtend CNG Sales Rep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Role_Access__c/fields/Customer_Activity_Access__c.field-meta.xml
<CustomField>
    <fullName>Customer_Activity_Access__c</fullName>
    <description>Level of access granted to Contact for the Customer Object</description>
    <inlineHelpText>Level of access granted to Contact for the Customer Object</inlineHelpText>
    <label>Customer Activity Access</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Public Read</fullName>
            </value>
            <value>
                <fullName>Public Read/Write</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/Customer_Task__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Customer Activity</label>
    <nameField>
        <displayFormat>CAN-{YYMMDD}-{0000}</displayFormat>
        <label>Customer Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Campaign_Order__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will contain the reference of Product Order for Approve Display Ad Proof Task</description>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Social_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Social_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This relationship to link social campaign to a customer task to get &quot;Campaign Tasks&quot;</description>
    <label>Social Campaign</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>1.This will capture the Task Type.</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upload Creative Assets</fullName>
            </value>
            <value>
                <fullName>Place GTM on Website</fullName>
            </value>
            <value>
                <fullName>Extend Access to Google Analytics</fullName>
            </value>
            <value>
                <fullName>Approve and Review Your Display Ads</fullName>
            </value>
            <value>
                <fullName>Approve and Review Your Facebook Ads</fullName>
            </value>
            <value>
                <fullName>Grant News Xtend Facebook Access</fullName>
            </value>
            <value>
                <fullName>Approve and Review Your Landing Page</fullName>
            </value>
            <value>
                <fullName>Approve Display Ad Proof</fullName>
                <isActive>false</isActive>
                <label>Approve Display Ad Proof</label>
            </value>
            <value>
                <fullName>Approve Facebook Ads Proof</fullName>
                <isActive>false</isActive>
                <label>Approve Facebook Ads Proof</label>
            </value>
            <value>
                <fullName>Generic Task</fullName>
                <isActive>false</isActive>
                <label>Generic Task</label>
            </value>
            <value>
                <fullName>Google Tag Manager</fullName>
                <isActive>false</isActive>
                <label>Google Tag Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_TriggerSettings__c/NXX2_TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This will be used to disable trigger</description>
    <label>NXX2 TriggerSettings</label>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_TriggerSettings__c/fields/CustomerActivityTriggerDisabled__c.field-meta.xml
<CustomField>
    <fullName>CustomerActivityTriggerDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CustomerActivityTriggerDisabled</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>Order__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Product Orders</relationshipLabel>
    <relationshipName>Product_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicate the type of campaign order line item</description>
    <inlineHelpText>Indicate the type of campaign order line item</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Unchanged</fullName>
            </value>
            <value>
                <fullName>Renew</fullName>
            </value>
            <value>
                <fullName>Unchanged (Fulfilled)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/recordTypes/Content.recordType-meta.xml
<RecordType>
    <fullName>Content</fullName>
    <active>true</active>
    <label>Content</label>
</RecordType>

News UAT/force-app/main/default/objects/Product_Order__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <label>Other</label>
</RecordType>

News UAT/force-app/main/default/objects/SocialCampaign__c/SocialCampaign__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Proof</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proofs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/SocialCampaign__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipName>Social_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/recordTypes/Display.recordType-meta.xml
<RecordType>
    <fullName>Display</fullName>
    <active>true</active>
    <description>Record for display ad</description>
    <label>Display</label>
</RecordType>

News UAT/force-app/main/default/classes/NXX2_CustomerActivityTriggerHandler.cls
/**
* @author       Kamal Sharma
* @date         2019-01-02
* @className	NXX2_CustomerActivityTriggerHandler
* @description  This is the handler class for customer activity trigger.
*/
public class NXX2_CustomerActivityTriggerHandler extends NXX2_TriggerHandler_Utility implements NXX2_TriggerHandler
{
    // Allows unit tests (or other code) to disable this trigger for the transaction
    public static Boolean TriggerDisabled = false;
 
    /**
    * @author       Kamal Sharma
    * @date         2019-01-02
    * @description  Checks to see if the trigger has been disabled either by custom setting or by running code
    * @param        NA
    * @return       Boolean
    */
    public Boolean IsDisabled()
    {
        NXX2_TriggerSettings__c triggerSettings = NXX2_TriggerSettings__c.getInstance();
        if (triggerSettings.CustomerActivityTriggerDisabled__c){
            return true;
        }else{
            return TriggerDisabled;
        }
    }
 
    public void BeforeInsert(List<SObject> newItems){}
 
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {}
 
    public void BeforeDelete(Map<Id, SObject> oldItems) {}
 	/**
    * @author       Kamal Sharma
    * @date         2019-01-02
    * @description  This method will initialize two process on new customer activity record insertion:
    * 				1.	Share customer activity with portal user based on configuration in customer role access
    * 				2.	Update proof status or close perticular task based on inserted customer activity type
    * @param        Map<Id, SObject> newItems
    * @return       void
    */
    public void AfterInsert(Map<Id, SObject> newItems) {
        List<Customer_Task__c> customeActivities = [SELECT Campaign_Order__r.Opportunity__c,Product_Order__c,Social_Campaign__r.Product_Order__c,Type__c,Social_Campaign__c,
                                                  Product_Order__r.Order__r.Opportunity__c,
                                                  Social_Campaign__r.Product_Order__r.Order__r.Opportunity__c 
                                                  FROM Customer_Task__c WHERE Id IN :newItems.keySet()];
        Map<Id,Id> customerActivityToOpportunityMap = new Map<Id,Id>();
        for(Customer_Task__c customerActivity : customeActivities){
            if(customerActivity.Campaign_Order__r.Opportunity__c != null){
            	customerActivityToOpportunityMap.put(customerActivity.Id, customerActivity.Campaign_Order__r.Opportunity__c);
            }else if(customerActivity.Product_Order__r.Order__r.Opportunity__c != null){
            	customerActivityToOpportunityMap.put(customerActivity.Id, customerActivity.Product_Order__r.Order__r.Opportunity__c);
            }else if(customerActivity.Social_Campaign__r.Product_Order__r.Order__r.Opportunity__c != null){
            	customerActivityToOpportunityMap.put(customerActivity.Id, customerActivity.Social_Campaign__r.Product_Order__r.Order__r.Opportunity__c);
            }
        }
        //Sharing logic for customer ctivity
        customerActivitySharingOnInsertion(customerActivityToOpportunityMap);
        //Update proof and task logic
        markCMSSendingctivitytoCustomerAscompleted(customeActivities);
    }
 
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {}
 
    public void AfterDelete(Map<Id, SObject> oldItems) {}
 
    public void AfterUndelete(Map<Id, SObject> oldItems) {}
    
    /**
    * @author       Kamal Sharma
    * @date         2019-01-02
    * @description  This method will share the customer activity with portal user.
    * @param        Map<Id,Id> customerActivityToOpportunityMap
    * @return       void
    */
    private void customerActivitySharingOnInsertion(Map<Id,Id> customerActivityToOpportunityMap){
        try{
            //This method is declaired in NXX2_TriggerHandler_Utility class
            //Get all related primary and agency account for the opportunities related to proof records.
            populateAccountsToPrimaryAccountsMap(new Set<Id>(customerActivityToOpportunityMap.values()),null);
            //This method is declaired in NXX2_TriggerHandler_Utility class
            //Get all contact role for the related primary and agency account fetched earlier.
            populateContactRoleDataForTheAccounts(accountsToPrimaryAccountsMap.keySet());
            //This method is declaired in NXX2_TriggerHandler_Utility class
            //Get customer role access record for the roles related to fetched contact roles.
            populateCustomerRoleAccessMap();
            //This method is declaired in NXX2_TriggerHandler_Utility class
            //Get existing customer portal user for the related contacts in contact roles.
            populateContactUserMap();
            //Share Customer Activity records with the fetched/created portal users.
            initializeSharing(customerActivityToOpportunityMap.keySet());
            if(customerActivityShareList.size() > 0){
            	insert customerActivityShareList;
            }
        }catch(Exception e){
            system.debug('Class NXX2_ShareRecordUtility, Method recalculateAccountSharing');
            system.debug('Exception: '+ e.getStackTraceString());
        }
    }
    
    /**
    * @author       Kamal Sharma
    * @date         2019-01-02
    * @description  This method will share the customer activity with portal user.
    * @param        Set<Id> customerActivityIds
    * @return       void
    */
    private void initializeSharing(Set<Id> customerActivityIds){
        //This variable belongs to NXX2_TriggerHandler_Utility class
        customerActivityShareList = new List<Customer_Task__Share>();
        for(Id accountId : accountContactRoleMap.keySet()){
            List<Contact_Role__c> contactRoles = accountContactRoleMap.get(accountId);
            for(Contact_Role__c contactRole : contactRoles){
                Customer_Role_Access__c customerRoleAccess = customerRoleAccessMap.get(contactRole.Role__c);
                if(customerRoleAccess.Account_Access__c != 'None' && customerRoleAccess.Customer_Activity_Access__c != 'None'){
                    //This method belongs to NXX2_TriggerHandler_Utility Class 
                    //and will create customer activity share record
                    populateCustomerActivityShareList(contactRole.Contact__c,customerActivityIds,customerRoleAccess);
                }
            }
        }
    }
    
    /**
    * @author       Paras Prajapati
    * @date         2019-01-02
    * @description  When user create customer task against Proof record of type 'Upload Creative Assets', 
    * 				the method will look for the task the CM has with subject = 'Send the content plan to client for approval'
    * 				in Product Order and mark that task completed
    * @param        List<Customer_Task__c> customerTaskList
    * @return       void
    */
    private void markCMSSendingctivitytoCustomerAscompleted(List<Customer_Task__c> customerTaskList){
        if(customerTaskList.size()>0){
            List<Id> productIds= new List<Id>();
            for(Customer_Task__c customer_Task : customerTaskList){
                if(customer_Task.Type__c=='Upload Creative Assets' && customer_Task.Social_Campaign__r.Product_Order__c!=null && customer_Task.Social_Campaign__c!=null){
                    productIds.add(customer_Task.Social_Campaign__r.Product_Order__c);
                }
            }
            if(productIds.size()>0){
                List<Task> taskList = [Select Id,subject,Status,CSPOFA__Orchestration_Step__r.Name from Task where Status!='Completed' AND CSPOFA__Orchestration_Step__c!=null AND subject = 'Send the content plan to client for approval' AND WhatId IN:productIds];
                if(taskList.size()>0){
                    for(Task taskRecord : taskList){
                        taskRecord.Status = 'Completed';
                    }
                    update taskList;
                    markProofRecordsWithCustomer(customerTaskList);
                }
            }
        }
    }

    /**
    * @author       Paras Prajapati
    * @date         2019-01-02
    * @description  When user create customer task against Proof with type 'Approve and Review Your Display Ads' 
    * 				or 'Approve and Review Your Facebook Ads' or Approve and Review Your Landing Page' 
    * 				then it will update Proof Status to 'With Customer'
    * @param        List<Customer_Task__c> customerTaskList
    * @return       void
    */
    private void markProofRecordsWithCustomer(List<Customer_Task__c> customerTaskList){
        if(customerTaskList.size()>0){
            List<Id> proofIds= new List<Id>();
            for(Customer_Task__c customer_Task : customerTaskList){
                if((customer_Task.Type__c=='Approve and Review Your Display Ads' || customer_Task.Type__c=='Approve and Review Your Facebook Ads' || customer_Task.Type__c=='Approve and Review Your Landing Page') &&  customer_Task.Social_Campaign__c!=null){
                    proofIds.add(customer_Task.Social_Campaign__c);
                }
            }
            if(proofIds.size()>0){
                List<SocialCampaign__c> listOfProof = [Select Id,Status__c from SocialCampaign__c where Id IN:proofIds];
                if(listOfProof.size()>0){
                    for(SocialCampaign__c social_Campaign:listOfProof){
                        social_Campaign.Status__c = 'With Customer';
                        social_Campaign.Number_of_Email_Sent_For_Approval__c= 0;
                        social_Campaign.Send_Approval_Emails__c = false;
                    }
                    update listOfProof;
                }
            }
        }
    }
}