News UAT/force-app/main/default/objects/Activity/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Activity/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>@NXRIII-75</description>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/Customer_Task__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Customer Activity</label>
    <nameField>
        <displayFormat>CAN-{YYMMDD}-{0000}</displayFormat>
        <label>Customer Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <inlineHelpText>This field will be used to add the comments.</inlineHelpText>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Created_From_Staging__c.field-meta.xml
<CustomField>
    <fullName>Created_From_Staging__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be checked if this record is created from staging record.</description>
    <label>Created From Staging</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <defaultValue>NOW() + $Setup.NXX2_CustomerActivitySettings__c.Number_Of_Days_To_Extend__c</defaultValue>
    <description>This field will capture the Due Date Entered by the User.</description>
    <label>Due Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will contain the reference of Product Order for Approve Display Ad Proof Task</description>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Social_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Social_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This relationship to link social campaign to a customer task to get &quot;Campaign Tasks&quot;</description>
    <label>Social Campaign</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>With Client</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
                <isActive>false</isActive>
                <label>In Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>1.This will capture the Task Type.</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upload Creative Assets</fullName>
            </value>
            <value>
                <fullName>Place GTM on Website</fullName>
            </value>
            <value>
                <fullName>Extend Access to Google Analytics</fullName>
            </value>
            <value>
                <fullName>Approve and Review Your Display Ads</fullName>
            </value>
            <value>
                <fullName>Approve and Review Your Facebook Ads</fullName>
            </value>
            <value>
                <fullName>Grant News Xtend Facebook Access</fullName>
            </value>
            <value>
                <fullName>Approve and Review Your Landing Page</fullName>
            </value>
            <value>
                <fullName>Approve Display Ad Proof</fullName>
                <isActive>false</isActive>
                <label>Approve Display Ad Proof</label>
            </value>
            <value>
                <fullName>Approve Facebook Ads Proof</fullName>
                <isActive>false</isActive>
                <label>Approve Facebook Ads Proof</label>
            </value>
            <value>
                <fullName>Generic Task</fullName>
                <isActive>false</isActive>
                <label>Generic Task</label>
            </value>
            <value>
                <fullName>Google Tag Manager</fullName>
                <isActive>false</isActive>
                <label>Google Tag Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Proof_Staging__c/NXX2_Proof_Staging__c.object-meta.xml
<CustomObject>
    <description>This will contain proof records of google cloud storage.</description>
    <label>NXX2 Proof Staging</label>
    <nameField>
        <label>NXX2 Campaign Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NXX2 Proofs Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_Proof_Staging__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Proof_Staging__c/fields/Related_Proof__c.field-meta.xml
<CustomField>
    <fullName>Related_Proof__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Actual proof which is created for this staging proof.</description>
    <label>Related Proof</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipLabel>NXX2 Proofs Staging</relationshipLabel>
    <relationshipName>NXX2_Proofs_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Task_Staging__c/NXX2_Task_Staging__c.object-meta.xml
<CustomObject>
    <description>This will contain tasks from google cloud storage</description>
    <label>NXX2 Task Staging</label>
    <nameField>
        <label>NXX2 Task Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NXX2 Tasks Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_Task_Staging__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <label>Campaign Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Task_Staging__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Task_Staging__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <label>Product Order</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Task_Staging__c/fields/Related_Proof__c.field-meta.xml
<CustomField>
    <fullName>Related_Proof__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Actual proof which is created for the staging proof related to his task</description>
    <label>Related Proof</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipLabel>NXX2 Tasks Staging</relationshipLabel>
    <relationshipName>NXX2_Tasks_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Task_Staging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Task_Staging__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Returned to CM</fullName>
            </value>
            <value>
                <fullName>Initial QA</fullName>
            </value>
            <value>
                <fullName>Peer review</fullName>
            </value>
            <value>
                <fullName>Peer review failed</fullName>
            </value>
            <value>
                <fullName>Ready to go live</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
            <value>
                <fullName>Cancellation Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicate the type of campaign order line item</description>
    <inlineHelpText>Indicate the type of campaign order line item</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Unchanged</fullName>
            </value>
            <value>
                <fullName>Renew</fullName>
            </value>
            <value>
                <fullName>Unchanged (Fulfilled)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/recordTypes/Website.recordType-meta.xml
<RecordType>
    <fullName>Website</fullName>
    <active>true</active>
    <label>Website</label>
</RecordType>

News UAT/force-app/main/default/classes/NXX2_CreateActualTaskForStagingTask.cls
/**
* @author       Kamal Sharma
* @date         2019-01-14
* @className	NXX2_CreateActualTaskForStagingTask
* @description  This class will be used to create actual proof records for staging proofs.  
*/
global class NXX2_CreateActualTaskForStagingTask implements Database.Batchable<sObject>,Database.Stateful{
    private string proofCustomerActivityRecordTypeId;
    private Map<String,String> stagingToActualTaskStatusMap;
    private Map<String,String> stagingToActualTaskTypesMap;
    private Map<String,String> customerActivityCommentsLinkedToTypeMap;
    /**
    * @author       Kamal Sharma
    * @date         2019-01-14
    * @description  Default constructor
    */
    public NXX2_CreateActualTaskForStagingTask(){
        proofCustomerActivityRecordTypeId = Schema.SObjectType.Customer_Task__c.getRecordTypeInfosByName().get('Proof Customer Activity').getRecordTypeId();
        stagingToActualTaskStatusMap = new Map<String,String>{
            'APPROVED' => 'Completed',
            'IN_REVIEW' => 'New',
            'NEW' => 'New',
            'WITH_CLIENT' => 'With Client',
            'NOT_REQUIRED' => 'New'
        };
        stagingToActualTaskTypesMap = new Map<String,String>{
            'UPLOAD_CREATIVE_ASSETS' => 'Upload Creative Assets',
            'DISPLAY_PROOF' => 'Approve and Review Your Display Ads',
            'SOCIAL_PROOF' => 'Approve and Review Your Facebook Ads',
            'GTM' => 'Place GTM on Website'
        };
        customerActivityCommentsLinkedToTypeMap = NXX2_AppUtility.getAllCommentsLinkedToType();
    }
    
    /**
    * @author       Kamal Sharma
	* @date         2019-01-14
    * @description  Start method implementation of Batch interface
    * @param        Database.BatchableContext BC
    * @return       Database.QueryLocator
    */
    global Database.QueryLocator start(Database.BatchableContext BC){
        //Fetch All the staging task Recods which are related to product order.
        return Database.getQueryLocator([SELECT Campaign_Id__c,Status__c,Product_Order__c,Title__c,
                                         Type__c,Related_Proof__c,Has_Merged__c,Link__c,Due_Date__c,
                                         Processing_Status__c,Error_Message__c,Error_Details__c 
                                         FROM NXX2_Task_Staging__c 
                                         WHERE Has_Merged__c = false 
                                        ]);
    }
    
    /**
    * @author       Kamal Sharma
	* @date         2019-01-14
    * @description  execute method implementation of Batch interface
    * @param        Database.BatchableContext BC, List<sObject> scope
    * @return       void
    */
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        try{
            processTaskRecords((List<NXX2_Task_Staging__c>)scope);
            for(NXX2_Task_Staging__c task : (List<NXX2_Task_Staging__c>)scope){
                task.Has_Merged__c = true;
                task.Processing_Status__c = 'Success';
            }
            update scope;
        }catch(Exception e){
            for(NXX2_Task_Staging__c task : (List<NXX2_Task_Staging__c>)scope){
                task.Processing_Status__c = 'Error';
                task.Error_Message__c = 'Exception Occured!';
                task.Error_Details__c = e.getMessage();
            }
            update scope;
        }
    }
    
    /**
    * @author       Kamal Sharma
	* @date         2019-01-14
    * @description  This method will process all staging task records to create proof records.
    * @param        List<NXX2_Task_Staging__c> stagingTasks
    * @return       void
    */
    public void processTaskRecords(List<NXX2_Task_Staging__c> stagingTasks){
        system.debug('*******stagingTasks********'+stagingTasks);
        Map<String,List<NXX2_Task_Staging__c>> proofIdToTasksMap = new Map<String,List<NXX2_Task_Staging__c>>();
        for(NXX2_Task_Staging__c task : stagingTasks){
            task.Has_Merged__c = true;
            if(!proofIdToTasksMap.containsKey(task.Campaign_Id__c)){
                proofIdToTasksMap.put(task.Campaign_Id__c, new List<NXX2_Task_Staging__c>());
            }
            proofIdToTasksMap.get(task.Campaign_Id__c).add(task);
        }
        List<NXX2_Proof_Staging__c> stagingProofs = [SELECT Name, External_Id__c, Related_Proof__c 
                                                     FROM NXX2_Proof_Staging__c 
                                                     WHERE Related_Proof__c != null 
                                                     AND External_Id__c IN :proofIdToTasksMap.keySet()];
        system.debug('*******stagingProofs********'+stagingProofs);
        List<Customer_Task__c> customerActivities = new List<Customer_Task__c>();
        for(NXX2_Proof_Staging__c proof : stagingProofs){
            for(NXX2_Task_Staging__c task : proofIdToTasksMap.get(proof.External_Id__c)){
                task.Related_Proof__c = proof.Related_Proof__c;
                if(stagingToActualTaskTypesMap.containsKey(task.Type__c)){
                    String ActualTaskType = stagingToActualTaskTypesMap.get(task.Type__c);
                    customerActivities.add(new Customer_Task__c(
                        Title__c = task.Title__c,
                        Type__c = ActualTaskType,
                        Comments__c = customerActivityCommentsLinkedToTypeMap.get(ActualTaskType),
                        Status__c = task.Status__c == null ? 'New' : stagingToActualTaskStatusMap.get(task.Status__c),
                        Social_Campaign__c = proof.Related_Proof__c,
                        recordTypeId = proofCustomerActivityRecordTypeId,
                        Link__c = task.Link__c,
                        Due_Date__c = task.Due_Date__c == null ? Date.today() : NXX2_AppUtility.getDateFromString(task.Due_Date__c),
                        Created_From_Staging__c = true
                    ));
                }
            }
        }
        system.debug('******Customer Activity******'+customerActivities);
        insert customerActivities;
    }
    
    /**
    * @author       Kamal Sharma
	* @date         2019-01-14
    * @description  finish method implementation of Batch interface
    * @param        Database.BatchableContext BC
    * @return       void
    */
    global void finish(Database.BatchableContext BC){
        NXX2_CreateProofAdFromStagingData b = new NXX2_CreateProofAdFromStagingData();
        database.executebatch(b,1);
    }
}