News UAT/force-app/main/default/objects/NXX2_Asset_Staging__c/NXX2_Asset_Staging__c.object-meta.xml
<CustomObject>
    <description>This will contain record of google cloud storage assets.</description>
    <label>NXX2 Asset Staging</label>
    <nameField>
        <label>NXX2 Asset Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NXX2 Assets Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_Asset_Staging__c/fields/Related_Proof__c.field-meta.xml
<CustomField>
    <fullName>Related_Proof__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Proof</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipLabel>NXX2 Assets Staging</relationshipLabel>
    <relationshipName>NXX2_Assets_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Proof_Staging__c/NXX2_Proof_Staging__c.object-meta.xml
<CustomObject>
    <description>This will contain proof records of google cloud storage.</description>
    <label>NXX2 Proof Staging</label>
    <nameField>
        <label>NXX2 Campaign Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NXX2 Proofs Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_Proof_Staging__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Proof_Staging__c/fields/Related_Proof__c.field-meta.xml
<CustomField>
    <fullName>Related_Proof__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Actual proof which is created for this staging proof.</description>
    <label>Related Proof</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipLabel>NXX2 Proofs Staging</relationshipLabel>
    <relationshipName>NXX2_Proofs_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/NXX2_ProofAd_Staging__c.object-meta.xml
<CustomObject>
    <description>This will contain records of proof ads from google cloud storage</description>
    <label>NXX2 ProofAd Staging</label>
    <nameField>
        <label>NXX2 ProofAd Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NXX2 ProofAds Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <label>External Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/fields/Has_Merged__c.field-meta.xml
<CustomField>
    <fullName>Has_Merged__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be used to identify whether a record has been moved to standard object or not.</description>
    <label>Has Merged</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/fields/Related_ProofAd__c.field-meta.xml
<CustomField>
    <fullName>Related_ProofAd__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will link to actual proof ad</description>
    <label>Related ProofAd</label>
    <referenceTo>SocialAd__c</referenceTo>
    <relationshipLabel>NXX2 ProofAds Staging</relationshipLabel>
    <relationshipName>NXX2_ProofAds_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_SocialForm_Staging__c/NXX2_SocialForm_Staging__c.object-meta.xml
<CustomObject>
    <description>This will contain record of social form from google cloud storage</description>
    <label>NXX2 SocialForm Staging</label>
    <nameField>
        <label>NXX2 SocialForm Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NXX2 SocialForms Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_SocialForm_Staging__c/fields/Related_Proof__c.field-meta.xml
<CustomField>
    <fullName>Related_Proof__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Proof</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipLabel>NXX2 SocialForms Staging</relationshipLabel>
    <relationshipName>NXX2_SocialForms_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Task_Staging__c/NXX2_Task_Staging__c.object-meta.xml
<CustomObject>
    <description>This will contain tasks from google cloud storage</description>
    <label>NXX2 Task Staging</label>
    <nameField>
        <label>NXX2 Task Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NXX2 Tasks Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_Task_Staging__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <label>Campaign Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Task_Staging__c/fields/Related_Proof__c.field-meta.xml
<CustomField>
    <fullName>Related_Proof__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Actual proof which is created for the staging proof related to his task</description>
    <label>Related Proof</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipLabel>NXX2 Tasks Staging</relationshipLabel>
    <relationshipName>NXX2_Tasks_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/classes/NXX2_ResetErrorRecordInStagingData.cls
/**
* @author       Kamal Sharma
* @date         2019-01-14
* @className    NXX2_CreateProofAdFromStagingData
* @description  This class will be used to create actual proof Ad records for staging proof Ads.  
*/
global class NXX2_ResetErrorRecordInStagingData implements Database.Batchable<sObject>,Database.Stateful{
    /**
    * @author       Kamal Sharma
    * @date         2019-01-14
    * @description  Start method implementation of Batch interface
    * @param        Database.BatchableContext BC
    * @return       Database.QueryLocator
    */
    global Database.QueryLocator start(Database.BatchableContext BC){
        //Fetch All the staging task Recods which are related to product order.
        system.debug('*******Proof*******');
        return Database.getQueryLocator([SELECT External_Id__c,Has_Merged__c,Error_Message__c,Processing_Status__c,
                                         Error_Details__c
                                         FROM NXX2_Proof_Staging__c
                                         WHERE Has_Merged__c = true 
                                         AND Processing_Status__c = 'Error'
                                         AND Error_Message__c = 'Exception Occured!'
                                         AND Related_Proof__c = null
                                        ]);
    }
    
    /**
    * @author       Kamal Sharma
    * @date         2019-01-14
    * @description  execute method implementation of Batch interface
    * @param        Database.BatchableContext BC, List<sObject> scope
    * @return       void
    */
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        system.debug('*******Scope*******'+scope);
        try{
            processProofRecords((List<NXX2_Proof_Staging__c>)scope);
        }catch(Exception e){
            system.debug('*******Error Occured*******'+e.getMessage());
        }
    }
    
    /**
    * @author       Kamal Sharma
    * @date         2019-01-14
    * @description  This method will process all staging task records to create proof records.
    * @param        List<NXX2_ProofAd_Staging__c> stagingProofAds
    * @return       void
    */
    public void processProofRecords(List<NXX2_Proof_Staging__c> stagingProofs){
        Set<String> CampaignIds = new Set<String>();
        for(NXX2_Proof_Staging__c stagingProof : stagingProofs){
            stagingProof.Has_Merged__c = false;
            stagingProof.Error_Details__c = '';
            stagingProof.Error_Message__c = '';
            stagingProof.Processing_Status__c = '';
            CampaignIds.add(stagingProof.External_Id__c);
        }
        update stagingProofs;
        List<NXX2_ProofAd_Staging__c> stagingProofAds = [SELECT External_Id__c,Has_Merged__c,
                                                         Error_Message__c,Processing_Status__c,
                                                         Error_Details__c
                                                         FROM NXX2_ProofAd_Staging__c
                                                         WHERE Has_Merged__c = true 
                                                         AND Processing_Status__c = 'Error'
                                                         AND Related_ProofAd__c = null
                                                         AND Campaign_Id__c IN :CampaignIds
                                                        ];
        for(NXX2_ProofAd_Staging__c stagingProofAd : stagingProofAds){
            stagingProofAd.Has_Merged__c = false;
            stagingProofAd.Error_Details__c = '';
            stagingProofAd.Error_Message__c = '';
            stagingProofAd.Processing_Status__c = '';
        }
        update stagingProofAds;
        List<NXX2_SocialForm_Staging__c> socialForms = [SELECT External_Id__c,Has_Merged__c,
                                                        Error_Message__c,Processing_Status__c,
                                                        Error_Details__c
                                                        FROM NXX2_SocialForm_Staging__c
                                                        WHERE Has_Merged__c = true 
                                                        AND Processing_Status__c = 'Error'
                                                        AND Related_Proof__c = null
                                                        AND Error_Message__c = 'No related social ad'
                                                        AND Campaign_Id__c IN :CampaignIds
                                                       ];
        for(NXX2_SocialForm_Staging__c socialForm : socialForms){
            socialForm.Has_Merged__c = false;
            socialForm.Error_Details__c = '';
            socialForm.Error_Message__c = '';
            socialForm.Processing_Status__c = '';
        }
        update socialForms;
        List<NXX2_Asset_Staging__c> assets = [SELECT External_Id__c,Has_Merged__c,
                                              Error_Message__c,Processing_Status__c,
                                              Error_Details__c
                                              FROM NXX2_Asset_Staging__c
                                              WHERE Has_Merged__c = true 
                                              AND Processing_Status__c = 'Error'
                                              AND Related_Proof__c = null
                                              AND Error_Message__c = 'Parent Id do not have any related object.'
                                              AND Campaign_Id__c IN :CampaignIds
                                             ];
        for(NXX2_Asset_Staging__c asset : assets){
            asset.Has_Merged__c = false;
            asset.Error_Details__c = '';
            asset.Error_Message__c = '';
            asset.Processing_Status__c = '';
        }
        update assets;
        List<NXX2_Task_Staging__c> tasks = [SELECT External_Id__c,Has_Merged__c,
                                            Error_Message__c,Processing_Status__c,
                                            Error_Details__c
                                            FROM NXX2_Task_Staging__c
                                            WHERE Has_Merged__c = true 
                                            AND Related_Proof__c = null
                                            AND Campaign_Id__c IN :CampaignIds
                                           ];
        for(NXX2_Task_Staging__c task : tasks){
            task.Has_Merged__c = false;
            task.Error_Details__c = '';
            task.Error_Message__c = '';
            task.Processing_Status__c = '';
        }
        update tasks;
    }
    
    /**
    * @author       Kamal Sharma
    * @date         2019-01-14
    * @description  finish method implementation of Batch interface
    * @param        Database.BatchableContext BC
    * @return       void
    */
    global void finish(Database.BatchableContext BC){
        NXX2_CreateActualProofForStagingProof b = new NXX2_CreateActualProofForStagingProof();
        database.executebatch(b,1);
    }
}