News UAT/force-app/main/default/objects/DNC_Settings__c/DNC_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These custom settings contain the parameters that&#39;ll be used by the DNC (Do Not Call) Register jobs</description>
    <label>DNC Job Settings</label>
</CustomObject>

News UAT/force-app/main/default/objects/DNC_Settings__c/fields/Delete_Scope_Size__c.field-meta.xml
<CustomField>
    <fullName>Delete_Scope_Size__c</fullName>
    <description>This parameter determines how many records in the scope are passed to the DNC delete process</description>
    <label>Delete Scope Size</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/DNC_Settings__c/fields/Delete_Window__c.field-meta.xml
<CustomField>
    <fullName>Delete_Window__c</fullName>
    <description>This parameters specifies (in number of days) the maximum age of the DNC entries. The delete process will remove any records in the DNC register that&#39;s older than the value specified in this parameter</description>
    <label>Delete Window</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/DNC_Settings__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/DNC_Settings__c/fields/Extract_Scope_Size__c.field-meta.xml
<CustomField>
    <fullName>Extract_Scope_Size__c</fullName>
    <description>This parameter determines how many records in the scope are passed to the DNC extract process</description>
    <label>Extract Scope Size</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/DNC_Wash_Register__c/DNC_Wash_Register__c.object-meta.xml
<CustomObject>
    <description>This object contains the list of phone numbers to be washed against the ACMA Do Not Call Register. The outcomes of the wash process are also recorded in this object.</description>
    <label>DNC Wash Register</label>
    <nameField>
        <displayFormat>WR-{0}</displayFormat>
        <label>Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DNC Wash Register</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/classes/DNCPhoneExtractSchedule_Test.cls
@isTest
public with sharing class DNCPhoneExtractSchedule_Test {
//Class for unit testing the DNC Phone Extract Scheduler
    
   //arbitrary cron setting  
   public static String CRON_EXP = '0 0 0 15 3 ? 2022';

   static testmethod void DNCSchedulerTest() {
      Test.startTest();

      //Create Custom Settings for Test
      DNC_Settings__c settings = new DNC_Settings__c(
            Name = 'DNC Defaults', 
            Delete_Scope_Size__c = 1000, 
            Delete_Window__c = 1, 
            Extract_Scope_Size__c = 50,
            External_Id__c = '12345678'
        );
      
      insert settings;
      
      // Schedule the test job 
    
      String jobId = System.schedule('DNCPhoneExtractScheduleTest',
                        CRON_EXP, 
                        new DNCPhoneExtractSchedule());
         
      // Get the information from the CronTrigger API object 
    
      CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
         NextFireTime
         FROM CronTrigger WHERE id = :jobId];

      // Verify the expressions are the same 
    
      System.assertEquals(CRON_EXP, 
         ct.CronExpression);

      // Verify the job has not run 
    
      System.assertEquals(0, ct.TimesTriggered);

      // Verify the next time the job will run 
    
      System.assertEquals('2022-03-15 00:00:00', 
         String.valueOf(ct.NextFireTime));
 
      // Verify the scheduled job hasn't run yet. 
    
      DNC_Wash_Register__c[] ml = [SELECT Id FROM DNC_Wash_Register__c 
                             WHERE Name = 'Scheduled Job Item'];
      System.assertEquals(ml.size(),0);
      Test.stopTest();



   }

}