News UAT/force-app/main/default/objects/Answer_to_Rule__c/Answer_to_Rule__c.object-meta.xml
<CustomObject>
    <label>Answer to Rule</label>
    <nameField>
        <displayFormat>A2R-{000000}</displayFormat>
        <label>Answer to Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer to Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Answer_to_Rule__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Answer to Rules</relationshipLabel>
    <relationshipName>Answer_to_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Approved_Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Approved_Sales_Order_Number__c</fullName>
    <inlineHelpText>Number of Approved Sales Order</inlineHelpText>
    <label>Approved Sales Order Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Campaign_Brief_Form_Completed__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Brief_Form_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if the all the required fields in the Campaign Brief Form have been filled</description>
    <inlineHelpText>Indicate if the all the required fields in the Campaign Brief Form have been filled</inlineHelpText>
    <label>Campaign Brief Form Completed</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Campaign_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Campaign_End_Date__c</fullName>
    <label>Advertising End Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Campaign_Progress__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Progress__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Campaign Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Campaign_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Start_Date__c</fullName>
    <label>Advertising Start Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/ExpectedCloseDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedCloseDate__c</fullName>
    <description>Field is populated with the first value entered in the Close Date field and stored for reporting purposes.</description>
    <label>Expected Close Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Has_an_Approved_SO__c.field-meta.xml
<CustomField>
    <fullName>Has_an_Approved_SO__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field that is populated with Trigger when there is an Approved CS Sales Order linked to the Opportunity.</description>
    <label>Has an Approved SO</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Is_Campaign_Start_Date_Changed__c.field-meta.xml
<CustomField>
    <fullName>Is_Campaign_Start_Date_Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Advertising Start Date Changed?</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Is_Close_Date_Changed__c.field-meta.xml
<CustomField>
    <fullName>Is_Close_Date_Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Close Date Changed?</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Pitch_material_due__c.field-meta.xml
<CustomField>
    <fullName>Pitch_material_due__c</fullName>
    <inlineHelpText>When are internal assets required?</inlineHelpText>
    <label>Pitch material due</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Response_Due__c.field-meta.xml
<CustomField>
    <fullName>Response_Due__c</fullName>
    <inlineHelpText>When is the response to client due</inlineHelpText>
    <label>Response Due</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Revenue_Group__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Group__c</fullName>
    <description>Revenue Group for the Opportunity - defaulted to the Account&#39;s Revenue Group.
If Revenue Group options change - also update the &#39;Revenue Group L1&#39; dependant formula field.</description>
    <label>Revenue Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amusements</fullName>
            </value>
            <value>
                <fullName>Employment</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle Dealers</fullName>
            </value>
            <value>
                <fullName>National (Communications/business equipment)</fullName>
            </value>
            <value>
                <fullName>National (Computers)</fullName>
            </value>
            <value>
                <fullName>National (Finance)</fullName>
            </value>
            <value>
                <fullName>National (Food and beverages)</fullName>
            </value>
            <value>
                <fullName>National (Gambling/gaming)</fullName>
            </value>
            <value>
                <fullName>National (Government/political)</fullName>
            </value>
            <value>
                <fullName>National (Media)</fullName>
            </value>
            <value>
                <fullName>National (Motor Vehicle Manufacturers)</fullName>
            </value>
            <value>
                <fullName>National (Other)</fullName>
            </value>
            <value>
                <fullName>National (Personal care products)</fullName>
            </value>
            <value>
                <fullName>National (Pharmaceutical / Health Products)</fullName>
            </value>
            <value>
                <fullName>National (Travel)</fullName>
            </value>
            <value>
                <fullName>Public Notices</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Stage_Changed__c.field-meta.xml
<CustomField>
    <fullName>Stage_Changed__c</fullName>
    <label>Stage Changed</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>CASE(TEXT(StageName),
  &quot;Identify Prospects&quot;, &quot;Open&quot;,
  &quot;Establish Rapport&quot;, &quot;Open&quot;,
  &quot;Qualify Opportunity&quot;, &quot;Open&quot;,
  &quot;Select Product(s) and Update Stage&quot;, &quot;Open&quot;,
  &quot;Develop Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Present Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Re-affirm Value/ Negotiate&quot;, &quot;Open&quot;,
  &quot;Awaiting Bookings&quot;, &quot;Open&quot;,
  &quot;Closed Won&quot;, &quot;Closed Won&quot;,
  &quot;Closed Lost&quot;, &quot;Closed Lost&quot;,
  &quot;Err: Invalid stage name&quot;
)</formula>
    <inlineHelpText>Field to allow reporting on Win/ Lost vs Open. Do not display on page layouts.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/recordTypes/Brief.recordType-meta.xml
<RecordType>
    <fullName>Brief</fullName>
    <active>true</active>
    <businessProcess>Brief%2F Reactive</businessProcess>
    <description>By request of a client brief.</description>
    <label>Brief</label>
</RecordType>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Overall_Status__c.field-meta.xml
<CustomField>
    <fullName>Overall_Status__c</fullName>
    <label>Overall Campaign Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Related_Order__c.field-meta.xml
<CustomField>
    <fullName>Related_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Fulfilment Ready</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Campaign Live</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/CS_OpportunitySOCloneController.cls
/**
* @author           Kevin Wu
* @date             2018-10-01
* @className        CS_OpportunitySOCloneController
* @testClassName    CS_OpportunitySOCloneControllerTest
* @description      Controller for Opportunity re-order functionality
*/
public with sharing class CS_OpportunitySOCloneController {
	final static String ERROR_CANT_NOT_REORDER = 'Please check the status of the Campaign. Re-Order is only possible on Ended Campaigns.';
	final static String ERROR_CAMPAIGN_STILL_LIVE = 'This campaign is still Live. You cannot re-order at this time.';

	/**
    * @name         : clone
    * @description  : deep clone opportunity with so, so lines and all the related records
    * @createdby    : Kevin Wu - 2018-10-01
    * @param        : String sourceOppyId, String cloneOppyName
    * @return       : String
    */
	@AuraEnabled
	public static String clone(String sourceOppyId, String cloneOppyName){
		CS_LightningResponse res = new CS_LightningResponse();

		
		try{
			csmso__Sales_Order__c so = getApprovedSalesOrder(sourceOppyId);
			
			if(so!=null){
				Opportunity clonedOppy = cloneOpportunity(sourceOppyId, cloneOppyName);
				cloneCampaignBriefAnswers(sourceOppyId, clonedOppy.Id);
				cloneOpportunityProducts(sourceOppyId, clonedOppy.Id);
				String result = csmso.SalesOrderSupport.cloneSalesOrderForOpportunity(so.Id, clonedOppy.Id);

				res.code = 2000;
				res.message = 'success';
				res.details = clonedOppy.Id;
			}else{
				res.code = 2100;
				res.message = 'error';
				res.details = ERROR_CANT_NOT_REORDER;
			}
			
		}catch(Exception ex){
			res.code = 2900;
			res.message = 'error';
			res.details = ex.getMessage();
		}
	
		return JSON.serialize(res);
	}

	/**
    * @name         : cloneOpportunity
    * @description  : clone an opportunity
    * @createdby    : Kevin Wu - 2018-10-01
    * @param        : String sourceOppyId, String cloneOppyName
    * @return       : Opportunity
    */
	public static Opportunity cloneOpportunity(String sourceOppyId, String cloneOppyName){

		Set<String> fields = Schema.getGlobalDescribe().get('Opportunity').getDescribe().fields.getMap().keySet();

		Opportunity optySource = Database.query('SELECT ' + String.join(new List<String>(fields), ',') + ' from Opportunity where Id = \'' +  sourceOppyId + '\'');

		Opportunity optyClone = optySource.clone(false,false,false,false);
		optyClone.Revenue_Group__c 			= optySource.Revenue_Group__c;
		optyClone.StageName 				= 'Develop/Present Solution';
		optyClone.Probability 				= 30;
		optyClone.Has_an_Approved_SO__c 	= false;
		optyClone.Approved_Sales_Order_Number__c 	= '';
		optyClone.Campaign_Brief_Form_Completed__c 	= false;
		optyClone.Is_Campaign_Start_Date_Changed__c = false;
		optyClone.Is_Close_Date_Changed__c 			= false;
		optyClone.Campaign_Start_Date__c 			= null;
		optyClone.Campaign_End_Date__c 				= null;
		optyClone.CloseDate 				= System.today() + 10;
		optyClone.Campaign_Progress__c 		= null;
		optyClone.ExpectedCloseDate__c 		= null;
		optyClone.Pitch_material_due__c 	= null;
		optyClone.Response_Due__c 			= null;
		optyClone.Stage_Changed__c 			= null;
		optyClone.Name 						= cloneOppyName != null ? cloneOppyName : optySource.Name + ' Reorder - ' + String.valueOf(Date.today()).substring(0,10);
		

		insert optyClone;
		system.debug('****** optyClone='+optyClone);
		return optyClone;
	}

	/**
    * @name         : getApprovedSalesOrder
    * @description  : retrieved sales order record that meets the criteria under opportunity
    * @createdby    : Kevin Wu - 2018-10-01
    * @param        : String oppyId
    * @return       : csmso__Sales_Order__c
    */
	public static csmso__Sales_Order__c getApprovedSalesOrder(String oppyId){
		List<csmso__Sales_Order__c> soList = [Select Id, (Select Id, Overall_Status__c, Status__c From Orders__r)
												From csmso__Sales_Order__c 
												Where 	csmso__Opportunity__c =: oppyId
														And csmso__Opportunity__r.StageName = 'Closed Won'
														And (csmso__Status__c = 'Manually Approved' 
														Or csmso__Status__c = 'Externally Approved') 
												Limit 1];
		csmso__Sales_Order__c so = (!soList.isEmpty()) ? soList.get(0) : null;
		if(so != null && so.Orders__r != null){
			Order__c co = so.Orders__r[0];
			if(co.Status__c != 'Campaign Ended'){
				String errorMessage = (co.Status__c == 'Campaign Live') ? ERROR_CAMPAIGN_STILL_LIVE : ERROR_CANT_NOT_REORDER;
				throw new OpportunitySOCloneException(errorMessage);
			}
		}

		return so;
	}

	/**
    * @name         : cloneOpportunityProducts
    * @description  : clone opportunity products under opportunity
    * @createdby    : Kevin Wu - 2018-10-01
    * @param        : String sourceOppyId, String cloneOppyId
    * @return       : n/a
    */
	public static void cloneOpportunityProducts(String sourceOppyId, String cloneOppyId){
		Set<String> fields = Schema.getGlobalDescribe().get('OpportunityLineItem').getDescribe().fields.getMap().keySet();
		List<OpportunityLineItem> oppyProducts = Database.query('SELECT ' + String.join(new List<String>(fields), ',') + ' from OpportunityLineItem where OpportunityId = \'' +  sourceOppyId + '\'');

		List<OpportunityLineItem> oppyProductsClone = new List<OpportunityLineItem>();
		for(OpportunityLineItem prod: oppyProducts){
			OpportunityLineItem prodClone = prod.clone(true, false, false, false);
			prodClone.Id = null;
			prodClone.OpportunityId = cloneOppyId;
			prodClone.UnitPrice = null;
			oppyProductsClone.add(prodClone);
		}
		if(!oppyProductsClone.isEmpty()){
			insert oppyProductsClone;
		}
	}

	/**
    * @name         : cloneCampaignBriefAnswers
    * @description  : clone all campaign brief answers 
    * @createdby    : Kevin Wu - 2018-10-01
    * @param        : String sourceOppyId, String cloneOppyId
    * @return       : n/a
    */
	public static void cloneCampaignBriefAnswers(String sourceOppyId, String cloneOppyId){
		Set<String> fields = Schema.getGlobalDescribe().get('Answer_to_Rule__c').getDescribe().fields.getMap().keySet();

		List<Answer_to_Rule__c> answerRules = Database.query('SELECT ' + String.join(new List<String>(fields), ',') + ' from Answer_to_Rule__c where Opportunity__c = \'' +  sourceOppyId + '\'');

		List<Answer_to_Rule__c> answerRulesClone = new List<Answer_to_Rule__c>();
		for(Answer_to_Rule__c ar: answerRules){
			Answer_to_Rule__c arClone = ar.clone(true, false, false, false);
			arClone.Opportunity__c = cloneOppyId;
			arClone.Id = null;
			answerRulesClone.add(arClone);
		}

		if(!answerRulesClone.isEmpty()){
			insert answerRulesClone;
		}
		
	}

	public class OpportunitySOCloneException extends Exception {}
}