News UAT/force-app/main/default/objects/Creative__c/Creative__c.object-meta.xml
<CustomObject>
    <label>Creative</label>
    <nameField>
        <label>Creative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Creative__c/fields/Assigned_Fulfilment_Owner__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Fulfilment_Owner__c</fullName>
    <formula>IF(Product_Order__r.Assigned_Fulfilment_Owner__c &lt;&gt; null , Product_Order__r.Assigned_Fulfilment_Owner__r.LastName &amp; &quot;, &quot; &amp; Product_Order__r.Assigned_Fulfilment_Owner__r.FirstName , &#39;&#39;)</formula>
    <label>Assigned Fulfilment Owner</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Creative__c/fields/Client_Approved__c.field-meta.xml
<CustomField>
    <fullName>Client_Approved__c</fullName>
    <label>Client Approved?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Creative__c/fields/CM_QA_check__c.field-meta.xml
<CustomField>
    <fullName>CM_QA_check__c</fullName>
    <label>CM QA check passed?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Creative__c/fields/Creative_Source__c.field-meta.xml
<CustomField>
    <fullName>Creative_Source__c</fullName>
    <label>Creative Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Premedia</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Creative__c/fields/Creative_URL__c.field-meta.xml
<CustomField>
    <fullName>Creative_URL__c</fullName>
    <label>Creative URL</label>
    <type>Url</type>
</CustomField>

News UAT/force-app/main/default/objects/Creative__c/fields/Creative_URL_Draft__c.field-meta.xml
<CustomField>
    <fullName>Creative_URL_Draft__c</fullName>
    <label>Creative URL Draft</label>
    <type>Url</type>
</CustomField>

News UAT/force-app/main/default/objects/Creative__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipLabel>Creatives</relationshipLabel>
    <relationshipName>Creatives</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>CASE(TEXT(StageName),
  &quot;Identify Prospects&quot;, &quot;Open&quot;,
  &quot;Establish Rapport&quot;, &quot;Open&quot;,
  &quot;Qualify Opportunity&quot;, &quot;Open&quot;,
  &quot;Select Product(s) and Update Stage&quot;, &quot;Open&quot;,
  &quot;Develop Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Present Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Re-affirm Value/ Negotiate&quot;, &quot;Open&quot;,
  &quot;Awaiting Bookings&quot;, &quot;Open&quot;,
  &quot;Closed Won&quot;, &quot;Closed Won&quot;,
  &quot;Closed Lost&quot;, &quot;Closed Lost&quot;,
  &quot;Err: Invalid stage name&quot;
)</formula>
    <inlineHelpText>Field to allow reporting on Win/ Lost vs Open. Do not display on page layouts.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Assigned_Campaign_Manager__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Campaign_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Campaign Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Fulfilment Ready</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Campaign Live</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Assigned_Campaign_Manager__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Campaign_Manager__c</fullName>
    <formula>IF( Order__r.Assigned_Campaign_Manager__c  &lt;&gt; null ,  Order__r.Assigned_Campaign_Manager__r.LastName &amp; &quot;, &quot; &amp; Order__r.Assigned_Campaign_Manager__r.FirstName , &#39;&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned Campaign Manager</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Assigned_Fulfilment_Owner__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Fulfilment_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Fulfilment Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Product Orders</relationshipLabel>
    <relationshipName>Product_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/QA_Check_Passed__c.field-meta.xml
<CustomField>
    <fullName>QA_Check_Passed__c</fullName>
    <label>QA Check Passed?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Returned to CM</fullName>
            </value>
            <value>
                <fullName>Initial QA</fullName>
            </value>
            <value>
                <fullName>Peer review</fullName>
            </value>
            <value>
                <fullName>Peer review failed</fullName>
            </value>
            <value>
                <fullName>Ready to go live</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
            <value>
                <fullName>Cancellation Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicate the type of campaign order line item</description>
    <inlineHelpText>Indicate the type of campaign order line item</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Unchanged</fullName>
            </value>
            <value>
                <fullName>Renew</fullName>
            </value>
            <value>
                <fullName>Unchanged (Fulfilled)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/recordTypes/Social.recordType-meta.xml
<RecordType>
    <fullName>Social</fullName>
    <active>true</active>
    <label>Social</label>
</RecordType>

News UAT/force-app/main/default/objects/QA_Checklist__c/QA_Checklist__c.object-meta.xml
<CustomObject>
    <label>QA Checklist</label>
    <nameField>
        <label>QA Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QA Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/QA_Checklist__c/fields/Campaign_Order__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>QA Checklists</relationshipLabel>
    <relationshipName>QA_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/QA_Checklist__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipLabel>QA Checklists</relationshipLabel>
    <relationshipName>QA_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/QA_Checklist__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Evaluation</fullName>
                <default>true</default>
                <label>Evaluation</label>
            </value>
            <value>
                <fullName>Client Revision</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/QA_Item__c/QA_Item__c.object-meta.xml
<CustomObject>
    <label>QA Item</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>QA Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QA Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/QA_Item__c/fields/QA_Checklist__c.field-meta.xml
<CustomField>
    <fullName>QA_Checklist__c</fullName>
    <label>QA Checklist</label>
    <referenceTo>QA_Checklist__c</referenceTo>
    <relationshipLabel>QA Items</relationshipLabel>
    <relationshipName>QA_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/classes/CS_TaskTriggerDelegateTest.cls
@isTest
private class CS_TaskTriggerDelegateTest {
	
	@isTest static void test_insertProductOrder() {
        Order__c order = TestDataSetupClass.createOrder(new Opportunity());
        order.Assigned_Campaign_Manager__c = UserInfo.getUserId();
        insert order;

        Product_Order__c pOrd = new Product_Order__c(
            Assigned_Fulfilment_Owner__c = UserInfo.getUserId(),
            Order__c = order.Id,
            Status__c = 'Cancelled'
        );
        insert pOrd;

        QA_Checklist__c checklist = new QA_Checklist__c(Product_Order__c = pOrd.Id);
        insert checklist;

		Id QATaskRecordTypeId =  Task.getSObjectType().getDescribe().getRecordTypeInfosByName().get('QA Check').getRecordTypeId();

		Task t = new Task(RecordTypeId = QATaskRecordTypeId,
							WhatId = pOrd.Id,
							Description = 'Process:Social');

		Test.startTest();

		insert t;

		Test.stopTest();
	}

	@isTest static void test_insertOrder() {
        Order__c order = TestDataSetupClass.createOrder(new Opportunity());
        order.Assigned_Campaign_Manager__c = UserInfo.getUserId();
        insert order;

        QA_Checklist__c checklist = new QA_Checklist__c(Campaign_Order__c = order.Id);
        insert checklist;

		Id QATaskRecordTypeId =  Task.getSObjectType().getDescribe().getRecordTypeInfosByName().get('QA Check').getRecordTypeId();
		Task t = new Task(RecordTypeId = QATaskRecordTypeId,
							WhatId = order.Id,
							Description = 'Process:');

		Test.startTest();

		insert t;

		Test.stopTest();
	}
	
	@isTest static void test_insertProductOrder_ClientRevision() {
        Order__c order = TestDataSetupClass.createOrder(new Opportunity());
        order.Assigned_Campaign_Manager__c = UserInfo.getUserId();
        insert order;

        Product_Order__c pOrd = new Product_Order__c(
            Assigned_Fulfilment_Owner__c = UserInfo.getUserId(),
            Order__c = order.Id,
            Status__c = 'Cancelled'
        );
        insert pOrd;

		 Id QATaskRecordTypeId =  Task.getSObjectType().getDescribe().getRecordTypeInfosByName().get('QA Check').getRecordTypeId();
		Task t = new Task(RecordTypeId = QATaskRecordTypeId,
							WhatId = pOrd.Id,
							Description = 'Process:Client Revision');

		Test.startTest();

		insert t;

		Test.stopTest();
		
		QA_Checklist__c qaCheckList = [select Name, Type__c, (select Id from QA_Items__r) from QA_Checklist__c where Product_Order__c = :pOrd.id];
		
		system.assertEquals('Client Revision', qaCheckList.Type__c);
		system.assertEquals(6, qaCheckList.QA_Items__r.size());
	}

	@isTest static void test_insertProductOrderWithValidation() {
		Order__c order = TestDataSetupClass.createOrder(new Opportunity());
		order.Assigned_Campaign_Manager__c = UserInfo.getUserId(); //mandatory field for testing
		insert order;

		Product_Order__c pOrd = new Product_Order__c(
				Assigned_Fulfilment_Owner__c = UserInfo.getUserId(),
				Order__c = order.Id,
				Status__c = 'Cancelled',
				QA_Check_Passed__c ='Yes' //mand field for testing
		);
		insert pOrd;

		Creative__c creative = new Creative__c(Name = 'Test Creative',
				Product_Order__c = pOrd.Id,
				Creative_Source__c = 'Premedia',
				Client_Approved__c = 'Yes',
				Creative_URL__c = 'www.dummywebsite.com/mycreative',
				CM_QA_check__c = 'Yes',
				Creative_URL_Draft__c  = 'www.dummywebsite.com/mycreativedraft'
		);

		Creative__c creative2 = new Creative__c(Name = 'Test Creative2',
				Product_Order__c = pOrd.Id,
				Creative_Source__c = 'Premedia',
				CM_QA_check__c = 'Yes',
				Creative_URL_Draft__c  = 'www.dummywebsite.com/mycreativedraft'
		);
		List<Creative__c> creatives = new List<Creative__c>{creative,creative2};

		insert creatives;

		QA_Checklist__c checklist = new QA_Checklist__c(Product_Order__c = pOrd.Id);
		insert checklist;


		Id QATaskRecordTypeId =  Task.getSObjectType().getDescribe().getRecordTypeInfosByName().get('To-Do').getRecordTypeId();



		CSPOFA__Orchestration_Process_Template__c template = new CSPOFA__Orchestration_Process_Template__c(
				Name = 'Campaign Setup',
				CSPOFA__OLA_Unit__c = 'day',
				CSPOFA__OLA_Time__c = 1
		);
		insert template;



		CSPOFA__Orchestration_Step_Template__c stepTemplateMandFields = new CSPOFA__Orchestration_Step_Template__c(
				CSPOFA__Orchestration_Process_Template__c = template.Id,
				CSPOFA__OLA_Unit__c = 'day',
				CSPOFA__OLA_Time__c = 1,
				Mandatory_Input_Fields__c = 'Client_Approved__c,Creative_URL__c'
		);


		/* orchestrator step templates */
		CSPOFA__Orchestration_Step_Template__c stepTemplateValidate = new CSPOFA__Orchestration_Step_Template__c(
				CSPOFA__Orchestration_Process_Template__c = template.Id,
				CSPOFA__OLA_Unit__c = 'day',
				CSPOFA__OLA_Time__c = 1,
				ValidationFunction__c = 'ClientApprovedValidation'
		);

		CSPOFA__Orchestration_Step_Template__c stepTemplateValidate2 = new CSPOFA__Orchestration_Step_Template__c(
				CSPOFA__Orchestration_Process_Template__c = template.Id,
				CSPOFA__OLA_Unit__c = 'day',
				CSPOFA__OLA_Time__c = 1,
				ValidationFunction__c = 'CreativeSourceValidation'
		);

		CSPOFA__Orchestration_Step_Template__c stepTemplateMandFieldsforPO = new CSPOFA__Orchestration_Step_Template__c(
				CSPOFA__Orchestration_Process_Template__c = template.Id,
				CSPOFA__OLA_Unit__c = 'day',
				CSPOFA__OLA_Time__c = 1,
				Mandatory_Input_Fields__c = 'QA_Check_Passed__c'
		);

		CSPOFA__Orchestration_Step_Template__c stepTemplateMandFieldsforCO = new CSPOFA__Orchestration_Step_Template__c(
				CSPOFA__Orchestration_Process_Template__c = template.Id,
				CSPOFA__OLA_Unit__c = 'day',
				CSPOFA__OLA_Time__c = 1,
				Mandatory_Input_Fields__c = 'Assigned_Campaign_Manager__c'
		);


		List<CSPOFA__Orchestration_Step_Template__c> stepTemplates = new List<CSPOFA__Orchestration_Step_Template__c>{
				stepTemplateMandFields,
				stepTemplateValidate,
				stepTemplateValidate2,
				stepTemplateMandFieldsforPO,
				stepTemplateMandFieldsforCO
		};

		insert stepTemplates;



		CSPOFA__Orchestration_Process__c process = new CSPOFA__Orchestration_Process__c(
				Product_Order__c = pOrd.Id,
				CSPOFA__Orchestration_Process_Template__c = template.Id
		);
		insert process;



		CSPOFA__Orchestration_Step__c manFieldsStep = new CSPOFA__Orchestration_Step__c(
				CSPOFA__Orchestration_Process__c = process.Id,
				CSPOFA__Orchestration_Step_Template__c = stepTemplates[0].Id
		);


		CSPOFA__Orchestration_Step__c validationStep = new CSPOFA__Orchestration_Step__c(
				CSPOFA__Orchestration_Process__c = process.Id,
				CSPOFA__Orchestration_Step_Template__c = stepTemplates[1].Id
		);

		CSPOFA__Orchestration_Step__c validationStep2 = new CSPOFA__Orchestration_Step__c(
				CSPOFA__Orchestration_Process__c = process.Id,
				CSPOFA__Orchestration_Step_Template__c = stepTemplates[2].Id
		);

		CSPOFA__Orchestration_Step__c validationStepPO = new CSPOFA__Orchestration_Step__c(
				CSPOFA__Orchestration_Process__c = process.Id,
				CSPOFA__Orchestration_Step_Template__c = stepTemplates[3].Id
		);

		CSPOFA__Orchestration_Step__c validationStepCO = new CSPOFA__Orchestration_Step__c(
				CSPOFA__Orchestration_Process__c = process.Id,
				CSPOFA__Orchestration_Step_Template__c = stepTemplates[4].Id
		);



		List<CSPOFA__Orchestration_Step__c> orchsteps = new List<CSPOFA__Orchestration_Step__c>{
				manFieldsStep,
				validationStep,
				validationStep2,
				validationStepPO,
				validationStepCO
		};

		insert orchsteps;


		/* creating tasks */
		Task t1 = new Task(RecordTypeId = QATaskRecordTypeId,
				WhatId = creatives[0].Id,
				Description = 'Process:Social',
				CSPOFA__Orchestration_Step__c = orchsteps[0].Id
		);

		Task t2 = new Task(RecordTypeId = QATaskRecordTypeId,
				WhatId = creatives[0].Id,
				Description = 'Process:Social',
				CSPOFA__Orchestration_Step__c = orchsteps[1].Id
		);

		Task t3 = new Task(RecordTypeId = QATaskRecordTypeId,
				WhatId = creatives[0].Id,
				Description = 'Process:Social',
				CSPOFA__Orchestration_Step__c = orchsteps[2].Id
		);

		Task t4 = new Task(RecordTypeId = QATaskRecordTypeId,
				WhatId = pOrd.Id,
				Description = 'Process:Social',
				CSPOFA__Orchestration_Step__c = orchsteps[3].Id
		);

		Task t5 = new Task(RecordTypeId = QATaskRecordTypeId,
				WhatId = order.Id,
				Description = 'Process:Social',
				CSPOFA__Orchestration_Step__c = orchsteps[4].Id
		);



		List<Task> testTasks = new List<Task>{t1,t2,t3,t4,t5 };


		Test.startTest();

		insert testTasks;

		for (Task t: testTasks) {
			t.Status = 'Completed';
			update t;
			// even though this is not best practice (i.e. DML within a for loop) the TaskTrigger needs refactoring to support bulk update
			// since updating mulitple type Tasks will invoke methods which will fail for different type tasks... i.e. mandatory fields will be expected on a validation task
		}

		//update testTasks;

		Test.stopTest();
	}
}