News UAT/force-app/main/default/objects/Creative__c/Creative__c.object-meta.xml
<CustomObject>
    <label>Creative</label>
    <nameField>
        <label>Creative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Creative__c/fields/Client_Approved__c.field-meta.xml
<CustomField>
    <fullName>Client_Approved__c</fullName>
    <label>Client Approved?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Creative__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipLabel>Creatives</relationshipLabel>
    <relationshipName>Creatives</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_InboundEmailConfig__mdt/NXX2_InboundEmailConfig__mdt.object-meta.xml
<CustomObject>
    <description>This configuration will be used to identify the inbound mail of client which are specific to Purchase Order approval or rejection.</description>
    <label>NXX2_InboundEmailConfig</label>
    <pluralLabel>NXX2_InboundEmailConfigs</pluralLabel>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_InboundEmailConfig__mdt/fields/EmailBodyTextForApproval__c.field-meta.xml
<CustomField>
    <fullName>EmailBodyTextForApproval__c</fullName>
    <label>EmailBodyTextForApproval</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_InboundEmailConfig__mdt/fields/EmailBodyTextForRequestChange__c.field-meta.xml
<CustomField>
    <fullName>EmailBodyTextForRequestChange__c</fullName>
    <defaultValue>&#39;REQUIRES CHANGES&#39;</defaultValue>
    <label>EmailBodyTextForRequestChange</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_InboundEmailConfig__mdt/fields/TaskRecordType__c.field-meta.xml
<CustomField>
    <fullName>TaskRecordType__c</fullName>
    <label>TaskRecordType</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_InboundEmailConfig__mdt/fields/TaskSubject__c.field-meta.xml
<CustomField>
    <fullName>TaskSubject__c</fullName>
    <label>TaskSubject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Approved_By_Client__c.field-meta.xml
<CustomField>
    <fullName>Approved_By_Client__c</fullName>
    <label>Approved By Client?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/recordTypes/Social.recordType-meta.xml
<RecordType>
    <fullName>Social</fullName>
    <active>true</active>
    <label>Social</label>
</RecordType>

News UAT/force-app/main/default/classes/NXX2_InboundEmailTriggerTest.cls
/**
* @author       Kamal Sharma
* @date         2018-05-25
* @className	NXX2_InboundEmailTriggerTest
* @description  This is a test class for NXX2_InboundEmailTrigger.
*/
@isTest(seeAllData=true)
public class NXX2_InboundEmailTriggerTest {
        /**
    * @author       Kamal Sharma
    * @date         2018-05-23
    * @description  This method will test the handleInboundEmail method of NXX2_InboundEmailTrigger class for negative and positive scenario.
    * @param        NA
    * @return       void
    */
    static testMethod void testInboundEmailTrigger() {
        List<NXX2_InboundEmailConfig__mdt> inboundMailConfig = [SELECT QualifiedApiName,EmailBodyTextForApproval__c,EmailBodyTextForRequestChange__c, TaskSubject__c, TaskRecordType__c FROM NXX2_InboundEmailConfig__mdt];
        Map<String,NXX2_InboundEmailConfig__mdt> mailValidationConfig = new Map<String,NXX2_InboundEmailConfig__mdt>();
        for(NXX2_InboundEmailConfig__mdt config : inboundMailConfig){
            mailValidationConfig.put(config.QualifiedApiName, config);
        }
        Integer recordsToValidate = 4;
        User user = TestDataFactory.createUser('System Administrator','Test','Demo',null,false,false);
        System.runAs(user){
            Test.startTest();
            Messaging.InboundEmail email;
            Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
            List<Product_Order__c> orders = NXX2_TestUtility.createProductOrder(recordsToValidate);
            List<Creative__c> creatives = NXX2_TestUtility.createCreative(orders);
            Product_Order__c productOrder;
            Task task;
            NXX2_InboundEmailTrigger emailTrigger = new NXX2_InboundEmailTrigger();
            List<Task> tasks = new List<Task>();
            List<Messaging.InboundEmail> emails = new List<Messaging.InboundEmail>();
            for(Integer i = 0; i < recordsToValidate; i++){
                email = new Messaging.InboundEmail();
            	email.fromAddress = 'kamal.sharma@crmit.com';
                productOrder = orders[i];
                if(Math.mod(i, 2) == 0){
                    task = NXX2_TestUtility.createTasks(mailValidationConfig.get('Inbound_Mail_Config_For_Social_PO').TaskSubject__c,mailValidationConfig.get('Inbound_Mail_Config_For_Social_PO').TaskRecordType__c,productOrder.Id);
                }else{
                    task = NXX2_TestUtility.createTasks(mailValidationConfig.get('Inbound_Mail_Config_For_Display_PO').TaskSubject__c,mailValidationConfig.get('Inbound_Mail_Config_For_Display_PO').TaskRecordType__c,creatives[i].Id);
                }
                tasks.add(task);
                emails.add(email);
            }
            insert tasks;
            List<Id> productIds = new List<Id>();
            List<Id> creativeIds = new List<Id>();
            for(Integer i = 0; i < recordsToValidate; i++){
                productIds.add(orders[i].Id);
                creativeIds.add(creatives[i].Id);
            }
            orders = [SELECT Name,(SELECT status FROM Tasks) FROM Product_Order__c WHERE Id IN :productIds];
            for(Integer i = 0; i < recordsToValidate; i++){
                emails[i].subject = orders[i].Name;
            }
        	Test.stopTest();
            
            //Validation for fulfillment type = social
            emails[0].plainTextBody = mailValidationConfig.get('Inbound_Mail_Config_For_Social_PO').EmailBodyTextForApproval__c;
            emailTrigger.handleInboundEmail(emails[0],env);
            emails[2].plainTextBody = mailValidationConfig.get('Inbound_Mail_Config_For_Social_PO').EmailBodyTextForRequestChange__c;
            emailTrigger.handleInboundEmail(emails[2],env);
            orders = [SELECT Approved_By_Client__c,(SELECT status FROM Tasks) FROM Product_Order__c WHERE Id IN :productIds];
            System.assertEquals(orders[0].tasks[0].status,'Completed');
            System.assertEquals(orders[0].Approved_By_Client__c,'Yes');
            System.assertEquals(orders[2].tasks[0].status,'Completed');
            System.assertEquals(orders[2].Approved_By_Client__c,'No');
            
            //Validation for fulfillment type = display
            emails[1].plainTextBody = mailValidationConfig.get('Inbound_Mail_Config_For_Display_PO').EmailBodyTextForApproval__c;
            emailTrigger.handleInboundEmail(emails[1],env);
            emails[3].plainTextBody = mailValidationConfig.get('Inbound_Mail_Config_For_Display_PO').EmailBodyTextForRequestChange__c;
            emailTrigger.handleInboundEmail(emails[3],env);
            creatives = [SELECT Client_Approved__c,(SELECT status FROM Tasks) FROM Creative__c WHERE Id IN :creativeIds];
            System.assertEquals(creatives[1].tasks[0].status,'Completed');
            System.assertEquals(creatives[1].Client_Approved__c,'Yes');
            System.assertEquals(creatives[3].tasks[0].status,'Completed');
            System.assertEquals(creatives[3].Client_Approved__c,'No');
        }
    }
}