News UAT/force-app/main/default/objects/OpportunityLineItem/fields/of_Periods__c.field-meta.xml
<CustomField>
    <fullName>of_Periods__c</fullName>
    <defaultValue>1</defaultValue>
    <label># of Periods</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/OpportunityLineItem/fields/Pattern__c.field-meta.xml
<CustomField>
    <fullName>Pattern__c</fullName>
    <label>Pattern</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every 2 Weeks</fullName>
            </value>
            <value>
                <fullName>Every 3 Weeks</fullName>
            </value>
            <value>
                <fullName>Every 4 Weeks</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/OpportunityLineItem/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Week(s)</fullName>
            </value>
            <value>
                <fullName>Month(s)</fullName>
                <default>true</default>
                <label>Month(s)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Print</fullName>
            </value>
            <value>
                <fullName>Community Classified</fullName>
            </value>
            <value>
                <fullName>Community Display</fullName>
            </value>
            <value>
                <fullName>Metro Classified</fullName>
            </value>
            <value>
                <fullName>Metro Display</fullName>
            </value>
            <value>
                <fullName>Display</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Rich Media</fullName>
            </value>
            <value>
                <fullName>NewsAdds</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product2/fields/PublicationList__c.field-meta.xml
<CustomField>
    <fullName>PublicationList__c</fullName>
    <label>PublicationList</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

News UAT/force-app/main/default/objects/Product2/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Airlie Beach</fullName>
            </value>
            <value>
                <fullName>Australian Golf Digest</fullName>
            </value>
            <value>
                <fullName>Best Recipes</fullName>
            </value>
            <value>
                <fullName>Big League</fullName>
            </value>
            <value>
                <fullName>Big League Specials</fullName>
            </value>
            <value>
                <fullName>Biloela</fullName>
            </value>
            <value>
                <fullName>Birth</fullName>
            </value>
            <value>
                <fullName>Body &amp; Soul</fullName>
            </value>
            <value>
                <fullName>Bundaberg</fullName>
            </value>
            <value>
                <fullName>Buro247</fullName>
            </value>
            <value>
                <fullName>Cairns</fullName>
            </value>
            <value>
                <fullName>Careers</fullName>
            </value>
            <value>
                <fullName>Carsguide</fullName>
            </value>
            <value>
                <fullName>Chadstone Fashion Capital</fullName>
            </value>
            <value>
                <fullName>Chinchilla-Surrat</fullName>
            </value>
            <value>
                <fullName>Coffs Harbour</fullName>
            </value>
            <value>
                <fullName>Community Mastheads</fullName>
            </value>
            <value>
                <fullName>Country Style</fullName>
            </value>
            <value>
                <fullName>Country Style Specials</fullName>
            </value>
            <value>
                <fullName>Courier Mail</fullName>
            </value>
            <value>
                <fullName>Daily Telegraph</fullName>
            </value>
            <value>
                <fullName>Delicious</fullName>
            </value>
            <value>
                <fullName>Delicious.com.au</fullName>
            </value>
            <value>
                <fullName>Diakrit</fullName>
            </value>
            <value>
                <fullName>Donna Hay</fullName>
            </value>
            <value>
                <fullName>Donna Hay Specials</fullName>
            </value>
            <value>
                <fullName>Emerald</fullName>
            </value>
            <value>
                <fullName>Escape.com.au</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Revenue_Schedule_Pattern__c/Revenue_Schedule_Pattern__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting used by OpportunityProductRevenueSchedule page.</description>
    <label>Revenue Schedule Pattern</label>
</CustomObject>

News UAT/force-app/main/default/objects/Revenue_Schedule_Pattern__c/fields/Pattern__c.field-meta.xml
<CustomField>
    <fullName>Pattern__c</fullName>
    <description>This field is used in Opportunity Revenue Schedule calculation as schedule pattern</description>
    <inlineHelpText>e.g. 3 on 4 off is 1110000</inlineHelpText>
    <label>Pattern</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/OpportunityProductSearch_Helper.cls
/*---------------------------------------------------------
 * Author: Bohao Chen
 * Company: Salesforce.com
 * Description: This is helper class for OpportunityProductSearch_ControllerX
 * History:
 * 6/06/2013  Bohao Chen  Created
 * 2016-02-16  Atul Gupta  Updated
 ---------------------------------------------------------*/
public with sharing class OpportunityProductSearch_Helper 
{
    public static final String ERROR_REQUIRED_FIELD_MSG = 'This field is required';
    
    public static Map<String, Revenue_Schedule_Pattern__c> patternInstanceMap 
    {
        get{ 
            return patternInstanceMap = patternInstanceMap == null ? Revenue_Schedule_Pattern__c.getAll() : patternInstanceMap; 
        } set; 
    }
    
    public static Boolean validateFieldValues(OpportunityLineItem o)
    {
        Boolean isValid = true;
        
        if(o.of_Periods__c == null)
            o.of_Periods__c.addError(OpportunityProductSearch_Helper.ERROR_REQUIRED_FIELD_MSG);

        if(o.Period__c == null)
            o.Period__c.addError(OpportunityProductSearch_Helper.ERROR_REQUIRED_FIELD_MSG);
        
        if(o.ServiceDate == null)
            o.ServiceDate.addError(OpportunityProductSearch_Helper.ERROR_REQUIRED_FIELD_MSG);
        
        if(o.Pattern__c == null)
            o.Pattern__c.addError(OpportunityProductSearch_Helper.ERROR_REQUIRED_FIELD_MSG);

        if(o.UnitPrice == null)
            o.UnitPrice.addError(OpportunityProductSearch_Helper.ERROR_REQUIRED_FIELD_MSG);
        
        if(o.of_Periods__c == null || o.Period__c == null || o.ServiceDate == null || o.Pattern__c == null || o.UnitPrice == null)
           isValid = false;

        return isValid;
    }
    
    
    public class ProductListWrapper {
        public List<ProductWrapper> prodList {get; set;}
        
        public ProductListWrapper (List<ProductWrapper> prodWrapList) {
            this.prodList = prodWrapList;
        }
        
        public ProductListWrapper (List<Product2> productList) {
            this.prodList = new List<ProductWrapper>();
            for (Product2 p : productList) {
                this.prodList.add(new ProductWrapper(p));
            }
        }
        
        public List<ProductWrapper> filterList(String keyword, String family, String prodCategory, String region) 
        {
            List<ProductWrapper> newList = new List<ProductWrapper>();
                
            for (ProductWrapper p : this.prodList) 
            {
                Boolean include = true;
                
                system.debug('=====p.product.Name=== ' + p.product.Name);
                
                if ((String.isBlank(p.product.Name) || (String.isNotBlank(keyword) && String.isNotBlank(p.product.Name) && !p.product.Name.containsIgnoreCase(keyword))) 
                    //&& (String.isBlank(p.product.Description) || (String.isNotBlank(keyword) && String.isNotBlank(p.product.Description) && !p.product.Description.containsIgnoreCase(keyword))) 
                    && (String.isBlank(p.product.PublicationList__c) || (String.isNotBlank(keyword) && String.isNotBlank(p.product.PublicationList__c) && !p.product.PublicationList__c.containsIgnoreCase(keyword)))
                    )
                {
                    include = false;
                }
                
                if ((String.isNotBlank(family) && String.isBlank(p.product.Family)) 
                    || (String.isNotBlank(family) && String.isNotBlank(p.product.Family) && !p.product.Family.equalsIgnoreCase(family)))
                {
                    include = false;    
                }
                
                if ((String.isNotBlank(prodCategory) && String.isBlank(p.product.Category__c))
                    || (String.isNotBlank(prodCategory) && String.isNotBlank(p.product.Category__c) && !p.product.Category__c.equalsIgnoreCase(prodCategory))) 
                {
                    include = false;    
                }
                
                if ((String.isNotBlank(region) && String.isBlank(p.product.Region__c)) 
                    || (String.isNotBlank(region) && String.isNotBlank(p.product.Region__c) && !p.product.Region__c.equalsIgnoreCase(region))) 
                {
                    include = false;    
                }

                if (include) newList.add(p);
            }
            
            return newList;
        }
    }
}