News UAT/force-app/main/default/objects/OpportunityLineItem/fields/of_Periods__c.field-meta.xml
<CustomField>
    <fullName>of_Periods__c</fullName>
    <defaultValue>1</defaultValue>
    <label># of Periods</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/OpportunityLineItem/fields/Pattern__c.field-meta.xml
<CustomField>
    <fullName>Pattern__c</fullName>
    <label>Pattern</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every 2 Weeks</fullName>
            </value>
            <value>
                <fullName>Every 3 Weeks</fullName>
            </value>
            <value>
                <fullName>Every 4 Weeks</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/OpportunityLineItem/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Week(s)</fullName>
            </value>
            <value>
                <fullName>Month(s)</fullName>
                <default>true</default>
                <label>Month(s)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/OpportunityLineItemWrapper.cls
public class OpportunityLineItemWrapper 
{   
    private final Integer NUM_OF_PERIOD    =   1;
    private final String DEFAULT_PERIOD    =   'Week(s)';
    private final String DEFAULT_PATTERN   =   'Weekly';
    
    public String productName { get; set; }
    public OpportunityLineItem opportunityLineItem { get; set; }
    public List<String> pattern { get; set; }
    public String frequency { get; set; }
    public Integer numOfSchedules { get; set; }
    // modified by Tim Fabros 15 / 07 / 2014 - SFE-516
    // getter method no longer hard coded to return null
    // BEGIN:
    public Boolean isSelect { get {return isSelect = isSelect == NUll ? false : isSelect;} set;}
    // END:
    
    public OpportunityLineItemWrapper(String productName, OpportunityLineItem opportunityLineItem)
    {
        this.productName = productName;
        this.opportunityLineItem = opportunityLineItem;
        this.pattern = new List<string>();
        this.numOfSchedules = 0;
        
        if(this.opportunityLineItem.of_Periods__c == null)
            this.opportunityLineItem.of_Periods__c = NUM_OF_PERIOD;
        if(this.opportunityLineItem.Period__c == null)
            this.opportunityLineItem.Period__c = DEFAULT_PERIOD;
        if(this.opportunityLineItem.Pattern__c == null)
            this.opportunityLineItem.Pattern__c = DEFAULT_PATTERN;
    }
    
    public OpportunityLineItemWrapper(OpportunityLineItem opportunityLineItem)
    {
        this.opportunityLineItem = opportunityLineItem;
        this.pattern = new List<string>();
        this.numOfSchedules = 0;
    }
    
    public List<String> getRevenueSchedulePattern()
    {
        List<String> pattern = new List<String>();
        
        if(OpportunityProductSearch_Helper.patternInstanceMap.containsKey(opportunityLineItem.Pattern__c))
        {
            String patternLongString = OpportunityProductSearch_Helper.patternInstanceMap.get(opportunityLineItem.Pattern__c).Pattern__c;
                
            if(String.isNotBlank(patternLongString))
                pattern = patternLongString.split('');
        }
        
        System.debug('===pattern=== ' + pattern);
        
        return pattern;
    }
    
    public String getRevenueScheduleFrequency()
    {
        String frequency;
        
        system.debug('==pattern instance==' + this.opportunityLineItem.Pattern__c);
        
        if(OpportunityProductSearch_Helper.patternInstanceMap.containsKey(opportunityLineItem.Pattern__c))
        {
            frequency = OpportunityProductSearch_Helper.patternInstanceMap.get(opportunityLineItem.Pattern__c).Frequency__c;
        }
        
        System.debug('===frequency=== ' + frequency);
        
        return frequency;
    }
}