News UAT/force-app/main/default/objects/SalesSummary__c/SalesSummary__c.object-meta.xml
<CustomObject>
    <description>A summary object of opportunity data (sales performance) vs target data</description>
    <label>Sales Summary</label>
    <nameField>
        <label>Summary Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/BookingRevenueType__c.field-meta.xml
<CustomField>
    <fullName>BookingRevenueType__c</fullName>
    <label>Booking Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Print</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <label>Count</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/DivisionScheme__c.field-meta.xml
<CustomField>
    <fullName>DivisionScheme__c</fullName>
    <label>Division Scheme</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SH1</fullName>
            </value>
            <value>
                <fullName>SH3</fullName>
            </value>
            <value>
                <fullName>SH4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Format:
If user x has an id of 123456789, their current role is Sales Consultant and the month that their sale belongs to is February 2016, then the external id can be calculated as u123456789rsalesconsultanttp022016ttarget which can be broken down into:
Username = u123456789
Role = rSalesConsultant (make lower case)
Time Zone = t022016 (02 is February and the year is 2016)
Type = Target</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Fisc Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/MonthId__c.field-meta.xml
<CustomField>
    <fullName>MonthId__c</fullName>
    <description>The Id of the month example &quot;201602&quot; is Febuary 2016</description>
    <label>Fisc Month Id</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/NRCredits__c.field-meta.xml
<CustomField>
    <fullName>NRCredits__c</fullName>
    <label>NR Credits</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/NRDebits__c.field-meta.xml
<CustomField>
    <fullName>NRDebits__c</fullName>
    <label>NR Debits</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Current role of the user</description>
    <label>Current Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/SalesSummaryStaging__c.field-meta.xml
<CustomField>
    <fullName>SalesSummaryStaging__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is of no use when the system is at REST, it is only used in APEX when receiving data from the staging object.</description>
    <label>Sales Summary Staging</label>
    <referenceTo>SalesSummaryStaging__c</referenceTo>
    <relationshipLabel>Sales Summaries</relationshipLabel>
    <relationshipName>Sales_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/TargetArea2__c.field-meta.xml
<CustomField>
    <fullName>TargetArea2__c</fullName>
    <label>Target Area 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Team</fullName>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/TargetArea__c.field-meta.xml
<CustomField>
    <fullName>TargetArea__c</fullName>
    <label>Target Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Print</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/TargetType__c.field-meta.xml
<CustomField>
    <fullName>TargetType__c</fullName>
    <label>Target Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Portfolio</fullName>
            </value>
            <value>
                <fullName>Rep Code</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Target</fullName>
                <color>#0B6FCE</color>
                <label>Target</label>
            </value>
            <value>
                <fullName>Actual</fullName>
                <color>#78C953</color>
                <label>Actual</label>
            </value>
            <value>
                <fullName>Pipeline</fullName>
                <color>#A845DC</color>
                <label>Pipeline</label>
            </value>
            <value>
                <fullName>Actual (NewsFact)</fullName>
                <color>#FF9900</color>
                <label>Actual (NewsFact)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Salesforce User Id</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Fisc Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/SalesSummaryStaging__c.object-meta.xml
<CustomObject>
    <description>A staging object for the data services team to push their data into for transformation into the Sales Summary object</description>
    <label>Sales Summary Staging</label>
    <nameField>
        <displayFormat>STAGE{0000000000}</displayFormat>
        <label>Staging Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Summary Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/BookingRevenueAmount__c.field-meta.xml
<CustomField>
    <fullName>BookingRevenueAmount__c</fullName>
    <label>Booking Revenue Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/BookingRevenueType__c.field-meta.xml
<CustomField>
    <fullName>BookingRevenueType__c</fullName>
    <label>Booking Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DIGITAL</fullName>
            </value>
            <value>
                <fullName>PRINT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/DivisionScheme__c.field-meta.xml
<CustomField>
    <fullName>DivisionScheme__c</fullName>
    <label>Division Scheme</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/EmployeeRole__c.field-meta.xml
<CustomField>
    <fullName>EmployeeRole__c</fullName>
    <label>Employee Role</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/FiscMonth__c.field-meta.xml
<CustomField>
    <fullName>FiscMonth__c</fullName>
    <label>Fisc Month</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/FiscMonthId__c.field-meta.xml
<CustomField>
    <fullName>FiscMonthId__c</fullName>
    <label>Fisc Month Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/FiscYear__c.field-meta.xml
<CustomField>
    <fullName>FiscYear__c</fullName>
    <label>Fisc Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/NRCredits__c.field-meta.xml
<CustomField>
    <fullName>NRCredits__c</fullName>
    <label>NR Credits</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/NRDebits__c.field-meta.xml
<CustomField>
    <fullName>NRDebits__c</fullName>
    <label>NR Debits</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/NRTargetAmount__c.field-meta.xml
<CustomField>
    <fullName>NRTargetAmount__c</fullName>
    <label>NR Target Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/PortfolioName__c.field-meta.xml
<CustomField>
    <fullName>PortfolioName__c</fullName>
    <label>Portfolio Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/SiebelLogin__c.field-meta.xml
<CustomField>
    <fullName>SiebelLogin__c</fullName>
    <label>Siebel Login</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/TargetArea2__c.field-meta.xml
<CustomField>
    <fullName>TargetArea2__c</fullName>
    <label>Target Area 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/TargetArea__c.field-meta.xml
<CustomField>
    <fullName>TargetArea__c</fullName>
    <label>Target Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/TargetType__c.field-meta.xml
<CustomField>
    <fullName>TargetType__c</fullName>
    <label>Target Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SalesSummaryStaging__c/fields/TeamName__c.field-meta.xml
<CustomField>
    <fullName>TeamName__c</fullName>
    <label>Team Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/SalesSummaryStagingTriggerHandler.cls
/*---------------------------------------------------------
 * Author: David Dawson
 * Company: Bluewolf
 * Description: Trigger Handler for the Sales Summary Staging object
 * History: Trigger Created.
 			Functionality added for sales summary staging record transformation
 ---------------------------------------------------------*/

public class SalesSummaryStagingTriggerHandler {
	
	public Map<String, String> TransformStagingData() {
		//final return object
		Map<String, String> errorLog = new Map<String, String>();

		//This is the list we will use to try and insert the new records.
		List<SalesSummary__c> transformObject = new List<SalesSummary__c>();

		//create a list of available users
		Set<String> userExtId = new Set<String>();
		for(SalesSummaryStaging__c sss :(List<SalesSummaryStaging__c>)Trigger.NEW){
			userExtId.add(String.valueOf(sss.SiebelLogin__c));
		}

		//get users from Salesforce that are used within the insert
		List<User> userList = new List<User>([SELECT Id, External_ID__c FROM User WHERE External_Id__c IN :userExtId]);
		Map<String, User> userMap = new Map<String, User>();
		for(User u :userList){
			userMap.put(u.External_Id__c, u);
		}

		for(SalesSummaryStaging__c sss :(List<SalesSummaryStaging__c>)Trigger.NEW){
			//ensure user exists
			if(userMap.containsKey(sss.SiebelLogin__c)){

				//Qualification for target record
				if(sss.TargetArea__c != null && sss.NRTargetAmount__c != null){
					SalesSummary__c targetRecord = new SalesSummary__c(OwnerId = userMap.get(sss.SiebelLogin__c).Id, Type__c = 'Target', UserId__c = userMap.get(sss.SiebelLogin__c).Id, MonthId__c = String.valueOf(sss.FiscMonthId__c.right(6)), Month__c = sss.FiscMonth__c, Year__c = sss.FiscYear__c, TargetType__c = sss.TargetType__c, TargetArea__c = sss.TargetArea__c, Count__c = sss.NRTargetAmount__c, TargetArea2__c = sss.TargetArea2__c, BookingRevenueType__c = sss.BookingRevenueType__c, DivisionScheme__c = sss.DivisionScheme__c, Role__c = sss.EmployeeRole__c, PortfolioName__c = sss.PortfolioName__c, State__c = sss.State__c, TeamName__c = sss.TeamName__c);
					targetRecord.SalesSummaryStaging__c = sss.Id;
					targetRecord.ExternalId__c = ExternalIdUtility.SalesSummaryExternalId(sss.SiebelLogin__c, sss.EmployeeRole__c, 'Target', sss.BookingRevenueType__c, sss.FiscMonthId__c);
					transformObject.add(targetRecord);
				}

				//Qualification for actual record
				if(sss.BookingRevenueType__c != null && sss.BookingRevenueAmount__c != null){
					SalesSummary__c actualRecord = new SalesSummary__c(OwnerId = userMap.get(sss.SiebelLogin__c).Id, Type__c = 'Actual (NewsFact)', UserId__c = userMap.get(sss.SiebelLogin__c).Id, MonthId__c = String.valueOf(sss.FiscMonthId__c.right(6)), Month__c = sss.FiscMonth__c, Year__c = sss.FiscYear__c, Count__c = sss.BookingRevenueAmount__c, BookingRevenueType__c = sss.BookingRevenueType__c, DivisionScheme__c = sss.DivisionScheme__c, Role__c = sss.EmployeeRole__c, PortfolioName__c = sss.PortfolioName__c, NRCredits__c = sss.NRCredits__c, NRDebits__c = sss.NRDebits__c, State__c = sss.State__c, TeamName__c = sss.TeamName__c);
					actualRecord.SalesSummaryStaging__c = sss.Id;
					actualRecord.ExternalId__c = ExternalIdUtility.SalesSummaryExternalId(sss.SiebelLogin__c, sss.EmployeeRole__c, 'Actual (NewsFact)', sss.BookingRevenueType__c, sss.FiscMonthId__c);
					transformObject.add(actualRecord);
				}
			}else{
				sss.addError('This user does not exist in Salesforce. Please ensure this user has been added into Salesforce before adding any summary information.');
			}
		}

		//upsert records
		try{
			upsert transformObject ExternalId__c;
		}catch(exception e){
			ExLog.log(e, 'config', transformObject, 'From SalesSummaryTriggerHandler.TransformStagingData().');  
		}

		//Set of the failed record sources (SalesSummaryStaging records)
		Set<Id> failedRecords = new Set<Id>();

		Schema.SObjectField f = SalesSummary__c.Fields.ExternalId__c;
		database.upsertresult[] results = database.upsert(transformObject, f, false);
	    for(integer idx = 0; idx < results.size(); idx++) {
	        if(!results[idx].isSuccess()) {
	            //will do the error handling in the trigger using the error log map
	            //(List<SalesSummaryStaging__c>)Trigger.newMap.get(transformObject[idx].SalesSummaryStaging__c).addError(results[idx].getErrors()[0].getMessage());
	            if(!errorLog.containsKey(transformObject[idx].SalesSummaryStaging__c)){
	            	errorLog.put(transformObject[idx].SalesSummaryStaging__c, results[idx].getErrors()[0].getMessage());
	            	failedRecords.add(transformObject[idx].SalesSummaryStaging__c);
	        	}
	        }
	    }

	    //loop through the failed sales summary staging records and roll back the children that succeeded
	    /*for(integer idx = 0; idx < results.size(); idx++) {
	    	if(results[idx].isSuccess()) {
	    		if(failedRecords.contains(transformObject[idx].SalesSummaryStaging__c)){
	    			//rollback the records
	    		}
	    	}
	    }*/

	    return errorLog;

	}
}