News UAT/force-app/main/default/objects/Knowledge__kav/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Job Info</fullName>
            </value>
            <value>
                <fullName>Reference/Upskill</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Tool</fullName>
            </value>
            <value>
                <fullName>Knowledge</fullName>
            </value>
            <value>
                <fullName>Product Resources</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Policy</fullName>
            </value>
            <value>
                <fullName>Agreement/Contract</fullName>
            </value>
            <value>
                <fullName>Checklist</fullName>
            </value>
            <value>
                <fullName>Form/Template</fullName>
            </value>
            <value>
                <fullName>Day in the Life</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Knowledge__kav/fields/External_Link__c.field-meta.xml
<CustomField>
    <fullName>External_Link__c</fullName>
    <label>External Link</label>
    <type>Url</type>
</CustomField>

News UAT/force-app/main/default/objects/Knowledge__kav/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <label>Icon</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Spreadsheet</fullName>
            </value>
            <value>
                <fullName>Presentation</fullName>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Knowledge__kav/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Opportunity Stage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discover Needs</fullName>
            </value>
            <value>
                <fullName>Develop/Present Solution</fullName>
            </value>
            <value>
                <fullName>Review/Reaffirm Value</fullName>
            </value>
            <value>
                <fullName>Confirmed/Awaiting Bookings</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Knowledge__kav/fields/Page__c.field-meta.xml
<CustomField>
    <fullName>Page__c</fullName>
    <label>Page</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
                <isActive>false</isActive>
                <label>Lead</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/AT_Knowledge.cls
public class AT_Knowledge {
    public class KnowledgeResults {
        @AuraEnabled
        public List<Article> articles {get; set;}
        
        @AuraEnabled
        public List<String> contentTypes {get; set;}
    }
    
    public class Article {
        @AuraEnabled
        public Integer order {get; set;}
        
        @AuraEnabled
        public String title {get; set;}
        
        @AuraEnabled
        public String label {get; set;}
        
        @AuraEnabled
        public String summary {get; set;}
        
        @AuraEnabled
        public String url {get; set;}
        
        @AuraEnabled
        public String link {get; set;}
        
        @AuraEnabled
        public Boolean hasLink {get; set;}
        
        @AuraEnabled
        public String contentType {get; set;}
        
        @AuraEnabled
        public String icon {get; set;}
        
        @AuraEnabled
        public String iconColor {get; set;}
        
        @AuraEnabled
        public String iconClass {get; set;}
        
        public Article(Knowledge__kav knowl, Integer order) {
            this.order = order;
            this.title = knowl.Title;
            this.label = knowl.Title;
            this.summary = knowl.Summary;
            this.url = '/articles/Knowledge/' + knowl.UrlName;
            this.link = knowl.External_Link__c;
            this.contentType = knowl.Content_Type__c;
            
            if ((knowl.Icon__c == null) || (knowl.Icon__c == '')) {
                this.iconClass = 'knowledge-other';
            } else {
                this.iconClass = 'knowledge-' + knowl.Icon__c.toLowerCase();
            }
            
            if (knowl.Icon__c == 'Document') {
                this.icon = 'utility:copy'; this.iconColor = 'blue';
            } else if (knowl.Icon__c == 'Spreadsheet') {
                this.icon = 'utility:matrix'; this.iconColor = 'green';
            } else if (knowl.Icon__c == 'Presentation') {
                this.icon = 'utility:desktop'; this.iconColor = 'red';
            } else if (knowl.Icon__c == 'Image') {
                this.icon = 'utility:image'; this.iconColor = 'orange';
            } else if (knowl.Icon__c == 'Video') {
                this.icon = 'utility:video'; this.iconColor = 'purple';
            } else if (knowl.Icon__c == 'Other') {
                this.icon = 'utility:file'; this.iconColor = 'grey';
            } else {
                this.icon = 'utility:file'; this.iconColor = 'grey';
            }
            
            this.hasLink = ((knowl.External_Link__c != null) && (knowl.External_Link__c != ''));
        }
    }
    
	@AuraEnabled
    public static KnowledgeResults queryKnowledge(String pageName, String filterFieldName, String filterValue) {
        String page = String.valueOf(pageName);
        String filterField = String.valueOf(filterFieldName);
        String filterVal = String.valueOf(filterValue);
        
        System.debug('Querying knowledge');
        System.debug('Page: ' + page + ', filterField: ' + filterField + ', filterValue:' + filterVal);
        
        if (filterField == 'Opportunity_Stage__c') {
            Opportunity opp = [SELECT StageName FROM Opportunity WHERE Id = :filterValue];
            
            filterVal = opp.StageName;
        }
        
        
        KnowledgeResults results = new KnowledgeResults();
        
        List<Article> articles = new List<Article>(); 
		Set<String> contentTypes = new Set<String>();

        Integer count = 0;
        
        String query = 'SELECT Id, Title, UrlName, Summary, External_Link__c, Content_Type__c, Icon__c FROM Knowledge__kav WHERE (Page__c INCLUDES (\'' + page + '\'))';
        
        if (String.isNotBlank(filterField) && String.isNotBlank(filterVal)) {
            String value = (filterVal == null) ? '' : filterVal;
            
            if (filterField == 'Opportunity_Stage__c') {
                query += (' AND (' + filterField + ' INCLUDES (\'' + value + '\'))');
            } else {
            	query += (' AND (' + filterField + ' = \'' + value + '\')');
            }
        }
        
        System.debug(query);
        
        for (SObject sobj: Database.query(query)) {
            Knowledge__kav knowl = (Knowledge__kav)sobj;
            
            articles.add(new Article(knowl, count));
            count++;
            
            contentTypes.add(knowl.Content_Type__c);
        }
        
        System.debug(articles);
        
        results.articles = articles;
        results.contentTypes = new List<String>(contentTypes);
        
        return results;
    }
}