News UAT/force-app/main/default/objects/CPQ_Approver__c/CPQ_Approver__c.object-meta.xml
<CustomObject>
    <label>CPQ Approver</label>
    <nameField>
        <displayFormat>APR-{0000}</displayFormat>
        <label>Approver</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPQ Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/CPQ_Approver__c/fields/L1_Approver__c.field-meta.xml
<CustomField>
    <fullName>L1_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>L1 Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CPQ_Approvers1</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/CPQ_Approver__c/fields/L2_Approver__c.field-meta.xml
<CustomField>
    <fullName>L2_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>L2 Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CPQ_Approvers2</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/CPQ_Approver__c/fields/L3_Approver__c.field-meta.xml
<CustomField>
    <fullName>L3_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>L3 Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CPQ_Approvers3</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/CPQ_Approver__c/fields/L4_Approver__c.field-meta.xml
<CustomField>
    <fullName>L4_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>L4 Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CPQ_Approvers4</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/CPQ_Approver__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Print</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>News Xtend</fullName>
            </value>
            <value>
                <fullName>Threshold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/CPQ_Approver__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CPQ_Approvers</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/classes/NewsXtendSalesOrderStateManagerTest.cls
@isTest(seeAllData=false)
public class NewsXtendSalesOrderStateManagerTest {

    @isTest 
    public static void validateChangeTest(){
        
        Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        insert acc;
        
        Contact con = TestDataSetupClass.createContact(acc);
        insert con;
        
        Opportunity opp = TestDataSetupClass.createOpportunity(acc, con);
        insert opp;
        
        csmso__Sales_Order__c so = TestDataSetupClass.createSalesOrder(acc, opp);
        insert so;
        so.csmso__Status__c = 'Draft';
        
        Test.startTest();
        NewsXtendSalesOrderStateManager nxsomClass = new NewsXtendSalesOrderStateManager();
        nxsomClass.validateChange(so);
        Test.stopTest();
    }
    
    @isTest 
    public static void validateChange_DraftTest(){
        
        Account acc = TestDataSetupClass.createAccount();
        insert acc;

        Contact contact = TestDataSetupClass.createContact(acc);
        insert contact;

        Opportunity opp = TestDataSetupClass.createOpportunity(acc, contact);
        insert opp;
        
        csmso__Sales_Order__c so = TestDataSetupClass.createSalesOrder(acc, opp);
        so.csmso__Status__c      = 'Draft';
		so.Basket_Products__c = 'Print Display';
		so.Platform_Set__c = 'Xtend,Print'; //dummy values to trigger the logic
		so.OwnerId = UserInfo.getUserId();//set owner in memory instead of query
		
        Test.startTest();
        NewsXtendSalesOrderStateManager nxsomClass = new NewsXtendSalesOrderStateManager();
        nxsomClass.getFieldAttributesForSalesOrder(so);
        Test.stopTest();
    }
    
     @isTest 
    public static void validateChange_NotDraftTest(){
        
        Account acc = TestDataSetupClass.createAccount();
        insert acc;

        Contact contact = TestDataSetupClass.createContact(acc);
        insert contact;

        Opportunity opp = TestDataSetupClass.createOpportunity(acc, contact);
        insert opp;
        
        csmso__Sales_Order__c so = TestDataSetupClass.createSalesOrder(acc, opp);
        so.csmso__Status__c      = 'Sent For Internal Approval';
		so.Basket_Products__c = 'Print Display';
		so.Platform_Set__c = 'Xtend,Print'; //dummy values to trigger the logic
        insert so;
        so.OwnerId = UserInfo.getUserId();//set owner in memory instead of query
        Test.startTest();
        NewsXtendSalesOrderStateManager nxsomClass = new NewsXtendSalesOrderStateManager();
        nxsomClass.getFieldAttributesForSalesOrder(so);
        Test.stopTest();
    }
	
	/**
	 * Same as validateChange_NotDraftTest but ran as non Opp owner user
	 * @type {[type]}
	 */
	@isTest
	public static void validateChange_NotDraftTestNotOwner(){
		Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
		User user = new User(Alias = 'newUser', Email = 'newuser@testorg.com',
							 EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
							 LocaleSidKey = 'en_US', ProfileId = p.Id,
							 TimeZoneSidKey = 'Australia/Sydney', UserName = 'testuserforcallout@testorg.com');
		insert user;
		Account acc = TestDataSetupClass.createAccount();
		insert acc;

		Contact contact = TestDataSetupClass.createContact(acc);
		insert contact;

		Opportunity opp = TestDataSetupClass.createOpportunity(acc, contact);
		insert opp;
		//create approver record
		CPQ_Approver__c cpqApp = new CPQ_Approver__c(
			Platform__c = 'Print',
			Sales_Rep__c = UserInfo.getUserId(),
			L1_Approver__c = user.Id,
			L2_Approver__c = user.Id,
			L3_Approver__c = user.Id,
			L4_Approver__c = null);
		insert cpqApp;
		
		csmso__Sales_Order__c so = TestDataSetupClass.createSalesOrder(acc, opp);
		so.csmso__Status__c = 'Sent For Internal Approval';
		so.Basket_Products__c = 'Print Display';
		so.Platform_Set__c = 'Xtend,Print'; //dummy values to trigger the logic
		insert so;
		//populate some values in memory as state manager class needs them, easier than query
		opp.OwnerId = UserInfo.getUserId();
		so.csmso__Opportunity__r = opp;
		so.OwnerId = UserInfo.getUserId();//set owner in memory instead of query
		
		Test.startTest();
		NewsXtendSalesOrderStateManager nxsomClass = new NewsXtendSalesOrderStateManager();
		System.runAs(user) {
			nxsomClass.getFieldAttributesForSalesOrder(so);
		}
		Test.stopTest();
	}
}