News UAT/force-app/main/default/objects/OpportunityReport__c/OpportunityReport__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>OpportunityReport</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpportunityReports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/OpportunityReport__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identify Prospects</fullName>
            </value>
            <value>
                <fullName>Establish Rapport</fullName>
            </value>
            <value>
                <fullName>Discover Needs</fullName>
            </value>
            <value>
                <fullName>Develop/Present Solution</fullName>
            </value>
            <value>
                <fullName>Review/Reaffirm Value</fullName>
            </value>
            <value>
                <fullName>Confirmed/Awaiting Bookings</fullName>
            </value>
            <value>
                <fullName>Submit Opportunity for BS Approval</fullName>
            </value>
            <value>
                <fullName>Submit Opportunity for CS Approval</fullName>
            </value>
            <value>
                <fullName>Develop Solution/ Proposal</fullName>
            </value>
            <value>
                <fullName>Present Solution/ Proposal</fullName>
            </value>
            <value>
                <fullName>Submit to BS for final concept approval</fullName>
            </value>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Re-affirm Value/Awaiting Bookings</fullName>
            </value>
            <value>
                <fullName>Review/Negotiate</fullName>
            </value>
            <value>
                <fullName>Walk-In Forecast</fullName>
            </value>
            <value>
                <fullName>Qualify Opportunity</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Select Product/s and Update Stage</fullName>
            </value>
            <value>
                <fullName>Develop Solution/Proposal</fullName>
            </value>
            <value>
                <fullName>Present Solution/Proposal</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Agreement Won</fullName>
            </value>
            <value>
                <fullName>Develop Solution</fullName>
            </value>
            <value>
                <fullName>Reaffirm Value</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/OpportunityCloneDeleteBatchTest.cls
@isTest
private class OpportunityCloneDeleteBatchTest {
	
	@isTest static void test_method_one() {
	
	 OpportunityReport__c testOpportunity = new OpportunityReport__c(name = 'testAccountForSalesOrderSupportTest',
                                          Stage__c='Qualify Opportunity',Close_Date__c=System.today().addYears(4));

  
 		insert testOpportunity;

 		Test.startTest();

        OpportunityCloneDeleteBatch obj = new OpportunityCloneDeleteBatch();
        DataBase.executeBatch(obj); 
            
        Test.stopTest();   



		// Implement test code
	}
	
	
	
}