News UAT/force-app/main/default/objects/AccountReport__c/AccountReport__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>AccountReport</label>
    <nameField>
        <label>AccountReport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountReports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/AccountReport__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Mark for Duplication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/AccountCloneDeleteBatch.cls
global class AccountCloneDeleteBatch implements Database.Batchable<sObject> {
	
	String query= 'Select id,Status__c FROM AccountReport__c where Status__c!=\'Active\'';
	global AccountCloneDeleteBatch() {
		 
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<AccountReport__c> scope) {
   		delete scope;
 	}
	
	global void finish(Database.BatchableContext BC) {
		AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
	      						TotalJobItems, CreatedBy.Email
	      						FROM AsyncApexJob WHERE Id =:BC.getJobId()];
	   // Send an email to the Apex job's submitter notifying of job completion.

		string subject = 'Batch Delete from the Custom Object AccountReport__c ' + a.Status;
		string body = 'The batch delete job for the object AccountReport__c processed ' + a.TotalJobItems +
	   ' batches with '+ a.NumberOfErrors + ' failures.';
		String[] toAddresses = new String[] {'shared_salesforce@news.com.au'};

		Batch_Utility.sendEmail(toAddresses,subject,body);
	}
	
}