News UAT/force-app/main/default/objects/AccountReport__c/AccountReport__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>AccountReport</label>
    <nameField>
        <label>AccountReport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountReports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/AccountReport__c/fields/AdPoint_Id__c.field-meta.xml
<CustomField>
    <fullName>AdPoint_Id__c</fullName>
    <externalId>true</externalId>
    <label>AdPoint Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/AccountReport__c/fields/Billing_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Status__c</fullName>
    <label>Billing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/AccountReport__c/fields/Is_Digital__c.field-meta.xml
<CustomField>
    <fullName>Is_Digital__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Turns this Account into a Digital Account - a corresponding Account is created in the Adpoint System.</description>
    <inlineHelpText>Check to enable this as a Digital Account and perform digital Adpoint Bookings. Once turned Digital, it cannot be unchecked.</inlineHelpText>
    <label>Is this a Digital Account?</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/AccountReport__c/fields/No_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>No_Parent_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to override the Parent Account required field</inlineHelpText>
    <label>No Parent Account</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/AccountReport__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Mark for Duplication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/AccountCloneDeleteBatchTest.cls
@isTest
private class AccountCloneDeleteBatchTest {
	
	@isTest static void test_method_one() {
	
	 AccountReport__c testAccount = new AccountReport__c(name = 'testAccountForSalesOrderSupportTest',
                                          Billing_Status__c = 'Green',
                                          No_Parent_Account__c = true,
                                          Is_Digital__c = true,
                                          Adpoint_Id__c = '99999',
                                          Status__c='Inactive');
  
 		insert testAccount;

 		Test.startTest();

        AccountCloneDeleteBatch obj = new AccountCloneDeleteBatch();
        DataBase.executeBatch(obj); 
            
        Test.stopTest();             
	
	}
	
		
}