News UAT/force-app/main/default/objects/External_Account__c/External_Account__c.object-meta.xml
<CustomObject>
    <description>Object to hold external accounts such as Billing and Booking Accounts</description>
    <label>Booking System Account</label>
    <nameField>
        <label>Booking System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking System Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/External_Account__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent External Account</description>
    <inlineHelpText>Parent External Account</inlineHelpText>
    <label>Parent Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Booking System Accounts</relationshipLabel>
    <relationshipName>External_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/JDE_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>JDE_Account_Number__c</fullName>
    <description>External Account JDE Number</description>
    <inlineHelpText>External Account JDE Number</inlineHelpText>
    <label>JDE Account Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/User/fields/Network_Username__c.field-meta.xml
<CustomField>
    <fullName>Network_Username__c</fullName>
    <description>Windows network username, for correlation with other systems (e.g. Genera, Global Viewpoint).</description>
    <externalId>true</externalId>
    <label>Network Username</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/GetStatementsController.cls
/**
* @description  GetStatementsController used in Lightning component GetStatementsCompController.js
* 
* @author       Paul Kang
* @date         2017-11-08
**/
public with sharing class GetStatementsController {

	@AuraEnabled
	public static String accessComputershare(Id recordId) {

		External_Account__c externalAccount = [SELECT Id, JDE_Account_Number__c FROM External_Account__c WHERE Id = :recordId];

		User user = [SELECT FirstName, LastName, Network_Username__c FROM User WHERE Id = :UserInfo.getUserId()];

		String token = GlobalViewPointGetToken.getAccessToken(externalAccount.JDE_Account_Number__c);

		//String token = GlobalViewPointGetToken.getAccessToken('3423706');
		System.debug('token returned in accessComputershare: ' + token);
		
		return token;
	}
}