News UAT/force-app/main/default/objects/Campaign_Response__c/Campaign_Response__c.object-meta.xml
<CustomObject>
    <description>Custom Object to store individual Campaign Responses by a Campaign Member.

Also serves as an integration object to Marketo.</description>
    <label>Campaign Response</label>
    <nameField>
        <displayFormat>CmpR-{0000}</displayFormat>
        <label>Campaign Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Campaign_Response__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Responses</relationshipLabel>
    <relationshipName>Campaign_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Campaign_Response__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Campaign Responses</relationshipLabel>
    <relationshipName>Campaign_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Lead/fields/LEAD__c.field-meta.xml
<CustomField>
    <fullName>LEAD__c</fullName>
    <displayFormat>LEAD{00000000}</displayFormat>
    <label>Lead SFDC ID</label>
    <type>AutoNumber</type>
</CustomField>

News UAT/force-app/main/default/classes/LeadManagement_Helper_Test.cls
@isTest
private class LeadManagement_Helper_Test 
{
    static testMethod void updateCampaignResponsesTest() 
    {
    	// create accounts
    	List<Account> accts = TestDataFactory.createAccounts(1, false);
    	insert accts;
    	
    	// create contacts
    	List<Contact> contacts = TestDataFactory.createContacts(1, accts[0]);
    	insert contacts;
    	
    	// create leads
    	List<Lead> leads = TestDataFactory.createLeads(1);
    	insert leads;
    	
    	// bind contact and lead together
    	

    	// create campaigns
    	List<Campaign> campaigns = TestDataFactory.createCampaigns(1);
    	insert campaigns;
    	
    	system.debug('@campaigns: ' + campaigns.size());
    	
    	// create campaign members
    	List<CampaignMember> campaignMembers = TestDataFactory.createCampaignMembers(1, leads, campaigns[0]);
    	insert campaignMembers;
    	
    	system.debug('@campaignMembers: ' + campaignMembers.size());
    	
    	// create campaign responses
    	List<Campaign_Response__c> campaignResps = TestDataFactory.createCampaignResponses(1, campaignMembers);
    	
    	
    	system.debug('@leads: ' + leads.size());
    	system.debug('@campaignResps: ' + campaignResps.size());
    	
    	// add lead into campaign responses
    	Integer i = 0;
    	for(Campaign_Response__c cr : campaignResps)
    	{
    		cr.Lead__c = leads[i].Id;
    		cr.Contact__c = null;
    		i++; 
    	}
    	
    	insert campaignResps;
    	
    	// convert leads to contacts
        List<Database.LeadConvert> lcs = new List<Database.LeadConvert>();
        
        i = 0;
        for(Lead l : leads)
        {
            Database.LeadConvert lc = new database.LeadConvert();
            lc.setLeadId(l.id);
            lc.setOwnerId(UserInfo.getUserId());
            lc.setConvertedStatus('Converted');
            //lc.setConvertedStatus('Qualified');
            lcs.add(lc);
            i++;
        }
        
        List<Database.LeadConvertResult> lcrs = Database.convertLead(lcs);
        
        for(Database.LeadConvertResult lcr : lcrs)
        {
            System.assert(lcr.isSuccess());
        }

    	// verify that contact has been added to campaign responses based on leads' contact
        /*for(Campaign_Response__c cr : campaignResps)
        {
            cr.Lead__c = leads[i].Id;
            cr.Contact__c = null;
            i++; 
        }*/
        
    }
}