News UAT/force-app/main/default/objects/Campaign_Response__c/Campaign_Response__c.object-meta.xml
<CustomObject>
    <description>Custom Object to store individual Campaign Responses by a Campaign Member.

Also serves as an integration object to Marketo.</description>
    <label>Campaign Response</label>
    <nameField>
        <displayFormat>CmpR-{0000}</displayFormat>
        <label>Campaign Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Campaign_Response__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Responses</relationshipLabel>
    <relationshipName>Campaign_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Campaign_Response__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Campaign Responses</relationshipLabel>
    <relationshipName>Campaign_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Lead/fields/LEAD__c.field-meta.xml
<CustomField>
    <fullName>LEAD__c</fullName>
    <displayFormat>LEAD{00000000}</displayFormat>
    <label>Lead SFDC ID</label>
    <type>AutoNumber</type>
</CustomField>

News UAT/force-app/main/default/classes/LeadManagement_Helper.cls
public without sharing class LeadManagement_Helper {

	public static void updateRelatedCampaignResponsesWithConvertedContact(set<Lead> leads)
	{
		map<Id,Id> contactIdByLeadId = new map<Id,Id>();

		for(Lead l : leads)
		{	//Just to be sure the leads passed as parameneter has been converted
			if(l.IsConverted && l.ConvertedContactId!=null)
			{
				contactIdByLeadId.put(l.id, l.ConvertedContactId);
			}
		}


		list<Campaign_Response__c> campaignResponsesToUpdate = new list<Campaign_Response__c>();
		for(Campaign_Response__c cr : [Select cr.Lead__c, cr.Contact__c From Campaign_Response__c cr Where cr.Lead__c IN : contactIdByLeadId.keySet()])
		{
			if(contactIdByLeadId.containsKey(cr.Lead__c))
			{
				cr.Contact__c = contactIdByLeadId.get(cr.Lead__c);
				campaignResponsesToUpdate.add(cr);
			}
		}

		if(campaignResponsesToUpdate.size()>0)
		{
			update campaignResponsesToUpdate;
		}

	}


}