News UAT/force-app/main/default/objects/Feature__c/Feature__c.object-meta.xml
<CustomObject>
    <description>Advertising &#39;Feature&#39; that is part of marketing Campaigns.</description>
    <label>Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Feature__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Business/Finance</fullName>
            </value>
            <value>
                <fullName>Careers</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Food/Drink</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Lifestyle</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Sport</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Feature__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <label>Feature Contact Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

News UAT/force-app/main/default/objects/Feature__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <inlineHelpText>Person to query regarding the Feature</inlineHelpText>
    <label>Feature Contact Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Feature__c/fields/Feature_Date__c.field-meta.xml
<CustomField>
    <fullName>Feature_Date__c</fullName>
    <label>Feature Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Feature__c/fields/Feature_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Feature_End_Date__c</fullName>
    <label>Feature End Date (optional)</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Feature__c/fields/Material_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Material_Deadline__c</fullName>
    <label>Material Deadline</label>
    <type>DateTime</type>
</CustomField>

News UAT/force-app/main/default/objects/Feature__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Adelaide Matters</fullName>
            </value>
            <value>
                <fullName>AdelaideNow</fullName>
            </value>
            <value>
                <fullName>advertiser.com.au</fullName>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Albert and Logan News - Fri</fullName>
            </value>
            <value>
                <fullName>Albert and Logan News - Wed</fullName>
            </value>
            <value>
                <fullName>Australian Golf Digest</fullName>
            </value>
            <value>
                <fullName>Ayr Advocate</fullName>
            </value>
            <value>
                <fullName>Bayside Leader</fullName>
            </value>
            <value>
                <fullName>Bayside Star</fullName>
            </value>
            <value>
                <fullName>Berwick Leader</fullName>
            </value>
            <value>
                <fullName>Best Recipes</fullName>
            </value>
            <value>
                <fullName>Best Weekend Magazine</fullName>
            </value>
            <value>
                <fullName>Big League</fullName>
            </value>
            <value>
                <fullName>birth.com.au</fullName>
            </value>
            <value>
                <fullName>Blacktown Advocate</fullName>
            </value>
            <value>
                <fullName>Body+Soul</fullName>
            </value>
            <value>
                <fullName>Bowen Independent</fullName>
            </value>
            <value>
                <fullName>Bribie Weekly</fullName>
            </value>
            <value>
                <fullName>Brimbank Leader</fullName>
            </value>
            <value>
                <fullName>Brisbane News</fullName>
            </value>
            <value>
                <fullName>Business Spectator</fullName>
            </value>
            <value>
                <fullName>Caboolture News</fullName>
            </value>
            <value>
                <fullName>Caboolture Shire Herald</fullName>
            </value>
            <value>
                <fullName>cairns.com.au</fullName>
            </value>
            <value>
                <fullName>Cairns Post</fullName>
            </value>
            <value>
                <fullName>Cairns Sun</fullName>
            </value>
            <value>
                <fullName>Canning Times</fullName>
            </value>
            <value>
                <fullName>Canterbury Bankstown Express</fullName>
            </value>
            <value>
                <fullName>Canvas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Feature__c/fields/Section_in_Product__c.field-meta.xml
<CustomField>
    <fullName>Section_in_Product__c</fullName>
    <label>Section in Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arts</fullName>
            </value>
            <value>
                <fullName>Big Wheels</fullName>
            </value>
            <value>
                <fullName>Body + Soul</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Career One</fullName>
            </value>
            <value>
                <fullName>CARSguide</fullName>
            </value>
            <value>
                <fullName>CM2</fullName>
            </value>
            <value>
                <fullName>Coastal &amp; Country Property</fullName>
            </value>
            <value>
                <fullName>Commercial Property</fullName>
            </value>
            <value>
                <fullName>Confidential</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Developments</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Escape</fullName>
            </value>
            <value>
                <fullName>Fashion</fullName>
            </value>
            <value>
                <fullName>Filler</fullName>
            </value>
            <value>
                <fullName>Food &amp; Wine</fullName>
            </value>
            <value>
                <fullName>Footy Central</fullName>
            </value>
            <value>
                <fullName>Form Guide</fullName>
            </value>
            <value>
                <fullName>General News</fullName>
            </value>
            <value>
                <fullName>Goss &amp; Glam</fullName>
            </value>
            <value>
                <fullName>Health &amp; Beauty</fullName>
            </value>
            <value>
                <fullName>HiT</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Insider</fullName>
            </value>
            <value>
                <fullName>Lifestyle</fullName>
            </value>
            <value>
                <fullName>Manufacture</fullName>
            </value>
            <value>
                <fullName>MegaWrap</fullName>
            </value>
            <value>
                <fullName>moneysaverHQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Feature__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <inlineHelpText>OPTIONAL. This field is automatically populated from the Product selected.</inlineHelpText>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ESB</fullName>
            </value>
            <value>
                <fullName>NAT</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Feature__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Multiple</fullName>
                <default>true</default>
                <label>Multiple</label>
            </value>
            <value>
                <fullName>App - Mobile</fullName>
            </value>
            <value>
                <fullName>App - Tablet</fullName>
            </value>
            <value>
                <fullName>Cross-platform</fullName>
            </value>
            <value>
                <fullName>Editorial - Local</fullName>
            </value>
            <value>
                <fullName>Editorial - Metro</fullName>
            </value>
            <value>
                <fullName>Editorial - Regional</fullName>
            </value>
            <value>
                <fullName>Magazine</fullName>
            </value>
            <value>
                <fullName>Marketing - Partnerships</fullName>
            </value>
            <value>
                <fullName>Marketing - Promotions</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Newspaper - Local</fullName>
            </value>
            <value>
                <fullName>Newspaper - Metro</fullName>
            </value>
            <value>
                <fullName>Newspaper - Regional</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Feature_Category_Colour__c/Feature_Category_Colour__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of Category and its Colour - for display in Feature Calendar</description>
    <label>Feature Category Colour</label>
</CustomObject>

News UAT/force-app/main/default/objects/Feature_Category_Colour__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <description>The colour of the Category, in Hex code</description>
    <inlineHelpText>The colour of the Category, in Hex code</inlineHelpText>
    <label>Colour</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/CtrlFeatureCalendar.cls
/**
* @company      Bluewolf
* @author       Noel Lim (noel.lim@bluewolf.com)
* @date         17/11/2014
* @description  Controller class for FeatureCalendar VF page
* - Remote method to update the Calendar via AJAX
* - Methods to build filter dropdowns and checkboxes
* - @todo remove Printable View
* @history
* - 20150216 added Feature End Date. This is an optional field, supported by FullCalendar as an optional field.
*/
global class CtrlFeatureCalendar {
    
    private static final String CSS_EVENT_TEXT_COLOR = '#ffffff';
    private static final String CSS_EVENT_BORDER_COLOR = '#000000';
    private static final String CSS_EVENT_DEFAULT_BACKGROUND_COLOR = '#3a87ad';
    
    public String featureNameFilter {get; set;}
    public String productFilter {get; set;}
    public String sectionFilter {get; set;}    
    public Date startDateFilter {get; private set;}   
    public Date endDateFilter {get; private set;}   
    public Map<String, List<String>> checkboxFilterMap {get; private set;}
    
    public Map<String, String> categoryColours{
        get{
            
            Map<String, Feature_Category_Colour__c> custSettingCatColour = Feature_Category_Colour__c.getAll();
            
            Map<String, String> mapCategoryColour = new Map<String, String>();
            for(String id : custSettingCatColour.keySet()){
                mapCategoryColour.put(custSettingCatColour.get(id).Name, custSettingCatColour.get(id).Colour__c);
            }        
    
            return mapCategoryColour;
        }
        set;
    }
    
    
    
    //CONSTRUCTOR
    public CtrlFeatureCalendar() {        
        buildCheckboxFilters();
    }
    
    /**
     * Queries Features to display in the Calendar based on date range and filters.
     *
     * Checkbox filters are received as JSON.
     */
    @RemoteAction    
    global static String getJSONFeatures(String strStartDate, String strEndDate, 
                        String featureNameFilterR, String productFilterR, String sectionFilterR, String strSDFilter, String strEDFilter, String jsonCheckboxFilters) {    
        
        Date startDate = Date.valueOf(strStartDate);
        Date endDate = Date.valueOf(strEndDate);
        
        if(strSDFilter != ''){
           startDate = Date.valueOf(strSDFilter);
        }
        if(strEDFilter != '')  {
           endDate = Date.valueOf(strEDFilter);
        }

        
        //QUERYSTRING - Feature End Date is optional
        String featureQuery = 'SELECT Name, Feature_Date__c, Feature_End_Date__c, Product__c, Contact_Name__c, Contact_Email__c, Material_Deadline__c, Category__c ' +
                               'FROM Feature__c WHERE ((Feature_Date__c >= :startDate AND Feature_Date__c <= :endDate) OR (Feature_End_Date__c >= :startDate AND Feature_End_Date__c <= :endDate))';

        if(featureNameFilterR != ''){
            featureQuery += ' AND Name LIKE \'%' + String.escapeSingleQuotes(featureNameFilterR) + '%\'';
        }
        if(productFilterR != ''){
            featureQuery += ' AND Product__c = \'' + String.escapeSingleQuotes(productFilterR) + '\'';
        }
        if(sectionFilterR != ''){
            featureQuery += ' AND Section_in_Product__c = \'' + String.escapeSingleQuotes(sectionFilterR) + '\'';
        }
        
        //System.debug(LoggingLevel.DEBUG, 'getJSONFeatures - query is ' + featureQuery);        
        
        Map<String, Object> mapDeserializedCF = (Map<String, Object>) JSON.deserializeUntyped(jsonCheckboxFilters);
        for(String filter : mapDeserializedCF.keySet()) {
            
            string clause = filter == 'Type' || filter == 'Status' ?'IN':'INCLUDES';
            
            Map<String,Object> mapFilterOption = (Map<String,Object>) mapDeserializedCF.get(filter);
            if(!mapFilterOption.isEmpty()){
                featureQuery += ' AND ' + filter + '__c ' + clause + ' (';
                Integer filterOptionSize = mapFilterOption.size();
                Integer count = 0;
                
                for(String filterOption : mapFilterOption.keySet()){
                    featureQuery += '\''+filterOption+'\'';
                    count++;
                    if(count < filterOptionSize)
                        featureQuery += ',';
                    else
                        featureQuery += ')';
                } 
            }
        }
        
        //BUILD and RETURN DATA
        List<Feature__c> features = Database.query(featureQuery);                
        List<FullCalendarEvent> fcEvents = new List<FullCalendarEvent>();  
        List<Feature_Category_Colour__c> lstCategory= new List<Feature_Category_Colour__c>([SELECT Name, Colour__c FROM Feature_Category_Colour__c LIMIT 100]);
        
        Map<String, String> mapCategoryColour = new Map<String, String>();
        for(Feature_Category_Colour__c categoryColour : lstCategory){
            mapCategoryColour.put(categoryColour.Name, categoryColour.Colour__c);
        }
              
        for(Feature__c feature : features)
        {
            FullCalendarEvent fce = new FullCalendarEvent();
            fce.title = feature.Name;
            fce.start = feature.Feature_Date__c;
            fce.endDate = feature.Feature_End_Date__c;
            fce.allDay = true;
            fce.url = URL.getSalesforceBaseUrl().toExternalForm() + '/' + feature.Id;
            fce.backgroundColor = mapCategoryColour.containsKey(feature.Category__c) ? mapCategoryColour.get(feature.Category__c) : CSS_EVENT_DEFAULT_BACKGROUND_COLOR;
            fce.borderColor = CSS_EVENT_BORDER_COLOR;
            fce.textColor = CSS_EVENT_TEXT_COLOR;
            
            fce.product = feature.Product__c;
            fce.contactName = feature.Contact_Name__c;
            fce.contactEmail = feature.Contact_Email__c;
            fce.materialDeadline = feature.Material_Deadline__c;
            fce.category = feature.Category__c;

            fcEvents.add(fce);
        }
        String jsonFCE = JSON.serializePretty(fcEvents);
        
        return jsonFCE;
    }

    //TODO refactor filterOption
    public List<SelectOption> getProductFilterOptions(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('',''));
        
        Schema.DescribeFieldResult fieldResult = Feature__c.Product__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
        for( Schema.PicklistEntry f : ple)
        {
          options.add(new SelectOption(f.getLabel(), f.getValue()));
        }

        return options;
    }

    //TODO refactor filterOption
    public List<SelectOption> getSectionFilterOptions(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('',''));
        
        Schema.DescribeFieldResult fieldResult = Feature__c.Section_in_Product__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
        for( Schema.PicklistEntry f : ple)
        {
          options.add(new SelectOption(f.getLabel(), f.getValue()));
        }

        return options;
    }

    /**
     * Build the Checkbox filters for loop rendering
     */
    private void buildCheckboxFilters(){

        checkboxFilterMap = new Map<String, List<String>>();
        List<String> pickVals;
        Schema.DescribeFieldResult fieldResult;
        List<Schema.PicklistEntry> ple;
        
        //STATE picklist
        fieldResult = Feature__c.State__c.getDescribe();
        ple = fieldResult.getPicklistValues();
        
        pickVals = new List<String>();
            
        for( Schema.PicklistEntry f : ple)
        {
            pickVals.add(f.getValue());
        }
        checkboxFilterMap.put('State', pickVals);
        
        //TYPE picklist
        fieldResult = Feature__c.Type__c.getDescribe();
        ple = fieldResult.getPicklistValues();
        
        pickVals = new List<String>();
            
        for( Schema.PicklistEntry f : ple)
        {
            pickVals.add(f.getValue());
        }
        checkboxFilterMap.put('Type', pickVals);
        
        //CATEGORY picklist
        fieldResult = Feature__c.Category__c.getDescribe();
        ple = fieldResult.getPicklistValues();
        
        pickVals = new List<String>();
            
        for( Schema.PicklistEntry f : ple)
        {
            pickVals.add(f.getValue());
        }
        checkboxFilterMap.put('Category', pickVals);
        
        //AUDIENCE picklist
        fieldResult = Feature__c.Audience__c.getDescribe();
        ple = fieldResult.getPicklistValues();
        
        pickVals = new List<String>();
            
        for( Schema.PicklistEntry f : ple)
        {
            pickVals.add(f.getValue());
        }
        checkboxFilterMap.put('Audience', pickVals);
        
        //STATUS picklist
        fieldResult = Feature__c.Status__c.getDescribe();
        ple = fieldResult.getPicklistValues();
        
        pickVals = new List<String>();
            
        for( Schema.PicklistEntry f : ple)
        {
            pickVals.add(f.getValue());
        }
        checkboxFilterMap.put('Status', pickVals);
    }
    
    /**
     * Represents the FullCalendar's Event data model, assist in JSON and APEX Remoting
     */
    public class FullCalendarEvent {

        public FullCalendarEvent() {
            
        }

        // Properties for use in the Visualforce view
        public String title {get; set;}        
        public DateTime start {get; set;}
        public DateTime endDate {get; set;} //This preferably would be 'end' but it's an APEX keyword        
        public Boolean allDay{get; set;}        
        public String url{get; set;}        
        public String textColor{get; set;}        
        public String backgroundColor{get; set;}        
        public String borderColor{get; set;}
        
        //non-Full Calendar fields
        public String product{get; set;}
        public String contactName{get; set;}
        public String contactEmail{get; set;}
        public DateTime materialDeadline{get; set;}
        public String category{get; set;}
    }
       
    
}