News UAT/force-app/main/default/objects/Feature__c/Feature__c.object-meta.xml
<CustomObject>
    <description>Advertising &#39;Feature&#39; that is part of marketing Campaigns.</description>
    <label>Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Feature__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Adelaide Matters</fullName>
            </value>
            <value>
                <fullName>AdelaideNow</fullName>
            </value>
            <value>
                <fullName>advertiser.com.au</fullName>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Albert and Logan News - Fri</fullName>
            </value>
            <value>
                <fullName>Albert and Logan News - Wed</fullName>
            </value>
            <value>
                <fullName>Australian Golf Digest</fullName>
            </value>
            <value>
                <fullName>Ayr Advocate</fullName>
            </value>
            <value>
                <fullName>Bayside Leader</fullName>
            </value>
            <value>
                <fullName>Bayside Star</fullName>
            </value>
            <value>
                <fullName>Berwick Leader</fullName>
            </value>
            <value>
                <fullName>Best Recipes</fullName>
            </value>
            <value>
                <fullName>Best Weekend Magazine</fullName>
            </value>
            <value>
                <fullName>Big League</fullName>
            </value>
            <value>
                <fullName>birth.com.au</fullName>
            </value>
            <value>
                <fullName>Blacktown Advocate</fullName>
            </value>
            <value>
                <fullName>Body+Soul</fullName>
            </value>
            <value>
                <fullName>Bowen Independent</fullName>
            </value>
            <value>
                <fullName>Bribie Weekly</fullName>
            </value>
            <value>
                <fullName>Brimbank Leader</fullName>
            </value>
            <value>
                <fullName>Brisbane News</fullName>
            </value>
            <value>
                <fullName>Business Spectator</fullName>
            </value>
            <value>
                <fullName>Caboolture News</fullName>
            </value>
            <value>
                <fullName>Caboolture Shire Herald</fullName>
            </value>
            <value>
                <fullName>cairns.com.au</fullName>
            </value>
            <value>
                <fullName>Cairns Post</fullName>
            </value>
            <value>
                <fullName>Cairns Sun</fullName>
            </value>
            <value>
                <fullName>Canning Times</fullName>
            </value>
            <value>
                <fullName>Canterbury Bankstown Express</fullName>
            </value>
            <value>
                <fullName>Canvas</fullName>
            </value>
            <value>
                <fullName>Darwin Sun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Feature__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <inlineHelpText>OPTIONAL. This field is automatically populated from the Product selected.</inlineHelpText>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ESB</fullName>
            </value>
            <value>
                <fullName>NAT</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Feature_Product_State__c/Feature_Product_State__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Map to determine State based on Product</description>
    <label>Feature Product State</label>
</CustomObject>

News UAT/force-app/main/default/objects/Feature_Product_State__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/FeatureTriggerHandler_Test.cls
/************************************************************************
/* class FeatureTriggerHandler_Test
/* description: test class for FeatureTriggerHandler
/* date: 13/02/2015
/* author: Noel Lim
/************************************************************************/
@isTest
private class FeatureTriggerHandler_Test {

    
    static testmethod void runTest(){

        TestDataFactory.createFeatureProdState();
         Map<String, Feature_Product_State__c> fpsCustomSetting = Feature_Product_State__c.getAll();
        System.assertEquals(fpsCustomSetting.size(), 2);

        Feature__c feat = TestDataFactory.createFeature();

        for(Feature__c tempF : [Select State__c From Feature__c
                         Where Id=:feat.Id LIMIT 1])
        {
            System.assertEquals('NSW', tempF.State__c);
        }

        //State does not change if it has a value
        feat.Product__c = 'Darwin Sun';
        update feat;
        for(Feature__c tempF : [Select State__c From Feature__c
                         Where Id=:feat.Id LIMIT 1])
        {
            System.assertEquals('NSW', tempF.State__c);
        }

        //State changes when set to empty
        feat.State__c = '';
        update feat;
        for(Feature__c tempF : [Select State__c From Feature__c
                         Where Id=:feat.Id LIMIT 1])
        {
            System.assertEquals('NT', tempF.State__c);
        }

    }

}