News UAT/force-app/main/default/objects/Division_Info__c/Division_Info__c.object-meta.xml
<CustomObject>
    <description>Information about each division used by Ad Proofing Emails</description>
    <label>Division Information</label>
    <nameField>
        <label>Division Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Division_Info__c/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <label>ABN</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Division_Info__c/fields/Disclaimer__c.field-meta.xml
<CustomField>
    <fullName>Disclaimer__c</fullName>
    <label>Disclaimer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

News UAT/force-app/main/default/objects/Division_Info__c/fields/SwitchBoard__c.field-meta.xml
<CustomField>
    <fullName>SwitchBoard__c</fullName>
    <label>Switch Board</label>
    <type>TextArea</type>
</CustomField>

News UAT/force-app/main/default/classes/EmailTemplate_Controller_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes 'EmailTemplate_Controller'
 * and triggers.
 *
 * History:
 * 19/10/2013  Bohao Chen  Created
 * ---------------------------------------------------------*/
@isTest
private class EmailTemplate_Controller_Test 
{
    static testMethod void emailTemplateComponentTest() 
    {

    	list<Division_Info__c> dis = TestDataFactory.createDivisionInformation();
    	insert dis;


    	EmailTemplate_Controller controller = new EmailTemplate_Controller();

		controller.divisionName = dis[0].Name;


		id folderId = [Select Id from Folder where Name='Logos & Identity' limit 1].id; 


		Document doc = new Document();
		doc.AuthorId = UserInfo.getUserId();
		doc.FolderId = folderId;
		doc.name = dis[0].Name + ' Logo';
		doc.body = Blob.valueOf('My image');
		insert doc;

		String logoId = controller.getLogoId();

		String orgId = controller.getOrgId();

		String divAddress = controller.getDivisionAddress();
		System.Assert(divAddress == dis[0].Address__c);


		String switchboard = controller.getSwitchboard();
		System.Assert(switchboard == dis[0].SwitchBoard__c);	
		

		String abn = controller.getAbn();
		System.Assert(abn == dis[0].Abn__c);


		String disclaimer = controller.getDisclaimer();
		System.Assert(disclaimer == dis[0].Disclaimer__c);		


		controller.divisionName = 'invalid division name';
		try{
			divAddress = controller.getDivisionAddress();
		}catch(Exception ex){
			System.Assert(divAddress == null);
		}

		try{
			switchboard = controller.getSwitchboard();
		}catch(Exception ex){
			System.Assert(switchboard == null);
		}

 		try{
			abn = controller.getAbn();
		}catch(Exception ex){
			System.Assert(abn == null);
		}       
   
 		try{
			disclaimer = controller.getDisclaimer();
		}catch(Exception ex){
			System.Assert(disclaimer == null);
		}      
    }
}