News UAT/force-app/main/default/objects/Campaign/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Asset_Staging__c/NXX2_Asset_Staging__c.object-meta.xml
<CustomObject>
    <description>This will contain record of google cloud storage assets.</description>
    <label>NXX2 Asset Staging</label>
    <nameField>
        <label>NXX2 Asset Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NXX2 Assets Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_Asset_Staging__c/fields/Asset_Size__c.field-meta.xml
<CustomField>
    <fullName>Asset_Size__c</fullName>
    <label>Asset Size</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Asset_Staging__c/fields/Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Type__c</fullName>
    <label>Asset Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Asset_Staging__c/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <label>Content Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Asset_Staging__c/fields/Headline__c.field-meta.xml
<CustomField>
    <fullName>Headline__c</fullName>
    <label>Headline</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Asset_Staging__c/fields/Related_Proof__c.field-meta.xml
<CustomField>
    <fullName>Related_Proof__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Proof</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipLabel>NXX2 Assets Staging</relationshipLabel>
    <relationshipName>NXX2_Assets_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Asset_Staging__c/fields/Related_Proof_Ad__c.field-meta.xml
<CustomField>
    <fullName>Related_Proof_Ad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Proof Ad</label>
    <referenceTo>SocialAd__c</referenceTo>
    <relationshipLabel>NXX2 Assets Staging</relationshipLabel>
    <relationshipName>NXX2_Assets_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Asset_Staging__c/fields/Seq_No__c.field-meta.xml
<CustomField>
    <fullName>Seq_No__c</fullName>
    <label>Seq No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Proof_Staging__c/NXX2_Proof_Staging__c.object-meta.xml
<CustomObject>
    <description>This will contain proof records of google cloud storage.</description>
    <label>NXX2 Proof Staging</label>
    <nameField>
        <label>NXX2 Campaign Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NXX2 Proofs Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_Proof_Staging__c/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <label>GUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Proof_Staging__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Proof_Staging__c/fields/Related_Proof__c.field-meta.xml
<CustomField>
    <fullName>Related_Proof__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Actual proof which is created for this staging proof.</description>
    <label>Related Proof</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipLabel>NXX2 Proofs Staging</relationshipLabel>
    <relationshipName>NXX2_Proofs_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/NXX2_ProofAd_Staging__c.object-meta.xml
<CustomObject>
    <description>This will contain records of proof ads from google cloud storage</description>
    <label>NXX2 ProofAd Staging</label>
    <nameField>
        <label>NXX2 ProofAd Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NXX2 ProofAds Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/fields/Creative_Type__c.field-meta.xml
<CustomField>
    <fullName>Creative_Type__c</fullName>
    <label>Creative Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <label>External Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/fields/Has_Merged__c.field-meta.xml
<CustomField>
    <fullName>Has_Merged__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be used to identify whether a record has been moved to standard object or not.</description>
    <label>Has Merged</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/fields/Related_ProofAd__c.field-meta.xml
<CustomField>
    <fullName>Related_ProofAd__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will link to actual proof ad</description>
    <label>Related ProofAd</label>
    <referenceTo>SocialAd__c</referenceTo>
    <relationshipLabel>NXX2 ProofAds Staging</relationshipLabel>
    <relationshipName>NXX2_ProofAds_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Social_Ad_Content__c/Social_Ad_Content__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Proof Ad Content</label>
    <nameField>
        <displayFormat>PAC-{000000}</displayFormat>
        <label>Proof Ad Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proof Ad Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Social_Ad_Content__c/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <description>This will decide the order of the content in social ad</description>
    <label>Display Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/Social_Ad_Content__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <description>This will contain the name of file uploaded for ad</description>
    <inlineHelpText>This will contain the name of file uploaded for ad</inlineHelpText>
    <label>File Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Social_Ad_Content__c/fields/File_Size__c.field-meta.xml
<CustomField>
    <fullName>File_Size__c</fullName>
    <description>This will contain the size of file uploaded for ad</description>
    <inlineHelpText>This will contain the size of file uploaded for ad</inlineHelpText>
    <label>File Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/Social_Ad_Content__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <description>This will contain the type of file uploaded for ad</description>
    <inlineHelpText>This will contain the type of file uploaded for ad</inlineHelpText>
    <label>File Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Social_Ad_Content__c/fields/GoogleDrive_File_Id__c.field-meta.xml
<CustomField>
    <fullName>GoogleDrive_File_Id__c</fullName>
    <description>FileId for the uploaded file in google drive</description>
    <label>GoogleDrive File Id</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Social_Ad_Content__c/fields/Social_Ad__c.field-meta.xml
<CustomField>
    <fullName>Social_Ad__c</fullName>
    <label>Social Ad</label>
    <referenceTo>SocialAd__c</referenceTo>
    <relationshipName>Social_Ad_Contents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/SocialAd__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Proof Ad</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>ProofAd Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proof Ads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Creative_Type__c.field-meta.xml
<CustomField>
    <fullName>Creative_Type__c</fullName>
    <description>This will be used for format of facebook ad</description>
    <inlineHelpText>This will be used for format of facebook ad</inlineHelpText>
    <label>Creative Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Ad_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single image</fullName>
            </value>
            <value>
                <fullName>Carousel</fullName>
            </value>
            <value>
                <fullName>Slideshow</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Social_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Social_Campaign__c</fullName>
    <description>Parent Proof</description>
    <inlineHelpText>Parent Proof</inlineHelpText>
    <label>Proof</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipLabel>Proff Ads</relationshipLabel>
    <relationshipName>Social_Ads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/classes/NXX2_CreateProofAdContentFromStaging.cls
/**
* @author       Kamal Sharma
* @date         2019-01-14
* @className	NXX2_CreateProofAdContentFromStaging
* @description  This class will be used to create actual proof Ad records for staging proof Ads.  
*/
global class NXX2_CreateProofAdContentFromStaging implements Database.Batchable<sObject>,Database.Stateful,Database.AllowsCallouts{
    /**
    * @author       Kamal Sharma
	* @date         2019-01-14
    * @description  Start method implementation of Batch interface
    * @param        Database.BatchableContext BC
    * @return       Database.QueryLocator
    */
    global Database.QueryLocator start(Database.BatchableContext BC){
        //Fetch All the staging task Recods which are related to product order.
        return Database.getQueryLocator([SELECT Asset_Size__c,Asset_Type__c,Campaign_Id__c,Content_Type__c,
                                         External_Id__c,File_Name__c,Has_Merged__c,Headline__c,Parent_Id__c,
                                         Processing_Status__c,Error_Message__c,Error_Details__c,Related_Proof_Ad__c,
                                         Path__c,Seq_No__c,GUID__c,Related_Proof__c
                                         FROM NXX2_Asset_Staging__c 
                                         WHERE Has_Merged__c = false 
                                         AND GUID__c != null AND GUID__c != '']);
    }
    
    /**
    * @author       Kamal Sharma
	* @date         2019-01-14
    * @description  execute method implementation of Batch interface
    * @param        Database.BatchableContext BC, List<sObject> scope
    * @return       void
    */
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        try{
        	processAssetRecords((List<NXX2_Asset_Staging__c>)scope);
        }catch(Exception e){
            for(NXX2_Asset_Staging__c asset : (List<NXX2_Asset_Staging__c>)scope){
                asset.Processing_Status__c = 'Error';
                asset.Error_Message__c = 'Exception Occured!';
                asset.Error_Details__c = e.getMessage();
            }
            update scope;
        }
    }
    
    /**
    * @author       Kamal Sharma
	* @date         2019-01-14
    * @description  This method will process all staging task records to create proof records.
    * @param        List<NXX2_Asset_Staging__c> stagingAssets
    * @return       void
    */
    public void processAssetRecords(List<NXX2_Asset_Staging__c> stagingAssets){
		Set<String> stagingProofAdIds = new Set<String>();
        for(NXX2_Asset_Staging__c stagingAsset : stagingAssets){
            stagingProofAdIds.add(stagingAsset.Parent_Id__c);
            stagingAsset.Has_Merged__c = true;
            stagingAsset.Processing_Status__c = 'Success';
        }
        Map<String,NXX2_ProofAd_Staging__c> stagingProofAdIdToActualProofAdIdMap = new Map<String,NXX2_ProofAd_Staging__c>();
        for(NXX2_ProofAd_Staging__c stagingProofAd : [SELECT Related_ProofAd__c,External_Id__c,
                                                      Related_ProofAd__r.Creative_Type__c,
                                                      Related_ProofAd__r.Social_Campaign__c
                                                      FROM NXX2_ProofAd_Staging__c 
                                                      WHERE Related_ProofAd__c != null 
                                                      AND External_Id__c IN :stagingProofAdIds]){
            stagingProofAdIdToActualProofAdIdMap.put(stagingProofAd.External_Id__c,stagingProofAd);
        }
        Map<String,Id> stagingProofIdToActualProofIdMap = new Map<String,Id>();
        for(NXX2_Proof_Staging__c stagingProofAd : [SELECT Related_Proof__c,External_Id__c 
                                                    FROM NXX2_Proof_Staging__c 
                                                    WHERE Related_Proof__c != null 
                                                    AND External_Id__c IN :stagingProofAdIds]){
            stagingProofIdToActualProofIdMap.put(stagingProofAd.External_Id__c,stagingProofAd.Related_Proof__c);
        }
        system.debug('*****stagingProofAdIdToActualProofAdIdMap*****'+stagingProofAdIdToActualProofAdIdMap);
        system.debug('*****stagingProofIdToActualProofIdMap*****'+stagingProofIdToActualProofIdMap);
        List<Social_Ad_Content__c> proofAdContents = new List<Social_Ad_Content__c>();
        for(NXX2_Asset_Staging__c stagingAsset : stagingAssets){
            system.debug('*****Asset CampaignId*****'+stagingAsset.Campaign_Id__c);
            system.debug('*****Asset PARENTID*****'+stagingAsset.Parent_Id__c);
            system.debug('*****Asset RelatedProof*****'+stagingProofAdIdToActualProofAdIdMap.get(stagingAsset.Parent_Id__c));
            system.debug('*****Asset GUID*****'+stagingAsset.GUID__c);
            if(stagingProofAdIdToActualProofAdIdMap.containsKey(stagingAsset.Parent_Id__c)){
                NXX2_ProofAd_Staging__c stagingAd = stagingProofAdIdToActualProofAdIdMap.get(stagingAsset.Parent_Id__c);
                String googleDriveFileId = NXX2_GoogleDriveDataMigrationService.processFileMigration(stagingAd.Related_ProofAd__c, stagingAsset.GUID__c);
                system.debug('*****Asset googleDriveFileId*****'+googleDriveFileId);
                if(googleDriveFileId != null){                
                    proofAdContents.add(new Social_Ad_Content__c(
                        Display_Order__c = stagingAsset.Seq_No__c == null ? 1 : Decimal.valueOf(stagingAsset.Seq_No__c),
                        File_Name__c  = stagingAsset.File_Name__c,
                        File_Size__c = stagingAsset.Asset_Size__c == null ? 0 : Decimal.valueOf(stagingAsset.Asset_Size__c),
                        File_Type__c = stagingAsset.Content_Type__c,
                        Social_Ad__c = stagingAd.Related_ProofAd__c,
                        GoogleDrive_File_Id__c = googleDriveFileId,
                        Created_From_Staging__c = true
                    ));
                    stagingAsset.Related_Proof_Ad__c = stagingAd.Related_ProofAd__c;
                    stagingAsset.Related_Proof__c = stagingAd.Related_ProofAd__r.Social_Campaign__c;
                }else{
                    stagingAsset.Processing_Status__c = 'Error';
                    stagingAsset.Error_Message__c = 'File does not exist in google drive';
                    stagingAsset.Error_Details__c = 'File does not exist in google drive';
                }
            }else if(stagingProofIdToActualProofIdMap.containsKey(stagingAsset.Parent_Id__c)){
                NXX2_GoogleDriveDataMigrationService.processFileMigration(stagingProofIdToActualProofIdMap.get(stagingAsset.Parent_Id__c), stagingAsset.GUID__c);
            	stagingAsset.Related_Proof__c = stagingProofIdToActualProofIdMap.get(stagingAsset.Parent_Id__c);
            }else{
                stagingAsset.Processing_Status__c = 'Error';
                stagingAsset.Error_Message__c = 'Parent Id do not have any related object.';
                stagingAsset.Error_Details__c = 'Parent Id which may be socialAd Id or Campaign Id does not belong to any actual proof ad or proof.';
            }
        }
        system.debug('*****ProofAdContents*****'+proofAdContents);
        insert proofAdContents;
        update stagingAssets;
    }
    
    /**
    * @author       Kamal Sharma
	* @date         2019-01-14
    * @description  finish method implementation of Batch interface
    * @param        Database.BatchableContext BC
    * @return       void
    */
    global void finish(Database.BatchableContext BC){
        NXX2_CreateSocialFormFromStaging b = new NXX2_CreateSocialFormFromStaging();
        database.executebatch(b,1);
    }
}