News UAT/force-app/main/default/objects/Campaign/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Proof_Staging__c/NXX2_Proof_Staging__c.object-meta.xml
<CustomObject>
    <description>This will contain proof records of google cloud storage.</description>
    <label>NXX2 Proof Staging</label>
    <nameField>
        <label>NXX2 Campaign Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NXX2 Proofs Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_Proof_Staging__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Proof_Staging__c/fields/Related_Proof__c.field-meta.xml
<CustomField>
    <fullName>Related_Proof__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Actual proof which is created for this staging proof.</description>
    <label>Related Proof</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipLabel>NXX2 Proofs Staging</relationshipLabel>
    <relationshipName>NXX2_Proofs_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/NXX2_ProofAd_Staging__c.object-meta.xml
<CustomObject>
    <description>This will contain records of proof ads from google cloud storage</description>
    <label>NXX2 ProofAd Staging</label>
    <nameField>
        <label>NXX2 ProofAd Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NXX2 ProofAds Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/fields/Button_Type__c.field-meta.xml
<CustomField>
    <fullName>Button_Type__c</fullName>
    <description>Button Type</description>
    <label>Button Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/fields/Creative_Type__c.field-meta.xml
<CustomField>
    <fullName>Creative_Type__c</fullName>
    <label>Creative Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <label>External Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/fields/Has_Merged__c.field-meta.xml
<CustomField>
    <fullName>Has_Merged__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be used to identify whether a record has been moved to standard object or not.</description>
    <label>Has Merged</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <label>Link</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/fields/Related_ProofAd__c.field-meta.xml
<CustomField>
    <fullName>Related_ProofAd__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will link to actual proof ad</description>
    <label>Related ProofAd</label>
    <referenceTo>SocialAd__c</referenceTo>
    <relationshipLabel>NXX2 ProofAds Staging</relationshipLabel>
    <relationshipName>NXX2_ProofAds_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <formula>MID(  Full_Text__c  , 0, 90)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Text</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/SocialAd__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Proof Ad</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>ProofAd Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proof Ads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Ad_Headline__c.field-meta.xml
<CustomField>
    <fullName>Ad_Headline__c</fullName>
    <description>This field will have headline for facebook ad</description>
    <inlineHelpText>This field will have headline for facebook ad</inlineHelpText>
    <label>Ad Headline</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Ad_Link__c.field-meta.xml
<CustomField>
    <fullName>Ad_Link__c</fullName>
    <description>This field will have link for facebook ad</description>
    <inlineHelpText>This field will have link for facebook ad</inlineHelpText>
    <label>Ad Link</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Ad_Newsfeed_Link_Description__c.field-meta.xml
<CustomField>
    <fullName>Ad_Newsfeed_Link_Description__c</fullName>
    <description>This field will have Newsfeed Link Description for facebook ad</description>
    <inlineHelpText>This field will have Newsfeed Link Description for facebook ad</inlineHelpText>
    <label>Ad Newsfeed Link Description</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Ad_Text__c.field-meta.xml
<CustomField>
    <fullName>Ad_Text__c</fullName>
    <description>This field will have Text for facebook ad</description>
    <inlineHelpText>This field will have Text for facebook ad</inlineHelpText>
    <label>Ad Text</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Ad_Type__c.field-meta.xml
<CustomField>
    <fullName>Ad_Type__c</fullName>
    <description>These are the available ad types for facebook ad</description>
    <inlineHelpText>This ad type will be used as an objective for facebook ad.</inlineHelpText>
    <label>Ad Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand Awareness</fullName>
            </value>
            <value>
                <fullName>Conversion</fullName>
            </value>
            <value>
                <fullName>Event Response</fullName>
            </value>
            <value>
                <fullName>Engagement</fullName>
            </value>
            <value>
                <fullName>Lead Generation</fullName>
            </value>
            <value>
                <fullName>Reach</fullName>
            </value>
            <value>
                <fullName>Traffic</fullName>
            </value>
            <value>
                <fullName>Video Views</fullName>
            </value>
            <value>
                <fullName>Messenger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Button_Type__c.field-meta.xml
<CustomField>
    <fullName>Button_Type__c</fullName>
    <description>This will be used to add action on facebook ad</description>
    <inlineHelpText>This will be used to add action on facebook ad</inlineHelpText>
    <label>Button Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Ad_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Download</fullName>
            </value>
            <value>
                <fullName>Get Directions</fullName>
            </value>
            <value>
                <fullName>Get Showtimes</fullName>
            </value>
            <value>
                <fullName>Learn More</fullName>
            </value>
            <value>
                <fullName>Send Message</fullName>
            </value>
            <value>
                <fullName>Request Time</fullName>
            </value>
            <value>
                <fullName>Save</fullName>
            </value>
            <value>
                <fullName>See Menu</fullName>
            </value>
            <value>
                <fullName>Show Now</fullName>
            </value>
            <value>
                <fullName>Sign Up</fullName>
            </value>
            <value>
                <fullName>Watch More</fullName>
            </value>
            <value>
                <fullName>Listen Now</fullName>
            </value>
            <value>
                <fullName>Apply Now</fullName>
            </value>
            <value>
                <fullName>Book Now</fullName>
            </value>
            <value>
                <fullName>Call Now</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>Subscribe</fullName>
            </value>
            <value>
                <fullName>Get Quote</fullName>
            </value>
            <value>
                <fullName>Donate Now</fullName>
            </value>
            <value>
                <fullName>Shop Now</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Get Offer</fullName>
            </value>
            <value>
                <fullName>Send WhatsApp Message</fullName>
            </value>
            <value>
                <fullName>Preregister</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Creative_Type__c.field-meta.xml
<CustomField>
    <fullName>Creative_Type__c</fullName>
    <description>This will be used for format of facebook ad</description>
    <inlineHelpText>This will be used for format of facebook ad</inlineHelpText>
    <label>Creative Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Ad_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single image</fullName>
            </value>
            <value>
                <fullName>Carousel</fullName>
            </value>
            <value>
                <fullName>Slideshow</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <description>Event Name</description>
    <label>Event Name</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Social_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Social_Campaign__c</fullName>
    <description>Parent Proof</description>
    <inlineHelpText>Parent Proof</inlineHelpText>
    <label>Proof</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipLabel>Proff Ads</relationshipLabel>
    <relationshipName>Social_Ads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Internal QA</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>With Customer</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
                <isActive>false</isActive>
                <label>In-Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/SocialCampaign__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Proof</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proofs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/SocialCampaign__c/fields/Created_From_Staging__c.field-meta.xml
<CustomField>
    <fullName>Created_From_Staging__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be checked if this record is created from staging record.</description>
    <label>Created From Staging</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Internal QA</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>With Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/recordTypes/Social.recordType-meta.xml
<RecordType>
    <fullName>Social</fullName>
    <active>true</active>
    <description>Record with social ad</description>
    <label>Social</label>
</RecordType>

News UAT/force-app/main/default/classes/NXX2_CreateProofAdFromStagingData.cls
/**
* @author       Kamal Sharma
* @date         2019-01-14
* @className    NXX2_CreateProofAdFromStagingData
* @description  This class will be used to create actual proof Ad records for staging proof Ads.  
*/
global class NXX2_CreateProofAdFromStagingData implements Database.Batchable<sObject>,Database.Stateful{
    private string socialProofAdRecordTypeId;
    private Map<String,String> stagingToActualProofAdTypeMap;
    private Map<String,String> stagingToActualProofAdCreativeTypeMap;
    /**
    * @author       Kamal Sharma
    * @date         2019-01-14
    * @description  Default constructor
    */
    public NXX2_CreateProofAdFromStagingData(){
        socialProofAdRecordTypeId = Schema.SObjectType.SocialAd__c.getRecordTypeInfosByName().get('Social Ad').getRecordTypeId();
        stagingToActualProofAdTypeMap = new Map<String,String>{
            'TRAFFIC' => 'Traffic',
            'CONVERSION' => 'Conversion',
            'LEAD_GENERATION' => 'Lead Generation',
            'ENGAGEMENT' => 'Engagement',
            'BRAND_AWARENESS' => 'Brand Awareness',
            'REACH' => 'Reach',
            'VIDEO_VIEWS' => 'Video Views',
            'EVENT_RESPONSE' => 'Event Response',
            'MESSENGER' => 'Messenger'
        };
        stagingToActualProofAdCreativeTypeMap = new Map<String,String>{
            'SLIDESHOW' => 'Slideshow',
            'CAROUSEL' => 'Carousel',
            'SINGLE_IMAGE' => 'Single image',
            'VIDEO' => 'Video'
        };
    }
    
    /**
    * @author       Kamal Sharma
    * @date         2019-01-14
    * @description  Start method implementation of Batch interface
    * @param        Database.BatchableContext BC
    * @return       Database.QueryLocator
    */
    global Database.QueryLocator start(Database.BatchableContext BC){
        //Fetch All the staging task Recods which are related to product order.
        system.debug('*******ProofAd*******');
        return Database.getQueryLocator([SELECT Campaign_Id__c,Has_Merged__c, Headline__c,Type__c,Related_ProofAd__c,Event_Name__c,
                                         Creative_Type__c,External_Id__c, Link__c, Link_Desc__c, Text__c, Button_Type__c,
                                         Processing_Status__c,Error_Message__c,Error_Details__c
                                         FROM NXX2_ProofAd_Staging__c 
                                         WHERE Has_Merged__c = false 
                                         AND Campaign_Id__c != ''
                                        ]);
    }
    
    /**
    * @author       Kamal Sharma
    * @date         2019-01-14
    * @description  execute method implementation of Batch interface
    * @param        Database.BatchableContext BC, List<sObject> scope
    * @return       void
    */
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        system.debug('*******Scope*******'+scope);
        try{
            processProofAdRecords((List<NXX2_ProofAd_Staging__c>)scope);
        }catch(Exception e){
            for(NXX2_ProofAd_Staging__c proofAd : (List<NXX2_ProofAd_Staging__c>)scope){
                proofAd.Processing_Status__c = 'Error';
                proofAd.Error_Message__c = 'Exception Occured!';
                proofAd.Error_Details__c = e.getMessage();
            }
            update scope;
        }
    }
    
    /**
    * @author       Kamal Sharma
    * @date         2019-01-14
    * @description  This method will process all staging task records to create proof records.
    * @param        List<NXX2_ProofAd_Staging__c> stagingProofAds
    * @return       void
    */
    public void processProofAdRecords(List<NXX2_ProofAd_Staging__c> stagingProofAds){
        Set<String> stagingProofIds = new Set<String>();
        Map<String,NXX2_ProofAd_Staging__c> stagingProofAdIdToStagingProofAdMap = new Map<String,NXX2_ProofAd_Staging__c>();
        for(NXX2_ProofAd_Staging__c stagingProofAd : stagingProofAds){
            stagingProofAd.Has_Merged__c = true;
            stagingProofIds.add(stagingProofAd.Campaign_Id__c);
            stagingProofAdIdToStagingProofAdMap.put(stagingProofAd.External_Id__c, stagingProofAd);
        }
        system.debug('*******stagingProofIds*******'+stagingProofIds);
        system.debug('*******stagingProofAdIdToStagingProofAdMap*******'+stagingProofAdIdToStagingProofAdMap);
        Map<String,NXX2_Proof_Staging__c> StagingProofIdToActualProofIdMap = new Map<String,NXX2_Proof_Staging__c>();
        for(NXX2_Proof_Staging__c proofStaging : [SELECT Related_Proof__c,External_Id__c,Related_Proof__r.Status__c,
                                                  Related_Proof__r.RecordType.Name  
                                                  FROM NXX2_Proof_Staging__c 
                                                  WHERE External_Id__c IN :stagingProofIds 
                                                  AND Related_Proof__c != null 
                                                  AND Related_Proof__r.RecordType.Name = 'Social']){
            StagingProofIdToActualProofIdMap.put(proofStaging.External_Id__c, proofStaging);
        }
        system.debug('*******StagingProofIdToActualProofIdMap*******'+StagingProofIdToActualProofIdMap);
        Map<String,SocialAd__c> stagingProofAdIdToActualProofAd = new Map<String,SocialAd__c>();
        SocialAd__c proofAd;
        for(NXX2_ProofAd_Staging__c stagingProofAd : stagingProofAds){
            system.debug('*******stagingProofAd*******'+stagingProofAd);
            system.debug('*******Campaign_Id__c*******'+StagingProofIdToActualProofIdMap.get(stagingProofAd.Campaign_Id__c));
            if(StagingProofIdToActualProofIdMap.containsKey(stagingProofAd.Campaign_Id__c)){
                NXX2_Proof_Staging__c stagingProof = StagingProofIdToActualProofIdMap.get(stagingProofAd.Campaign_Id__c);
                proofAd = new SocialAd__c(
                    Ad_Headline__c = stagingProofAd.Headline__c,
                    Ad_Link__c = stagingProofAd.Link__c,
                    Ad_Newsfeed_Link_Description__c = stagingProofAd.Link_Desc__c,
                    Ad_Text__c = stagingProofAd.Text__c,
                    Ad_Type__c = stagingToActualProofAdTypeMap.get(stagingProofAd.Type__c),
                    Creative_Type__c = stagingToActualProofAdCreativeTypeMap.get(stagingProofAd.Creative_Type__c),
                    Button_Type__c = stagingProofAd.Button_Type__c,
                    Event_Name__c = stagingProofAd.Event_Name__c,
                    Social_Campaign__c = stagingProof.Related_Proof__c,
                    RecordTypeId = socialProofAdRecordTypeId,
                    Status__c = stagingProof.Related_Proof__r.Status__c,
                    Created_From_Staging__c = true
                );
                stagingProofAdIdToActualProofAd.put(stagingProofAd.External_Id__c,proofAd);
            }else{
                stagingProofAd.Processing_Status__c = 'Error';
                stagingProofAd.Error_Message__c = 'No Proof Exist For The Campaign Id.';
                stagingProofAd.Error_Details__c = 'No Proof Exist For The Campaign Id.';
            }
        }
        system.debug('******Social Proof Ad******'+stagingProofAdIdToActualProofAd.values());
        insert stagingProofAdIdToActualProofAd.values();
        for(String stagingProofAdId : stagingProofAdIdToActualProofAd.keyset()){
            stagingProofAdIdToStagingProofAdMap.get(stagingProofAdId).Related_ProofAd__c = stagingProofAdIdToActualProofAd.get(stagingProofAdId).Id;
            stagingProofAdIdToStagingProofAdMap.get(stagingProofAdId).Processing_Status__c = 'Success';
        }
        update stagingProofAdIdToStagingProofAdMap.values();
    }
    
    /**
    * @author       Kamal Sharma
    * @date         2019-01-14
    * @description  finish method implementation of Batch interface
    * @param        Database.BatchableContext BC
    * @return       void
    */
    global void finish(Database.BatchableContext BC){
        NXX2_CreateDisplayProofAdFromStaging b = new NXX2_CreateDisplayProofAdFromStaging();
        database.executebatch(b,1);
    }
}