News UAT/force-app/main/default/objects/Campaign/fields/Max_Call_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Call_Attempts__c</fullName>
    <defaultValue>20</defaultValue>
    <description>Controls the maximum number of call attempts to a Campaign Member.</description>
    <inlineHelpText>Controls the maximum number of call attempts to a Campaign Member. This is a soft limit.</inlineHelpText>
    <label>Max # Call Attempts</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/Campaign/fields/Publication_Division__c.field-meta.xml
<CustomField>
    <fullName>Publication_Division__c</fullName>
    <description>Drives the filtering of Bookings in the Execution Console Action page. 

Possible to select multiple Divisions - as some Retention or Contact Plan campaign will cover multiple divisions.</description>
    <inlineHelpText>Provide a value for Retention or Contact Plan campaigns</inlineHelpText>
    <label>Publication Division</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADN</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>CNS</fullName>
            </value>
            <value>
                <fullName>DBL</fullName>
            </value>
            <value>
                <fullName>GAD</fullName>
            </value>
            <value>
                <fullName>GCP</fullName>
            </value>
            <value>
                <fullName>HWT</fullName>
            </value>
            <value>
                <fullName>LDR</fullName>
            </value>
            <value>
                <fullName>MNG</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>NMG</fullName>
            </value>
            <value>
                <fullName>NWN</fullName>
            </value>
            <value>
                <fullName>PST</fullName>
            </value>
            <value>
                <fullName>QNP</fullName>
            </value>
            <value>
                <fullName>QST</fullName>
            </value>
            <value>
                <fullName>NQN</fullName>
            </value>
            <value>
                <fullName>NTN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Campaign_Response__c/Campaign_Response__c.object-meta.xml
<CustomObject>
    <description>Custom Object to store individual Campaign Responses by a Campaign Member.

Also serves as an integration object to Marketo.</description>
    <label>Campaign Response</label>
    <nameField>
        <displayFormat>CmpR-{0000}</displayFormat>
        <label>Campaign Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Campaign_Response__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related account from the contact.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Responses</relationshipLabel>
    <relationshipName>Campaign_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Campaign_Response__c/fields/Call_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Call_Attempt__c</fullName>
    <label>Call Attempt #</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/Campaign_Response__c/fields/Call_Back_Date__c.field-meta.xml
<CustomField>
    <fullName>Call_Back_Date__c</fullName>
    <description>Date to call customer back - only allowed for Response Subtypes of &#39;Call Back Same Agent&#39; or &#39;Call Back Any Agent&#39;</description>
    <inlineHelpText>Validated against Response Type and Response Subtype</inlineHelpText>
    <label>Call Back Date</label>
    <type>DateTime</type>
</CustomField>

News UAT/force-app/main/default/objects/Campaign_Response__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Responses</relationshipLabel>
    <relationshipName>Campaign_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Campaign_Response__c/fields/Publication_Division__c.field-meta.xml
<CustomField>
    <fullName>Publication_Division__c</fullName>
    <formula>IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;ADN&quot;),&quot;ADN,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;CNG&quot;),&quot;CNG,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;CNS&quot;),&quot;CNS,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;DBL&quot;),&quot;DBL,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;GAD&quot;),&quot;GAD,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;GCP&quot;),&quot;GCP,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;HWT&quot;),&quot;HWT,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;LDR&quot;),&quot;LDR,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;MNG&quot;),&quot;MNG,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;National&quot;),&quot;National,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;NMG&quot;),&quot;NMG,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;NWN&quot;),&quot;NWN,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;PST&quot;),&quot;PST,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;QNP&quot;),&quot;QNP,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;QST&quot;),&quot;QST,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;NQN&quot;),&quot;NQN,&quot;,null)+ 
IF(INCLUDES(Campaign__r.Publication_Division__c,&quot;NTN&quot;),&quot;NTN,&quot;,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Publication Division</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Campaign_Response__c/fields/Response_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Response_Subtype__c</fullName>
    <label>Response Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Response_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Achieved Initial Objective</fullName>
            </value>
            <value>
                <fullName>Already Booked</fullName>
            </value>
            <value>
                <fullName>Awaiting Decision</fullName>
            </value>
            <value>
                <fullName>Booking Error</fullName>
            </value>
            <value>
                <fullName>Build/Maintain Presence and Branding</fullName>
            </value>
            <value>
                <fullName>CRR Complaint/Credit status</fullName>
            </value>
            <value>
                <fullName>Decision Maker Unavailable</fullName>
            </value>
            <value>
                <fullName>Disconnected/Wrong Number</fullName>
            </value>
            <value>
                <fullName>Duped Record</fullName>
            </value>
            <value>
                <fullName>FSAM</fullName>
            </value>
            <value>
                <fullName>Future Contact Scheduled</fullName>
            </value>
            <value>
                <fullName>Growing Business/New Product or Service</fullName>
            </value>
            <value>
                <fullName>Lead to ADM</fullName>
            </value>
            <value>
                <fullName>Lead to ADM and Opt In</fullName>
            </value>
            <value>
                <fullName>Lead to Telemarketing</fullName>
            </value>
            <value>
                <fullName>No ROI</fullName>
            </value>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Opt In</fullName>
            </value>
            <value>
                <fullName>Opt Out From Further Contact</fullName>
            </value>
            <value>
                <fullName>Out of Business</fullName>
            </value>
            <value>
                <fullName>Request Call Back - Same Agent</fullName>
            </value>
            <value>
                <fullName>Short Term Objective</fullName>
            </value>
            <value>
                <fullName>Unhappy With Price</fullName>
            </value>
            <value>
                <fullName>Unhappy With Product</fullName>
            </value>
            <value>
                <fullName>Unhappy With Service</fullName>
            </value>
            <value>
                <fullName>Unsuitable Lead</fullName>
            </value>
            <value>
                <fullName>Will Attend</fullName>
            </value>
            <value>
                <fullName>Will Not Attend</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Campaign_Response__c/fields/Response_Type__c.field-meta.xml
<CustomField>
    <fullName>Response_Type__c</fullName>
    <label>Response Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Follow Up</fullName>
            </value>
            <value>
                <fullName>No Sales Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/CampaignMember/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/CampaignMember/fields/Call_Back_Date__c.field-meta.xml
<CustomField>
    <fullName>Call_Back_Date__c</fullName>
    <description>Store the time to call back a Campaign member</description>
    <label>Call Back Date</label>
    <type>DateTime</type>
</CustomField>

News UAT/force-app/main/default/objects/CampaignMember/fields/Call_Count__c.field-meta.xml
<CustomField>
    <fullName>Call_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Automatically set by the Execution UI 

Must be editable by the Campaign Coordinator or Team Lead</description>
    <inlineHelpText>Number of call attempts on this Campaign Member. Each Campaign has a maximum number of call attempts, which will prevent contact to the Member once the limit is reached.</inlineHelpText>
    <label>Call Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/CampaignMember/fields/DNC_Summary__c.field-meta.xml
<CustomField>
    <fullName>DNC_Summary__c</fullName>
    <description>Bubble up the &#39;Is Contactable&#39; info from the Contact and Lead up to the Campaign Member Level for display at the Campaign member list for Campaign Coordinators/Team Leads to see</description>
    <formula>NOT(OR(Contact.DNC_A_Number_Is_Contactable__c, Lead.DNC_A_Number_Is_Contactable__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Member not contactable - all phone numbers of a Lead or Contact are not contactable</inlineHelpText>
    <label>DNC Summary</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/CampaignMember/fields/Execution_Status__c.field-meta.xml
<CustomField>
    <fullName>Execution_Status__c</fullName>
    <description>Salesforce status to drive Execution, Read Only for users, automatically set by Salesforce</description>
    <label>Execution Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Attempted</fullName>
            </value>
            <value>
                <fullName>Call to Do</fullName>
            </value>
            <value>
                <fullName>Call Limit Reached</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/CampaignMember/fields/In_Progress__c.field-meta.xml
<CustomField>
    <fullName>In_Progress__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in Execution Control to mark a Member as currently in progress - opened by the Agent currently locking it</description>
    <label>In Progress</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/CampaignMember/fields/Locked_By__c.field-meta.xml
<CustomField>
    <fullName>Locked_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The current User updating the Member in Execution UI</description>
    <inlineHelpText>This is the user who has a lock on this Campaign Member</inlineHelpText>
    <label>Locked By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaign_Members_Locked</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/CampaignMember/fields/Response_Type__c.field-meta.xml
<CustomField>
    <fullName>Response_Type__c</fullName>
    <description>Response Comment from the latest Campaign Response</description>
    <inlineHelpText>Response Comment from the latest Campaign Response</inlineHelpText>
    <label>Latest Response Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Follow Up</fullName>
            </value>
            <value>
                <fullName>No Sales Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/CampaignActionPage_ControllerX_Test.cls
/**
* This class contains unit tests for validating the behavior of Apex classes
* and triggers.
*
* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod
* keyword in the method definition.
*
* All test methods in an organization are executed whenever Apex code is deployed
* to a production organization to confirm correctness, ensure code
* coverage, and prevent regressions. All Apex classes are
* required to have at least 75% code coverage in order to be deployed
* to a production organization. In addition, all triggers must have some code coverage.
* 
* The @isTest class annotation indicates this class only contains test
* methods. Classes defined with the @isTest annotation do not count against
* the organization size limit for all Apex scripts.
*
* See the Apex Language Reference for more information about Testing and Code Coverage.
*
*   CampaignActionPage_ControllerX - coverage: 81%
*   CampaignActionPage_Helper - coverage: 91%
*/
@isTest
private class CampaignActionPage_ControllerX_Test {
    
    static testMethod void myUnitResponseTest() {
        
        List<Account> accounts = TestDataFactory.createAccounts(2, false);
        insert accounts;
        
        List<Campaign> campaigns = TestDataFactory.createCampaigns(1);
        campaigns[0].Publication_Division__c = 'NWN;NMG;HWT';
        insert campaigns;
        
        List<Contact> contacts = new List<Contact>();
        List<Contact> contacts1 = TestDataFactory.createContacts(40, accounts[0]);
        List<Contact> contacts2 = TestDataFactory.createContacts(40, accounts[1]);
        contacts.addAll(contacts1);
        contacts.addAll(contacts2);
        insert contacts;
        
        
        list<CampaignMember> campaignMembers =  TestDataFactory.createCampaignMembers(contacts.size(), contacts, campaigns[0]);
        insert campaignMembers;
        
        insert TestDataFactory.createCampaignResponses(1,campaignMembers);
        
        
        Test.startTest();
        
        PageReference pageRef = Page.campaignActionPage;
        pageRef.getParameters().put('refTabId','ts-nn-nn');
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(campaignMembers[0]);
        
        CampaignActionPage_ControllerX controller = new CampaignActionPage_ControllerX(stdController); 
        
        Test.setCurrentPage(pageRef);
        
        
        
        controller.setToInprogress();
        
        controller.member = [SELECT In_Progress__c, Locked_By__c, Execution_Status__c, CampaignId, ContactId,
                             LeadId, Account__c, Status, Call_Count__c, Call_Back_Date__c, Campaign.Max_Call_Attempts__c,
                             DNC_Summary__c, Campaign.Name
                             FROM CampaignMember WHERE Id =: controller.member.Id LIMIT 1];
        
        system.assert(controller.member.In_Progress__c);  
        system.assert(controller.member.Locked_By__c == UserInfo.getUserId());
        
        
        controller.doCancel();
        system.assert(!controller.member.In_Progress__c);
        
        controller.newResponse = new Campaign_Response__c(); 
        controller.setToInprogress();        
        controller.newResponse.Response_Type__c = 'Follow Up';
        controller.newResponse.Response_SubType__c = 'Decision Maker Unavailable';
        controller.newResponse.Call_Back_Date__c = system.now();
        controller.doSave();
        system.assert(controller.member.Execution_Status__c == 'Attempted');
        system.assert(controller.member.Locked_By__c == null);   
        
        controller.newResponse = new Campaign_Response__c(); 
        controller.setToInprogress();  
        controller.newResponse.Response_Type__c = 'Follow Up';
        controller.newResponse.Response_SubType__c = 'Request Call Back - Same Agent';
        controller.doSave();
        system.assert(controller.member.Execution_Status__c == 'Call to Do');
        
        controller.newResponse = new Campaign_Response__c(); 
        controller.setToInprogress();  
        controller.newResponse.Response_Type__c = 'Follow Up';
        controller.newResponse.Response_SubType__c = 'Request Call Back - Any Agent';
        controller.doSave();
        system.assert(controller.member.Execution_Status__c == 'Call to Do'); 
        system.assert(controller.member.Locked_By__c == null);         
        
        controller.newResponse = new Campaign_Response__c(); 
        controller.setToInprogress();  
        controller.newResponse.Response_Type__c = 'Yes';
        controller.newResponse.Response_SubType__c = 'New Business';
        controller.doSave();
        system.assert(controller.member.Execution_Status__c == 'Completed'); 
        system.assert(controller.member.Locked_By__c == null);        

        controller.newResponse = new Campaign_Response__c(); 
        controller.setToInprogress();  
        controller.newResponse.Response_Type__c = 'No';
        controller.newResponse.Response_SubType__c = 'No ROI';
        controller.doSave();
        system.assert(controller.member.Execution_Status__c == 'Completed'); 
        system.assert(controller.member.Locked_By__c == null);        

        controller.newResponse = new Campaign_Response__c(); 
        controller.setToInprogress();  
        controller.newResponse.Response_Type__c = 'No Sales Call';
        controller.newResponse.Response_SubType__c = 'Out of Business';
        controller.doSave();
        system.assert(controller.member.Execution_Status__c == 'Completed'); 
        system.assert(controller.member.Locked_By__c == null);        

        Test.stopTest();
    }
    
    
    static testMethod void myUnitLimitTest() {
        
        List<Account> accounts = TestDataFactory.createAccounts(2, false);
        insert accounts;
        
        List<Campaign> campaigns = TestDataFactory.createCampaigns(1);
        insert campaigns;
        
        List<Contact> contacts = new List<Contact>();
        List<Contact> contacts1 = TestDataFactory.createContacts(40, accounts[0]);
        contacts.addAll(contacts1);
        insert contacts;
        
        
        list<CampaignMember> campaignMembers =  TestDataFactory.createCampaignMembers(contacts.size(), contacts, campaigns[0]);
        insert campaignMembers;
        
        insert TestDataFactory.createCampaignResponses(1,campaignMembers);
        
        Test.startTest(); 
        
        PageReference pageRef = Page.campaignActionPage;        
        ApexPages.StandardController stdController = new ApexPages.StandardController(campaignMembers[0]);       
        CampaignActionPage_ControllerX controller = new CampaignActionPage_ControllerX(stdController);
        Test.setCurrentPage(pageRef);
        
        controller.setToInprogress(); 
        
        controller.member = [SELECT In_Progress__c, Locked_By__c, Execution_Status__c, CampaignId, ContactId,
                             LeadId, Account__c, Status, Call_Count__c, Call_Back_Date__c, Campaign.Max_Call_Attempts__c,
                             DNC_Summary__c, Campaign.Name
                             FROM CampaignMember WHERE Id =: controller.member.Id LIMIT 1];
        
        system.assert(controller.member.In_Progress__c);  
        system.assert(controller.member.Locked_By__c == UserInfo.getUserId());
        
        controller.member = [Select ContactId, CampaignId, LeadId, Account__c, Status, Locked_By__c, Call_Count__c, Call_Back_Date__c, Campaign.Max_Call_Attempts__c,DNC_Summary__c
                             from CampaignMember
                             where id = :campaignMembers[0].id];
        
        
        controller.newResponse.Response_Type__c = 'Follow Up';
        controller.newResponse.Response_SubType__c = 'Request Call Back - Same Agent';
        controller.member.Campaign.Max_Call_Attempts__c = 0;
        controller.newResponse.Call_Attempt__c = controller.member.Campaign.Max_Call_Attempts__c + 1;
        system.debug('@ myUnitLimitTest controller.newResponse.Call_Attempt__c:' + controller.newResponse.Call_Attempt__c);
        system.debug('@ myUnitLimitTest controller.member.Campaign.Max_Call_Attempts__c:' + controller.member.Campaign.Max_Call_Attempts__c);
        system.debug('@ myUnitLimitTest controller.newResponse.Response_Type__c:' + controller.newResponse.Response_Type__c);
        controller.doSave();
        
        system.debug('@ myUnitLimitTest #controller.newResponse.Call_Attempt__c:' + controller.newResponse.Call_Attempt__c);
        system.debug('@ myUnitLimitTest #controller.member.Campaign.Max_Call_Attempts__c:' + controller.member.Campaign.Max_Call_Attempts__c);
        system.debug('@ myUnitLimitTest #controller.newResponse.Response_Type__c:' + controller.newResponse.Response_Type__c);        
        system.debug('@ myUnitLimitTest #controller.member.Execution_Status__c:' + controller.member.Execution_Status__c);
        system.assert(controller.member.Execution_Status__c == 'Call Limit Reached'); 
        system.assert(controller.member.Locked_By__c == null);
                
        Test.stopTest();
        
        
    }   
    
    
    static testMethod void myUnitLeadMemberTest() {
        
        List<Account> accounts = TestDataFactory.createAccounts(2, false);
        insert accounts;
        
        List<Campaign> campaigns = TestDataFactory.createCampaigns(1);
        insert campaigns;
        
        list<Lead> leads = TestDataFactory.createLeads(1);
        insert leads;
        
        
        list<CampaignMember> campaignMembers =  TestDataFactory.createCampaignMembers(1, leads, campaigns[0]);
        insert campaignMembers;
        
        insert TestDataFactory.createCampaignResponses(1,campaignMembers);
        
        
        Test.startTest();
        
        PageReference pageRef = Page.campaignActionPage;
        pageRef.getParameters().put('refTabId','ts-nn-nn');
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(campaignMembers[0]);
        
        CampaignActionPage_ControllerX controller = new CampaignActionPage_ControllerX(stdController); 
        
        Test.setCurrentPage(pageRef);
        
        
        
        controller.setToInprogress();  
        
        controller.member = [SELECT In_Progress__c, Locked_By__c, Execution_Status__c, CampaignId, ContactId,
                             LeadId, Account__c, Status, Call_Count__c, Call_Back_Date__c, Campaign.Max_Call_Attempts__c,
                             DNC_Summary__c, Campaign.Name
                             FROM CampaignMember WHERE Id =: controller.member.Id LIMIT 1];
        
        system.assert(controller.member.In_Progress__c);  
        system.assert(controller.member.Locked_By__c == UserInfo.getUserId());
        
        controller.setToInprogress();
        
        
        Test.stopTest();
        
        
    }  

    static testMethod void PersonAccountMemberTest() {
        
        List<Account> accounts = TestDataFactory.createAccounts(1, true);
        insert accounts;
        accounts = [SELECT Id, IsPersonAccount, PersonContactId FROM Account WHERE Id =: accounts];

        list<Id> contactIds = new list<Id>();
        for(Account a: accounts)
        {
            contactIds.add(a.PersonContactId);
        }
        list<Contact> contacts = [SELECT Id, Name, AccountId FROM Contact WHERE Id IN :contactIds];

        List<Campaign> campaigns = TestDataFactory.createCampaigns(1);
        insert campaigns;

        list<CampaignMember> campaignMembers =  TestDataFactory.createCampaignMembers(1, contacts, campaigns[0]);
        insert campaignMembers;

        insert TestDataFactory.createCampaignResponses(1,campaignMembers);
        
        Test.startTest();
        
        PageReference pageRef = Page.campaignActionPage;
        pageRef.getParameters().put('refTabId','ts-nn-nn');
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(campaignMembers[0]);
        
        CampaignActionPage_ControllerX controller = new CampaignActionPage_ControllerX(stdController); 
        
        Test.setCurrentPage(pageRef);
        
        
        
        controller.setToInprogress();  
        
        controller.member = [SELECT In_Progress__c, Locked_By__c, Execution_Status__c, CampaignId, ContactId,
                             LeadId, Account__c, Status, Call_Count__c, Call_Back_Date__c, Campaign.Max_Call_Attempts__c,
                             DNC_Summary__c, Campaign.Name
                             FROM CampaignMember WHERE Id =: controller.member.Id LIMIT 1];
        
        system.assert(controller.member.In_Progress__c);  
        system.assert(controller.member.Locked_By__c == UserInfo.getUserId());
        
        controller.setToInprogress();
        
        Test.stopTest();
        
        
    }   

    static testMethod void additionalTest() {
        
        SystemParameters__c sysParam = new SystemParameters__c();
        sysParam.Name = 'Opportunity.Contact__c';
        sysParam.External_Id__c = 'Opportunity.Contact__c';
        sysParam.Value__c = 'CF00N90000008T5gO';
        insert sysParam;

        List<Account> accounts = TestDataFactory.createAccounts(2, false);
        insert accounts;
        
        List<Campaign> campaigns = TestDataFactory.createCampaigns(1);
        campaigns[0].Publication_Division__c = 'NWN;NMG;HWT';
        insert campaigns;
        
        List<Contact> contacts = new List<Contact>();
        List<Contact> contacts1 = TestDataFactory.createContacts(40, accounts[0]);
        List<Contact> contacts2 = TestDataFactory.createContacts(40, accounts[1]);
        contacts.addAll(contacts1);
        contacts.addAll(contacts2);
        insert contacts;
        
        
        list<CampaignMember> campaignMembers =  TestDataFactory.createCampaignMembers(contacts.size(), contacts, campaigns[0]);
        insert campaignMembers;
        
        CampaignMember cm = campaignMembers[0];
        cm.Execution_Status__c = 'Completed';
        update cm;

        insert TestDataFactory.createCampaignResponses(1,campaignMembers);
                
        Test.startTest();
        
        PageReference pageRef = Page.campaignActionPage;
        pageRef.getParameters().put('refTabId','ts-nn-nn');
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(campaignMembers[0]);
        
        CampaignActionPage_ControllerX controller = new CampaignActionPage_ControllerX(stdController); 
        
        Test.setCurrentPage(pageRef);
        String oppContactId = controller.opportunityContactFieldId;            
        
        controller.setToInprogress();    
        controller.doCancel();

        Test.stopTest();
    }      

    static testMethod void anotherUserTest() {
        
        SystemParameters__c sysParam = new SystemParameters__c();
        sysParam.Name = 'Opportunity.Contact__c';
        sysParam.External_Id__c = 'Opportunity.Contact__c';
        sysParam.Value__c = 'CF00N90000008T5gO';
        insert sysParam;

        List<Account> accounts = TestDataFactory.createAccounts(2, false);
        insert accounts;
        
        List<Campaign> campaigns = TestDataFactory.createCampaigns(1);
        campaigns[0].Publication_Division__c = 'NWN;NMG;HWT';
        insert campaigns;
        
        List<Contact> contacts = new List<Contact>();
        List<Contact> contacts1 = TestDataFactory.createContacts(40, accounts[0]);
        List<Contact> contacts2 = TestDataFactory.createContacts(40, accounts[1]);
        contacts.addAll(contacts1);
        contacts.addAll(contacts2);
        insert contacts;
    
        List<User> users = TestDataFactory.createUsers(1, 'News Direct Sales Inbound', null, null, false);
        insert users;
        
        list<CampaignMember> campaignMembers =  TestDataFactory.createCampaignMembers(contacts.size(), contacts, campaigns[0]);
        insert campaignMembers;


        CampaignMember cm = campaignMembers[0];
        cm.Execution_Status__c = 'Call Limit Reached';
        cm.Locked_By__c = users[0].Id;
        update cm;

        insert TestDataFactory.createCampaignResponses(1,campaignMembers);
                
        Test.startTest();
        
        PageReference pageRef = Page.campaignActionPage;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(campaignMembers[0]);
        CampaignActionPage_ControllerX controller = new CampaignActionPage_ControllerX(stdController); 
        
        Test.setCurrentPage(pageRef);
        controller.setToInprogress();        
        controller.doCancel();

        Test.stopTest();
    }   

    static testMethod void alreadyStartedAnotherCampaignMemberTest() {
        
        SystemParameters__c sysParam = new SystemParameters__c();
        sysParam.Name = 'Opportunity.Contact__c';
        sysParam.External_Id__c = 'Opportunity.Contact__c';
        sysParam.Value__c = 'CF00N90000008T5gO';
        insert sysParam;

        List<Account> accounts = TestDataFactory.createAccounts(2, false);
        insert accounts;
        
        List<Campaign> campaigns = TestDataFactory.createCampaigns(1);
        campaigns[0].Publication_Division__c = 'NWN;NMG;HWT';
        insert campaigns;
        
        List<Contact> contacts = new List<Contact>();
        List<Contact> contacts1 = TestDataFactory.createContacts(40, accounts[0]);
        List<Contact> contacts2 = TestDataFactory.createContacts(40, accounts[1]);
        contacts.addAll(contacts1);
        contacts.addAll(contacts2);
        insert contacts;
    
        List<User> users = TestDataFactory.createUsers(1, 'News Direct Sales Inbound', null, null, false);
        insert users;
        
        list<CampaignMember> campaignMembers =  TestDataFactory.createCampaignMembers(contacts.size(), contacts, campaigns[0]);
        insert campaignMembers;

        for(CampaignMember cm : campaignMembers)
        {
            cm.Locked_By__c = UserInfo.getUserId();
        }
        update campaignMembers;

        insert TestDataFactory.createCampaignResponses(1,campaignMembers);
                
        Test.startTest();
        
        PageReference pageRef = Page.campaignActionPage;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(campaignMembers[0]);
        CampaignActionPage_ControllerX controller = new CampaignActionPage_ControllerX(stdController); 
        
        Test.setCurrentPage(pageRef);
        controller.setToInprogress();        
        controller.doCancel();

        Test.stopTest();
    }  

    static testMethod void leadCampaignMemberTest() {
                
        List<Campaign> campaigns = TestDataFactory.createCampaigns(1);
        campaigns[0].Publication_Division__c = 'NWN;NMG;HWT';
        insert campaigns;
        
        list<Lead> leads = TestDataFactory.createLeads(1);
        insert leads;        
        
        list<CampaignMember> campaignMembers =  TestDataFactory.createCampaignMembers(1, leads, campaigns[0]);
        insert campaignMembers;
        
        insert TestDataFactory.createCampaignResponses(1,campaignMembers);

                
        Test.startTest();
        
        PageReference pageRef = Page.campaignActionPage;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(campaignMembers[0]);
        CampaignActionPage_ControllerX controller = new CampaignActionPage_ControllerX(stdController); 
        
        Test.setCurrentPage(pageRef);
        controller.setToInprogress();        

        // convert the lead
        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(leads[0].id);
        lc.setDoNotCreateOpportunity(false);
        lc.setConvertedStatus('Converted');
        //lc.setConvertedStatus('Qualified');
        Database.LeadConvertResult lcr = Database.convertLead(lc);

        controller.doSave();

        Test.stopTest();
    }  

}