News UAT/force-app/main/default/objects/Opportunity/fields/Closure_Summary__c.field-meta.xml
<CustomField>
    <fullName>Closure_Summary__c</fullName>
    <label>Closure Summary</label>
    <type>TextArea</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <label>Competitor</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B Mag</fullName>
            </value>
            <value>
                <fullName>Cinema</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Letterbox</fullName>
            </value>
            <value>
                <fullName>Magazines - Bauer</fullName>
            </value>
            <value>
                <fullName>Magazines - EMAP</fullName>
            </value>
            <value>
                <fullName>Magazines - Fairfax Magazines</fullName>
            </value>
            <value>
                <fullName>Magazines - Other</fullName>
            </value>
            <value>
                <fullName>Magazines – Pacific Magazines</fullName>
            </value>
            <value>
                <fullName>Map Magazine</fullName>
            </value>
            <value>
                <fullName>No Competitor</fullName>
            </value>
            <value>
                <fullName>Online - Fairfax Digital</fullName>
            </value>
            <value>
                <fullName>Online - News Digital Media</fullName>
            </value>
            <value>
                <fullName>Online - NineMSN</fullName>
            </value>
            <value>
                <fullName>Online - Other</fullName>
            </value>
            <value>
                <fullName>Online - Sensis</fullName>
            </value>
            <value>
                <fullName>Online - Yahoo</fullName>
            </value>
            <value>
                <fullName>Outdoor - APN</fullName>
            </value>
            <value>
                <fullName>Outdoor - Adshel</fullName>
            </value>
            <value>
                <fullName>Outdoor - Australia Outdoor Network</fullName>
            </value>
            <value>
                <fullName>Outdoor - Eyecorp</fullName>
            </value>
            <value>
                <fullName>Press - APN</fullName>
            </value>
            <value>
                <fullName>Press - Fairfax Community</fullName>
            </value>
            <value>
                <fullName>Press - Fairfax Metro</fullName>
            </value>
            <value>
                <fullName>Press - News Communitities</fullName>
            </value>
            <value>
                <fullName>Press - News Metro</fullName>
            </value>
            <value>
                <fullName>Press - Other</fullName>
            </value>
            <value>
                <fullName>Press - Trading Post</fullName>
            </value>
            <value>
                <fullName>Press - Yellow Pages</fullName>
            </value>
            <value>
                <fullName>Radio - Austereo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/OpportunityGroup__c.field-meta.xml
<CustomField>
    <fullName>OpportunityGroup__c</fullName>
    <label>Opportunity Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Inserts</fullName>
            </value>
            <value>
                <fullName>NewsXtend</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Magazine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Reason_Won_Lost__c.field-meta.xml
<CustomField>
    <fullName>Reason_Won_Lost__c</fullName>
    <label>Reason Won/Lost</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alternative Media</fullName>
            </value>
            <value>
                <fullName>Below the Line</fullName>
            </value>
            <value>
                <fullName>Editorial</fullName>
            </value>
            <value>
                <fullName>Inventory Limitation</fullName>
            </value>
            <value>
                <fullName>Lack of Colour</fullName>
            </value>
            <value>
                <fullName>Masthead Reputation</fullName>
            </value>
            <value>
                <fullName>No budget</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Product/Environment</fullName>
            </value>
            <value>
                <fullName>Reach</fullName>
            </value>
            <value>
                <fullName>Relationship</fullName>
            </value>
            <value>
                <fullName>Response Rate %</fullName>
            </value>
            <value>
                <fullName>Share of Voice</fullName>
            </value>
            <value>
                <fullName>Synergy Lost</fullName>
            </value>
            <value>
                <fullName>Target audience</fullName>
            </value>
            <value>
                <fullName>Timing</fullName>
            </value>
            <value>
                <fullName>Track Record</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Created In Error</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Client Objective</fullName>
            </value>
            <value>
                <fullName>Audience</fullName>
            </value>
            <value>
                <fullName>Connection</fullName>
            </value>
            <value>
                <fullName>Platform</fullName>
            </value>
            <value>
                <fullName>Impact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Revenue_Close__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Close__c</fullName>
    <label>Revenue At Close</label>
    <summarizedField>OpportunityLineItem.Revenue_AtClose__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

News UAT/force-app/main/default/objects/OpportunityLineItem/fields/Revenue_AtClose__c.field-meta.xml
<CustomField>
    <fullName>Revenue_AtClose__c</fullName>
    <inlineHelpText>Revenue for opportunity product line at the time the opportunity has Closed Won/ Lost.</inlineHelpText>
    <label>Revenue At Close</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/classes/OpportunityManagement_Trigger_Test.cls
/*---------------------------------------------------------
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 * Author: Bohao Chen
 * Company: Salesforce.com
 * Description: This is test class for trigger 'OpportunityManagement'
 * History:
 * 13/06/2013  Bohao Chen  Created
 * 2015-12-01 darshan.gosar@bluewolfgroup.com 
 *   Upadated to remove seeAllData condition
 * 2017-05-17 Item-00276 louis.wang@bluewolf.com - updated test class to work with conditional mandatory Opportunity.Contact__c
    // This class provides test coverage for 
    //  - OpportunityLineItemManagement.trigger    79%
    //  - OpportunityManagement.trigger            86% 
 * 16/03/2018  Pratyush Chalasani (Ativa) - added tests for updating contact role records
 * 17/10/2018  David Scullion - reduced number of opportunities created to resolve error System.LimitException: Too many SOQL queries: 101
 ---------------------------------------------------------*/
@isTest
private class OpportunityManagement_Trigger_Test 
{
    static List<Opportunity> opportunities;
    static List<OpportunityLineItem> opportunityLineItems;
    static List<Contact> contacts;
    static List<Account> accts;
    
    @isTest
    static void testContactRoleInsert() {
        // check whether a contact role is created when a new opportunity is inserted
        
        OpportunityManagement_Trigger_Test.initTestData();
        
        Test.startTest();
        
        List<OpportunityContactRole> roles = [SELECT Id, ContactId, IsPrimary FROM OpportunityContactRole WHERE OpportunityId = :opportunities[0].Id];
        
        System.assertNotEquals(null, roles, 'Should have data in roles');
        System.assertEquals(1, roles.size(), 'Should have 1 record in roles');
        System.assertEquals(true, roles[0].IsPrimary, 'Role should be primary');
        System.assertEquals(contacts[0].Id, roles[0].ContactId, 'Role should be linked to existing contact');
        
        Test.stopTest();
    }
    
    @isTest
    static void testContactRoleUpdate() {
        // update contact on opportunity and check if a new contact role is created
        
        OpportunityManagement_Trigger_Test.initTestData();
        
        Test.startTest();
        
        Contact newCnt = TestDataFactory.createContacts(1, accts[0])[0];
        
        insert newCnt;
        
        opportunities[0].Contact__c = newCnt.Id;
        
        /*
         * 03-11-2018: Mohsin Ali (Ative)
         * Adding this to revert the flag of before & after update to false.
		*/
        News_TriggerHelper.OpportunityManagement_Before_Update_Executing = !News_TriggerHelper.OpportunityManagement_Before_Update_Executing;
    	News_TriggerHelper.OpportunityManagement_After_Update_Executing = !News_TriggerHelper.OpportunityManagement_After_Update_Executing;

        update opportunities[0];
        
        List<OpportunityContactRole> roles = [SELECT Id, ContactId, IsPrimary FROM OpportunityContactRole WHERE OpportunityId = :opportunities[0].Id ORDER BY Id];
        
        System.assertNotEquals(null, roles, 'Should have data in roles');
        System.assertEquals(2, roles.size(), 'Should have 2 records in roles');
        System.assertEquals(false, roles[0].IsPrimary, '1st role should not be primary');
        System.assertEquals(true, roles[1].IsPrimary, '2nd role should be primary');
        System.assertEquals(newCnt.Id, roles[1].ContactId, '2nd role should be linked to new contact');
        
        Test.stopTest();
    }
    
    @isTest
    static void testContactRoleRevert() {
        // update contact on opportunity, revert to original contact, and check if a new contact role is created
        
        OpportunityManagement_Trigger_Test.initTestData();
        
        Test.startTest();
        
        Id originalCnt = opportunities[0].Contact__c;
        
        Contact newCnt = TestDataFactory.createContacts(1, accts[0])[0];
        
        insert newCnt;
        
        opportunities[0].Contact__c = newCnt.Id;

        /*
         * 03-11-2018: Mohsin Ali (Ative)
         * Adding this to revert the flag of before & after update to false.
		*/
        News_TriggerHelper.OpportunityManagement_Before_Update_Executing = !News_TriggerHelper.OpportunityManagement_Before_Update_Executing;
    	News_TriggerHelper.OpportunityManagement_After_Update_Executing = !News_TriggerHelper.OpportunityManagement_After_Update_Executing;
        
        update opportunities[0];
        
        opportunities[0].Contact__c = originalCnt;

        /*
         * 03-11-2018: Mohsin Ali (Ative)
         * Adding this to revert the flag of before & after update to false.
		*/
        News_TriggerHelper.OpportunityManagement_Before_Update_Executing = !News_TriggerHelper.OpportunityManagement_Before_Update_Executing;
    	News_TriggerHelper.OpportunityManagement_After_Update_Executing = !News_TriggerHelper.OpportunityManagement_After_Update_Executing;
        
        update opportunities[0];
        
        List<OpportunityContactRole> roles = [SELECT Id, ContactId, IsPrimary FROM OpportunityContactRole WHERE OpportunityId = :opportunities[0].Id ORDER BY Id];
        
        System.assertNotEquals(null, roles, 'Should have data in roles');
        System.assertEquals(2, roles.size(), 'Should have 2 records in roles');
        System.assertEquals(true, roles[0].IsPrimary, '1st role should be primary');
        System.assertEquals(false, roles[1].IsPrimary, '2nd role should not be primary');
        System.assertEquals(originalCnt, roles[0].ContactId, '1st role should be linked to new contact');
        
        Test.stopTest();
    }
    
    static testMethod void revenueAtCloseLostTest() 
    {
        OpportunityManagement_Trigger_Test.initTestData();
        
        Test.startTest();
        
        for(Opportunity opportunity : opportunities)
        {
            opportunity.StageName = 'Closed Lost';
            opportunity.Reason_Won_Lost__c = 'Other';
            opportunity.Probability = 0;
            opportunity.Competitor__c = 'Direct Mail';
            opportunity.Closure_Summary__c = 'testing';
        }

        /*
         * 03-11-2018: Mohsin Ali (Ative)
         * Adding this to revert the flag of before & after update to false.
		*/
        News_TriggerHelper.OpportunityManagement_Before_Update_Executing = !News_TriggerHelper.OpportunityManagement_Before_Update_Executing;
    	News_TriggerHelper.OpportunityManagement_After_Update_Executing = !News_TriggerHelper.OpportunityManagement_After_Update_Executing;

        update opportunities;
                
        for(OpportunityLineItem o : [Select o.UnitPrice, o.Revenue_AtClose__c, o.PricebookEntryId, o.OpportunityId 
                                    From OpportunityLineItem o Where o.OpportunityId IN: opportunities])
        {
            system.assertEquals(2000, o.Revenue_AtClose__c);
        }
        
        for(Opportunity oppt : [Select Revenue_Close__c From Opportunity Where Id IN: opportunities])
        {
            system.assertEquals(20000, oppt.Revenue_Close__c);
        }
        
        for(Opportunity opportunity : opportunities)
        {
            opportunity.StageName = 'Qualified Opportunity';
        }

        /*
         * 03-11-2018: Mohsin Ali (Ative)
         * Adding this to revert the flag of before & after update to false.
		*/
        News_TriggerHelper.OpportunityManagement_Before_Update_Executing = !News_TriggerHelper.OpportunityManagement_Before_Update_Executing;
    	News_TriggerHelper.OpportunityManagement_After_Update_Executing = !News_TriggerHelper.OpportunityManagement_After_Update_Executing;
        
        update opportunities;
                
        for(OpportunityLineItem o : [Select o.UnitPrice, o.Revenue_AtClose__c, o.PricebookEntryId, o.OpportunityId 
                                    From OpportunityLineItem o Where o.OpportunityId IN: opportunities])
        {
            system.assertEquals(null, o.Revenue_AtClose__c);
        }
        
        for(Opportunity oppt : [Select Revenue_Close__c From Opportunity Where Id IN: opportunities])
        {
            system.assertEquals(0, oppt.Revenue_Close__c);
        }
        
        Test.stopTest();
    }
    
    static testMethod void revenueAtCloseWonTest() 
    {
        
        OpportunityManagement_Trigger_Test.initTestData();
        Test.startTest();
        
        for(Opportunity opportunity : opportunities)
        {
            opportunity.StageName = 'Closed Won';
            opportunity.Reason_Won_Lost__c = 'Other';
            opportunity.Probability = 0;
            opportunity.Competitor__c = 'Direct Mail';
            opportunity.Closure_Summary__c = 'testing';
            opportunity.OpportunityGroup__c = 'Other';
        }
        
        update opportunities[0];
        
        Test.stopTest();
        /*
        for(OpportunityLineItem o : [Select o.UnitPrice, o.Revenue_AtClose__c, o.PricebookEntryId, o.OpportunityId 
                                    From OpportunityLineItem o Where o.OpportunityId IN: opportunities])
        {
            system.assertEquals(2000, o.Revenue_AtClose__c);
        }
        
        for(Opportunity oppt : [Select Revenue_Close__c From Opportunity Where Id IN: opportunities])
        {
            system.assertEquals(20000, oppt.Revenue_Close__c);
        }*/
    }
    
    static void initTestData()
    {
        // create account
        OpportunityManagement_Trigger_Test.accts = TestDataFactory.createAccounts(1, false);
        insert OpportunityManagement_Trigger_Test.accts;
        
        // create contact
        OpportunityManagement_Trigger_Test.contacts = TestDataFactory.createContacts(1, accts[0]);
        insert OpportunityManagement_Trigger_Test.contacts;
        // SFE-766 2015-12-01 darshan.gosar@bluewolfgroup.com
            // To cover test scenarios without seeAllData condition    
        List<Product2> products = TestDataFactory.createProducts(10);
        List<Pricebook2> pricebooks = TestDataFactory.createCustomPricebookData();
        List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntryData(pricebooks[0], products);
 //       OpportunityManagement_Trigger_Test.opportunities = TestDataFactory.createOpportunities_withContact(30, null, accts[0], contacts[0]); // Updated by Bohao Chen on 30/05/2014
        OpportunityManagement_Trigger_Test.opportunities = TestDataFactory.createOpportunities_withContact(5, null, accts[0], contacts[0]); // Updated by David Scullion on 17/10/2018
        insert OpportunityManagement_Trigger_Test.opportunities;
        
        OpportunityManagement_Trigger_Test.opportunityLineItems = TestDataFactory.createOpportunityLineItems(OpportunityManagement_Trigger_Test.opportunities, products, pricebookEntries, null);
        insert OpportunityManagement_Trigger_Test.opportunityLineItems;
    }
    
}