News UAT/force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/OpportunityLineItem/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales Order</description>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Shell Order encompassing Booking(s) - to be related to an Opportunity Product/s</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{0000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Placer Contact</description>
    <label>Placer Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Placer_Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <infoMessage>Should generally be related to the Placer Account.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders (Placer Contact)</relationshipLabel>
    <relationshipName>Sales_Orders_PlacerContact</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/classes/OLIUpdateOppProbability_Batch_Test.cls
/*---------------------------------------------------------
 * Author: Bluewolf
 * Company: Bluewolf.com
 * Description: This is the test class for OLIUpdateOppProbability_Batch batch class
 * History:
 * 2015-12-14  Atul Gupta  Created
 * 2015-12-14  Atul Gupta  Updated
 * 2016-01-15 atul.gupta@bluewolfgroup.com
 * 2017-05-17 Item-00276 louis.wang@bluewolf.com - updated test class to work with conditional mandatory Opportunity.Contact__c
    // This class provides test coverage for
    //  - OLIUpdateOppProbabilityAndOwner_Batch   100%
 ---------------------------------------------------------*/
@isTest
private class OLIUpdateOppProbability_Batch_Test { 
	
	static testMethod void opptyLineItemTest(){
		
		// create account
        List<Account> accounts = TestDataFactory.createAccounts(1, false);
		insert accounts;
		
		// create contact
        List<Contact> contacts = TestDataFactory.createContacts(1, accounts[0]);
		insert contacts;
		
		// create 10 products
		List<Product2> products = TestDataFactory.createProducts(10);
		
		//call TestDataFactory method to create Opportunity records
		//List<Pricebook2> pricebooks = TestDataFactory.createPricebookData();
		Id pricebookId = Test.getStandardPricebookId();
        List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntryData(null, null, products);
        
        // create opportunities
		List<Opportunity> opportunities = TestDataFactory.createOpportunities_withContact(2,null,accounts[0],contacts[0]);
		insert opportunities;
		
		// create 2 sales orders
        List<Sales_Order__c> salesOrders = TestDataFactory.createSalesOrders(1, accounts[0], accounts[0], accounts[0], contacts[0], null);
		insert salesOrders;
		
		// create opportunity line items
		List<OpportunityLineItem> olis = TestDataFactory.createOpportunityLineItems(opportunities, products, pricebookEntries, salesOrders[0].Id);
		insert olis;
		
		system.debug('@@olis : '+ olis.size());
		
		//assert that there are 20 records inserted
		System.assertEquals(olis.size(), 20);
		
        Test.startTest();
        OLIUpdateOppProbabilityAndOwner_Batch opptyLineItemBatch = new OLIUpdateOppProbabilityAndOwner_Batch();
        Database.executeBatch(opptyLineItemBatch);
        Test.stopTest();

        //Verify that OpportunityLineItem records have been updated
        List<OpportunityLineItem> opptyLineItem = [Select Id, LastModifiedById from OpportunityLineItem];
        for(OpportunityLineItem lineItem : opptyLineItem){
        	
        	system.assertEquals(UserInfo.getUserId(), lineItem.LastModifiedById);
        }
	}

}