News UAT/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>CASE(TEXT(StageName),
  &quot;Identify Prospects&quot;, &quot;Open&quot;,
  &quot;Establish Rapport&quot;, &quot;Open&quot;,
  &quot;Qualify Opportunity&quot;, &quot;Open&quot;,
  &quot;Select Product(s) and Update Stage&quot;, &quot;Open&quot;,
  &quot;Develop Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Present Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Re-affirm Value/ Negotiate&quot;, &quot;Open&quot;,
  &quot;Awaiting Bookings&quot;, &quot;Open&quot;,
  &quot;Closed Won&quot;, &quot;Closed Won&quot;,
  &quot;Closed Lost&quot;, &quot;Closed Lost&quot;,
  &quot;Err: Invalid stage name&quot;
)</formula>
    <inlineHelpText>Field to allow reporting on Win/ Lost vs Open. Do not display on page layouts.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Assigned_Campaign_Manager__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Campaign_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Campaign Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Fulfilment Ready</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Campaign Live</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Assigned_Campaign_Manager__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Campaign_Manager__c</fullName>
    <formula>IF( Order__r.Assigned_Campaign_Manager__c  &lt;&gt; null ,  Order__r.Assigned_Campaign_Manager__r.LastName &amp; &quot;, &quot; &amp; Order__r.Assigned_Campaign_Manager__r.FirstName , &#39;&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned Campaign Manager</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Assigned_Fulfilment_Owner__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Fulfilment_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Fulfilment Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Assigned_Social_Owner__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Social_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Social Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Product Orders</relationshipLabel>
    <relationshipName>Product_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Returned to CM</fullName>
            </value>
            <value>
                <fullName>Initial QA</fullName>
            </value>
            <value>
                <fullName>Peer review</fullName>
            </value>
            <value>
                <fullName>Peer review failed</fullName>
            </value>
            <value>
                <fullName>Ready to go live</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
            <value>
                <fullName>Cancellation Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/CS_EndOpenTasksAndProcessesTest.cls
@isTest
private class CS_EndOpenTasksAndProcessesTest {
    @isTest
    static void test_process() {
        Order__c order = TestDataSetupClass.createOrder(new Opportunity());
        order.Assigned_Campaign_Manager__c = UserInfo.getUserId();
        order.status__c = 'Draft';
        insert order;

        Product_Order__c pOrd = new Product_Order__c(
            Assigned_Fulfilment_Owner__c = UserInfo.getUserId(),
            Assigned_Social_Owner__c = UserInfo.getUserId(),
            Order__c = order.Id,
            Status__c = 'Cancelled'
        );
        insert pOrd;

        CSPOFA__Orchestration_Process_Template__c template = new CSPOFA__Orchestration_Process_Template__c(
            Name = 'Campaign Setup'
        );
        insert template;

        CSPOFA__Orchestration_Process__c process = new CSPOFA__Orchestration_Process__c(
            Order__c = order.Id,
            CSPOFA__Orchestration_Process_Template__c = template.Id
        );
        CSPOFA__Orchestration_Process__c process2 = new CSPOFA__Orchestration_Process__c(
            Order__c = order.Id,
            CSPOFA__Orchestration_Process_Template__c = template.Id
        );
        insert new List<CSPOFA__Orchestration_Process__c>{process, process2};

        CSPOFA__Orchestration_Step__c step = new CSPOFA__Orchestration_Step__c(
            New_Orch_Process__c = template.Name,
            CSPOFA__Orchestration_Process__c = process.Id
        );
        CSPOFA__Orchestration_Step__c step2 = new CSPOFA__Orchestration_Step__c(
            New_Orch_Process__c = template.Name,
            CSPOFA__Orchestration_Process__c = process2.Id,
            CSPOFA__Status__c = 'Waiting'
        );
        insert new List<CSPOFA__Orchestration_Step__c>{step, step2};

        Test.startTest();

        CS_EndOpenTasksAndProcesses endProcess = new CS_EndOpenTasksAndProcesses();
        List<sObject> result = endProcess.process(new List<SObject>{step});

        Test.stopTest();

        System.assertEquals('Complete', result.get(0).get('CSPOFA__Status__c'));
    }   
}