News UAT/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Bookings related to Bookings in Cyber$ell (Genera), CyberAd, or Digital Booking Systems</description>
    <label>Booking</label>
    <nameField>
        <label>Booking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>External Booking/Billing Account</description>
    <inlineHelpText>Select the External Booking or Billing Account related to this Booking</inlineHelpText>
    <label>Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Booking related to Case</description>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/External_Account__c.object-meta.xml
<CustomObject>
    <description>Object to hold external accounts such as Billing and Booking Accounts</description>
    <label>Booking System Account</label>
    <nameField>
        <label>Booking System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking System Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/External_Account__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The External Account&#39;s parent Customer Account</description>
    <inlineHelpText>The External Account&#39;s parent Customer Account</inlineHelpText>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>External_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent External Account</description>
    <inlineHelpText>Parent External Account</inlineHelpText>
    <label>Parent Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Booking System Accounts</relationshipLabel>
    <relationshipName>External_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/classes/Case_EnhancedAccountSearch.cls
/**
* @company      Bluewolf
* @author       Louis Wang (louis.wang@bluewolf.com)
* @date         2015-01-29
* @description  This class contains methods that are used for Case Sidebar pages (console) <p>
*                   - Case_AccountInfo <p>
*                   - Case_EnhancedAccountSearch (in particular) <p>
*                   - Case_NewAccountContact <p>
*                   - Case_RefreshPrimaryTab <p>
*/
public with sharing class Case_EnhancedAccountSearch 
{
    public string keywordString {get;set;}
    public list<Booking__c> bookingList {get;set;}
    public list<Case> caseList {get;set;}
    public list<Account> accountList {get;set;}
    public list<Contact> contactList {get;set;}
    public Case caseRecord {get;set;}

    private static final string QUERY_LIMIT = '10';

    public Case_EnhancedAccountSearch(ApexPages.StandardController controller) 
    {
    }

    public PageReference init()
    {
        // setup init to ensure essential parameters are available from the URL
        string caseRecordId = ApexPages.currentPage().getParameters().get('id');

        caseRecord = Case_Sidebar_Helper.fetchCaseRecord(caseRecordId);

        resetSearchLists();

        if(caseRecord==null)
        {
            string errorMsg = Case_Sidebar_Helper.PASS_CORRECT_INFO;
            AddVfMessage(errorMsg);
        }
        return null;
    }

    private void AddVfMessage(string InfoDetail)
    {
        apexpages.Message msg = new Apexpages.Message(ApexPages.Severity.Info,InfoDetail);
        apexpages.addMessage(msg);            
    }    

    public PageReference searchNow_Booking()
    {
        // Perform SOQL serach for all the 
        system.debug('>>>>>>>>>>>>>>>>>>> keywordString: ' + keywordString);
        string bookingSearchKey = ApexPages.currentPage().getParameters().get('bookingSearchKey');
        system.debug('>>>>>>>>>>>>>>>>>>> bookingSearchKey: ' + bookingSearchKey); 
        string searchString = Case_Sidebar_Helper.format_SearchString(keywordString, true);
        if(searchString!='')
        {
            String soqlString = Case_Sidebar_Helper.generate_bookingSoql(searchString, QUERY_LIMIT); 
            bookingList = Database.query(soqlString);                           
        }
        else 
        {
            bookingList = new List<Booking__c>();
        }
        return null;
    }

    public PageReference searchNow_Case()
    {
        // Perform SOQL serach for all the 
        system.debug('>>>>>>>>>>>>>>>>>>> keywordString: ' + keywordString);
        string caseSearchKey = ApexPages.currentPage().getParameters().get('caseSearchKey');
        system.debug('>>>>>>>>>>>>>>>>>>> caseSearchKey: ' + caseSearchKey);
        string searchString = Case_Sidebar_Helper.format_SearchString(keywordString, true);
        if(searchString!='')
        {
            String soqlString = Case_Sidebar_Helper.generate_caseSoql(searchString, QUERY_LIMIT); 
            caseList = Database.query(soqlString);
        }
        else 
        {
            caseList = new List<Case>();
        }
        return null;
    }
    public PageReference searchNow_Account()
    {
        // Perform SOQL serach for all the
        system.debug('>>>>>>>>>>>>>>>>>>> keywordString: ' + keywordString);
        string accountSearchKey = ApexPages.currentPage().getParameters().get('accountSearchKey');
        system.debug('>>>>>>>>>>>>>>>>>>> accountSearchKey: ' + accountSearchKey);
        string searchString = Case_Sidebar_Helper.format_SearchString(keywordString, false);
        if(searchString!='')
        {
            //David Dawson 25/11/2016 Item-00182
            //first query the booking system account object to form a set of account ids
            String bsaSearchString = Case_Sidebar_Helper.generate_bsaSoql(searchString, QUERY_LIMIT);
            List<External_Account__c> bsaList = Database.query(bsaSearchString);
            Set<Id> bsaSet = new Set<Id>();
            String soqlString = '';
            if(!bsaList.isEmpty()){
                for(External_Account__c bsa :bsaList){
                    bsaSet.add(bsa.Customer_Account__c);
                }
                soqlString = Case_Sidebar_Helper.generate_accountSoql(searchString, QUERY_LIMIT, 'bsaSet');
            }else{
                soqlString = Case_Sidebar_Helper.generate_accountSoql(searchString, QUERY_LIMIT, null);
            }
            
            accountList = Database.query(soqlString);
        }
        else 
        {
            accountList = new List<Account>();
        }
        return null;
    }
    public PageReference searchNow_Contact()
    {
        // Perform SOQL serach for all the 
        system.debug('>>>>>>>>>>>>>>>>>>> keywordString: ' + keywordString);
        string contactSearchKey = ApexPages.currentPage().getParameters().get('contactSearchKey');
        system.debug('>>>>>>>>>>>>>>>>>>> contactSearchKey: ' + contactSearchKey);
        string searchString = Case_Sidebar_Helper.format_SearchString(keywordString, false);
        if(searchString!='')
        {
            String soqlString = Case_Sidebar_Helper.generate_contactSoql(searchString, QUERY_LIMIT); 
            contactList = Database.query(soqlString);
        }
        else 
        {
            contactList = new List<Contact>();
        }
        return null;
    }

    private void resetSearchLists()
    {
        bookingList = new list<Booking__c>();
        caseList = new list<Case>();
        accountList = new list<Account>();
        contactList = new list<Contact>();
    }

    public PageReference createNewAccount()
    {
        // SFE-739 2015-10-20 louis.wang@bluewolf.com - display "last keyword used" on New Account page
        return Case_Sidebar_Helper.gotoPage(Page.Case_NewAccountContact, true, caseRecord.Id, 'account', keywordString);
    }
    
    public PageReference applySelection()
    {
        // Based on the particular record in the particualr list block, derive the accociated Account and Conatct
        //  records and update them to Case record.
        String tempSelectedType = ApexPages.currentPage().getParameters().get('tempSelectedType');
        string tempAccountId = ApexPages.currentPage().getParameters().get('tempAccountId');
        string tempContactId = ApexPages.currentPage().getParameters().get('tempContactId');
        boolean tempIsPersonAccount = ApexPages.currentPage().getParameters().get('tempIsPersonAccount') == 'true';
        string tempBookingId = ApexPages.currentPage().getParameters().get('tempBookingId');
        string tempCaseId = ApexPages.currentPage().getParameters().get('tempCaseId');
		
        Id inferredContactId;
        
        if(tempSelectedType=='booking')
        {
            inferredContactId = Case_Sidebar_Helper.fetchContactId_FromChosenAccount(tempAccountId, tempIsPersonAccount, tempContactId);
        }
        else if(tempSelectedType=='case')
        {
            inferredContactId = Case_Sidebar_Helper.fetchContactId_FromChosenAccount(tempAccountId, tempIsPersonAccount, tempContactId);
        }
        else if(tempSelectedType=='account')
        {
            inferredContactId = Case_Sidebar_Helper.fetchContactId_FromChosenAccount(tempAccountId, tempIsPersonAccount, tempContactId);
        }
        else if(tempSelectedType=='contact')
        {
            inferredContactId = tempContactId;
        }
        
        try
        {
            caseRecord.AccountId = tempAccountId;
            caseRecord.ContactId = inferredContactId;
            update caseRecord;
        }
        catch(Exception ex)
        {
            ApexPages.addMessages(ex);
            return null;
        }
        return Case_Sidebar_Helper.gotoPage(Page.Case_RefreshPrimaryTab, true, null, null);
    }

    public PageReference gotoAccountInfoPage()
    {
        return Case_Sidebar_Helper.gotoPage(Page.Case_AccountInfo, true, caseRecord.Id, null);
    }

}