News UAT/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Bookings related to Bookings in Cyber$ell (Genera), CyberAd, or Digital Booking Systems</description>
    <label>Booking</label>
    <nameField>
        <label>Booking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <description>Parent Sales Order</description>
    <inlineHelpText>Parent Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Shell Order encompassing Booking(s) - to be related to an Opportunity Product/s</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{0000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SFE-412 - New look up field to link sales orders and bookings to campaigns</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/classes/BookingUpdate_Batch.cls
global class BookingUpdate_Batch implements Database.Batchable<sObject>
{
    // AUTHOR:     2015-09-07 Louis Wang (Bluewolf)
    // DESC:       SFE-412
    //				This batch will find all booking records that has,
    //					- blank Campaign__c 
    //					- but has a value for Sales_Order__r.Campaign__c
    //				It will then populate Campaign__c from Sales_Order
    //				This batch will be scheduled to execute regularly, 
    //				so such records won't exist.
	global String query;

	global BookingUpdate_Batch() 
	{
        this.query = 'SELECT Id, Campaign__c, Sales_Order__r.Campaign__c ' +
						'FROM Booking__c ' +
						'WHERE Campaign__c = null ' +
						'AND Sales_Order__r.Campaign__c != null ' +
						'ORDER BY LastModifiedDate DESC '; 
	}

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Booking__c> scope)
    {
        System.debug('@BookigUpdate_Batch ***************** Batch Execution Started ****************');
        for(Booking__c b : scope)
        {
        	b.Campaign__c = b.Sales_Order__r.Campaign__c;
        }
        update scope;
    }   
    
    global void finish(Database.BatchableContext BC)
    {
        System.debug('@BookigUpdate_Batch ***************** Batch Execution Finished ****************');
    }	
}