News UAT/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Bookings related to Bookings in Cyber$ell (Genera), CyberAd, or Digital Booking Systems</description>
    <label>Booking</label>
    <nameField>
        <label>Booking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking__c/fields/Advertiser_Account__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advertiser Account</description>
    <label>Advertiser Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Booking_Number__c.field-meta.xml
<CustomField>
    <fullName>Booking_Number__c</fullName>
    <description>Booking Number</description>
    <label>Old Booking #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <description>Parent Sales Order</description>
    <inlineHelpText>Parent Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <label>Sales Rep</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Third_Party_Created__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Created__c</fullName>
    <description>3rd Party Created Date</description>
    <label>3rd Party Created</label>
    <type>DateTime</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/Booking_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Booking Line Items</description>
    <label>Booking Line Item</label>
    <nameField>
        <displayFormat>BKL{00000000}</displayFormat>
        <label>Booking Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Campaign/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Booking related to Case</description>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales Order related to the Case</description>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Case/recordTypes/Advertising.recordType-meta.xml
<RecordType>
    <fullName>Advertising</fullName>
    <active>true</active>
    <businessProcess>Customer Enquiry</businessProcess>
    <description>Request to Book/Amend/Cancel Advertisement</description>
    <label>Advertising</label>
</RecordType>

News UAT/force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/OpportunityLineItem/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales Order</description>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product2/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Shell Order encompassing Booking(s) - to be related to an Opportunity Product/s</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{0000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Advertiser_Account__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advertiser Account</description>
    <label>Advertiser Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders_Advertiser</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Placer Contact</description>
    <label>Placer Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Placer_Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <infoMessage>Should generally be related to the Placer Account.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders (Placer Contact)</relationshipLabel>
    <relationshipName>Sales_Orders_PlacerContact</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/SystemParameters__c/SystemParameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>System parameter is to improve the application customisation in the sense that it can be adapted as required.</description>
    <label>System parameters</label>
</CustomObject>

News UAT/force-app/main/default/objects/SystemParameters__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Short description</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

News UAT/force-app/main/default/objects/SystemParameters__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>Value of a key-value pair, where name is the key</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/User/fields/Network_Username__c.field-meta.xml
<CustomField>
    <fullName>Network_Username__c</fullName>
    <description>Windows network username, for correlation with other systems (e.g. Genera, Global Viewpoint).</description>
    <externalId>true</externalId>
    <label>Network Username</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/SalesOrderDetailsHelper_Test.cls
/*---------------------------------------------------------
 * Author: Bohao Chen
 * Company: Salesforce.com
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 * 2016-01-15  Atul Gupta  Updated
 * 2016-01-15 atul.gupta@bluewolfgroup.com
 * 2017-05-17 Item-00276 louis.wang@bluewolf.com - updated test class to work with conditional mandatory Opportunity.Contact__c
 *	 This class provides test coverage for
 *	  - SalesOrderDetails_Helper 90%
 ---------------------------------------------------------*/
@isTest
private class SalesOrderDetailsHelper_Test
{
	
	static testMethod void createOpportunityAndLineItemsTest()
	{
		// create account
        List<Account> accounts = TestDataFactory.createAccounts(1, false);
        insert accounts;
        
        // create contact
        List<Contact> contacts = TestDataFactory.createContacts(1, accounts[0]);
        insert contacts;
        
        // create 10 products
        List<Product2> products = TestDataFactory.createProducts(10);
        
        List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntryData(null, null, products);
        
        // create 10 sales orders
        List<Sales_Order__c> salesOrders = TestDataFactory.createSalesOrders(1, accounts[0], accounts[0], accounts[0], contacts[0], null);
        insert salesOrders;
        
        SystemParameters__c faxParam = new SystemParameters__c();
        faxParam.Name = 'Default Sales Rep';
        faxParam.Description__c = 'Fax Default Cover PageId';
        faxParam.External_Id__c = 'FaxDefaultCoverPageId';
        faxParam.Value__c = Userinfo.getUserId();
        insert faxParam;

        List<User> users = TestDataFactory.createUsers(21, 'System Administrator', null, null, false);
        insert users;
        
        // create bookings
		List<Booking__c> bookings = new List<Booking__c>();

		Integer i;
		for(Sales_Order__c so : salesOrders)
		{
	        for(i = 0; i < 2; i++)
	        {
	        	String randomNum = String.valueOf(math.random() * 1000);
	            Booking__c booking = new Booking__c();
	            // added by Tim Fabros 02 / 09 / 2014 - SFE-581
            	booking.Name = '2132' + i;
	            booking.Sales_Order__c = so.Id;
	            booking.Booking_Number__c = randomNum;
	            booking.External_Id__c = randomNum;
	            booking.Advertiser_Account__c = so.Advertiser_Account__c;
	            booking.Sales_Rep__c = users[0].Network_Username__c;//'Sales_Rep';
	            bookings.add(booking);
	        }
    	}

        insert bookings;

		// Create booking line items
		List<Booking_Line_Item__c> bookingLineItems = new List<Booking_Line_Item__c>();

		i = 0;
		for(Sales_Order__c so : salesOrders)
		{
	        for(Integer j = 0; j < 2; j++)
	        {
				bookingLineItems.addAll(TestDataFactory.createBookingLineItems(10, bookings[i*2+j], null, products));
			}
			i++;
		}

		insert bookingLineItems;

		Test.startTest();
        
        for(Sales_Order__c so : salesOrders)
        {
            try{
                SalesOrderDetails_Helper.createOpportunityAndLineItems(so.Id);
            }catch(SalesOrderDetails_Helper.CreateOpportunityException dEx){
                //Webservice method will attemptn to create opportunity with blank amount and run into new validation
                //new validation rule https://newscorpaustralia--testfixes.cs72.my.salesforce.com/03d90000001Hmgi?setupid=OpportunityValidations
                //Expected behaviour as per David
                system.debug(dEx.getMessage());
            }
        }

		Test.stopTest();

	}
	
	static testMethod void createOpportunityAndLineItemsTest1()
	{
		// create account
        List<Account> accounts = TestDataFactory.createAccounts(1, false);
        insert accounts;
        
        // create contact
        List<Contact> contacts = TestDataFactory.createContacts(1, accounts[0]);
        insert contacts;
        
        // create 10 products
        List<Product2> products = TestDataFactory.createProducts(10);
        
        List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntryData(null, null, products);
        
        // create 10 sales orders
        List<Sales_Order__c> salesOrders = TestDataFactory.createSalesOrders(1, accounts[0], accounts[0], accounts[0], contacts[0], null);
        insert salesOrders;
        
        SystemParameters__c faxParam = new SystemParameters__c();
        faxParam.Name = 'Default Sales Rep';
        faxParam.Description__c = 'Fax Default Cover PageId';
        faxParam.External_Id__c = 'FaxDefaultCoverPageId';
        faxParam.Value__c = Userinfo.getUserId();
        insert faxParam;
        
        // create bookings
		List<Booking__c> bookings = new List<Booking__c>();

		Integer i;
		for(Sales_Order__c so : salesOrders)
		{
	        for(i = 0; i < 2; i++)
	        {
	        	String randomNum = String.valueOf(math.random() * 1000);
	            Booking__c booking = new Booking__c();
	            // added by Tim Fabros 02 / 09 / 2014 - SFE-581
            	booking.Name = '2132' + i;
	            booking.Sales_Order__c = so.Id;
	            booking.Booking_Number__c = randomNum;
	            booking.External_Id__c = randomNum;
	            booking.Advertiser_Account__c = so.Advertiser_Account__c;
	            bookings.add(booking);
	        }
    	}

        insert bookings;

		// Create booking line items
		List<Booking_Line_Item__c> bookingLineItems = new List<Booking_Line_Item__c>();

		i = 0;
		for(Sales_Order__c so : salesOrders)
		{
	        for(Integer j = 0; j < 2; j++)
	        {
				bookingLineItems.addAll(TestDataFactory.createBookingLineItems(10, bookings[i*2+j], null, products));
			}
			i++;
		}

		insert bookingLineItems;

		Test.startTest();

		for(Sales_Order__c so : salesOrders)
		{
            try{
                SalesOrderDetails_Helper.createOpportunityAndLineItems(so.Id);
            }catch(SalesOrderDetails_Helper.CreateOpportunityException dEx){
                //Webservice method will attempt to create opportunity with blank amount and run into new validation
                //new validation rule https://newscorpaustralia--testfixes.cs72.my.salesforce.com/03d90000001Hmgi?setupid=OpportunityValidations
                //Expected behaviour as per David
                system.debug(dEx.getMessage());
            }
        }
        
        Test.stopTest();

	}
	
	//test for sales orders upsert
	static testMethod void testUpsertSalesOrders(){
		
		// create account
        List<Account> accounts = TestDataFactory.createAccounts(1, false);
        insert accounts;
        
        // create contact
        List<Contact> contacts = TestDataFactory.createContacts(1, accounts[0]);
        insert contacts;

        // create 10 sales orders
        List<Sales_Order__c> salesOrders = TestDataFactory.createSalesOrders(1, accounts[0], accounts[0], accounts[0], contacts[0], null);
        insert salesOrders;
        
        //create campaign records
        List<Campaign> campaignsList = TestDataFactory.createCampaigns(5);
        insert campaignsList;
        
        //TestDataFactory.createFaxSystemParameters();
        SystemParameters__c faxParam = new SystemParameters__c();
        faxParam.Name = 'Default Sales Rep';
        faxParam.Description__c = 'Fax Default Cover PageId';
        faxParam.External_Id__c = 'FaxDefaultCoverPageId';
        faxParam.Value__c = Userinfo.getUserId();
        insert faxParam;
        
        //create booking record
        Booking__c bookRec = TestDataFactory.createBooking(salesOrders[0]);
        bookRec.Third_Party_Created__c = null;
        update bookRec;
        
        Map<string, string> wrapMap = new Map<string, string>();
        wrapMap.put('salesOrderSFID', salesOrders[0].Id);
        wrapMap.put('bookingSFID', bookRec.Id);
        wrapMap.put('campaignSFID', campaignsList[0].Id);
        
        SalesOrderDetails_Helper.SalesOrderDetail sOrder = new SalesOrderDetails_Helper.SalesOrderDetail();
        sOrder.bookingID = '1234567890';
        sOrder.totalCost = '3033';
        
		SalesOrderDetails_Helper.SalesOrderWrapper swrap = new SalesOrderDetails_Helper.SalesOrderWrapper();
		swrap.salesOrder = sOrder;
		swrap.parameter = wrapMap;

		
		SalesOrderDetails_Helper.upsertSalesOrderDertails(swrap);
		
	}
	
	static testMethod void testBookingError(){
		
		// create account
        List<Account> accounts = TestDataFactory.createAccounts(1, false);
        insert accounts;
        
        // create contact
        List<Contact> contacts = TestDataFactory.createContacts(1, accounts[0]);
        insert contacts;
		
		//create case record
		String caseRT = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Advertising').getRecordTypeId();
		Case caseRecord = TestDataFactory.createSingleCase(caseRT, accounts[0].Id);
		insert caseRecord;
		
        // create 10 sales orders
        List<Sales_Order__c> salesOrders = TestDataFactory.createSalesOrders(1, accounts[0], accounts[0], accounts[0], contacts[0], null);
        insert salesOrders;
        
        //create campaign records
        List<Campaign> campaignsList = TestDataFactory.createCampaigns(5);
        insert campaignsList;
        
        //TestDataFactory.createFaxSystemParameters();
        SystemParameters__c faxParam = new SystemParameters__c();
        faxParam.Name = 'Default Sales Rep';
        faxParam.Description__c = 'Fax Default Cover PageId';
        faxParam.External_Id__c = 'FaxDefaultCoverPageId';
        faxParam.Value__c = Userinfo.getUserId();
        insert faxParam;

        Map<string, string> wrapMap = new Map<string, string>();
        wrapMap.put('salesOrderSFID', salesOrders[0].Id);
        wrapMap.put('campaignSFID', campaignsList[0].Id);
        wrapMap.put('caseSourceSFID', caseRecord.Id);
        
        SalesOrderDetails_Helper.SalesOrderDetail sOrder = new SalesOrderDetails_Helper.SalesOrderDetail();
        sOrder.bookingID = '1234567890';
        sOrder.totalCost = '3033';
        sOrder.bookingDivision = 'test';
		sOrder.bookingNum = 'test';
		sOrder.placerConId = 'test';
		sOrder.salesOrderID = 'test';
		sOrder.billingAccountID = 'test';
		sOrder.orderId = 'test';
		sOrder.divisionName = 'test';
		sOrder.publicationName = 'test';
		sOrder.adType = 'test';
		sOrder.placerContact = 'test';
		sOrder.payerAccount = 'test';
		sOrder.bookingprofile = 'test';
		sOrder.placerFName = 'test';
		sOrder.placerLName = 'test';
		sOrder.intgID = 'test';
		sOrder.main = 'test';
		sOrder.address = 'test';
		sOrder.city = 'test';
		sOrder.postCode = 'test';
		sOrder.bpType = 'test';
		sOrder.baType = 'test';
		sOrder.baNumber = 'test';
		sOrder.accountName = 'test';
		sOrder.localNumber = 'test';
		sOrder.areaCode = 'test';
		sOrder.createdDate = 'test';
		sOrder.baName = 'test';
		sOrder.state = 'test';
		sOrder.country = 'test';
		sOrder.status = 'test';
		sOrder.sourceSystem = 'test';
		sOrder.bookingContact = 'test';
		sOrder.newsLines = 'test';
		sOrder.searchDate = 'test';
		sOrder.productID = 'test';
		sOrder.startDate = 'test';
		sOrder.lastDate = 'test';
		sOrder.runSchedule = 'test';
		sOrder.classificationCode = 'test';
		sOrder.newsDepth = 'test';
		sOrder.newsCaption = 'test';
		sOrder.bookingAccount = 'test';
		sOrder.bookedPoint = 'test';
		sOrder.salesOrderSFID = 'test';
		sOrder.bookingSFID = 'test';
        
		SalesOrderDetails_Helper.SalesOrderWrapper swrap = new SalesOrderDetails_Helper.SalesOrderWrapper();
		swrap.salesOrder = sOrder;
		swrap.parameter = wrapMap;
		swrap.message = 'messageTest';
		swrap.orderId = 'orderIdTest';

		try{		
			SalesOrderDetails_Helper.upsertSalesOrderDertails(swrap);
		}catch(Exception ex){
			system.assertEquals(true, ex.getMessage().contains('Booking could not be created'));
		}
		
	}
	
	//test if sales order passed is null
	static testMethod void testSalesOrderIdIsNULL()
	{
		// create account
        List<Account> accounts = TestDataFactory.createAccounts(1, false);
        insert accounts;
        
        // create contact
        List<Contact> contacts = TestDataFactory.createContacts(1, accounts[0]);
        insert contacts;
        
        // create 10 products
        List<Product2> products = TestDataFactory.createProducts(10);
        
        List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntryData(null, null, products);
        
        // create 10 sales orders
        List<Sales_Order__c> salesOrders = TestDataFactory.createSalesOrders(1, accounts[0], accounts[0], accounts[0], contacts[0], null);
        insert salesOrders;
		
        SystemParameters__c faxParam = new SystemParameters__c();
        faxParam.Name = 'Default Sales Rep';
        faxParam.Description__c = 'Fax Default Cover PageId';
        faxParam.External_Id__c = 'FaxDefaultCoverPageId';
        faxParam.Value__c = Userinfo.getUserId();
        insert faxParam;
        
        // create bookings
		List<Booking__c> bookings = new List<Booking__c>();

		Integer i;
		for(Sales_Order__c so : salesOrders)
		{
	        for(i = 0; i < 2; i++)
	        {
	        	String randomNum = String.valueOf(math.random() * 1000);
	            Booking__c booking = new Booking__c();
	            // added by Tim Fabros 02 / 09 / 2014 - SFE-581
            	booking.Name = '2132' + i;
	            booking.Sales_Order__c = so.Id;
	            booking.Booking_Number__c = randomNum;
	            booking.External_Id__c = randomNum;
	            booking.Advertiser_Account__c = so.Advertiser_Account__c;
	            bookings.add(booking);
	        }
    	}

        insert bookings;

		// Create booking line items
		List<Booking_Line_Item__c> bookingLineItems = new List<Booking_Line_Item__c>();

		i = 0;
		for(Sales_Order__c so : salesOrders)
		{
	        for(Integer j = 0; j < 2; j++)
	        {
				bookingLineItems.addAll(TestDataFactory.createBookingLineItems(10, bookings[i*2+j], null, products));
			}
			i++;
		}

		insert bookingLineItems;

		Test.startTest();
		try{
			for(Sales_Order__c so : salesOrders)
			{
				SalesOrderDetails_Helper.createOpportunityAndLineItems(null);
			}
		}catch(Exception ex){
			system.debug('@@ex : '+ex.getMessage());
			system.assertEquals(true, ex.getMessage().contains('Sales order id cannot be null'));
		}
		Test.stopTest();

	}
	
	//test if bookinglineitems are not created
	static testMethod void testBookingLineItemsNull()
	{
		// create account
        List<Account> accounts = TestDataFactory.createAccounts(1, false);
        insert accounts;
        
        // create contact
        List<Contact> contacts = TestDataFactory.createContacts(1, accounts[0]);
        insert contacts;
        
        // create 10 products
        List<Product2> products = TestDataFactory.createProducts(10);
        
        List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntryData(null, null, products);
        
        // create 10 sales orders
        List<Sales_Order__c> salesOrders = TestDataFactory.createSalesOrders(1, accounts[0], accounts[0], accounts[0], contacts[0], null);
        insert salesOrders;
		
        SystemParameters__c faxParam = new SystemParameters__c();
        faxParam.Name = 'Default Sales Rep';
        faxParam.Description__c = 'Fax Default Cover PageId';
        faxParam.External_Id__c = 'FaxDefaultCoverPageId';
        faxParam.Value__c = Userinfo.getUserId();
        insert faxParam;
        
        // create bookings
		List<Booking__c> bookings = new List<Booking__c>();

		Integer i;
		for(Sales_Order__c so : salesOrders)
		{
	        for(i = 0; i < 2; i++)
	        {
	        	String randomNum = String.valueOf(math.random() * 1000);
	            Booking__c booking = new Booking__c();
	            // added by Tim Fabros 02 / 09 / 2014 - SFE-581
            	booking.Name = '2132' + i;
	            booking.Sales_Order__c = so.Id;
	            booking.Booking_Number__c = randomNum;
	            booking.External_Id__c = randomNum;
	            booking.Advertiser_Account__c = so.Advertiser_Account__c;
	            bookings.add(booking);
	        }
    	}

        insert bookings;
		
		Test.startTest();
		try{
			for(Sales_Order__c so : salesOrders)
			{
				SalesOrderDetails_Helper.createOpportunityAndLineItems(so.Id);
			}
		}catch(Exception ex){
			system.debug('@@ex : '+ex.getMessage());
			
			system.assertEquals(true, ex.getMessage().contains('exist for this sales order.'));
		}
		Test.stopTest();

	}
	
	//test if noFiscalCalendarFound is true
	static testMethod void testnoFiscalCalendarFound()
	{
		// create account
        List<Account> accounts = TestDataFactory.createAccounts(1, false);
        insert accounts;
        
        // create contact
        List<Contact> contacts = TestDataFactory.createContacts(1, accounts[0]);
        insert contacts;
        
        // create 10 products
        List<Product2> products = TestDataFactory.createProducts(10);
        
        List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntryData(null, null, products);
        
        // create 10 sales orders
        List<Sales_Order__c> salesOrders = TestDataFactory.createSalesOrders(1, accounts[0], accounts[0], accounts[0], contacts[0], null);
        insert salesOrders;
		
        SystemParameters__c faxParam = new SystemParameters__c();
        faxParam.Name = 'Default Sales Rep';
        faxParam.Description__c = 'Fax Default Cover PageId';
        faxParam.External_Id__c = 'FaxDefaultCoverPageId';
        faxParam.Value__c = Userinfo.getUserId();
        insert faxParam;
        
        // create bookings
		List<Booking__c> bookings = new List<Booking__c>();

		Integer i;
		for(Sales_Order__c so : salesOrders)
		{
	        for(i = 0; i < 2; i++)
	        {
	        	String randomNum = String.valueOf(math.random() * 1000);
	            Booking__c booking = new Booking__c();
	            // added by Tim Fabros 02 / 09 / 2014 - SFE-581
            	booking.Name = '2132' + i;
	            booking.Sales_Order__c = so.Id;
	            booking.Booking_Number__c = randomNum;
	            booking.External_Id__c = randomNum;
	            booking.Advertiser_Account__c = so.Advertiser_Account__c;
	            bookings.add(booking);
	        }
    	}

        insert bookings;
        
        Date runDate;
        
		List<FiscalYearSettings> fySettingList = [Select f.WeekStartDay, f.StartDate, f.EndDate 
														From FiscalYearSettings f 
														Where f.IsStandardYear = false 
														ORDER BY f.startdate];
		if(!fySettingList.isEmpty()){
			
			Integer previousYear = fySettingList[0].StartDate.year() - 1 ;
			system.debug('@@previousYear :'+ previousYear);
			
			runDate = Date.newInstance(previousYear, 2, 17);
		}
		
		// Create booking line items
		List<Booking_Line_Item__c> bookingLineItems = new List<Booking_Line_Item__c>();

		i = 0;
		for(Sales_Order__c so : salesOrders)
		{
	        for(Integer j = 0; j < 2; j++)
	        {
				bookingLineItems.addAll(TestDataFactory.createBookingLineItems(10, bookings[i*2+j], null, products));
			}
			i++;
		}

		insert bookingLineItems;

		Test.startTest();
		try{
			for(Sales_Order__c so : salesOrders)
			{
				SalesOrderDetails_Helper.createOpportunityAndLineItems(so.Id);
			}
		}catch(Exception ex){
			
		}
		Test.stopTest();

	}
	
	//
	static testMethod void testNOBookingIsCreatedException(){
		
		// create account
        List<Account> accounts = TestDataFactory.createAccounts(1, false);
        insert accounts;
        
        // create contact
        List<Contact> contacts = TestDataFactory.createContacts(1, accounts[0]);
        insert contacts;

        // create 10 sales orders
        List<Sales_Order__c> salesOrders = TestDataFactory.createSalesOrders(1, accounts[0], accounts[0], accounts[0], contacts[0], null);
        insert salesOrders;
        
        //create campaign records
        List<Campaign> campaignsList = TestDataFactory.createCampaigns(5);
        insert campaignsList;
        
        SystemParameters__c faxParam = new SystemParameters__c();
        faxParam.Name = 'Default Sales Rep';
        faxParam.Description__c = 'Fax Default Cover PageId';
        faxParam.External_Id__c = 'FaxDefaultCoverPageId';
        faxParam.Value__c = Userinfo.getUserId();
        insert faxParam;
        
        //create booking record
        Booking__c bookRec = TestDataFactory.createBooking(salesOrders[0]);
        bookRec.Third_Party_Created__c = null;
        update bookRec;
        
        Map<string, string> wrapMap = new Map<string, string>();
        wrapMap.put('abc', 'testabc');
        
        SalesOrderDetails_Helper.SalesOrderDetail sOrder = new SalesOrderDetails_Helper.SalesOrderDetail();
        sOrder.bookingID = '1234567890';
        sOrder.totalCost = '3033';
        
		SalesOrderDetails_Helper.SalesOrderWrapper swrap = new SalesOrderDetails_Helper.SalesOrderWrapper();
		swrap.salesOrder = sOrder;
		swrap.parameter = wrapMap;

		try{
			SalesOrderDetails_Helper.upsertSalesOrderDertails(swrap);
		}catch(Exception ex){
			system.assertEquals(true, ex.getMessage().contains('Booking could not be created'));
		}
	}
	
	//test coverage for convertSalesOrderWrapperToBookingLineItem method
	static testMethod void testCovertSales(){
        
        SystemParameters__c faxParam = new SystemParameters__c();
        faxParam.Name = 'Default Sales Rep';
        faxParam.Description__c = 'Fax Default Cover PageId';
        faxParam.External_Id__c = 'FaxDefaultCoverPageId';
        faxParam.Value__c = Userinfo.getUserId();
        insert faxParam;
        
        // create account
        List<Account> accounts = TestDataFactory.createAccounts(1, false);
        insert accounts;
        
        // create contact
        List<Contact> contacts = TestDataFactory.createContacts(1, accounts[0]);
        insert contacts;
        
        List<Product2> products = TestDataFactory.createProducts(1);
        
        for(Product2 pro : products){
        	pro.Name = 'Dummy';
        }
        update products;
        
        List<Pricebook2> priceBookList = TestDataFactory.createCustomPricebookData_Standard();
        
        List<PricebookEntry> entryList = TestDataFactory.createPricebookEntryData(priceBookList[0], products);
        
        List<Opportunity> opportunities = TestDataFactory.createOpportunities_withContact(2, priceBookList[0].Id, accounts[0], contacts[0]);
        insert opportunities;
        
        // create 10 sales orders
        List<Sales_Order__c> salesOrders = TestDataFactory.createSalesOrders(1, accounts[0], accounts[0], accounts[0], contacts[0], null);
        insert salesOrders;
        
        Booking__c bookRec = TestDataFactory.createBooking(salesOrders[0]);
        
        Map<string, string> wrapMap = new Map<string, string>();
        wrapMap.put('abc', 'testabc');
        
        SalesOrderDetails_Helper.SalesOrderDetail sOrder = new SalesOrderDetails_Helper.SalesOrderDetail();
        sOrder.bookingID = '1234567890';
        sOrder.totalCost = '3033';
        sOrder.startDate = '31/5/2013';
        sOrder.newsLines = '2.2';
        sOrder.productID = '1234';
        sOrder.classificationCode = '1234';
        sOrder.newsDepth = '1234';
        sOrder.newsCaption = '1234';
        sOrder.publicationName = '1234';
        sOrder.divisionName = '1234';
        sOrder.adType = '1234';
        sOrder.status = '1234';
        
		SalesOrderDetails_Helper.SalesOrderWrapper swrap = new SalesOrderDetails_Helper.SalesOrderWrapper();
		swrap.salesOrder = sOrder;
		swrap.parameter = wrapMap;
		
		Booking_Line_Item__c item = SalesOrderDetails_Helper.convertSalesOrderWrapperToBookingLineItem(swrap);
		
		OpportunityLineItem lineItem = SalesOrderDetails_Helper.createDummyOpportunityLineItem(salesOrders[0], opportunities[0]);
		
		String extId = SalesOrderDetails_Helper.formatBookingExternalId(swrap, bookRec);
	}
	
}