News UAT/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Bookings related to Bookings in Cyber$ell (Genera), CyberAd, or Digital Booking Systems</description>
    <label>Booking</label>
    <nameField>
        <label>Booking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <description>Parent Sales Order</description>
    <inlineHelpText>Parent Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Shell Order encompassing Booking(s) - to be related to an Opportunity Product/s</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{0000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/SystemParameters__c/SystemParameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>System parameter is to improve the application customisation in the sense that it can be adapted as required.</description>
    <label>System parameters</label>
</CustomObject>

News UAT/force-app/main/default/objects/SystemParameters__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Short description</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

News UAT/force-app/main/default/objects/SystemParameters__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>Value of a key-value pair, where name is the key</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/AdPointOrder_Ctr_Test.cls
/*
 * History:
 * 2015-11-25   Darshan G   Updated
 // 2015-11-25 darshan.gosar@bluewolfgroup.com 
        // This class provides test coverage for
        //  - AdPointOrder_Controller  100%
 */
@isTest
private class AdPointOrder_Ctr_Test 
{
    static testMethod void vfPageTest() 
    {
        List<SystemParameters__c> sysParams = new List<SystemParameters__c>();
        
        SystemParameters__c sysParam1 = new SystemParameters__c();
        sysParam1.Value__c = 'https://test.adpoint.news.newslimited.local';
        sysParam1.Description__c = 'domain URLfor AdPoint';
        sysParam1.Name = 'AdPoint_Url';
        sysParam1.External_Id__c = 'AdPoint_Url';
        sysParams.add(sysParam1);
        
        SystemParameters__c sysParam2 = new SystemParameters__c();
        sysParam2.Value__c = '005O0000000oq1q';
        sysParam2.Description__c = 'This is the ID of user who is default sales rep';
        sysParam2.Name = 'Default Sales Rep';
        sysParam2.External_Id__c = 'Default Sales Rep';
        sysParams.add(sysParam2);
        
        insert sysParams;
 
        Sales_Order__c so = TestDataFactory.createSalesOrder('AdPoint');
        Booking__c booking = TestDataFactory.createBooking(so);
        
        Test.startTest();
        
        PageReference pageRef = Page.AdPointOrder;
        pageRef.getParameters().put('s', 'true');
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController ctr = new ApexPages.StandardController(booking);
        AdPointOrder_Controller adPointOrderCtr = new AdPointOrder_Controller(ctr);
        
        String adPointUrl = adPointOrderCtr.PageBaseURL;
        Boolean showFlag = adPointOrderCtr.showHeaderAndSidebar;
        
        system.assertEquals('https://test.adpoint.news.newslimited.local', adPointUrl);
        system.assert(showFlag);
        
         // SFE-766 2015-11-25 darshan.gosar@bluewolfgroup.com
            // Added to increase code coverage
        AdPointOrder_Controller adPointOrderCtrl = new AdPointOrder_Controller();
        adPointOrderCtrl.syncCalled = false;
        Test.stopTest();
    }
}