News UAT/force-app/main/default/objects/Case/fields/Booking_Division__c.field-meta.xml
<CustomField>
    <fullName>Booking_Division__c</fullName>
    <description>Booking Division for Complaint/DRS</description>
    <label>Booking Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADN</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>GAD</fullName>
            </value>
            <value>
                <fullName>GCP</fullName>
            </value>
            <value>
                <fullName>HWT</fullName>
            </value>
            <value>
                <fullName>LDR</fullName>
            </value>
            <value>
                <fullName>NWN</fullName>
            </value>
            <value>
                <fullName>QNP</fullName>
            </value>
            <value>
                <fullName>QST</fullName>
            </value>
            <value>
                <fullName>MNG</fullName>
            </value>
            <value>
                <fullName>CNS</fullName>
            </value>
            <value>
                <fullName>NQN</fullName>
            </value>
            <value>
                <fullName>DBL</fullName>
            </value>
            <value>
                <fullName>PST</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales Order related to the Case</description>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Shell Order encompassing Booking(s) - to be related to an Opportunity Product/s</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{0000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Booking_Division__c.field-meta.xml
<CustomField>
    <fullName>Booking_Division__c</fullName>
    <description>Division for Booking, primarily for CyberAd bookings.</description>
    <label>Booking Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADV</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>GAD</fullName>
            </value>
            <value>
                <fullName>GCP</fullName>
            </value>
            <value>
                <fullName>HWT</fullName>
            </value>
            <value>
                <fullName>LDR</fullName>
            </value>
            <value>
                <fullName>NWN</fullName>
            </value>
            <value>
                <fullName>QNP</fullName>
            </value>
            <value>
                <fullName>QST</fullName>
            </value>
            <value>
                <fullName>CNS</fullName>
            </value>
            <value>
                <fullName>NQN</fullName>
            </value>
            <value>
                <fullName>NTN</fullName>
            </value>
            <value>
                <fullName>MNG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/SmartTemplateLoader.cls
/*---------------------------------------------------------
 * Author: John Moriarty
 * Company: Salesforce.com
 * Description: Implement smart templates, driven by division
 * Requirement 
 * 
 * History:
 * 12/03/2014  John Moriarty  Created
 ---------------------------------------------------------*/

global class SmartTemplateLoader implements Support.EmailTemplateSelector {
    // Empty constructor
    global SmartTemplateLoader() {    }
    // The main interface method
    global ID getDefaultEmailTemplateId(ID caseId) {
        // Select the case we're interested in, choosing any fields that are relevant to our decision
        Case c = [SELECT Sales_Order__r.Booking_Division__c FROM Case WHERE Id=:caseId];
        //Grab the record type
        String recordTypeName = '';
        
        //ID to return
        Id templateId = null;
        String divn = '';
        String templateName = 'Ad_Proofing_';
        
        //Now to grab the booking ID if it exists.
        if(c.Sales_Order__c != null)
        	divn = c.Sales_Order__r.Booking_Division__c;
        	
        if(divn.length() > 0) {
        	//We now have our division. Let's find the template.
        	templateName = templateName + divn;
        	
        	// get the template ID
	        List<EmailTemplate> ets = [SELECT id FROM EmailTemplate WHERE DeveloperName = :templateName];
	        //Return the ID of the template selected
	        if (!ets.isEmpty()) {
	            EmailTemplate et = ets[0];
	            templateId = et.Id;
	            System.Debug('Template Id ' + templateId + ' found');
	        }
       }
       
       return templateId;
    }    	
}