News UAT/force-app/main/default/objects/Case/fields/Case_Origin_Copy__c.field-meta.xml
<CustomField>
    <fullName>Case_Origin_Copy__c</fullName>
    <label>Case Origin Copy</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/Pillar__c.field-meta.xml
<CustomField>
    <fullName>Pillar__c</fullName>
    <label>Pillar</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Careers</fullName>
            </value>
            <value>
                <fullName>Cars Guide</fullName>
            </value>
            <value>
                <fullName>Funeral</fullName>
            </value>
            <value>
                <fullName>Gen Class</fullName>
                <default>true</default>
                <label>Gen Class</label>
            </value>
            <value>
                <fullName>Legal Notices</fullName>
            </value>
            <value>
                <fullName>LET</fullName>
            </value>
            <value>
                <fullName>Marketplace</fullName>
            </value>
            <value>
                <fullName>Motoring</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Personal Notices</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Trades</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/SuppliedTo__c.field-meta.xml
<CustomField>
    <fullName>SuppliedTo__c</fullName>
    <description>The Email Address from the Routing Email</description>
    <label>Supplied To Email</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

News UAT/force-app/main/default/objects/Keyword_Match__c/Keyword_Match__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Item-00040 - This setting is used by Email Routing (Email-to-Case)</description>
    <label>Keyword Match</label>
</CustomObject>

News UAT/force-app/main/default/objects/Keyword_Match__c/fields/Input_Keyword__c.field-meta.xml
<CustomField>
    <fullName>Input_Keyword__c</fullName>
    <label>Input Keyword</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Keyword_Match__c/fields/Input_Object__c.field-meta.xml
<CustomField>
    <fullName>Input_Object__c</fullName>
    <label>Input Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Keyword_Match__c/fields/Output_Object__c.field-meta.xml
<CustomField>
    <fullName>Output_Object__c</fullName>
    <label>Output Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Keyword_Match__c/fields/Output_Object_Field__c.field-meta.xml
<CustomField>
    <fullName>Output_Object_Field__c</fullName>
    <label>Output Object Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Keyword_Match__c/fields/Output_Object_Field_String__c.field-meta.xml
<CustomField>
    <fullName>Output_Object_Field_String__c</fullName>
    <label>Output Object Field String</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Pillar__c/Pillar__c.object-meta.xml
<CustomObject>
    <label>Pillar</label>
    <nameField>
        <label>Pillar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pillar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/classes/EmailMessageManagement_Trigger_Test.cls
/**
 * Author: Bohao Chen
 * Company: Salesforce.com
 * This class contains unit tests for validating the behavior of Apex classes and triggers.
 * test requirement R-1275
 * 20/11/2013  Bohao Chen  Created
 * 26/02/2014  Bohao Chen  Updated
 * 
 *  Test Coverage Summary
 *      - EmailMessageManagement.trigger    100%
 *      - EmailMessageTrigger_Helper.cls    84%
 */
@isTest
private class EmailMessageManagement_Trigger_Test 
{
    static testMethod void caseOwnerTest() 
    {
        // create integrator user
        User user = TestDataFactory.createUser('System Administrator', 'Integrator', null, null, null, false);
        insert user;
        
        // create group emails
        List<Group> groups = TestDataFactory.createGroups(1, 'Queue');
        
        // Associate a queue with the sObject that can be associated with the queue, including custom objects.
        List<QueueSobject> mappingObjects = new List<QueueSobject>();
         
        for(Group g : groups)
        {
            QueueSobject mappingObject = new QueueSobject(QueueId = g.Id, SobjectType = 'Case');
            mappingObjects.add(mappingObject);
        }
        
        System.runAs(new User(Id = UserInfo.getUserId()))
        {insert mappingObjects;}
        
        // create new cases
        List<Case> cases = TestDataFactory.createCases(1, null, null);
        
        Integer i = 0;
        
        for(Case c : cases)
        {
            c.Origin = 'Email - Inbound for Routing';
        }
        insert cases;
        
        system.debug('@EmailMessageManagement_Trigger_Test caseOriginCopyTest insert test cases');
        
        // 2016-04-06 Item-00056 louis.wang@bluewolf.com - added custom setting records 'Keyword Match'
        list<Keyword_Match__c> kmList = new list<Keyword_Match__c>();
        Keyword_Match__c km1 = new Keyword_Match__c();
        km1.Name = 'KM-000001';
        km1.External_Id__c = 'KM-000001';
        km1.Input_Object__c = 'EmailMessage';
        km1.Input_Keyword__c = 'Employment';
        km1.Output_Object__c = 'Case';
        km1.Output_Object_Field__c = 'Pillar__c';
        km1.Output_Object_Field_String__c = 'CareerOne';
        kmList.add(km1);
        Keyword_Match__c km2 = new Keyword_Match__c();
        km2.Name = 'KM-000002';
        km2.External_Id__c = 'KM-000002';
        km2.Input_Object__c = 'EmailMessage';
        km2.Input_Keyword__c = 'Newslife Media';
        km2.Output_Object__c = 'Case';
        km2.Output_Object_Field__c = 'Genesys_Publication__c';
        km2.Output_Object_Field_String__c = 'News Life Media';
        kmList.add(km2);
        insert kmList;

        Test.startTest();
        
        i = 0;
        for(Case c : [Select Origin, OwnerId, SuppliedTo__c 
                      From Case 
                      Where Id IN: cases])
        {
           //system.assertEquals('Email - Inbound for Routing', c.Origin);
           system.assertEquals('Case owner: ' + UserInfo.getUserId(), 'Case owner: ' + c.OwnerId);
        }
        
        List<EmailMessage> ems = new List<EmailMessage>();
        
        i = 0;
        for(Case c : cases)
        {
            EmailMessage em = TestDataFactory.createEmailMessage(c, 'queue' + i + '@email.com');
            em.Incoming = true;
            //Added LMancilla SFE-445 - Convert HTML to text for Ad Proof
            em.Subject='Ad Proof';
            em.HtmlBody='<HTML>Employment Newslife Media</HTML>';            
            //End LMancilla
            em.MessageDate = datetime.now();
            ems.add(em);
            i++;
        }
        
        insert ems;

        system.debug('@EmailMessageManagement_Trigger_Test caseOriginCopyTest ems: ' + ems);

        i = 0;
        for(Case c : [Select Case_Origin_Copy__c, Origin, OwnerId, SuppliedTo__c 
                      From Case 
                      Where Id IN: cases])
        {
           //system.assertEquals('Email - Inbound for Routing', c.Origin);
           system.assertEquals('Case owner: ' + groups[0].Id, 'Case owner: ' + c.OwnerId);
        }
                
        Test.stopTest();
        
    }
}