News UAT/force-app/main/default/objects/SystemParameters__c/SystemParameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>System parameter is to improve the application customisation in the sense that it can be adapted as required.</description>
    <label>System parameters</label>
</CustomObject>

News UAT/force-app/main/default/objects/SystemParameters__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Short description</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

News UAT/force-app/main/default/objects/SystemParameters__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>Value of a key-value pair, where name is the key</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/AdPointProductAvailabilityCheck_Ctr_Test.cls
@isTest
private class AdPointProductAvailabilityCheck_Ctr_Test 
{
    static testMethod void vfPageTest() 
    {
    	SystemParameters__c sysParam = new SystemParameters__c();
    	sysParam.Value__c = 'https://test.adpoint.news.newslimited.local';
    	sysParam.Description__c = 'domain URLfor AdPoint';
    	sysParam.Name = 'AdPoint_Url';
    	sysParam.External_Id__c = 'AdPoint_Url';
    	insert sysParam;
 
        Test.startTest();
    	
        PageReference pageRef = Page.AdPointProductAvailabilityCheck;
        pageRef.getParameters().put('s', 'true');
        Test.setCurrentPage(pageRef);
        
        AdPointProductAvailabilityCheck_Ctr adPointProductCheckCtr = new AdPointProductAvailabilityCheck_Ctr();
        
        String adPointUrl = adPointProductCheckCtr.adPointUrl;
        Boolean showFlag = adPointProductCheckCtr.showHeaderAndSidebar;
        
        system.assertEquals('https://test.adpoint.news.newslimited.local', adPointUrl);
        system.assert(showFlag);
        
        Test.stopTest();
    }
}