News UAT/force-app/main/default/objects/Sales_Actuals__c/Sales_Actuals__c.object-meta.xml
<CustomObject>
    <label>Sales Actual</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>SA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Sales_Actuals__c/fields/PeriodId__c.field-meta.xml
<CustomField>
    <fullName>PeriodId__c</fullName>
    <externalId>true</externalId>
    <label>Period ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Actuals__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <externalId>true</externalId>
    <label>Product Family</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/AT_SalesPerformance_Test.cls
@isTest(SeeAllData = true) // Need SeeAllData to test anything related to RevenueForecast
public class AT_SalesPerformance_Test {
    static void init() {
        // Make sure the current user has forecasting enabled
        User currentUser = new User(Id = UserInfo.getUserId(), ForecastEnabled = true);
        
        update currentUser;
    }
    
    @isTest
    static void testActuals() {
        List<AT_SalesPerformance.MonthPeriod> periods = AT_SalesPerformance.getCurrentAndNextPeriods(2);
        
        List<Id> periodIDs = new List<Id>();
        
        for (AT_SalesPerformance.MonthPeriod mp: periods) periodIDs.add(mp.periodID);
        
        Map<Id, Integer> periodMonths = AT_SalesPerformance.getPeriodMonths(periodIDs);
        
        List<AT_SalesPerformance.MonthPeriod> qtrPeriods = AT_SalesPerformance.getFYQuarterPeriods();
        
        List<Sales_Actuals__c> actuals = new List<Sales_Actuals__c>{
            new Sales_Actuals__c(Product_Family__c = 'Print', Amount__c = 1000, PeriodId__c = periodIDs[0], Date__c = System.Today()),
                new Sales_Actuals__c(Product_Family__c = 'Digital', Amount__c = 1000, PeriodId__c = periodIDs[0], Date__c = System.Today())
                };
                    
                    insert actuals;
        
        List<AT_SalesPerformance.Sales> data = AT_SalesPerformance.getSalesActualsForPeriods(periodIDs);
    }
    
    @isTest
    static void testPipeline() {
        List<AT_SalesPerformance.MonthPeriod> periods = AT_SalesPerformance.getCurrentAndNextPeriods(2);
        
        List<Id> periodIDs = new List<Id>();
        
        for (AT_SalesPerformance.MonthPeriod mp: periods) periodIDs.add(mp.periodID);
        
        List<AT_SalesPerformance.Sales> data = AT_SalesPerformance.getPipelineForPeriods(periodIDs);
    }
    
    @isTest
    static void testTargets() {
        List<AT_SalesPerformance.MonthPeriod> periods = AT_SalesPerformance.getCurrentAndNextPeriods(2);
        
        List<Id> periodIDs = new List<Id>();
        
        for (AT_SalesPerformance.MonthPeriod mp: periods) periodIDs.add(mp.periodID);
        
        List<AT_SalesPerformance.Sales> data = AT_SalesPerformance.getTargetsForPeriods(periodIDs);
    }
    
    @isTest
    static void UnitTest01(){        
        Test.startTest();
        testActuals();
        testPipeline();
        testTargets();
        Test.stopTest();
    }
    
}