News UAT/force-app/main/default/objects/FiscalCalendar__mdt/FiscalCalendar__mdt.object-meta.xml
<CustomObject>
    <label>NewsCorp Fiscal Calendar</label>
    <pluralLabel>NewsCorp Fiscal Calendars</pluralLabel>
</CustomObject>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/DT_ID__c.field-meta.xml
<CustomField>
    <fullName>DT_ID__c</fullName>
    <label>DT ID</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_DOY_NR__c.field-meta.xml
<CustomField>
    <fullName>FISC_DOY_NR__c</fullName>
    <label>FISC DOY NR</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_HFYR_NM__c.field-meta.xml
<CustomField>
    <fullName>FISC_HFYR_NM__c</fullName>
    <label>FISC HFYR NM</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_HFYR_NR__c.field-meta.xml
<CustomField>
    <fullName>FISC_HFYR_NR__c</fullName>
    <label>FISC HFYR NR</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_HFYR_SNAM__c.field-meta.xml
<CustomField>
    <fullName>FISC_HFYR_SNAM__c</fullName>
    <label>FISC HFYR SNAM</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_MNTH_FIRST_DAY_DT__c.field-meta.xml
<CustomField>
    <fullName>FISC_MNTH_FIRST_DAY_DT__c</fullName>
    <label>FISC MNTH FIRST DAY DT</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_MNTH_ID__c.field-meta.xml
<CustomField>
    <fullName>FISC_MNTH_ID__c</fullName>
    <label>FISC MNTH ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_MNTH_LAST_DAY_DT__c.field-meta.xml
<CustomField>
    <fullName>FISC_MNTH_LAST_DAY_DT__c</fullName>
    <label>FISC MNTH LAST DAY DT</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_MNTH_NM__c.field-meta.xml
<CustomField>
    <fullName>FISC_MNTH_NM__c</fullName>
    <label>FISC MNTH NM</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_MNTH_NR__c.field-meta.xml
<CustomField>
    <fullName>FISC_MNTH_NR__c</fullName>
    <label>FISC MNTH NR</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_MNTH_SNAM__c.field-meta.xml
<CustomField>
    <fullName>FISC_MNTH_SNAM__c</fullName>
    <label>FISC MNTH SNAM</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_QRTR_NM__c.field-meta.xml
<CustomField>
    <fullName>FISC_QRTR_NM__c</fullName>
    <label>FISC QRTR NM</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_QRTR_NR__c.field-meta.xml
<CustomField>
    <fullName>FISC_QRTR_NR__c</fullName>
    <label>FISC QRTR NR</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_QRTR_SNAM__c.field-meta.xml
<CustomField>
    <fullName>FISC_QRTR_SNAM__c</fullName>
    <label>FISC QRTR SNAM</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_WEEK_FIRST_DAY_DT__c.field-meta.xml
<CustomField>
    <fullName>FISC_WEEK_FIRST_DAY_DT__c</fullName>
    <label>FISC WEEK FIRST DAY DT</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_WEEK_ID__c.field-meta.xml
<CustomField>
    <fullName>FISC_WEEK_ID__c</fullName>
    <label>FISC WEEK ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_WEEK_LAST_DAY_DT__c.field-meta.xml
<CustomField>
    <fullName>FISC_WEEK_LAST_DAY_DT__c</fullName>
    <label>FISC WEEK LAST DAY DT</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_WEEK_NR__c.field-meta.xml
<CustomField>
    <fullName>FISC_WEEK_NR__c</fullName>
    <label>FISC WEEK NR</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_YEAR_FIRST_DAY_DT__c.field-meta.xml
<CustomField>
    <fullName>FISC_YEAR_FIRST_DAY_DT__c</fullName>
    <label>FISC YEAR FIRST DAY DT</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_YEAR_ID__c.field-meta.xml
<CustomField>
    <fullName>FISC_YEAR_ID__c</fullName>
    <label>FISC YEAR ID</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_YEAR_LAST_DAY_DT__c.field-meta.xml
<CustomField>
    <fullName>FISC_YEAR_LAST_DAY_DT__c</fullName>
    <label>FISC YEAR LAST DAY DT</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_YEAR_MNTH_DS__c.field-meta.xml
<CustomField>
    <fullName>FISC_YEAR_MNTH_DS__c</fullName>
    <label>FISC YEAR MNTH DS</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_YEAR_NR__c.field-meta.xml
<CustomField>
    <fullName>FISC_YEAR_NR__c</fullName>
    <label>FISC YEAR NR</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/FiscalCalendar__mdt/fields/FISC_YEAR_QRTR_DS__c.field-meta.xml
<CustomField>
    <fullName>FISC_YEAR_QRTR_DS__c</fullName>
    <label>FISC YEAR QRTR DS</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/NewsCorpFiscalCalendar.cls
/*------------------------------------------------------------------------------
author: David Dawson
company: Bluewolf

description: 
This class facilitates accessing of the NewsCorp fiscal calendar
programatically through the custom metadata type object (__mdt)

history:
* 06/05/2016 Class created
* 08/05/2016 monthId functionality created to accept dates and return their month ids
* 11/05/2016 DT ID functionality created to accept dates and return their DT ID
------------------------------------------------------------------------------*/

public class NewsCorpFiscalCalendar {

	//provides the month id for all dates provided in a list. Return type is Map<Provided Date, Month Id>.
	public Static Map<Date, String> monthID(List<Date> dateList){

		Map<String, Date> idMap = fiscDTID(dateList);
		Set<String> idSet = idMap.keySet();
		Map<Date, String> refMap = new Map<Date, String>();

		List<FiscalCalendar__mdt> fiscList = new List<FiscalCalendar__mdt>([SELECT Id, DT_ID__c, FISC_MNTH_ID__c FROM FiscalCalendar__mdt WHERE DT_ID__c IN :idSet]);

		for(FiscalCalendar__mdt fisc :fiscList){
			refMap.put(idMap.get(fisc.DT_ID__c), fisc.FISC_MNTH_ID__c);
		}

		return refMap;

	}

	//provides the DT ID for all dates provided in a list. Return type is Map<Provided Date, DT ID>.
	public Static Map<String, Date> fiscDTID(List<Date> dateList){

		Map<String, Date> fiscList = new Map<String, Date>();

		for(Date d :dateList){
			String day = String.valueOf(d.day());
			String month = String.valueOf(d.month());
			String year = String.valueOf(d.year());

			if(day.length() < 2){
				day = '0' + day;
			}
			if(month.length() < 2){
				month = '0' + month;
			}

			String concat = year + month + day;
			fiscList.put(concat, d);		

		}

		return fiscList;
	}

	public Static Map<Date, FiscalCalendar__mdt> returnFiscalMonths (Date startDate, Date endDate){

		List<FiscalCalendar__mdt> fiscList = new List<FiscalCalendar__mdt>([SELECT Id, DT_ID__c, FISC_MNTH_ID__c , Date__c, FISC_DOY_NR__c, FISC_HFYR_NM__c, 
			FISC_HFYR_NR__c, FISC_HFYR_SNAM__c, FISC_MNTH_FIRST_DAY_DT__c, FISC_MNTH_LAST_DAY_DT__c, FISC_MNTH_NM__c, FISC_MNTH_NR__c, FISC_MNTH_SNAM__c,
			FISC_QRTR_NM__c, FISC_QRTR_NR__c, FISC_QRTR_SNAM__c, FISC_WEEK_FIRST_DAY_DT__c, FISC_WEEK_ID__c, FISC_WEEK_LAST_DAY_DT__c, FISC_WEEK_NR__c,
			FISC_YEAR_FIRST_DAY_DT__c, FISC_YEAR_ID__c, FISC_YEAR_LAST_DAY_DT__c, FISC_YEAR_MNTH_DS__c, FISC_YEAR_NR__c, FISC_YEAR_QRTR_DS__c
			FROM FiscalCalendar__mdt WHERE Date__c >= :startDate AND Date__c <= :endDate ORDER BY FISC_MNTH_ID__c]);

		Map<Date, FiscalCalendar__mdt> fiscalMap = new Map<Date, FiscalCalendar__mdt>();
		for(FiscalCalendar__mdt f : fiscList){

			fiscalMap.put(f.Date__c, f);
		}

		return fiscalMap;


	}

}