News UAT/force-app/main/default/objects/Exception_Record__c/Exception_Record__c.object-meta.xml
<CustomObject>
    <description>This object is to store exception records throw from batches</description>
    <label>Exception Record</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Exception Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/SystemParameters__c/SystemParameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>System parameter is to improve the application customisation in the sense that it can be adapted as required.</description>
    <label>System parameters</label>
</CustomObject>

News UAT/force-app/main/default/objects/SystemParameters__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>Value of a key-value pair, where name is the key</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/AccountBatch_Helper_Test.cls
/*---------------------------------------------------------
* Author:  Darshan Gosar
* Description: This class contains unit tests for validating the behavior of AccountBatch_Helper
* Company: Salesforce.com
* History:
* 2015-12-15   Darshan Gosar       Created
// SFE-766 2015-12-15 darshan.gosar@bluewolfgroup.com 
    // This class provides test coverage for 
    //  - AccountBatch_Helper                      91% 
---------------------------------------------------------*/
@isTest
private class AccountBatch_Helper_Test 
{

    static List<Account> advertiserAccounts;
    
    static public void setupTestData(){    
        
        SystemParameters__c batchSetting = new SystemParameters__c(Name = 'Spending_Batch_Exception_Recipients', Value__c = 'test.test@test.com', External_Id__c = '1234');
        insert batchSetting;  
                
        advertiserAccounts = TestDataFactory.createAccounts(10, false);
        insert advertiserAccounts; 
    }
    

    static testMethod void sendBatchErrorMessagesTest() 
    {
        setupTestData();  
        
        Map<String, List<String>> errorMessageByFailedAcctId = new Map<String, List<String>>();
        
        for(Account a: advertiserAccounts){
            List<String> errorMessages = new List<String>();
            errorMessages.add('Test Message 1');
            errorMessages.add('Test Message 2');
            errorMessageByFailedAcctId.put(a.Id, errorMessages);
        }
              
        Test.startTest();
        AccountBatch_Helper.sendBatchErrorMessages(errorMessageByFailedAcctId, 'AccountCalculateTcsTas_Batch');
        Test.stopTest();                
    }
    
    static testMethod void processFailRecordsTest() 
    {
        setupTestData();  
        
        Map<String, List<String>> errorMessageByFailedAcctId = new Map<String, List<String>>();
        
        for(Account a: advertiserAccounts){
            List<String> errorMessages = new List<String>();
            errorMessages.add('Test Message 1');
            errorMessages.add('Test Message 2');
            errorMessageByFailedAcctId.put(a.Id, errorMessages);
        }
              
        Test.startTest();
        AccountBatch_Helper.processFailRecords(errorMessageByFailedAcctId, 'Insert');
        Test.stopTest();  
        
        List<Exception_Record__c> exceptionRecordList = new List<Exception_Record__c>();
        exceptionRecordList = [Select Id from Exception_Record__c];
        
        system.assertEquals(advertiserAccounts.size(), exceptionRecordList.size(), 'Exception Records are not created as expected');
    }  
    
    static testMethod void runAccountCalculateTcsTasBatchTest() 
    {
        setupTestData(); 
              
        Test.startTest();
        AccountBatch_Helper.runAccountCalculateTcsTasBatch(advertiserAccounts[0].Id);
        Test.stopTest();  
    }     
}