News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Payment_Schedule__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Payment_Schedule__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Cancelled</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment_Schedule__c.Payment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Payment Schedule</label>
    <nameField>
        <label>Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Payment_Schedule__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Payment_Line_Item__c.Price__c</summarizedField>
    <summaryFilterItems>
        <field>Payment_Line_Item__c.Type__c</field>
        <operation>equals</operation>
        <value>,Normal, Credit Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment_Line_Item__c.Payment_Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Schedule__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Campaign Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/CS_BatchTierCalculation.cls
global class CS_BatchTierCalculation implements Database.Batchable<sObject> {
	
	public String query;
	private Date monthAfter = system.today().addMonths(1);
	private list<Id> accIds;

	global CS_BatchTierCalculation() {
		query = 'select Payment__r.order__r.Opportunity__r.accountid, Amount__c from payment_schedule__c where Billing_Date__c  >= TODAY AND Billing_Date__c  < :monthAfter and status__c != ' + '\'Cancelled\'';
	}

	global CS_BatchTierCalculation(Id accountId) {
		query = 'select Payment__r.order__r.Opportunity__r.accountid, Amount__c from payment_schedule__c where Billing_Date__c  >= TODAY '+
		+'AND Billing_Date__c  < :monthAfter and status__c != ' + '\'Cancelled\' AND payment__r.order__r.account__c= \'' + accountId + '\'';
	}

	global CS_BatchTierCalculation(List<Id> accountIds) {
		accIds = accountIds;// Added by shabu
		query = 'select Payment__r.order__r.Opportunity__r.accountid, Amount__c from payment_schedule__c where Billing_Date__c  >= TODAY '+
		+'AND Billing_Date__c  < :monthAfter and status__c != ' + '\'Cancelled\' AND payment__r.order__r.account__c IN  :accIds';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {

		return Database.getQueryLocator(query);
	}

  	global void execute(Database.BatchableContext BC, List<sObject> scope) {

  		List<payment_schedule__c> paySchList = (List<payment_schedule__c>)scope;

  		CS_TierCalculation.setAccountTierFor(paySchList);

    }
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}