News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date__c</fullName>
    <description>This field is supposed to be read only and mirrored from Payment record End Date. Re-labelled to End Date
NXRIII-311</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Change In Business</fullName>
            </value>
            <value>
                <fullName>Client Perceived ROI</fullName>
            </value>
            <value>
                <fullName>Customer Service Issue</fullName>
            </value>
            <value>
                <fullName>Moving to Another Provider (specify below)</fullName>
            </value>
            <value>
                <fullName>Package Adjustment</fullName>
            </value>
            <value>
                <fullName>Seasonal Campaign Booked as Evergreen</fullName>
            </value>
            <value>
                <fullName>Upsell</fullName>
            </value>
            <value>
                <fullName>Downsell</fullName>
            </value>
            <value>
                <fullName>Financial Difficulty</fullName>
            </value>
            <value>
                <fullName>Achieved Desired Outcome</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Cancellation_Reason_Notes__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason_Notes__c</fullName>
    <description>This field is supposed to be read only and mirrored from Payment record 
NXRIII-311</description>
    <label>Cancellation Reason Notes</label>
    <type>TextArea</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Cancelled_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_Date__c</fullName>
    <description>This field is supposed to be read only and mirrored from Payment record 
NXRIII-311</description>
    <label>Cancelled Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Billing Period End Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Minimum_Evergreen_Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Evergreen_Cancellation_Date__c</fullName>
    <description>This field is supposed to be read only and mirrored from Payment record
NXRIII-311</description>
    <label>Minimum Evergreen Cancellation Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Payment__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Change in Business</fullName>
            </value>
            <value>
                <fullName>Client perceived ROI</fullName>
            </value>
            <value>
                <fullName>Customer Service Issue</fullName>
            </value>
            <value>
                <fullName>Moving to Another Provider (specify below)</fullName>
            </value>
            <value>
                <fullName>Package Adjustment</fullName>
            </value>
            <value>
                <fullName>Seasonal Campaign booked as Evergreen</fullName>
            </value>
            <value>
                <fullName>Upsell</fullName>
            </value>
            <value>
                <fullName>Downsell</fullName>
            </value>
            <value>
                <fullName>Financial Difficulty</fullName>
            </value>
            <value>
                <fullName>Achieved Desired Outcome</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/fields/Cancellation_Reason_Notes__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason_Notes__c</fullName>
    <label>Cancellation Reason Notes</label>
    <type>TextArea</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/fields/Cancelled_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_Date__c</fullName>
    <description>Date the campaign has been cancelled</description>
    <label>Cancelled Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/fields/Minimum_Evergreen_Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Evergreen_Cancellation_Date__c</fullName>
    <description>Date before which an evergreen contract cannot be cancelled</description>
    <label>Minimum Evergreen Cancellation Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/classes/CS_PaymentTriggerDelegate.cls
public with sharing class CS_PaymentTriggerDelegate  extends CS_TriggerHandler.DelegateBase 
{
	Map<Id,Payment__c> mapOrderIdPayment;

	public override void prepareAfter() 
    {
		mapOrderIdPayment = new Map<Id,Payment__c>();
	}

	public override void afterInsert(sObject o) 
    {
		Payment__c newPayment = (Payment__c)o;
		{
			mapOrderIdPayment.put(newPayment.Order__c, newPayment);
		}
	}

	public override void afterUpdate(sObject old, sObject o)
    {
		Payment__c newPayment = (Payment__c)o;
        Payment__c oldPayment = (Payment__c)old;
		

		if ((newPayment.End_Date__c!=oldPayment.End_Date__c) || 
			(newPayment.Cancellation_Reason__c!=oldPayment.Cancellation_Reason__c) ||
			(newPayment.Cancellation_Reason_Notes__c!=oldPayment.Cancellation_Reason_Notes__c) ||
			(newPayment.Minimum_Evergreen_Cancellation_Date__c!=oldPayment.Minimum_Evergreen_Cancellation_Date__c) ||
			(newPayment.Cancelled_Date__c!=oldPayment.Cancelled_Date__c))
		{
			mapOrderIdPayment.put(newPayment.Order__c, newPayment);
		}
	}

	private void SyncCampaignOrder()
	{
		if (mapOrderIdPayment.size()>0)
		{
			List<Order__c> lstOrderSync = [select Id, End_Date__c,Cancellation_Reason__c,
				Cancellation_Reason_Notes__c , Minimum_Evergreen_Cancellation_Date__c, 
				Cancelled_Date__c
				from Order__c where Id in : mapOrderIdPayment.keySet()];

			for (Order__c tmpOrder : lstOrderSync)
			{
				Payment__c tmpPayment = mapOrderIdPayment.get(tmpOrder.Id);

				tmpOrder.Cancellation_Reason__c = tmpPayment.Cancellation_Reason__c;
				tmpOrder.Minimum_Evergreen_Cancellation_Date__c=tmpPayment.Minimum_Evergreen_Cancellation_Date__c;
				tmpOrder.Cancelled_Date__c=tmpPayment.Cancelled_Date__c;
				tmpOrder.Cancellation_Reason_Notes__c=tmpPayment.Cancellation_Reason_Notes__c;
				tmpOrder.Cancellation_Date__c = tmpPayment.End_Date__c; //Cancellation Date has been re-labelled to End Date
			}

			update lstOrderSync;
		}
	}

	public override void finish() 
    {
		if (Trigger.isAfter)
		{
			SyncCampaignOrder();
		}
	}
}