News UAT/force-app/main/default/objects/Portfolio_Account_Staging__c/Portfolio_Account_Staging__c.object-meta.xml
<CustomObject>
    <description>landing object for all current account - portfolio mappings from Phoenix report team</description>
    <label>Portfolio Account Staging</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Portfolio Account Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Account Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Portfolio_Staging__c/Portfolio_Staging__c.object-meta.xml
<CustomObject>
    <description>Staging table for loading Portfolio details and its Owners from Phoenix BI tool.</description>
    <label>Portfolio Staging</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Portfolio Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Portfolio_Staging__c/fields/Portfolio_Code__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Code__c</fullName>
    <externalId>true</externalId>
    <label>Portfolio Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/BatchDeleteProcess_Test.cls
@isTest
private class BatchDeleteProcess_Test {

	@testSetup static void Setup() {
		Portfolio_Staging__c port = new Portfolio_Staging__c();
		port.Portfolio_Code__c = '01';

		insert port;

		Portfolio_Account_Staging__c psa = new Portfolio_Account_Staging__c();
		psa.Account_Name__c = 'Sample';

		insert psa;
	}

	/**
	* Delete the Portfolio_S
	 */
	@isTest static void batchDelete_Test() {
		
		Test.startTest();

		BatchDeleteProcess d = new BatchDeleteProcess();
		Database.executeBatch(d);

		Test.stopTest();

		System.assertEquals(0,[select count() from Portfolio_Account_Staging__c],'Portfolio_Account_Staging__c should be empty');
	}


	@isTest static void batchDeletePortStaging_Test() {
		Test.startTest();

		BatchDeleteProcess d = new BatchDeleteProcess(true);
		Database.executeBatch(d);

		Test.stopTest();
		System.assertEquals(0,[select count() from Portfolio_Staging__c],'Portfolio_Staging__c should be empty');
	}
}