News UAT/force-app/main/default/objects/NXX2_Proof_Staging__c/NXX2_Proof_Staging__c.object-meta.xml
<CustomObject>
    <description>This will contain proof records of google cloud storage.</description>
    <label>NXX2 Proof Staging</label>
    <nameField>
        <label>NXX2 Campaign Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NXX2 Proofs Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_ProofAd_Staging__c/NXX2_ProofAd_Staging__c.object-meta.xml
<CustomObject>
    <description>This will contain records of proof ads from google cloud storage</description>
    <label>NXX2 ProofAd Staging</label>
    <nameField>
        <label>NXX2 ProofAd Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NXX2 ProofAds Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Opportunity/fields/Payer_Account__c.field-meta.xml
<CustomField>
    <fullName>Payer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payer Account</relationshipLabel>
    <relationshipName>Opportunities_Payer</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Fulfillment_Type__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Type__c</fullName>
    <formula>Product_Node__r.Product_Line__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fulfillment Type</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Product Orders</relationshipLabel>
    <relationshipName>Product_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/recordTypes/Social.recordType-meta.xml
<RecordType>
    <fullName>Social</fullName>
    <active>true</active>
    <label>Social</label>
</RecordType>

News UAT/force-app/main/default/classes/NXX2_SchedulerForDataMigrationTest.cls
@isTest
private class NXX2_SchedulerForDataMigrationTest {
	static testMethod void testDataMigration(){
        NXX2_TestUtility.disableAllTriggerDuringTesting();
        List<BusinessHours> bhs = [select id from BusinessHours where IsDefault=true];
        csmso__SalesOrderAPI__c soApi = TestDataSetupClass.createSalesOrderAPI();
        insert soApi;
        List<Account> accounts = TestDataFactory.createAccounts(3,false);
        insert accounts;
        List<Contact> contacts = TestDataFactory.createContacts(1,accounts[0]);
        insert contacts;
        List<Opportunity> opportunities = TestDataFactory.createOpportunities_withContact(2,Test.getStandardPricebookId(),accounts[0],contacts[0]);
        opportunities[0].Payer_Account__c = accounts[1].Id;
        opportunities[1].Payer_Account__c = accounts[2].Id;
        insert opportunities;
        Order__c campaignOrder = NXX2_TestUtility.createCampaignOrder(opportunities[0].Id, contacts[0].Id, accounts[0].Id);
        List<csmso__Product_Node__c> nodes = NXX2_TestUtility.createProductNodesForProductLine('Display');
        List<Product_Order__c> pos = NXX2_TestUtility.createProductOrderWithProductNodes(campaignOrder.Id,nodes);
        pos = [SELECT Name, Fulfillment_Type__c FROM Product_Order__c];
        NXX2_TestUtility.insertStagingTasks(pos);
        List<NXX2_Proof_Staging__c> proofs = NXX2_TestUtility.insertStagingProofs(pos);
        List<NXX2_ProofAd_Staging__c> proofAds = NXX2_TestUtility.insertStagingProofAds(pos);
        NXX2_TestUtility.insertStagingAssets(proofAds,proofs,false);
        NXX2_TestUtility.insertStagingSocialForm(proofAds);
		Test.startTest();
        Test.setMock(HttpCalloutMock.class, new NXX2_GoogleDriveAPIMockUp());
        NXX2_SchedulerForDataMigration sh1 = new NXX2_SchedulerForDataMigration();
        String sch = '0 0 23 * * ?'; 
        system.schedule('Test Data Migration', sch, sh1);
        Test.stopTest();  	
    }
    static testMethod void testDataMigration1(){
        NXX2_TestUtility.disableAllTriggerDuringTesting();
        List<BusinessHours> bhs = [select id from BusinessHours where IsDefault=true];
        csmso__SalesOrderAPI__c soApi = TestDataSetupClass.createSalesOrderAPI();
        insert soApi;
        List<Account> accounts = TestDataFactory.createAccounts(3,false);
        insert accounts;
        List<Contact> contacts = TestDataFactory.createContacts(1,accounts[0]);
        insert contacts;
        List<Opportunity> opportunities = TestDataFactory.createOpportunities_withContact(2,Test.getStandardPricebookId(),accounts[0],contacts[0]);
        opportunities[0].Payer_Account__c = accounts[1].Id;
        opportunities[1].Payer_Account__c = accounts[2].Id;
        insert opportunities;
        Order__c campaignOrder = NXX2_TestUtility.createCampaignOrder(opportunities[0].Id, contacts[0].Id, accounts[0].Id);
        List<csmso__Product_Node__c> nodes = NXX2_TestUtility.createProductNodesForProductLine('Social');
        List<Product_Order__c> pos = NXX2_TestUtility.createProductOrderWithProductNodes(campaignOrder.Id,nodes);
        pos = [SELECT Name, Fulfillment_Type__c FROM Product_Order__c];
        NXX2_TestUtility.insertStagingTasks(pos);
        List<NXX2_Proof_Staging__c> proofs = NXX2_TestUtility.insertStagingProofs(pos);
        List<NXX2_ProofAd_Staging__c> proofAds = NXX2_TestUtility.insertStagingProofAds(pos);
        NXX2_TestUtility.insertStagingAssets(proofAds,proofs,false);
        NXX2_TestUtility.insertStagingSocialForm(proofAds);
		Test.startTest();
        Test.setMock(HttpCalloutMock.class, new NXX2_GoogleDriveAPIMockUp());
        NXX2_SchedulerForDataMigration sh1 = new NXX2_SchedulerForDataMigration();
        String sch = '0 0 23 * * ?'; 
        system.schedule('Test Data Migration', sch, sh1);
        Test.stopTest();  	
    }
    static testMethod void testDataMigration2(){
        NXX2_TestUtility.disableAllTriggerDuringTesting();
        List<BusinessHours> bhs = [select id from BusinessHours where IsDefault=true];
        csmso__SalesOrderAPI__c soApi = TestDataSetupClass.createSalesOrderAPI();
        insert soApi;
        List<Account> accounts = TestDataFactory.createAccounts(3,false);
        insert accounts;
        List<Contact> contacts = TestDataFactory.createContacts(1,accounts[0]);
        insert contacts;
        List<Opportunity> opportunities = TestDataFactory.createOpportunities_withContact(2,Test.getStandardPricebookId(),accounts[0],contacts[0]);
        opportunities[0].Payer_Account__c = accounts[1].Id;
        opportunities[1].Payer_Account__c = accounts[2].Id;
        insert opportunities;
        Order__c campaignOrder = NXX2_TestUtility.createCampaignOrder(opportunities[0].Id, contacts[0].Id, accounts[0].Id);
        List<csmso__Product_Node__c> nodes = NXX2_TestUtility.createProductNodesForProductLine('Social');
        List<Product_Order__c> pos = NXX2_TestUtility.createProductOrderWithProductNodes(campaignOrder.Id,nodes);
        pos = [SELECT Name, Fulfillment_Type__c FROM Product_Order__c];
        NXX2_TestUtility.insertErrorStagingTasks(pos);
        List<NXX2_Proof_Staging__c> errorProofs = NXX2_TestUtility.insertErrorStagingProofs(pos);
        List<NXX2_ProofAd_Staging__c> errorProofAds = NXX2_TestUtility.insertErrorStagingProofAds(pos);
        NXX2_TestUtility.insertErrorStagingAssets(errorProofAds,errorProofs,false);
        NXX2_TestUtility.insertErrorStagingSocialForm(errorProofAds);
		Test.startTest();
        Test.setMock(HttpCalloutMock.class, new NXX2_GoogleDriveAPIMockUp());
        NXX2_SchedulerForDataMigration sh1 = new NXX2_SchedulerForDataMigration();
        String sch = '0 0 23 * * ?'; 
        system.schedule('Test Data Migration', sch, sh1);
        Test.stopTest();  	
    }
}