News UAT/force-app/main/default/objects/Business_Announcement__c/Business_Announcement__c.object-meta.xml
<CustomObject>
    <label>Business Announcement</label>
    <nameField>
        <label>Announcement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Business_Announcement__c/fields/Announcement__c.field-meta.xml
<CustomField>
    <fullName>Announcement__c</fullName>
    <label>Announcement</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

News UAT/force-app/main/default/objects/Business_Announcement__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <inlineHelpText>Ensure all text is on a single line. Do not include any line breaks, or else the text will not show properly on the home page.</inlineHelpText>
    <label>Content</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

News UAT/force-app/main/default/objects/Business_Announcement__c/fields/Display__c.field-meta.xml
<CustomField>
    <fullName>Display__c</fullName>
    <label>Display</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ticker</fullName>
            </value>
            <value>
                <fullName>Pop-up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Business_Announcement__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>This is the Order of this announcement.</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Fulfilment Ready</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Campaign Live</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/User_Announcement_Status__c/User_Announcement_Status__c.object-meta.xml
<CustomObject>
    <label>User Announcement Status</label>
    <nameField>
        <displayFormat>UAS-{0000}</displayFormat>
        <label>Announcement Status</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Announcement Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/User_Announcement_Status__c/fields/Announcement__c.field-meta.xml
<CustomField>
    <fullName>Announcement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Announcement</label>
    <referenceTo>Business_Announcement__c</referenceTo>
    <relationshipLabel>User Announcement Statuses</relationshipLabel>
    <relationshipName>User_Announcement_Statuses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/User_Announcement_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Displayed</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/User_Announcement_Status__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Announcement_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/classes/AT_Announcements_Test.cls
@isTest
public class AT_Announcements_Test {
	@isTest
    static void testTickerAnnouncements() {
        //SELECT Id, Name, Content__c FROM Business_Announcement__c WHERE (Display__c INCLUDES ('Pop-up')) AND (Id NOT IN (SELECT Announcement__c FROM User_Announcement_Status__c WHERE (User__c = :UserInfo.getUserId()) AND (Status__c = 'Actioned'))) ORDER BY Order__c ASC]
        
        Business_Announcement__c ann = new Business_Announcement__c(Content__c = 'test', Display__c = 'Ticker', Order__c = 0);
        
        insert ann;
        
        List<AT_Announcements.Announcement> anns = AT_Announcements.getAnnouncements();
        
        System.assertNotEquals(null, anns);
        System.assertEquals(1, anns.size());
        
        System.assertEquals('test', anns[0].text);
    }
    
    @isTest
    static void testPopupAnnouncements() {
        //SELECT Id, Name, Content__c FROM Business_Announcement__c WHERE (Display__c INCLUDES ('Pop-up')) AND (Id NOT IN (SELECT Announcement__c FROM User_Announcement_Status__c WHERE (User__c = :UserInfo.getUserId()) AND (Status__c = 'Actioned'))) ORDER BY Order__c ASC]
        
        Business_Announcement__c ann = new Business_Announcement__c(Content__c = 'test', Display__c = 'Pop-up', Order__c = 0);
        
        insert ann;
        
        List<AT_Announcements.Announcement> anns = AT_Announcements.getPopups();
        
        System.assertNotEquals(null, anns);
        System.assertEquals(1, anns.size());
        
        System.assertEquals('test', anns[0].text);
        
        AT_Announcements.displayPopup(anns[0].id);
        
        AT_Announcements.actionPopup(anns[0].id);
        
        anns = AT_Announcements.getPopups();
        
        System.assertEquals(0, anns.size());
    }
}