News UAT/force-app/main/default/objects/Customer_Task__c/Customer_Task__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Customer Activity</label>
    <nameField>
        <displayFormat>CAN-{YYMMDD}-{0000}</displayFormat>
        <label>Customer Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will contain the reference of Product Order for Approve Display Ad Proof Task</description>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Product Orders</relationshipLabel>
    <relationshipName>Product_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/SocialCampaign__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Proof</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proofs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/SocialCampaign__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipName>Social_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/classes/NXX2_SalesforceDataServiceTest.cls
@isTest
public class NXX2_SalesforceDataServiceTest{
    public static testMethod void testUtility() {
        Test.startTest();
        NXX2_TestUtility.disableAllTriggerDuringTesting();
        List<Account> accounts = TestDataFactory.createAccounts(1,false);
        insert accounts;
        List<Contact> contacts = TestDataFactory.createContacts(1,accounts[0]);
        insert contacts;
        List<Opportunity> opportunities = TestDataFactory.createOpportunities_withContact(1,Test.getStandardPricebookId(),accounts[0],contacts[0]);
        Order__c campaignOrder = NXX2_TestUtility.createCampaignOrder(opportunities[0].Id, contacts[0].Id, accounts[0].Id);
        List<Product_Order__c> pos = NXX2_TestUtility.createProductOrder(1, campaignOrder.Id);
        SocialCampaign__c proof = NXX2_TestUtility.createProof(pos[0].Id);
        List<Customer_Task__c> activityForCO = NXX2_TestUtility.createCustomerActivityForCampaignOrder(new List<Order__c>{campaignOrder});
        Test.stopTest();
        NXX2_SalesforceDataService.getSocialAdTypes();
        NXX2_SalesforceDataService.getSocialAdCreativeTypes();
        NXX2_SalesforceDataService.findMataDataIsConfiguredForRespectiveObjectOrNot(proof.Id);
        NXX2_SalesforceDataService.getCustomerTaskLists(activityForCO[0].Id, 'SocialCampaign__c', true);
        NXX2_SalesforceDataService.getCustomerTaskLists(activityForCO[0].Id, 'SocialCampaign__c', false);
        NXX2_SalesforceDataService.getCustomerTaskLists(activityForCO[0].Id, 'Order__c', true);        
        NXX2_SalesforceDataService.getCustomerTaskLists(activityForCO[0].Id, 'Product_Order__c', true);
        NXX2_SalesforceDataService.getCustomerTaskLists(activityForCO[0].Id, 'Account', true);
        NXX2_SalesforceDataService.getCustomerTaskLists(activityForCO[0].Id, 'Account', false);
        NXX2_SalesforceDataService.getCustomerTaskLists(activityForCO[0].Id, 'CommunityHomeTasks', true);
        NXX2_SalesforceDataService.getAccountsLists(new List<Id>{accounts[0].Id});
        NXX2_SalesforceDataService.fetchLoggedInUsersDetails();
        NXX2_SalesforceDataService.getMyAccounts(UserInfo.getUserId());
        NXX2_SalesforceDataService.updateCustomerTask(activityForCO[0].Id);
        NXX2_SalesforceDataService.getProofNumber(proof.Id);
        NXX2_SalesforceDataService.getPayerAccountOpportunities(new List<Id>{accounts[0].Id});
        NXX2_SalesforceDataService.getPrimareyAccountOpportunities(new List<Id>{accounts[0].Id});
        NXX2_SalesforceDataService.getProofRecordsAssocatedToAccounts(new Set<String>{accounts[0].Id});
        NXX2_SalesforceDataService.fetchAllContactRolesLinkedToContact(contacts[0].Id);
        NXX2_SalesforceDataService.fetchContactsDetails(new List<Id>{contacts[0].Id});
    }
}