News UAT/force-app/main/default/objects/Customer_Task__c/Customer_Task__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Customer Activity</label>
    <nameField>
        <displayFormat>CAN-{YYMMDD}-{0000}</displayFormat>
        <label>Customer Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Campaign_Order__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will contain the reference of Product Order for Approve Display Ad Proof Task</description>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Social_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Social_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This relationship to link social campaign to a customer task to get &quot;Campaign Tasks&quot;</description>
    <label>Social Campaign</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>With Client</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
                <isActive>false</isActive>
                <label>In Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>1.This will capture the Task Type.</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upload Creative Assets</fullName>
            </value>
            <value>
                <fullName>Place GTM on Website</fullName>
            </value>
            <value>
                <fullName>Extend Access to Google Analytics</fullName>
            </value>
            <value>
                <fullName>Approve and Review Your Display Ads</fullName>
            </value>
            <value>
                <fullName>Approve and Review Your Facebook Ads</fullName>
            </value>
            <value>
                <fullName>Grant News Xtend Facebook Access</fullName>
            </value>
            <value>
                <fullName>Approve and Review Your Landing Page</fullName>
            </value>
            <value>
                <fullName>Approve Display Ad Proof</fullName>
                <isActive>false</isActive>
                <label>Approve Display Ad Proof</label>
            </value>
            <value>
                <fullName>Approve Facebook Ads Proof</fullName>
                <isActive>false</isActive>
                <label>Approve Facebook Ads Proof</label>
            </value>
            <value>
                <fullName>Generic Task</fullName>
                <isActive>false</isActive>
                <label>Generic Task</label>
            </value>
            <value>
                <fullName>Google Tag Manager</fullName>
                <isActive>false</isActive>
                <label>Google Tag Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Email_Configuration_Detail__mdt/NXX2_Email_Configuration_Detail__mdt.object-meta.xml
<CustomObject>
    <description>This will be used to provide emial configuration details like community name for url, reply email id etc.</description>
    <label>NXX2 Email Configuration Detail</label>
    <pluralLabel>NXX2 Email Configuration Details</pluralLabel>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_Email_Configuration_Detail__mdt/fields/Asset_File_Name_For_Logo__c.field-meta.xml
<CustomField>
    <fullName>Asset_File_Name_For_Logo__c</fullName>
    <description>This will be used to show logo in email</description>
    <label>Asset File Name For Logo</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Email_Configuration_Detail__mdt/fields/Community_Name__c.field-meta.xml
<CustomField>
    <fullName>Community_Name__c</fullName>
    <description>Name of the community which will be used to fetch url to provide link in email</description>
    <label>Community Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Email_Configuration_Detail__mdt/fields/Customer_Activity_Portal_Page_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Customer_Activity_Portal_Page_Base_Url__c</fullName>
    <description>Base url of the customer activity portal page</description>
    <label>Customer Activity Portal Page Base Url</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Email_Configuration_Detail__mdt/fields/No_Reply_Email_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>No_Reply_Email_Display_Name__c</fullName>
    <description>The display name of no reply email which will be used to fetch the sender email id.</description>
    <label>No Reply Email Display Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/NXX2_Email_Configuration_Detail__mdt/fields/Proof_Portal_Page_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Proof_Portal_Page_Base_Url__c</fullName>
    <description>Base url of the proof portal page</description>
    <label>Proof Portal Page Base Url</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Product Orders</relationshipLabel>
    <relationshipName>Product_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Returned to CM</fullName>
            </value>
            <value>
                <fullName>Initial QA</fullName>
            </value>
            <value>
                <fullName>Peer review</fullName>
            </value>
            <value>
                <fullName>Peer review failed</fullName>
            </value>
            <value>
                <fullName>Ready to go live</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
            <value>
                <fullName>Cancellation Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicate the type of campaign order line item</description>
    <inlineHelpText>Indicate the type of campaign order line item</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Unchanged</fullName>
            </value>
            <value>
                <fullName>Renew</fullName>
            </value>
            <value>
                <fullName>Unchanged (Fulfilled)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/recordTypes/Content.recordType-meta.xml
<RecordType>
    <fullName>Content</fullName>
    <active>true</active>
    <label>Content</label>
</RecordType>

News UAT/force-app/main/default/objects/Product_Order__c/recordTypes/Social.recordType-meta.xml
<RecordType>
    <fullName>Social</fullName>
    <active>true</active>
    <label>Social</label>
</RecordType>

News UAT/force-app/main/default/objects/SocialCampaign__c/SocialCampaign__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Proof</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proofs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/SocialCampaign__c/fields/Due_Date_For_Auto_Approval__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_For_Auto_Approval__c</fullName>
    <formula>CreatedDate  +  $Setup.NXX2_Proofs_Setting__c.Approve_Task_After_X_Days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Due Date For Auto Approval</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipName>Social_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/fields/Proof_Name__c.field-meta.xml
<CustomField>
    <fullName>Proof_Name__c</fullName>
    <description>Proof Name</description>
    <label>Proof Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Internal QA</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>With Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/recordTypes/Display.recordType-meta.xml
<RecordType>
    <fullName>Display</fullName>
    <active>true</active>
    <description>Record for display ad</description>
    <label>Display</label>
</RecordType>

News UAT/force-app/main/default/objects/SocialCampaign__c/recordTypes/Social.recordType-meta.xml
<RecordType>
    <fullName>Social</fullName>
    <active>true</active>
    <description>Record with social ad</description>
    <label>Social</label>
</RecordType>

News UAT/force-app/main/default/classes/NXX2_SendReminderEmailForContentApproval.cls
/**
* @author       Kamal Sharma
* @date         2018-05-25
* @className    NXX2_SendReminderEmailForContentApproval
* @description  This class exposes a method for process builder 
*               which will be called to send reminder email to the customer for creative approval.
*/
public class NXX2_SendReminderEmailForContentApproval {
    /**
    * @author       Kamal Sharma
    * @date         2018-05-23
    * @description  This method will be invoked by process builder to send reminder email 
    *               to the customer for creative approval.
    * @param        List<Customer_Task__c> activities
    * @return       void
    */
    @InvocableMethod(label='Send Reminder Email To Content Approval' description='This method will send reminder email to the customer to approve creative')
    public static void sendEmailToCustomer(List<SocialCampaign__c> proofs) {
        if(proofs != null){
            List<Id> contacts = new List<Id>();
            SocialCampaign__c proof = [SELECT Proof_Name__c,RecordType.Name,Due_Date_For_Auto_Approval__c,
                                       Product_Order__r.Order__r.Campaign_Customer_Contact__r.Name,
                                       Product_Order__r.Order__r.Campaign_Customer_Contact__r.Email,
                                       (SELECT Type__c FROM Customer_Tasks__r WHERE Status__c = 'With Client' ORDER BY CreatedDate desc)
                                       FROM SocialCampaign__c WHERE Id = :proofs[0].Id];
            if(proof != null){
                Customer_Task__c relatedTask;
                for(Customer_Task__c task : proof.Customer_Tasks__r){
                    if(proof.RecordType.Name == 'Social' && task.Type__c == 'Approve and Review Your Facebook Ads'){
                        relatedTask = task;
                        break;
                    }
                    if(proof.RecordType.Name == 'Display' && task.Type__c == 'Approve and Review Your Display Ads'){
                        relatedTask = task;
                        break;
                    }
                }
                NXX2_Email_Configuration_Detail__mdt emailConfiguration = [SELECT Community_Name__c,
                                                                           Asset_File_Name_For_Logo__c,
                                                                           No_Reply_Email_Display_Name__c,
                                                                           Customer_Activity_Portal_Page_Base_Url__c,
                                                                           Proof_Portal_Page_Base_Url__c
                                                                           FROM NXX2_Email_Configuration_Detail__mdt 
                                                                           WHERE DeveloperName = 'Send_Email_Config'];
                EmailTemplate emailTemplate = [SELECT Id, Subject, HtmlValue, Body 
                                               FROM EmailTemplate 
                                               WHERE DeveloperName = 'NXX2_Reminder_to_approve_proof_content'];
                Network myNetwork = [SELECT Id FROM Network WHERE Name = :emailConfiguration.Community_Name__c];
                ConnectApi.Community  myCommunity;
                if(Test.isRunningTest()){
                    myCommunity = new ConnectApi.Community();
                    myCommunity.siteUrl = 'Test';
                }else{
                    myCommunity = ConnectApi.Communities.getCommunity(myNetwork.id);
                }
                String customeTaskLink = myCommunity.siteUrl + emailConfiguration.Customer_Activity_Portal_Page_Base_Url__c + (relatedTask != null ? String.valueOf(relatedTask.Id) : '');
                String proofLink = myCommunity.siteUrl + emailConfiguration.Proof_Portal_Page_Base_Url__c + proof.Id;
                OrgWideEmailAddress fromEmail = [SELECT Id, DisplayName, Address FROM OrgWideEmailAddress WHERE DIsplayName = :emailConfiguration.No_Reply_Email_Display_Name__c];
                List<Messaging.Singleemailmessage> listSingleEmailMessages = new List<Messaging.Singleemailmessage>();
                String HTML_Email_Body = emailTemplate.HtmlValue.replace('{!Receiving_User.Name}',proof.Product_Order__r.Order__r.Campaign_Customer_Contact__r.Name);
                HTML_Email_Body = HTML_Email_Body.replace('COMMUNITY_URL',myCommunity.siteUrl);
                HTML_Email_Body = HTML_Email_Body.replace('ORG_ID',UserInfo.getOrganizationId());
                HTML_Email_Body = HTML_Email_Body.replace('LOGO_NAME',emailConfiguration.Asset_File_Name_For_Logo__c);
                HTML_Email_Body = HTML_Email_Body.replace('VIEW_CUSTOMER_TASK_LINK',customeTaskLink);
                HTML_Email_Body = HTML_Email_Body.replace('{!SocialCampaign__c.Name}',proof.Proof_Name__c);
                HTML_Email_Body = HTML_Email_Body.replace('VIEW_PROOF_LINK',proofLink);
                HTML_Email_Body = HTML_Email_Body.replace('{!SocialCampaign__c.Due_Date_For_Auto_Approval__c}',NXX2_AppUtility.formatDateForEmail(proof.Due_Date_For_Auto_Approval__c));
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(new String[] { proof.Product_Order__r.Order__r.Campaign_Customer_Contact__r.Email });
                mail.setOrgWideEmailAddressId(fromEmail.Id);
                mail.setSubject(emailTemplate.Subject);
                mail.setHtmlBody(HTML_Email_Body);
                listSingleEmailMessages.add(mail);
                if(!Test.isRunningTest()){
                    Messaging.sendEmail(listSingleEmailMessages);
                }
            }
        }
    }
}