News UAT/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Payment__c/fields/Number_of_Pending_PS__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Pending_PS__c</fullName>
    <label>Number of Pending PS</label>
    <summaryFilterItems>
        <field>Payment_Schedule__c.Status__c</field>
        <operation>equals</operation>
        <value>Pending</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment_Schedule__c.Payment__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

News UAT/force-app/main/default/classes/CS_BatchEvergreenRenewal.cls
/**
 * Batch class which picks up all payments scheduled for renewal
 */
global class CS_BatchEvergreenRenewal implements Database.Batchable<sObject> {
	
	private String query;
	
	public CS_BatchEvergreenRenewal() {
		query = 'select id from Payment__c where Number_of_Pending_PS__c = 3 and End_Date__c = null';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC){
		return Database.getQueryLocator(query);
	}
	
	global void execute(Database.BatchableContext BC, List<sObject> scope){
		List<Payment__c> payments = (List<Payment__c>) scope;
		Set<Id> paymentIds = new Set<Id>();
		for (Payment__c p : payments) {
			paymentIds.add(p.Id);
		}
		CS_EvergreenPaymentRenewalHelper.clonePaymentScheduleWithLineItems(paymentIds);
	}

	/**
	 * Does nothing
	 */
	global void finish(Database.BatchableContext BC){
	}
	
	

}