News UAT/force-app/main/default/objects/Industry_Code__c/Industry_Code__c.object-meta.xml
<CustomObject>
    <description>ANZSIC 2006 Industry Codes.

4 levels (Division, Subdivision, Group, Class)</description>
    <label>Industry Code</label>
    <nameField>
        <label>Industry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industry Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Industry_Code__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Code</label>
    <referenceTo>Industry_Code__c</referenceTo>
    <relationshipLabel>Opportunities_IndustryCode</relationshipLabel>
    <relationshipName>Opportunities_IndustryCode</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Owner_Division__c.field-meta.xml
<CustomField>
    <fullName>Owner_Division__c</fullName>
    <formula>IF(LEFT(Owner.UserRole.Name,14) = &quot;NSW Consortium&quot;, 
&quot;KAC&quot;, 
IF(LEFT(Owner.UserRole.Name,16) = &quot;NSW Key Accounts&quot;, 
&quot;KAC&quot;, 
IF(LEFT(Owner.UserRole.Name,8) = &quot;Prestige&quot;, 
&quot;KAC&quot;, 
IF(Left(Owner.UserRole.Name,7) = &quot;VIC KAM&quot;, 
&quot;KAC&quot;, 
IF(Left(Owner.UserRole.Name,16) = &quot;Key Accounts VIC&quot;, 
&quot;KAC&quot;, 
IF(Left(Owner.UserRole.Name,14) = &quot;Consortium VIC&quot;, 
&quot;KAC&quot;, 
IF(LEFT(Owner.UserRole.Name,7) = &quot;KAC VIC&quot;, 
&quot;KAC&quot;, 
IF(Left(Owner.UserRole.Name,7) = &quot;IMA NSW&quot;, 
&quot;NSW&quot;, 
IF(Left(Owner.UserRole.Name,7) = &quot;SME NSW&quot;, 
&quot;NSW&quot;, 
IF(Left(Owner.UserRole.Name,11) = &quot;SME GSD NSW&quot;, 
&quot;NSW&quot;, 
IF(Left(Owner.UserRole.Name,6) = &quot;SME FS&quot;, 
&quot;NSW&quot;, 
IF(Left(Owner.UserRole.Name,6) = &quot;EGM SA&quot;, 
&quot;SA&quot;, 
IF(Left(Owner.UserRole.Name,21) = &quot;Customer Solutions SA&quot;, 
&quot;SA&quot;, 
IF(Left(Owner.UserRole.Name,9) = &quot;IMA GM SA&quot;, 
&quot;SA&quot;, 
IF(Left(Owner.UserRole.Name,10) = &quot;IMA GSD SA&quot;, 
&quot;SA&quot;, 
IF(Left(Owner.UserRole.Name,10) = &quot;IMA ASM SA&quot;, 
&quot;SA&quot;, 
IF(Left(Owner.UserRole.Name,10) = &quot;IMA ISM SA&quot;, 
&quot;SA&quot;, 
IF(Left(Owner.UserRole.Name,9) = &quot;SME GM SA&quot;, 
&quot;SA&quot;, 
IF(Left(Owner.UserRole.Name,10) = &quot;SME GSD SA&quot;, 
&quot;SA&quot;, 
IF(Left(Owner.UserRole.Name,5) = &quot;AE SA&quot;, 
&quot;SA&quot;, 
IF(Left(Owner.UserRole.Name,6) = &quot;SME SA&quot;, 
&quot;SA&quot;, 
IF(Left(Owner.UserRole.Name,22) = &quot;Customer Solutions VIC&quot;, 
&quot;VIC&quot;, 
IF(Left(Owner.UserRole.Name,7) = &quot;EGM VIC&quot;, 
&quot;VIC&quot;, 
IF(Left(Owner.UserRole.Name,7) = &quot;IMA VIC&quot;, 
&quot;VIC&quot;, 
IF(Left(Owner.UserRole.Name,7) = &quot;SME VIC&quot;, 
&quot;VIC&quot;, 
IF(Left(Owner.UserRole.Name,15) = &quot;VSD Real Estate&quot;, 
&quot;VIC&quot;, 
IF(Left(Owner.UserRole.Name,21) = &quot;QLD – General Manager&quot;, 
&quot;QLD&quot;, 
IF(Left(Owner.UserRole.Name,22) = &quot;QLD – Sales Enablement&quot;, 
&quot;QLD&quot;, 
IF(Left(Owner.UserRole.Name,13) = &quot;EGM BNE KIAMA&quot;, 
&quot;QLD&quot;, 
IF(Left(Owner.UserRole.Name,11) = &quot;EGM BNE SME&quot;, 
&quot;QLD&quot;, 
IF(Left(Owner.UserRole.Name,7) = &quot;IMA BNE&quot;, 
&quot;QLD&quot;, 
IF(Left(Owner.UserRole.Name,10) = &quot;KACIMA BNE&quot;, 
&quot;QLD&quot;, 
IF(Left(Owner.UserRole.Name,7) = &quot;SME BNE&quot;, 
&quot;QLD&quot;,
IF(Left(Owner.UserRole.Name,42) = &quot;Community Newspaper Group Ltd Partner User&quot;, 
&quot;WA&quot;,
LEFT(Owner.UserRole.Name, FIND(&#39;-&#39;, Owner.UserRole.Name)-1) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
)
)
)
)
)
)
)
)
)</formula>
    <label>Owner Division</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/AT_UpdateOpportunityStage.cls
public class AT_UpdateOpportunityStage {
    
    @InvocableMethod(label='Create Opp Orders')
    public static void createOppOrders(List<Id> oppIDs) {
        // Debugging for NXRIII-358
        System.debug('Creating opp orders for: ' + oppIDs);
        
        CS_OpportunityTriggerDelegate delegate = new CS_OpportunityTriggerDelegate();
        
        // Fix for NXRIII-356, call prepareAfter() so that the orchUser variable is set properly
        // (NXRIII-358: moving this to the top to prevent overwriting newlyClosedOneOpps)
        delegate.prepareAfter();
        
        delegate.newlyClosedOneOpps = new Map<Id, Opportunity>();
        
        for (Opportunity opp: [SELECT Id, AccountId, Name, OwnerId, Owner_Division__c, Contact__c, Amount, Industry_Code__c FROM Opportunity WHERE Id IN :oppIDs]) {
            delegate.newlyClosedOneOpps.put(opp.Id, opp);
        }
        
        // Debugging for NXRIII-358
        System.debug('Newly Closed Won: ' + delegate.newlyClosedOneOpps);
        
        if (!delegate.newlyClosedOneOpps.keySet().isEmpty()) {
            delegate.CreateResetOrders();
        }
    }
    
    public AT_UpdateOpportunityStage(List<Id> oppIDs){
        createOppOrders(oppIDs);
    }
}