News UAT/force-app/main/default/objects/History_Tracking__c/History_Tracking__c.object-meta.xml
<CustomObject>
    <description>This object is created to keep track of changes on a record level.</description>
    <label>History Tracking</label>
    <nameField>
        <displayFormat>HT-{00000000}</displayFormat>
        <label>History Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/History_Tracking__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The sales order record that is being tracked.</description>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>History Tracking</relationshipLabel>
    <relationshipName>History_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/History_Tracking__c/fields/Snapshot_JSON__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_JSON__c</fullName>
    <description>Snapshot of the records</description>
    <inlineHelpText>Snapshot of the records</inlineHelpText>
    <label>Snapshot JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/classes/CS_SOHistoryTrackingController.cls
/**
* @author           Kevin Wu
* @date             2018-10-01
* @className        CS_SOHistoryTrackingController
* @testClassName    CS_SOHistoryTrackingControllerTest
* @description      Controller for SO History Tracking component
*/
public with sharing class CS_SOHistoryTrackingController {
	
	/**
    * @name         : getSoHistory
    * @description  : get all history tracking information by sales order id
    * @createdby    : Kevin Wu - 2018-10-01
    * @param        : String salesOrderId
    * @return       : String
    */
    @AuraEnabled
	public static String getSoHistory(String salesOrderId) {
		CS_LightningResponse res = new CS_LightningResponse(); 

    	try{
    		List<History_Tracking__c> soHistory = CS_HistoryTrackingService.getHistoryTrackingBySO(CS_HistoryTrackingService.SALES_ORDER_API_NAME, salesOrderId);
    		List<String> allSnapshots;
    		Map<String, List<Schema.FieldSetMember>> fieldSetMappings;
            Map<String, List<Object>> allFieldMappings;
    		if(!soHistory.isEmpty()){
    			allSnapshots = new List<String>();
    			for(History_Tracking__c ht: soHistory){
	    			allSnapshots.add(ht.Snapshot_JSON__c);
	    		}
    			fieldSetMappings = CS_HistoryTrackingService.getFieldSetMappings(CS_HistoryTrackingService.SALES_ORDER_API_NAME);
                allFieldMappings = CS_HistoryTrackingService.getAllFieldMappings(CS_HistoryTrackingService.SALES_ORDER_API_NAME);
    		}
    		Map<String, Object> results = new Map<String, Object>();
    		results.put('salesOrderHistory',allSnapshots);
    		results.put('fieldSetMappings',fieldSetMappings);
            results.put('fieldMappings',allFieldMappings);

            res.code = 2000;
            res.message = 'Success';
            res.details = JSON.serialize(results);

		}catch(Exception ex){
			res.code = 5000;
			res.message = 'System error.';
			res.details = ex.getMessage();
		}
        
        return JSON.serialize(res);
	}


	/**
	* @name         : getSoHistory
	* @description  : Get the
	* @createdby    : Petar Mikic - 2019-03-11
	* @param        : String salesOrderId
	* @return       : String
	*/
	@AuraEnabled
	public static String getCampaignInfo(String salesOrderId) {
		CS_LightningResponse res = new CS_LightningResponse();

		try {
			Order__c CO = [SELECT ID,Name, Sales_Order__r.Name From Order__c WHERE Sales_order__r.Id =: salesOrderId];

			Map<String,String> results = new Map<String, String>();
			results.put('auditCO_Name', CO.Name);
			results.put('auditSO_Name', CO.Sales_Order__r.Name);

			res.code = 2000;
			res.message = 'Success';
			res.details = JSON.serialize(results);
			
		} catch(Exception ex) {
			res.code = 5000;
			res.message = 'System error.';
			res.details = ex.getMessage();
		}

		return JSON.serialize(res);
	}
}