News UAT/force-app/main/default/objects/Billing_File__c/Billing_File__c.object-meta.xml
<CustomObject>
    <label>Billing File</label>
    <nameField>
        <label>Billing File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Billing_File__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Sent To Billing</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Payment Schedule</label>
    <nameField>
        <label>Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Payment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Campaign Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/PS_Billing_File_Association__c/PS_Billing_File_Association__c.object-meta.xml
<CustomObject>
    <label>PS Billing File Association</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>PS Billing File Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Billing File Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/PS_Billing_File_Association__c/fields/Billing_File__c.field-meta.xml
<CustomField>
    <fullName>Billing_File__c</fullName>
    <label>Billing File</label>
    <referenceTo>Billing_File__c</referenceTo>
    <relationshipLabel>PS Billing File Associations</relationshipLabel>
    <relationshipName>PS_Billing_File_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/PS_Billing_File_Association__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <label>Payment Schedule</label>
    <referenceTo>Payment_Schedule__c</referenceTo>
    <relationshipLabel>PS Billing File Associations</relationshipLabel>
    <relationshipName>PS_Billing_File_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/classes/CS_SendBillingFileController.cls
/**
 * Sends billing file to ESB
 */
global class CS_SendBillingFileController {
	
	@TestVisible
	private ApexPages.StandardController controller;
	
	/**
	 * sends CSV file to ESB - used only for testing in classic
	 * @param Id billingFileId
	 * @return String
	 */
	webservice static String sendBillingFile(Id billingFileId) {
		Billing_File__c bf = [
			select id, name, Billing_Date__c, Status__c, Error_Message__c
			from Billing_File__c
			where id = :billingFileId
		];
		try {
			if (bf.Status__c == 'Sent to Billing') {
				return 'File already sent to Billing';
			}
			String res = FileExporter.pushFileToOut(bf.Id);
			if (res.contains('FAIL') || res.contains('Error')) {
				bf.Status__c = 'Error';
				bf.Error_Message__c = res;
				update bf;
				return 'Cannot send file to ESB.' + ' ' + res;
			}
			bf.Status__c = 'Sent to Billing';
			bf.Error_Message__c = '';
			update bf;
			List<Payment_Schedule__c> psToUpdate = [
				select id, status__c
				from Payment_Schedule__c
				where id in (
					select Payment_Schedule__c
					from PS_Billing_File_Association__c
					where Billing_File__c = :billingFileId
				)
			];
			if (!psToUpdate.isEmpty()) {
				for (Payment_Schedule__c ps : psToUpdate) {
					ps.Status__c = 'Invoiced';
				}
				update psToUpdate;
			}
			return 'File sent to ESB';
		} catch (Exception e) {
			bf.Status__c = 'Error';
			bf.Error_Message__c = e.getMessage();
			update bf;
			return 'Error - ' + e.getMessage();
		}
	}
	
	public CS_SendBillingFileController(ApexPages.StandardController sc) {
		this.controller = sc;
	}
	
	/**
	 * For lightning - custom action to execute code
	 * @return PageReference
	 */
	public PageReference sendBillingFile() {
		Billing_File__c bf = [
			select id, name, Billing_Date__c, Status__c, Error_Message__c
			from Billing_File__c
			where id = :controller.getRecord().Id
		];
		if (bf.Status__c == 'Sent to Billing') {
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL, 'File already sent to Billing'));
			return null;
		}
		String res = FileExporter.pushFileToOut(bf.Id);
		if (res.contains('FAIL') || res.contains('Error')) {
			bf.Status__c = 'Error';
			bf.Error_Message__c = res;
			update bf;
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL, 'Cannot send file to ESB.' + ' ' + res));
			return null;
		}
		bf.Status__c = 'Sent to Billing';
		bf.Error_Message__c = '';
		update bf;
		List<Payment_Schedule__c> psToUpdate = [
			select id, Status__c
			from Payment_Schedule__c
			where id in (
				select Payment_Schedule__c
				from PS_Billing_File_Association__c
				where Billing_File__c = :controller.getRecord().Id
			)
		];
		if (!psToUpdate.isEmpty()) {
			for (Payment_Schedule__c ps : psToUpdate) {
				ps.Status__c = 'Invoiced';
			}
			update psToUpdate;
		}
		return controller.view();
	}

}