News UAT/force-app/main/default/objects/NXX2_TriggerSettings__c/NXX2_TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This will be used to disable trigger</description>
    <label>NXX2 TriggerSettings</label>
</CustomObject>

News UAT/force-app/main/default/objects/NXX2_TriggerSettings__c/fields/FeedCommentTriggerDisabled__c.field-meta.xml
<CustomField>
    <fullName>FeedCommentTriggerDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FeedCommentTriggerDisabled</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/SocialAd__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Proof Ad</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>ProofAd Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proof Ads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Internal QA</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>With Customer</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
                <isActive>false</isActive>
                <label>In-Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/NXX2_FeedCommentTriggerHandler.cls
/**
* @author       Kamal Sharma
* @date         2019-01-02
* @className	NXX2_FeedCommentTriggerHandler
* @description  This is the handler class for feed comment trigger.
*/
public class NXX2_FeedCommentTriggerHandler implements NXX2_TriggerHandler
{
    // Allows unit tests (or other code) to disable this trigger for the transaction
    public static Boolean TriggerDisabled = false;
    /**
    * @author       Kamal Sharma
    * @date         2019-01-02
    * @description  Checks to see if the trigger has been disabled either by custom setting or by running code
    * @param        NA
    * @return       Boolean
    */
    public Boolean IsDisabled()
    {
        NXX2_TriggerSettings__c triggerSettings = NXX2_TriggerSettings__c.getInstance();
        if (triggerSettings.FeedCommentTriggerDisabled__c)
            return true;
        else
            return TriggerDisabled;
    }
    
    /**
    * @author       Kamal Sharma
    * @date         2019-01-02
    * @description  This method will check that if the feed comment belongs to proof ad(SocialAd__c) 
    * 				then this will be allowed to insert only if the proof ad status is not approved.
    * @param        Map<Id, SObject> newItems
    * @return       void
    */
    public void BeforeInsert(List<SObject> newItems) {
        if(UserInfo.getUserType() != 'Standard'){
            Map<Id,FeedComment> proofAdToFeedCommentMap = new Map<Id,FeedComment>();
            for(FeedComment comment : (List<FeedComment>)newItems){
                String parentName = comment.parentId.getSObjectType().getDescribe().getName();
                if(parentName == 'SocialAd__c'){
                    proofAdToFeedCommentMap.put(comment.parentId,comment);
                }
            }
            if(proofAdToFeedCommentMap.size() > 0){
                List<SocialAd__c> proofAds = [SELECT Status__c FROM SocialAd__c WHERE Id IN : proofAdToFeedCommentMap.keySet()];
                for(SocialAd__c proofAd : proofAds){
                    if(proofAd.Status__c == 'Approved'){
                        proofAdToFeedCommentMap.get(proofAd.Id).addError('Comments are not allowed on approved ad.');
                    }
                }
            }
        }
    }
    
    /**
    * @author       Kamal Sharma
    * @date         2019-01-02
    * @description  This method will check that if the feed comment under updation belongs to proof ad(SocialAd__c) 
    * 				then this will be allowed to update only if the proof ad status is not approved.
    * @param        Map<Id, SObject> newItems
    * @return       void
    */
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        if(UserInfo.getUserType() != 'Standard'){
            Map<Id,FeedComment> proofAdToFeedCommentMap = new Map<Id,FeedComment>();
            for(FeedComment comment : ((Map<Id,FeedComment>)newItems).values()){
                String parentName = comment.parentId.getSObjectType().getDescribe().getName();
                if(parentName == 'SocialAd__c'){
                    proofAdToFeedCommentMap.put(comment.parentId,comment);
                }
            }
            if(proofAdToFeedCommentMap.size() > 0){
                List<SocialAd__c> proofAds = [SELECT Status__c FROM SocialAd__c WHERE Id IN : proofAdToFeedCommentMap.keySet()];
                for(SocialAd__c proofAd : proofAds){
                    if(proofAd.Status__c == 'Approved'){
                        proofAdToFeedCommentMap.get(proofAd.Id).addError('Comments are not allowed on approved ad.');
                    }
                }
            }
        }
    }
    
    public void BeforeDelete(Map<Id, SObject> oldItems) {}
    
    public void AfterInsert(Map<Id, SObject> newItems) {}
    
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {}
    
    public void AfterDelete(Map<Id, SObject> oldItems) {}
    
    public void AfterUndelete(Map<Id, SObject> oldItems) {}
}