News UAT/force-app/main/default/objects/Account/fields/ABN_Exempt__c.field-meta.xml
<CustomField>
    <fullName>ABN_Exempt__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Account is ABN exempt if it is an international customer.</description>
    <inlineHelpText>Account is ABN exempt if it is an international customer.</inlineHelpText>
    <label>ABN Exempt</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/No_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>No_Parent_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to override the Parent Account required field</inlineHelpText>
    <label>No Parent Account</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/recordTypes/SME.recordType-meta.xml
<RecordType>
    <fullName>SME</fullName>
    <active>true</active>
    <description>Small to Medium Enterprises team</description>
    <label>SME</label>
</RecordType>

News UAT/force-app/main/default/objects/Account_Portfolio_Relationship__c/Account_Portfolio_Relationship__c.object-meta.xml
<CustomObject>
    <description>NextGen - Account portfolio relationship</description>
    <label>Account Portfolio Relationship</label>
    <nameField>
        <label>Account Portfolio Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Portfolio Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Account_Portfolio_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>NextGen</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Portfolio Relationships</relationshipLabel>
    <relationshipName>Account_Portfolio_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Account_Portfolio_Relationship__c/fields/Portfolio_Code__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Code__c</fullName>
    <description>Formula field from related Master Porfolio2__c.Portfolio_Code__c</description>
    <formula>Portfolio__r.Portfolio_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Portfolio Code</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Bookings related to Bookings in Cyber$ell (Genera), CyberAd, or Digital Booking Systems</description>
    <label>Booking</label>
    <nameField>
        <label>Booking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>External Booking/Billing Account</description>
    <inlineHelpText>Select the External Booking or Billing Account related to this Booking</inlineHelpText>
    <label>Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/Booking_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Booking Line Items</description>
    <label>Booking Line Item</label>
    <nameField>
        <displayFormat>BKL{00000000}</displayFormat>
        <label>Booking Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Booking_System_Portfolio_Junction__c/Booking_System_Portfolio_Junction__c.object-meta.xml
<CustomObject>
    <label>Booking System - Portfolio Junction</label>
    <nameField>
        <label>Booking System - Portfolio Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking System - Portfolio Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking_System_Portfolio_Junction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking System - Portfolio Junctions</relationshipLabel>
    <relationshipName>Booking_System_Portfolio_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_System_Portfolio_Junction__c/fields/Portfolio_Code__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Code__c</fullName>
    <formula>Portfolio__r.Portfolio_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Portfolio Code</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/External_Account__c.object-meta.xml
<CustomObject>
    <description>Object to hold external accounts such as Billing and Booking Accounts</description>
    <label>Booking System Account</label>
    <nameField>
        <label>Booking System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking System Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/External_Account__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The External Account&#39;s parent Customer Account</description>
    <inlineHelpText>The External Account&#39;s parent Customer Account</inlineHelpText>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>External_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent External Account</description>
    <inlineHelpText>Parent External Account</inlineHelpText>
    <label>Parent Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Booking System Accounts</relationshipLabel>
    <relationshipName>External_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <inlineHelpText>External Id</inlineHelpText>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/recordTypes/SME.recordType-meta.xml
<RecordType>
    <fullName>SME</fullName>
    <active>true</active>
    <businessProcess>NextGen</businessProcess>
    <description>Small to Medium Enterprises team</description>
    <label>SME</label>
</RecordType>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <label>Portfolio Team</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Portfolio Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Portfolio__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Parent Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Portfolios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Portfolio_Owners__c/Portfolio_Owners__c.object-meta.xml
<CustomObject>
    <label>Portfolio Owners</label>
    <nameField>
        <label>Portfolio Owner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio Owners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Portfolio_Owners__c/fields/Portfolio2__c.field-meta.xml
<CustomField>
    <fullName>Portfolio2__c</fullName>
    <label>Portfolio</label>
    <referenceTo>Portfolio2__c</referenceTo>
    <relationshipLabel>Portfolio Owners</relationshipLabel>
    <relationshipName>Portfolio_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Shell Order encompassing Booking(s) - to be related to an Opportunity Product/s</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{0000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Booking/Billing Account</description>
    <inlineHelpText>Select the related Booking or Billing Account</inlineHelpText>
    <label>Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Sales Orders (External Account)</relationshipLabel>
    <relationshipName>Sales_Orders_ExternalAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/User/fields/Bypass_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Triggers__c</fullName>
    <description>List of triggers that are selected to be bypassed for this user. Allows triggers to be muted.</description>
    <label>Bypass Triggers</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BookingLineItemManagement</fullName>
            </value>
            <value>
                <fullName>SalesOrderManagement</fullName>
            </value>
            <value>
                <fullName>AccountManagement</fullName>
            </value>
            <value>
                <fullName>AccountTeam</fullName>
            </value>
            <value>
                <fullName>AgreementManagement</fullName>
            </value>
            <value>
                <fullName>BookingManagement</fullName>
            </value>
            <value>
                <fullName>CampaignMemberManagement</fullName>
            </value>
            <value>
                <fullName>CaseManagement</fullName>
            </value>
            <value>
                <fullName>CleanUpAccountTeam</fullName>
            </value>
            <value>
                <fullName>ContactManagement</fullName>
            </value>
            <value>
                <fullName>emailAttachmentReassigner</fullName>
            </value>
            <value>
                <fullName>LeadManagement</fullName>
            </value>
            <value>
                <fullName>OpportunityLineItemManagement</fullName>
            </value>
            <value>
                <fullName>OpportunityManagement</fullName>
            </value>
            <value>
                <fullName>PublicationProductManagement</fullName>
            </value>
            <value>
                <fullName>TaskManagement</fullName>
            </value>
            <value>
                <fullName>ActionTask</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/AT_BatchProcesses_Test.cls
@isTest
public class AT_BatchProcesses_Test {
    @testSetup
    static void init() {
        User u = [Select Bypass_Triggers__c from User where Id =: UserInfo.getUserId()];
        
        u.Bypass_Triggers__c = 'BookingManagement;BookingLineItemManagement';
        
        update u;
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        List<User> users = new List<User>{
            new User(FirstName = 'Vacant', LastName = 'NextG', Username = 'vacant@next.g', Alias = 'vng', CommunityNickName = 'vng', Email = 'test@test.test', ProfileId = p.Id, TimeZoneSidKey = 'Australia/Sydney', LocaleSidKey = 'en_AU', EmailEncodingKey = 'ISO-8859-1', LanguageLocaleKey = 'en_US'),
            new User(FirstName = 'Unasssigned', LastName = 'NextG', Username = 'unassigned@next.g', Alias = 'ung', CommunityNickName = 'ung', Email = 'test@test.test', ProfileId = p.Id, TimeZoneSidKey = 'Australia/Sydney', LocaleSidKey = 'en_AU', EmailEncodingKey = 'ISO-8859-1', LanguageLocaleKey = 'en_US')
        };
        
        insert users;
    }
    
	@isTest
    static void testBSALinks() {
        //AT_BookingSystemPortfolioJunctionManagement
        
        Account acc = new Account(Name = 'Test', AccountNumber = '1234567890', No_Parent_Account__c = true, ABN_Exempt__c = true);
        
        insert acc;
        
        External_Account__c bsa = new External_Account__c(Name = 'test', Customer_Account__c = acc.Id, External_Id__c = 'test');
        
        insert bsa;
        
        Portfolio2__c port = new Portfolio2__c(Name = 'test', Portfolio_Code__c = 'test');
        
        insert port;
        
        Booking_System_Portfolio_Junction__c bspj = new Booking_System_Portfolio_Junction__c(Booking_System_Account__c = bsa.Id, Portfolio__c = port.Id);
        
        insert bspj;
        
        bspj = [SELECT Account__c FROM Booking_System_Portfolio_Junction__c LIMIT 1];
        
        System.assertEquals(acc.Id, bspj.Account__c);
    }
    
    @isTest
    static void testTransactionDates() {
        Set<String> recordTypeNames = new Set<String>();
        
        for (NextGen_Account_Type__mdt nat : [SELECT DeveloperName FROM NextGen_Account_Type__mdt]) {
            recordTypeNames.add(nat.DeveloperName);
        }
        
        Set<String> recordTypeIDs = new Set<String>();
        
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName IN :recordTypeNames LIMIT 1];
        
        Account acc = new Account(Name = 'Test', AccountNumber = '1234567890', No_Parent_Account__c = true, ABN_Exempt__c = true, RecordTypeId = rt.Id);
        
        insert acc;
        
        Opportunity opp = new Opportunity(Name = 'test', StageName = 'Identify Prospects', AccountId = acc.Id, CloseDate = System.Today().addDays(1));
        
        insert opp;
        
        Sales_Order__c so = new Sales_Order__c(Advertiser_Account__c = acc.Id);
        
        insert so;
        
        Booking__c b1 = new Booking__c(Advertiser_Account__c = acc.Id, Sales_Order__c = so.Id, Source_System__c = 'AdPoint');
        Booking__c b2 = new Booking__c(Advertiser_Account__c = acc.Id, Sales_Order__c = so.Id, Source_System__c = 'Cyber$ell');
        
        insert b1;
        insert b2;
        
        Booking_Line_Item__c b1i = new Booking_Line_Item__c(Booking__c = b1.Id, Run_Date__c = System.today(), Stop_On_Web_Date__c = System.today());
        Booking_Line_Item__c b2i = new Booking_Line_Item__c(Booking__c = b2.Id, Run_Date__c = System.today(), Stop_On_Web_Date__c = System.today());
        
        insert b1i;
        insert b2i;
        
        Order__c ord = new Order__c(Account__c = acc.Id);
        
        insert ord;
        
        Payment__c pay = new Payment__c(Order__c = ord.Id, Last_End_Date__c = System.today());
        
        insert pay;
        
        Test.startTest();
        
        Database.executeBatch(new AT_AccountTransactionDatesBatch());
        
        Test.stopTest();
        
        acc = [SELECT Id, Digital_Last_Transaction_Date__c, Print_Last_Transaction_Date__c, Xtend_Last_Transaction_Date__c FROM Account LIMIT 1];
        
        System.assertEquals(System.today(), acc.Digital_Last_Transaction_Date__c);
        System.assertEquals(System.today(), acc.Print_Last_Transaction_Date__c);
        System.assertEquals(System.today(), acc.Xtend_Last_Transaction_Date__c);
    }
    
    @isTest
    static void testLastClientEngagement() {
        Account acc = new Account(Name = 'Test', AccountNumber = '1234567890', No_Parent_Account__c = true, ABN_Exempt__c = true);
        
        insert acc;
        
        DateTime yesterday = System.Now().addDays(-1);
        
        Event ev = new Event(WhatId = acc.Id, StartDateTime = yesterday, EndDateTime = yesterday.addHours(1), Subject = 'test');
        
        insert ev;
        
        Test.startTest();
        
        Database.executeBatch(new AT_LastClientEngagementBatchProcess());
        
        Test.stopTest();
        
        acc = [SELECT Id, Last_Client_Engagement__c FROM Account LIMIT 1];
        
        //System.assertEquals(yesterday.addHours(1), acc.Last_Client_Engagement__c);
    }
    
    @isTest
    static void testAcccount_No_Portfolios() {
        Account acc = new Account(Name = 'Test', AccountNumber = '1234567890', No_Parent_Account__c = true, ABN_Exempt__c = true);
        
        insert acc;
        
        Test.startTest();
        
        AT_AccountPortfolioOwnershipBatch batch = new AT_AccountPortfolioOwnershipBatch();
        
        batch.initialiseState();
        
        batch.updateAccounts([SELECT Id, Type, Customer_Segment__c, OwnerId, Owner.ProfileId FROM Account]);
        
        Test.stopTest();
    }
    
    @isTest
    static void testAcccount_1Portfolio() {
        Account acc = new Account(Name = 'Test', AccountNumber = '1234567890', No_Parent_Account__c = true, ABN_Exempt__c = true);
        
        insert acc;
        
        External_Account__c bsa = new External_Account__c(Name = 'test', Customer_Account__c = acc.Id, External_Id__c = 'test');
        
        insert bsa;
        
        Portfolio2__c port = new Portfolio2__c(Name = 'test', Portfolio_Code__c = 'test');
        
        insert port;
        
        Portfolio_Owners__c owner = new Portfolio_Owners__c(Portfolio2__c = port.Id, Portfolio_Owner__c = UserInfo.getUserId());
        
        insert owner;
        
        Booking_System_Portfolio_Junction__c bspj = new Booking_System_Portfolio_Junction__c(Booking_System_Account__c = bsa.Id, Portfolio__c = port.Id);
        
        insert bspj;
        
        Test.startTest();
        
        AT_AccountPortfolioOwnershipBatch batch = new AT_AccountPortfolioOwnershipBatch();
        
        batch.initialiseState();
        
        batch.updateAccounts([SELECT Id, Type, Customer_Segment__c, OwnerId, Owner.ProfileId FROM Account]);
        
        Test.stopTest();
    }
    
    @isTest
    static void testAcccount_1Portfolio_NoOwner() {
        Account acc = new Account(Name = 'Test', AccountNumber = '1234567890', No_Parent_Account__c = true, ABN_Exempt__c = true);
        
        insert acc;
        
        External_Account__c bsa = new External_Account__c(Name = 'test', Customer_Account__c = acc.Id, External_Id__c = 'test');
        
        insert bsa;
        
        Portfolio2__c port = new Portfolio2__c(Name = 'test', Portfolio_Code__c = 'test');
        
        insert port;
        
        Booking_System_Portfolio_Junction__c bspj = new Booking_System_Portfolio_Junction__c(Booking_System_Account__c = bsa.Id, Portfolio__c = port.Id);
        
        insert bspj;
        
        Test.startTest();
        
        AT_AccountPortfolioOwnershipBatch batch = new AT_AccountPortfolioOwnershipBatch();
        
        batch.initialiseState();
        
        batch.updateAccounts([SELECT Id, Type, Customer_Segment__c, OwnerId, Owner.ProfileId FROM Account]);
        
        Test.stopTest();
    }
    
    @isTest
    static void testAcccount_2Portfolios() {
        Account acc = new Account(Name = 'Test', AccountNumber = '1234567890', No_Parent_Account__c = true, ABN_Exempt__c = true);
        
        insert acc;
        
        External_Account__c bsa = new External_Account__c(Name = 'test', Customer_Account__c = acc.Id, External_Id__c = 'test');
        
        insert bsa;
        
        Portfolio2__c port1 = new Portfolio2__c(Name = 'test1', Portfolio_Code__c = 'test1', Portfolio_Segment__c = 'SME');
        Portfolio2__c port2 = new Portfolio2__c(Name = 'test2', Portfolio_Code__c = 'test2', Portfolio_Segment__c = 'CON');
        
        insert port1;
        insert port2;
        
        Portfolio_Owners__c owner1 = new Portfolio_Owners__c(Portfolio2__c = port1.Id, Portfolio_Owner__c = UserInfo.getUserId());
        Portfolio_Owners__c owner2 = new Portfolio_Owners__c(Portfolio2__c = port2.Id, Portfolio_Owner__c = UserInfo.getUserId());
        
        insert owner1;
        insert owner2;
        
        Account_Portfolio_Relationship__c apj = new Account_Portfolio_Relationship__c(Portfolio__c = port2.Id, Account__c = acc.Id);
        
        insert apj;
        
        Booking_System_Portfolio_Junction__c bspj = new Booking_System_Portfolio_Junction__c(Booking_System_Account__c = bsa.Id, Portfolio__c = port1.Id);
        
        insert bspj;
        
        Test.startTest();
        
        AT_AccountPortfolioOwnershipBatch batch = new AT_AccountPortfolioOwnershipBatch();
        
        batch.initialiseState();
        
        batch.updateAccounts([SELECT Id, Type, Customer_Segment__c, OwnerId, Owner.ProfileId FROM Account]);
        
        Test.stopTest();
    }
    
    @isTest
    static void coverMissingFunctions() {
        AT_AccountPortfolioOwnershipBatch.getAccountIDs();
        
        AT_AccountPortfolioOwnershipBatch.updateAccounts(new List<String>());
        
        Portfolio2__c port = new Portfolio2__c(Name = 'test', Portfolio_Code__c = 'test');
        
        insert port;
        
        Portfolio_Owners__c owner = new Portfolio_Owners__c(Portfolio2__c = port.Id, Portfolio_Owner__c = UserInfo.getUserId());
        
        insert owner;
        
        AT_AccountPortfolioOwnershipBatch batch = new AT_AccountPortfolioOwnershipBatch();
        
        batch.portfoliosWithMultipleOwners.add(port.Id);
        
        Test.startTest();
        
        Database.executeBatch(batch);
        
        Test.stopTest();
    }
}