News UAT/force-app/main/default/objects/Account/fields/ABN_Exempt__c.field-meta.xml
<CustomField>
    <fullName>ABN_Exempt__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Account is ABN exempt if it is an international customer.</description>
    <inlineHelpText>Account is ABN exempt if it is an international customer.</inlineHelpText>
    <label>ABN Exempt</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Last_Client_Engagement__c.field-meta.xml
<CustomField>
    <fullName>Last_Client_Engagement__c</fullName>
    <description>Indicates the last interaction (call or appointment) with this customer</description>
    <inlineHelpText>Indicates the last interaction (call or appointment) with this customer</inlineHelpText>
    <label>Last Client Engagement</label>
    <type>DateTime</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/No_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>No_Parent_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to override the Parent Account required field</inlineHelpText>
    <label>No Parent Account</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/classes/TaskTrigger_Test.cls
@isTest
public class TaskTrigger_Test {
	@isTest
    static void testTaskCompleted() {
        Account acc = new Account(Name = 'Test', AccountNumber = '1234567890', No_Parent_Account__c = true, ABN_Exempt__c = true);
        
        insert acc;
        
        Task tk = new Task(ActivityDate = System.Today(), Subject = 'test', OwnerId = UserInfo.getUserId(), WhatId = acc.Id);
        
        insert tk;
        
        tk.Status = 'Completed';
        
        update tk;
        
        acc = [SELECT Last_Client_Engagement__c FROM Account WHERE Id = :acc.Id];
            
        System.assertNotEquals(null, acc.Last_Client_Engagement__c);
        
        System.assertEquals(System.Today(), acc.Last_Client_Engagement__c.date());
    }
}