News UAT/force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account Type</description>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency - Full Service</fullName>
            </value>
            <value>
                <fullName>Agency - Media Buyer</fullName>
            </value>
            <value>
                <fullName>Agency – Overseas Advertising Agency</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>State Government</fullName>
            </value>
            <value>
                <fullName>Private Party</fullName>
            </value>
            <value>
                <fullName>Consortium</fullName>
            </value>
            <value>
                <fullName>Agency Independent</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Sole Trader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Bookings related to Bookings in Cyber$ell (Genera), CyberAd, or Digital Booking Systems</description>
    <label>Booking</label>
    <nameField>
        <label>Booking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking__c/fields/Account_No__c.field-meta.xml
<CustomField>
    <fullName>Account_No__c</fullName>
    <formula>Sales_Order__r.External_Account__r.Account_No__c</formula>
    <label>Account #</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Calc_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Calc_External_Id__c</fullName>
    <description>Calculated External Id, for use in integration</description>
    <formula>TEXT(Source_System__c) + &#39;_&#39; + External_Sales_Division__c + Name + &#39;_&#39; + TEXT(YEAR(DATEVALUE(Third_Party_Created__c))) + LPAD(TEXT(MONTH(DATEVALUE(Third_Party_Created__c))), 2,&#39;0&#39;) + LPAD(TEXT(DAY(DATEVALUE(Third_Party_Created__c))), 2,&#39;0&#39;)</formula>
    <label>Calc External Id</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/CyberAd_AdType__c.field-meta.xml
<CustomField>
    <fullName>CyberAd_AdType__c</fullName>
    <description>CyberAd Ad Type</description>
    <label>CyberAd AdType</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>External Booking/Billing Account</description>
    <inlineHelpText>Select the External Booking or Billing Account related to this Booking</inlineHelpText>
    <label>Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Payer_Account__c.field-meta.xml
<CustomField>
    <fullName>Payer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payer Account</description>
    <label>Payer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Payer Account)</relationshipLabel>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <description>Parent Sales Order</description>
    <inlineHelpText>Parent Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Third_Party_Created__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Created__c</fullName>
    <description>3rd Party Created Date</description>
    <label>3rd Party Created</label>
    <type>DateTime</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/External_Account__c.object-meta.xml
<CustomObject>
    <description>Object to hold external accounts such as Billing and Booking Accounts</description>
    <label>Booking System Account</label>
    <nameField>
        <label>Booking System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking System Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/External_Account__c/fields/Account_No__c.field-meta.xml
<CustomField>
    <fullName>Account_No__c</fullName>
    <description>Used to store the Billing/Booking Account Number</description>
    <inlineHelpText>Used to store the Billing/Booking Account Number</inlineHelpText>
    <label>Account #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Booking/Billing Account Type</description>
    <inlineHelpText>Booking/Billing Account Type</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Established</fullName>
                <default>true</default>
                <label>Established</label>
            </value>
            <value>
                <fullName>Ad Agency</fullName>
            </value>
            <value>
                <fullName>ABN Exempt</fullName>
            </value>
            <value>
                <fullName>Casual Business</fullName>
            </value>
            <value>
                <fullName>Private Party</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Newsagent</fullName>
            </value>
            <value>
                <fullName>Overseas Agent</fullName>
            </value>
            <value>
                <fullName>Non Established</fullName>
            </value>
            <value>
                <fullName>Client of Ad Agency</fullName>
            </value>
            <value>
                <fullName>Sub corporate</fullName>
            </value>
            <value>
                <fullName>Client of Overseas Advertising Agency</fullName>
            </value>
            <value>
                <fullName>Client of Overseas Agent</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Overseas Advertising Agency</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent External Account</description>
    <inlineHelpText>Parent External Account</inlineHelpText>
    <label>Parent Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Booking System Accounts</relationshipLabel>
    <relationshipName>External_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <inlineHelpText>External Id</inlineHelpText>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Payer_Account__c.field-meta.xml
<CustomField>
    <fullName>Payer_Account__c</fullName>
    <description>Default Payer Customer Account. Used by integration.</description>
    <formula>BLANKVALUE( Parent__c ,  Customer_Account__c )</formula>
    <label>Payer Account</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/recordTypes/Billing_Account.recordType-meta.xml
<RecordType>
    <fullName>Billing_Account</fullName>
    <active>true</active>
    <description>Billing Accounts from CyberAd or JDE</description>
    <label>Billing Account</label>
</RecordType>

News UAT/force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Shell Order encompassing Booking(s) - to be related to an Opportunity Product/s</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{0000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Account_No__c.field-meta.xml
<CustomField>
    <fullName>Account_No__c</fullName>
    <formula>External_Account__r.Account_No__c</formula>
    <label>Account #</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Booking_Division__c.field-meta.xml
<CustomField>
    <fullName>Booking_Division__c</fullName>
    <description>Division for Booking, primarily for CyberAd bookings.</description>
    <label>Booking Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADV</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>GAD</fullName>
            </value>
            <value>
                <fullName>GCP</fullName>
            </value>
            <value>
                <fullName>HWT</fullName>
            </value>
            <value>
                <fullName>LDR</fullName>
            </value>
            <value>
                <fullName>NWN</fullName>
            </value>
            <value>
                <fullName>QNP</fullName>
            </value>
            <value>
                <fullName>QST</fullName>
            </value>
            <value>
                <fullName>CNS</fullName>
            </value>
            <value>
                <fullName>NQN</fullName>
            </value>
            <value>
                <fullName>NTN</fullName>
            </value>
            <value>
                <fullName>MNG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Calc_External_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Calc_External_Account_Name__c</fullName>
    <description>Calculated external account name for new billing accounts.</description>
    <formula>IF(NOT(ISBLANK(External_Account__c)) ,  External_Account__r.Name,
if(Advertiser_Account__r.IsPersonAccount, Advertiser_Account__r.FirstName + &#39; &#39; + Advertiser_Account__r.LastName,
Advertiser_Account__r.Name  ))</formula>
    <label>Calc_External_Account_Name</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Calc_External_id__c.field-meta.xml
<CustomField>
    <fullName>Calc_External_id__c</fullName>
    <formula>IF(ISBLANK( External_Id__c ),  Id ,External_Id__c)</formula>
    <label>Calc External id</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Placer Contact</description>
    <label>Placer Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Placer_Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <infoMessage>Should generally be related to the Placer Account.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders (Placer Contact)</relationshipLabel>
    <relationshipName>Sales_Orders_PlacerContact</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Booking/Billing Account</description>
    <inlineHelpText>Select the related Booking or Billing Account</inlineHelpText>
    <label>Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Sales Orders (External Account)</relationshipLabel>
    <relationshipName>Sales_Orders_ExternalAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Payer_Account__c.field-meta.xml
<CustomField>
    <fullName>Payer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payer Account</description>
    <inlineHelpText>Payer – The account that pays for the advertising.</inlineHelpText>
    <label>Payer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders (Payer Account)</relationshipLabel>
    <relationshipName>Sales_Orders_Payer</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Placer_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Placer_Contact_Phone__c</fullName>
    <formula>SUBSTITUTE(Contact__r.Phone, &#39;+&#39;, &#39;&#39;)</formula>
    <label>Placer Contact Phone</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/RESTCyberAdSalesOrder.cls
@RestResource(urlMapping='/CyberAd/salesOrder/*')
global without sharing class RESTCyberAdSalesOrder {


    //Get a SalesOrderDetails based on parameter passed
    @HttpGet
    global static SalesOrderDetails_Helper.SalesOrderDetail doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        SalesOrderDetails_Helper.SalesOrderDetail result = new SalesOrderDetails_Helper.SalesOrderDetail();


        system.debug('### req:' + req);

        //List of URL components
        list<string> params = req.requestURI.split('/');
        //The last item from the paramter list expect a sales_order__c ID
        //optonally a booking__c id separed by a dash '-'
        //booking is passed when oppening an existing booking
        String salesOrderAndBookingID = params[params.size()-1];

        //removes .xml from parameter
        salesOrderAndBookingID = salesOrderAndBookingID.replace('.xml', '');

        string salesOrderID;
        String bookingID;

        //sets variable with the passed ids
        if(salesOrderAndBookingID.indexOf('-')>0)
        {
            salesOrderID = salesOrderAndBookingID.split('-')[0];
            bookingID = salesOrderAndBookingID.split('-')[1];
        }
        else
        {
            salesOrderID = salesOrderAndBookingID;
        }

        System.debug('### params: ' + params);
        System.debug('### salesOrderID: ' + salesOrderID);
        System.debug('### bookingID: ' + bookingID);



        //Gets sales_order__c details
        Sales_Order__c salesOrder = getSalesOrderBySalesOrderID(salesOrderID);
        result.salesOrderSFID   =   salesOrderID;
        result.salesOrderID     =   salesOrder.Calc_External_Id__c;
        result.orderId          =   salesOrder.Calc_External_Id__c;
        result.divisionName     =   salesOrder.Booking_Division__c;
        result.payerAccount     =   salesOrder.Payer_Account__r.Name;
        result.placerContact    =   salesOrder.Contact__r.External_Id__c;
        result.placerFName      =   salesOrder.Contact__r.FirstName;
        result.placerLName      =   salesOrder.Contact__r.LastName;
        result.intgId           =   salesOrder.Calc_External_Id__c;
        result.main             =   salesOrder.Placer_Contact_Phone__c;
        result.localNumber      =   salesOrder.Placer_Contact_Phone__c;
        
        if(!salesOrder.Payer_Account__r.isPersonAccount)
        {
            result.address          =   salesOrder.Payer_Account__r.BillingStreet;
            result.postCode         =   salesOrder.Payer_Account__r.BillingPostalcode;
            result.state            =   salesOrder.Payer_Account__r.BillingState;
            result.country          =   salesOrder.Payer_Account__r.BillingCountry;
            if(salesOrder.Payer_Account__r.BillingCity!=null && salesOrder.Payer_Account__r.BillingCity.trim().length()>0)
                result.city         =   salesOrder.Payer_Account__r.BillingCity.toUpperCase();            
        }
        else
        {
            result.address          =   salesOrder.Payer_Account__r.PersonMailingStreet;
            result.postCode         =   salesOrder.Payer_Account__r.PersonMailingPostalCode;
            result.state            =   salesOrder.Payer_Account__r.PersonMailingState;
            result.country          =   salesOrder.Payer_Account__r.PersonMailingCountry;           
            if(salesOrder.Payer_Account__r.PersonMailingCity!=null && salesOrder.Payer_Account__r.PersonMailingCity.trim().length()>0)
                result.city         =   salesOrder.Payer_Account__r.PersonMailingCity.toUpperCase();            

        }
        //=='Established'?'Established':'Non Established'
        String billingAccountType = 'Non Established';

        if(     salesOrder.External_Account__r != null
            &&  salesOrder.External_Account__r.Account_Type__c != '' 
            &&  salesOrder.External_Account__r.Account_Type__c != 'Casual'
            &&  salesOrder.External_Account__r.Account_Type__c != 'Billing_Account'
            &&  salesOrder.External_Account__r.Account_Type__c != 'Private Party'
            &&  salesOrder.External_Account__r.Account_Type__c != 'Casual Business'
            &&  salesOrder.External_Account__r.Account_Type__c != 'Transient'
            &&  salesOrder.External_Account__r.Account_Type__c !='Non Established')
        {
            billingAccountType = 'Established';
        }            

        result.bAType           =   billingAccountType;
        result.bAName           =   salesOrder.Calc_External_Account_Name__c;
        result.bANumber         =   salesOrder.External_Account__r.Account_No__c;
        result.accountName      =   salesOrder.Calc_External_Account_Name__c;
        result.billingAccountId =   salesOrder.External_Account__r.External_Id__c;
        result.bookingprofile   =   result.bAName; //passing baName as bookingProfile is not being used in salesforce





        result.createdDate      =   formatDate(system.today());

        //if thre request includes a booking id
        if(bookingID!=null)
        {
            result.bookingSFID = bookingID;

            Booking__c booking = getBookingByBookingID(bookingID);
            if(booking.Third_Party_Created__c!=null)
            {
                result.createdDate      =   formatDate(Date.valueOf(booking.Third_Party_Created__c));
            }
            
            
            
            result.adType           =   booking.CyberAd_AdType__c;
            result.bookingId        =   booking.Name;
        }
        else
        {
            result.adType           =   'Billing';
        }



        result.divisionName = salesOrder.Booking_Division__c;//'GAD';
        result.bookingDivision = salesOrder.Booking_Division__c; //'GAD';
        //result.publicationName = 'GAT';

        // added by Tim Fabros 20 / 05 / 2014 - SFE-174 
        // Updated by Bohao Chen 28/05/2014
        // BEGIN: 

        // check if billing account and is a CyberAd
        // check if country is not Australia
        // check if not australian state/territory
        System.debug('@outside if statement: ' + result.country);
        System.debug('@outside if statement: ' + result.state);
        System.debug('@outside if statement: ' + result.postCode);
        System.debug('@outside if source system: ' + salesOrder.Source_System__c);

        String lowerCaseCountry = result.country.toLowerCase();
        String lowerCaseState = result.state.toLowerCase();

        if(salesOrder.Source_System__c == 'CyberAd' && 
            ((lowerCaseCountry != 'australia' && lowerCaseCountry != 'aus' && lowerCaseCountry != 'au') ||
                (lowerCaseState != 'nsw' && lowerCaseState != 'qld' && lowerCaseState != 'vic' && lowerCaseState != 'tas' && 
                    lowerCaseState != 'wa' && lowerCaseState != 'nt' && lowerCaseState != 'act' && lowerCaseState != 'sa'))) 
        {
            
            result.state = 'OTH';
            result.postCode = '9999';
            System.debug('@inside if statement: ' + result.state);
            System.debug('@inside if statement: ' + result.postCode);
        }
        // END:

        System.debug('### result: ' + result);
        return result;
    }



    @HttpPost
    global static string createUpdateSalesOrderDetails()
    {
        RestRequest req = RestContext.request;
        Blob body = req.requestBody;
        system.debug('### req.requestBody:' + req.requestBody);

        String bodySalesOrderDetail = body.toString();
        system.debug('### bodySalesOrderDetail:' + bodySalesOrderDetail);

        //add empty parameters {} if none was sent to CyberAd
        bodySalesOrderDetail = bodySalesOrderDetail.replace(' : \n}',' : {}\n}');

        SalesOrderDetails_Helper.SalesOrderWrapper jsonwrap = new SalesOrderDetails_Helper.SalesOrderWrapper();

        try
        {

            jsonwrap = (SalesOrderDetails_Helper.SalesOrderWrapper) JSON.deserialize(bodySalesOrderDetail, SalesOrderDetails_Helper.SalesOrderWrapper.class);
            system.debug('### jsonwrap:' + jsonwrap);
            jsonwrap.message = 'Post has been deserialized successfully' ;
            system.debug('### jsonwrap.salesOrder:' + jsonwrap.salesOrder);
            SalesOrderDetails_Helper.upsertSalesOrderDertails(jsonwrap);
        }
        catch(Exception ex)
        {
            jsonwrap.message = 'Post could not be deserialized \n' + ex.getMessage();
        }

        System.debug('### jsonwrap: ' + jsonwrap);

        return jsonwrap.message;
    }


    static private Sales_Order__c getSalesOrderBySalesOrderId(String soID)
    {
        system.debug('@ getSalesOrderBySalesOrderId(String soID)');
        Sales_Order__c so;

        try
        {   // added Source_System__c && External_Account__r.RecordTypeId. Addition made by Tim Fabros 20 / 05 / 2014 - SFE-174
            // BEGIN:
             so = [Select   Booking_Division__c,
                            Payer_Account__r.Name,
                            Contact__r.FirstName,
                            Contact__r.LastName,
                            Contact__r.External_Id__c,
                            Calc_External_Id__c,
                            Placer_Contact_Home__c,
                            Payer_Account__r.BillingStreet,
                            Payer_Account__r.BillingCity,
                            Payer_Account__r.BillingPostalcode,
                            Payer_Account__r.BillingState,
                            Payer_Account__r.BillingCountry,
                            Payer_Account__r.isPersonAccount,
                            Payer_Account__r.PersonMailingStreet,
                            Payer_Account__r.PersonMailingPostalCode,
                            Payer_Account__r.PersonMailingState,
                            Payer_Account__r.PersonMailingCountry, 
                            Payer_Account__r.PersonMailingCity,                             
                            External_Account__r.Account_Type__c,
                            Calc_External_Account_Name__c,
                            External_Account__r.Account_No__c,
                            External_Account__r.External_Id__c,
                            External_Account__r.RecordTypeId,
                            Placer_Contact_Phone__c, Source_System__c
                      From Sales_Order__c
                      Where id = :soID];
                      // END:
                      system.debug('### so:' + so);
        }
        catch(Exception ex)
        {
            System.debug('### Sales Orde do not exist in Salesforce with id: ' + soID);
        }
        return so;
    }


    static private Booking__c getBookingByBookingId(String bookingId)
    {
        system.debug('@ getBookingByBookingId(String bookingId)');
        Booking__c bk;
        try
        {
            bk = [Select Third_Party_Created__c,
                         Name,
                         CyberAd_AdType__c,
                         Booking_number__c
                    From Booking__c
                    Where id = :bookingId];
                    
                    
            system.debug('### bk:' + bk);
        }
        catch(Exception ex)
        {
            System.debug('### Booking do not exist in Salesforce with id: ' + bookingId);
        }
        return bk;
    }

    static private string  formatDate(date d)
    {
        string day = string.valueOf(d.day()).length()==2?string.valueOf(d.day()):'0'+d.day();
        string month = string.valueOf(d.month()).length()==2?string.valueOf(d.month()):'0'+d.month();
        return  day + '/' +  month + '/' + d.year();
    }


}