News UAT/force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account Type</description>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency - Full Service</fullName>
            </value>
            <value>
                <fullName>Agency - Media Buyer</fullName>
            </value>
            <value>
                <fullName>Agency – Overseas Advertising Agency</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>State Government</fullName>
            </value>
            <value>
                <fullName>Private Party</fullName>
            </value>
            <value>
                <fullName>Consortium</fullName>
            </value>
            <value>
                <fullName>Agency Independent</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Sole Trader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Billing_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Status__c</fullName>
    <label>Billing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Credit_Status__c.field-meta.xml
<CustomField>
    <fullName>Credit_Status__c</fullName>
    <label>Credit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Mark for Duplication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/External_Account__c.object-meta.xml
<CustomObject>
    <description>Object to hold external accounts such as Billing and Booking Accounts</description>
    <label>Booking System Account</label>
    <nameField>
        <label>Booking System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking System Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/External_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Booking/Billing Account Type</description>
    <inlineHelpText>Booking/Billing Account Type</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Established</fullName>
                <default>true</default>
                <label>Established</label>
            </value>
            <value>
                <fullName>Ad Agency</fullName>
            </value>
            <value>
                <fullName>ABN Exempt</fullName>
            </value>
            <value>
                <fullName>Casual Business</fullName>
            </value>
            <value>
                <fullName>Private Party</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Newsagent</fullName>
            </value>
            <value>
                <fullName>Overseas Agent</fullName>
            </value>
            <value>
                <fullName>Non Established</fullName>
            </value>
            <value>
                <fullName>Client of Ad Agency</fullName>
            </value>
            <value>
                <fullName>Sub corporate</fullName>
            </value>
            <value>
                <fullName>Client of Overseas Advertising Agency</fullName>
            </value>
            <value>
                <fullName>Client of Overseas Agent</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Overseas Advertising Agency</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/BSA__c.field-meta.xml
<CustomField>
    <fullName>BSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For configuring post pay on leapfrog. GBA.</description>
    <label>GBA</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is not a valid GBA.</errorMessage>
        <filterItems>
            <field>External_Account__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Booking Account</value>
        </filterItems>
        <filterItems>
            <field>External_Account__c.Customer_Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Booking System Accounts (BSA)</relationshipLabel>
    <relationshipName>Booking_System_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/BSA_Net_DA__c.field-meta.xml
<CustomField>
    <fullName>BSA_Net_DA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For leapfrog post-pay configuration.</description>
    <label>Net DA</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3) AND 4</booleanFilter>
        <errorMessage>This is not a valid Net DA Account</errorMessage>
        <filterItems>
            <field>External_Account__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Billing Account</value>
        </filterItems>
        <filterItems>
            <field>External_Account__c.Division__c</field>
            <operation>equals</operation>
            <value>National</value>
        </filterItems>
        <filterItems>
            <field>External_Account__c.Division__c</field>
            <operation>equals</operation>
            <value>NOZ</value>
        </filterItems>
        <filterItems>
            <field>External_Account__c.Customer_Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Booking System Accounts (BSA Net DA)</relationshipLabel>
    <relationshipName>BSA_Net_DAs</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Credit_Status__c.field-meta.xml
<CustomField>
    <fullName>Credit_Status__c</fullName>
    <description>External Account Credit Status</description>
    <inlineHelpText>External Account Credit Status</inlineHelpText>
    <label>Credit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 = Green/Go</fullName>
            </value>
            <value>
                <fullName>2 = Review (bookings go to credit but will run regardless)</fullName>
            </value>
            <value>
                <fullName>3 = Risk (bookings can be made but will not run)</fullName>
            </value>
            <value>
                <fullName>4 = High Risk (bookings cannot be made, sales to follow up with NFSS)</fullName>
            </value>
            <value>
                <fullName>5 = Cash (Pre-payment required)</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The External Account&#39;s parent Customer Account</description>
    <inlineHelpText>The External Account&#39;s parent Customer Account</inlineHelpText>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>External_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent External Account</description>
    <inlineHelpText>Parent External Account</inlineHelpText>
    <label>Parent Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Booking System Accounts</relationshipLabel>
    <relationshipName>External_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Parent_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account_Number__c</fullName>
    <description>For Outbound messaging</description>
    <formula>External_Account__r.Account_No__c</formula>
    <label>Parent Account Number</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeName__c</fullName>
    <description>For outbound messaging</description>
    <formula>RecordType.Name</formula>
    <label>RecordTypeName</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>External Account Status</description>
    <inlineHelpText>External Account Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Marked For Deletion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/BookingSystemAccount_Helper.cls
/*
 * @Author: Paul Kang
 * @Description: Booking System Account (External_Account__c) assign the worst Credit Status back the Account.Billing_Status__c
 * sequence of Credit_Status__c colours is:
 * 1. Green
 * 2. Amber
 * 3. Orange
 * 4. Red
 * Where Red is the worst followed by Orange and so forth 
 * History 
 * 2017-12-20: Paul Kang updated 
 * 2018-02-08: Paul Kang fixed an issue when creating a new External_Account__c record from UI related to Credit_Status__c null
 * 2018-09-20: Mohsin Ali - Adding another condition to exclude Contra condition in Query: AND (Account_Type__c != 'Contra'). Refer to Jira: NR-1398
*/ 
public without sharing class BookingSystemAccount_Helper {

    public static void resetNetDA(Map<Id, External_Account__c> externalAccounts, Map<Id, External_Account__c> oldMap) {
        for (External_Account__c extAccount : externalAccounts.values()) {
            if (extAccount.BSA__c != oldMap.get(extAccount.Id).BSA__c && extAccount.BSA_Net_DA__c == oldMap.get(extAccount.Id).BSA_Net_DA__c) {
                //clear netDA
                extAccount.BSA_Net_DA__c = null;
            }
        }
    }


    // Called from BookingSystemAccount.trigger
    public static void assignCreditStatus(List<External_Account__c> bookingSystemAcct) {

        Set<Id> parentAcctIds = new Set<Id>();
        for(External_Account__c ea : bookingSystemAcct)
        {
            if(ea.Customer_Account__c != null)
            parentAcctIds.add(ea.Customer_Account__c);
        }
        System.debug('parentAcctIds:' + parentAcctIds);
        
        //Map<External_Account__c, Integer> extAccMaxCreditStatus = new Map<External_Account__c, Integer>();

        Map<Id, Integer> accountCreditStatus = new Map<Id,Integer>();

        Map<String, Integer> creditStatusMap = new Map<String,Integer>{'green'=>1,'amber'=>2,'orange'=>3,'red'=>4};

        Map<Integer, String> creditStatusInvMap = new Map<Integer,String>{1=>'green',2=>'amber',3=>'orange',4=>'red'};

            // Only compare the credit statuses where External_Account__c 
            // Active, RecordType = Booking Account, has no parent account and is not of type Agency

            for(External_Account__c ea : [SELECT Customer_Account__c, Credit_Status__c 
                                                            FROM External_Account__c
                                                                WHERE Customer_Account__c in :parentAcctIds
                                                                AND RecordTypeName__c = 'Booking Account' 
                                                                AND Status__c = 'Active'
                                                                AND Parent_Account_Number__c = null 
                                                                AND (not Account_Type__c like '%Agency%')
                                         						AND (Account_Type__c != 'Contra')])
            {
                System.debug('ea:' + ea);

                if (ea.Credit_Status__c != null) {
                    
                    if(creditStatusMap.containsKey(ea.Credit_Status__c.toLowerCase()))
                    {
                        Integer crvalue = creditStatusMap.get(ea.Credit_Status__c.toLowerCase());

                        if(!accountCreditStatus.containsKey(ea.Customer_Account__c))
                        { 
                             accountCreditStatus.put(ea.Customer_Account__c, crvalue);   
                        }
                        else if(accountCreditStatus.get(ea.Customer_Account__c) < crvalue)
                        {
                            accountCreditStatus.put(ea.Customer_Account__c, crvalue);
                        }
                    }
                }
                System.debug('ea.Customer_Account__c:' + ea.Customer_Account__c);
                System.debug('ea.Credit_Status__c:' + ea.Credit_Status__c);

            }        

            System.debug('accountCreditStatus:' + accountCreditStatus);

            List<Account> accts = new List<Account>();
            for(id key : accountCreditStatus.keySet())
            {
                accts.add(new Account(id=key, Billing_Status__c=creditStatusInvMap.get(accountCreditStatus.get(key))));
            }

            
            System.debug('accts:' + accts);

            update accts;

    }

}