News UAT/force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account Type</description>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency - Full Service</fullName>
            </value>
            <value>
                <fullName>Agency - Media Buyer</fullName>
            </value>
            <value>
                <fullName>Agency – Overseas Advertising Agency</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>State Government</fullName>
            </value>
            <value>
                <fullName>Private Party</fullName>
            </value>
            <value>
                <fullName>Consortium</fullName>
            </value>
            <value>
                <fullName>Agency Independent</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Sole Trader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Consortium__c.field-meta.xml
<CustomField>
    <fullName>Consortium__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consortium</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>equals</operation>
            <value>Consortium</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>KAC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agency</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Current_FY__c.field-meta.xml
<CustomField>
    <fullName>Current_FY__c</fullName>
    <description>NextGen</description>
    <formula>IF( AND(Upper(RecordType.DeveloperName) = &#39;KAC&#39;, ISPICKVAL(Account_Type__c,&#39;Consortium&#39;)),Consortium_Current_FY__c, ( Current_FY_Digital__c + Current_FY_Print__c + Current_FY_Xtend__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current FY</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/recordTypes/Agency_Account_Type.recordType-meta.xml
<RecordType>
    <fullName>Agency_Account_Type</fullName>
    <active>true</active>
    <description>E.g. Advertising, Media, Creative, PR, and more</description>
    <label>Agency Account</label>
</RecordType>

News UAT/force-app/main/default/objects/Account_Services_Rel__c/Account_Services_Rel__c.object-meta.xml
<CustomObject>
    <description>Account to Account &#39;Junction&#39;  Object for the Serviced By and Services relationship between Customer Accounts</description>
    <label>Account Services Relationship</label>
    <nameField>
        <displayFormat>ASR-{00000}</displayFormat>
        <label>Account Services Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Services Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Account_Services_Rel__c/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <description>The direction is always [A] Services [B]</description>
    <label>Services</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PAYS on behalf of</fullName>
            </value>
            <value>
                <fullName>PLACES on behalf of</fullName>
            </value>
            <value>
                <fullName>is the Creative Agency for</fullName>
            </value>
            <value>
                <fullName>is the Media /Planning Agency</fullName>
                <label>is the Media / Planning Agency</label>
            </value>
            <value>
                <fullName>Provides Full Service (Pay, Place, Planning) for</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account_Services_Rel__c/fields/Source_Account__c.field-meta.xml
<CustomField>
    <fullName>Source_Account__c</fullName>
    <description>The Account doing the Servicing - i.e. the source Account or Agency

E.g. in the relationship &#39;[A] is serviced by [B]&#39;, this is &#39;[A]&#39;</description>
    <inlineHelpText>The Account doing the Servicing - i.e. the source Account or Agency

E.g. in the relationship &#39;[A] is serviced by [B]&#39;, this is &#39;[A]&#39;</inlineHelpText>
    <label>Source Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>notEqual</operation>
            <value>Consortium</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Account_Services_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

News UAT/force-app/main/default/objects/Account_Services_Rel__c/fields/Target_Account__c.field-meta.xml
<CustomField>
    <fullName>Target_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Account being Serviced - i.e. the target Account or Business

E.g. in the relationship &#39;[A] is serviced by [B]&#39;, this is &#39;[B]&#39;</description>
    <inlineHelpText>The Account being Serviced - i.e. the target Account or Business</inlineHelpText>
    <label>Target Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>notEqual</operation>
            <value>Consortium</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Serviced By</relationshipLabel>
    <relationshipName>Account_Services_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/classes/AT_AccountHierarchy.cls
public class AT_AccountHierarchy {
    public class Record {
        @AuraEnabled
        public String name {get; set;}
        @AuraEnabled
        public String label {get; set;}
        @AuraEnabled
        public String href {get; set;}
        
        @AuraEnabled
        public String ownerID {get; set;}
        @AuraEnabled
        public String ownerName {get; set;}
        @AuraEnabled
        public String ownerHREF {get; set;}
        
        @AuraEnabled
        public Boolean expanded {get; private set;}
        
        @AuraEnabled
        public List<String> expandedRows {get; set;}
        
        @AuraEnabled
        public List<Record> items {get; set;}
        
        @AuraEnabled
        public Decimal spend {get; set;}
        
        @AuraEnabled
        public String relationship {get; set;}
        
        public Record(String name) {
            this.name = name;
            this.label = name;
            
            this.href = '#';
            
            this.items = new List<Record>();
            
            this.expandedRows = new List<String>();
            
            this.expanded = true;
        }
        
        public Record(String id, String name) {
            this.name = id;
            this.label = name;
            
            this.href = '/lightning/r/Account/' + id + '/view';
            
            this.items = new List<Record>();
            
            this.expandedRows = new List<String>();
            
            this.expanded = true;
        }
        
        public Record(String id, String name, String ownerID, String ownerName) {
            this.name = id;
            this.label = name;
            
            this.ownerID = ownerID;
            this.ownerName = ownerName;
            
            this.href = '/lightning/r/Account/' + id + '/view';
            
            this.ownerHREF = '/lightning/r/User/' + ownerID + '/view';
            
            this.items = new List<Record>();
            
            this.expandedRows = new List<String>();
            
            this.expanded = true;
        }
    }
    
    public class Hierarchy {
        @AuraEnabled
        public String type {get; set;}
        
        @AuraEnabled
        public String consortiumID {get; set;}
        @AuraEnabled
        public String consortiumName {get; set;}
        
        @AuraEnabled
        public List<Record> records {get; set;}
        
        public Hierarchy() {
            this.records = new List<Record>();
        }
    }
    
	@AuraEnabled
    public static Hierarchy getAccountHierarchy(String recordID) {
        Hierarchy hierarchy = new Hierarchy();
        
        Account acc = [SELECT RecordType.DeveloperName, Account_Type__c, Consortium__c FROM Account WHERE Id = :recordID];
        
        if (acc.Account_Type__c == 'Consortium') {
            hierarchy.type = 'consortium';
        } else if (acc.RecordType.DeveloperName == 'Agency_Account_Type') {
            hierarchy.type = 'agency';
        } else {
            hierarchy.type = 'client';
        }
        
        if (hierarchy.type == 'consortium') {
            List<Record> agencies = new List<Record>();
            
            Map<String, Map<String, List<Record>>> agencyRelationshipClients = new Map<String, Map<String, List<Record>>>();
            
            for (Account ag: [SELECT Id, Name, OwnerId, Owner.Name, Current_FY__c FROM Account WHERE Consortium__c = :recordID ORDER BY Name ASC]) {
                Record agency = new Record(ag.Id, ag.Name, ag.OwnerId, ag.Owner.Name);
                    
                agency.spend = (ag.Current_FY__c != null) ? ag.Current_FY__c : 0;
                
                agencies.add(agency);
            }
            
            for (Account_Services_Rel__c rel: [SELECT Services__c, Source_Account__c, Source_Account__r.Name, Source_Account__r.OwnerId, Source_Account__r.Owner.Name, Source_Account__r.Current_FY__c, Target_Account__c, Target_Account__r.Name, Target_Account__r.Current_FY__c, Target_Account__r.OwnerId, Target_Account__r.Owner.Name FROM Account_Services_Rel__c WHERE (Source_Account__r.Consortium__c = :recordID) ORDER BY Source_Account__r.Name ASC, Services__c, Target_Account__r.Name ASC]) {
                Record client = new Record(rel.Target_Account__c, rel.Target_Account__r.Name, rel.Target_Account__r.OwnerId, rel.Target_Account__r.Owner.Name);
                
                client.spend = (rel.Target_Account__r.Current_FY__c != null) ? rel.Target_Account__r.Current_FY__c : 0;
                
                appendToMap(agencyRelationshipClients, String.valueOf(rel.Source_Account__c), rel.Services__c, client);
            }
            
            for (Record a: agencies) {
                Map<String, List<Record>> relationships = agencyRelationshipClients.get(a.name);
                
                //a.spend = 0;
                
                if (relationships != null) {
                    for (String rel: relationships.keySet()) {
                        Record relationship = new Record(rel);
                        
                        relationship.items = relationships.get(rel);
                        
                        //for (Record r: relationship.items) a.spend += r.spend;
                        
                        a.items.add(relationship);
                        
                        /*Commenting this to collapse the output records. Refer to Jira: NR-1587*/
                        //a.expandedRows.add(rel);
                    }
                }
            }
            
            hierarchy.records = agencies;
        } else if (hierarchy.type == 'agency') {
            Account agency = [SELECT Id, Name, Consortium__c, Consortium__r.Name, Owner.Name FROM Account WHERE Id = :recordID];
            
            hierarchy.consortiumID = agency.Consortium__c;
            hierarchy.consortiumName = agency.Consortium__r.Name;
            
            List<Record> agencies = new List<Record>();
            
            Map<String, Map<String, List<Record>>> agencyRelationshipClients = new Map<String, Map<String, List<Record>>>();
            
            for (Account_Services_Rel__c rel: [SELECT Services__c, Source_Account__c, Source_Account__r.Name, Source_Account__r.OwnerId, Source_Account__r.Owner.Name, Source_Account__r.Current_FY__c, Target_Account__c, Target_Account__r.Name, Target_Account__r.Current_FY__c, Target_Account__r.OwnerId, Target_Account__r.Owner.Name FROM Account_Services_Rel__c WHERE (Source_Account__c = :recordID) ORDER BY Services__c ASC, Target_Account__r.Name ASC]) {
                if (agencyRelationshipClients.get(rel.Source_Account__c) == null) {
                    //agencies.add(new Record(rel.Source_Account__c, rel.Source_Account__r.Name, rel.Source_Account__r.OwnerId, rel.Source_Account__r.Owner.Name));
                    
                    Record ag = new Record(rel.Source_Account__c, rel.Source_Account__r.Name, rel.Source_Account__r.OwnerId, rel.Source_Account__r.Owner.Name);
                    
                    ag.spend = (rel.Source_Account__r.Current_FY__c != null) ? rel.Source_Account__r.Current_FY__c : 0;
                        
                    agencies.add(ag);
                }
            
                Record client = new Record(rel.Target_Account__c, rel.Target_Account__r.Name, rel.Target_Account__r.OwnerId, rel.Target_Account__r.Owner.Name);
                
                client.spend = (rel.Target_Account__r.Current_FY__c != null) ? rel.Target_Account__r.Current_FY__c : 0;
                
                appendToMap(agencyRelationshipClients, String.valueOf(rel.Source_Account__c), rel.Services__c, client);            }
            
            for (Record a: agencies) {
                Map<String, List<Record>> relationships = agencyRelationshipClients.get(a.name);
                
                //a.spend = 0;
                
                if (relationships != null) {
                    for (String rel: relationships.keySet()) {
                        Record relationship = new Record(rel);
                        
                        relationship.items = relationships.get(rel);
                        
                        //for (Record r: relationship.items) a.spend += r.spend;
                        
                        a.items.add(relationship);
                        
                        /*Commenting this to collapse the output records. Refer to Jira: NR-1587*/
                        //a.expandedRows.add(rel);
                    }               }            }
            
            hierarchy.records = agencies;
            
            System.debug(hierarchy.records);
            
            /*List<Record> agencies = new List<Record>();
            
            List<Record> clients = new List<Record>();
            
            Decimal totalSpend = 0;
            
            for (Account_Services_Rel__c rel: [SELECT Services__c, Target_Account__c, Target_Account__r.Name, Target_Account__r.Owner.Name, Target_Account__r.Current_FY__c FROM Account_Services_Rel__c WHERE (Source_Account__c = :recordID) ORDER BY Target_Account__r.Name ASC]) {
                clients.add(new Record(rel.Target_Account__c, rel.Target_Account__r.Name + ' (' + rel.Target_Account__r.Owner.Name + ') (Relationship: ' + rel.Services__c + ')'));
                            
                totalSpend += rel.Target_Account__r.Current_FY__c;
            }
            
            Record agencyRecord = new Record(agency.Id, agency.Name + ' (' + agency.Owner.Name + '), Current FY Spend:  $' + totalSpend);
            agencyRecord.items = clients;
                
            agencies.add(agencyRecord);
            
            hierarchy.records = agencies;*/
        } else if (hierarchy.type == 'client') {
            List<Record> consortiums = new List<Record>();
            
            Map<String, List<Record>> consortiumAgencyMap = new Map<String, List<Record>>();
            
            for (Account_Services_Rel__c rel: [SELECT Source_Account__c, Source_Account__r.Name, Source_Account__r.Owner.Name, Source_Account__r.Consortium__c, Source_Account__r.Consortium__r.Name, Services__c, Source_Account__r.Current_FY__c FROM Account_Services_Rel__c WHERE (Target_Account__c = :recordID) ORDER BY Source_Account__r.Consortium__r.Name ASC, Source_Account__r.Name ASC]) {
                if (consortiumAgencyMap.get(rel.Source_Account__r.Consortium__c) == null) {
                    consortiums.add(new Record(rel.Source_Account__r.Consortium__c, rel.Source_Account__r.Consortium__r.Name));
                }
                
                Record agency = new Record(rel.Source_Account__c, rel.Source_Account__r.Name, rel.Source_Account__r.OwnerId, rel.Source_Account__r.Owner.Name);
                
                agency.relationship = rel.Services__c;
                agency.spend = (rel.Source_Account__r.Current_FY__c != null) ? rel.Source_Account__r.Current_FY__c : 0;
                
                appendToMap(consortiumAgencyMap, rel.Source_Account__r.Consortium__c, agency);
            }
            
            for (Record c: consortiums) {
                List<Record> agencies = consortiumAgencyMap.get(c.name);
                
                if (agencies != null) c.items = agencies;
            }
            
            hierarchy.records = consortiums;
        }
        
        return hierarchy;
    } 
    
    private static void appendToMap(Map<String, List<Record>> listMap, String key, Record value) {
        List<Record> existing = listMap.get(key);
        
        if (existing == null) {
            existing = new List<Record>();
            
            listMap.put(key, existing);
        }
        
        existing.add(value);
    }
    
    private static void appendToMap(Map<String, Map<String, List<Record>>> outerMap, String outerKey, String innerKey, Record value) {
        Map<String, List<Record>> innerMap = outerMap.get(outerKey);
        
        if (innerMap == null) innerMap = new Map<String, List<Record>>();
        
        List<Record> records = innerMap.get(innerKey);
        
        if (records == null) records = new List<Record>();
        
        records.add(value);
        
        innerMap.put(innerKey, records);
        
        outerMap.put(outerKey, innerMap);
    }
}