News UAT/force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account Type</description>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency - Full Service</fullName>
            </value>
            <value>
                <fullName>Agency - Media Buyer</fullName>
            </value>
            <value>
                <fullName>Agency – Overseas Advertising Agency</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>State Government</fullName>
            </value>
            <value>
                <fullName>Private Party</fullName>
            </value>
            <value>
                <fullName>Consortium</fullName>
            </value>
            <value>
                <fullName>Agency Independent</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Sole Trader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Billing_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Status__c</fullName>
    <label>Billing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Credit_Status__c.field-meta.xml
<CustomField>
    <fullName>Credit_Status__c</fullName>
    <label>Credit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/No_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>No_Parent_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to override the Parent Account required field</inlineHelpText>
    <label>No Parent Account</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/External_Account__c.object-meta.xml
<CustomObject>
    <description>Object to hold external accounts such as Billing and Booking Accounts</description>
    <label>Booking System Account</label>
    <nameField>
        <label>Booking System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking System Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/External_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Booking/Billing Account Type</description>
    <inlineHelpText>Booking/Billing Account Type</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Established</fullName>
                <default>true</default>
                <label>Established</label>
            </value>
            <value>
                <fullName>Ad Agency</fullName>
            </value>
            <value>
                <fullName>ABN Exempt</fullName>
            </value>
            <value>
                <fullName>Casual Business</fullName>
            </value>
            <value>
                <fullName>Private Party</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Newsagent</fullName>
            </value>
            <value>
                <fullName>Overseas Agent</fullName>
            </value>
            <value>
                <fullName>Non Established</fullName>
            </value>
            <value>
                <fullName>Client of Ad Agency</fullName>
            </value>
            <value>
                <fullName>Sub corporate</fullName>
            </value>
            <value>
                <fullName>Client of Overseas Advertising Agency</fullName>
            </value>
            <value>
                <fullName>Client of Overseas Agent</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Overseas Advertising Agency</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Credit_Status__c.field-meta.xml
<CustomField>
    <fullName>Credit_Status__c</fullName>
    <description>External Account Credit Status</description>
    <inlineHelpText>External Account Credit Status</inlineHelpText>
    <label>Credit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 = Green/Go</fullName>
            </value>
            <value>
                <fullName>2 = Review (bookings go to credit but will run regardless)</fullName>
            </value>
            <value>
                <fullName>3 = Risk (bookings can be made but will not run)</fullName>
            </value>
            <value>
                <fullName>4 = High Risk (bookings cannot be made, sales to follow up with NFSS)</fullName>
            </value>
            <value>
                <fullName>5 = Cash (Pre-payment required)</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The External Account&#39;s parent Customer Account</description>
    <inlineHelpText>The External Account&#39;s parent Customer Account</inlineHelpText>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>External_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent External Account</description>
    <inlineHelpText>Parent External Account</inlineHelpText>
    <label>Parent Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Booking System Accounts</relationshipLabel>
    <relationshipName>External_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <inlineHelpText>External Id</inlineHelpText>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/classes/BookingSystemAccount_HelperTest.cls
/*
* Author: Paul Kang
* Test to Rollup the worst colour from the Account's External_Account__c Credit_Status__c
*/

@isTest
private class BookingSystemAccount_HelperTest {

	public static Integer accounts = 10;
	public static Integer bookingAccounts = 10;
	

	@testSetup static void setup() {

		// Ignore the deduplication rules and save the records anyway
		Database.DMLOptions dml = new Database.DMLOptions(); 
		dml.DuplicateRuleHeader.allowSave = true;

        // Create common test accounts
        List<Account> testAccts = new List<Account>();
        for(Integer i=0;i < accounts;i++) {
            Account newAcct = new Account(Name = 'TestAcct'+ string.valueof(i) );
            newAcct.No_Parent_Account__c = true;
            testAccts.add(newAcct);
        }

  		List<Database.SaveResult> sr = Database.insert(testAccts, dml);   

  		System.debug('@save result ' + sr);

        	  // Create Booking System Accounts
		List<External_Account__c> testBSAs = new List<External_Account__c>();
        
        for (Account acct : testAccts) {

	        for(Integer i=0; i < bookingAccounts; i++) {
	        	External_Account__c newBSA = new External_Account__c();

	        	System.debug('@acct.id ' + acct.Id);
	        	newBSA.Customer_Account__c = acct.Id;

	        	if (math.mod(i, 2) == 0) {
	        		newBSA.Credit_Status__c = 'Amber';
	        	} else {
	        		newBSA.Credit_Status__c = 'Orange';
	        	}

	        	newBSA.External_Id__c = 'GBA_T' + acct.Id + String.valueof(i);

	        	testBSAs.add(newBSA);
	        }
    	}

    	List<Database.SaveResult> result = Database.Insert(testBSAs, dml);    
		System.debug('@save result BSAs' + result);

    }


    /*
    * Initial setup, the worst Credit_Status__c colour is Orange, this will check if the additional External_Account__c 'Red' will 
    * override the Account.Billing_Status__c as the worst colour    
    * 
    */
	@isTest static void test_assignCreditStatus() {

			System.debug('@BookingSystemAccount_HelperTest.test_assignCreditStatus START');

			Account acct = [Select Id, Billing_Status__c from Account Limit 1];


			Test.startTest();
			External_Account__c ext = new External_Account__c(External_Id__c = 'GBA_T234234', 
											Customer_Account__c=acct.Id, 
											Credit_Status__c = 'Red',
											Account_Type__c = 'Established');
			insert ext;

			

			BookingSystemAccount_Helper.assignCreditStatus(new External_Account__c[]{ext});
			Test.stopTest();

			acct = [Select Id, Billing_Status__c from Account Limit 1];
			System.assertEquals('Red', acct.Billing_Status__c);


       
	}

	
}