News UAT/force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account Type</description>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency - Full Service</fullName>
            </value>
            <value>
                <fullName>Agency - Media Buyer</fullName>
            </value>
            <value>
                <fullName>Agency – Overseas Advertising Agency</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>State Government</fullName>
            </value>
            <value>
                <fullName>Private Party</fullName>
            </value>
            <value>
                <fullName>Consortium</fullName>
            </value>
            <value>
                <fullName>Agency Independent</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Sole Trader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/DPID_Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>DPID_Primary_Address__c</fullName>
    <label>DPID - Primary Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/No_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>No_Parent_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to override the Parent Account required field</inlineHelpText>
    <label>No Parent Account</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Revenue_Group__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Group__c</fullName>
    <inlineHelpText>Revenue Groups are based on the News Corp categorisations that are defined for budget and forecasting reporting. This field will feed into Opportunity and Booking information.</inlineHelpText>
    <label>Revenue Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amusements</fullName>
            </value>
            <value>
                <fullName>Employment</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle Dealers</fullName>
            </value>
            <value>
                <fullName>National (Communications/business equipment)</fullName>
            </value>
            <value>
                <fullName>National (Computers)</fullName>
            </value>
            <value>
                <fullName>National (Finance)</fullName>
            </value>
            <value>
                <fullName>National (Food and beverages)</fullName>
            </value>
            <value>
                <fullName>National (Gambling/gaming)</fullName>
            </value>
            <value>
                <fullName>National (Government/political)</fullName>
            </value>
            <value>
                <fullName>National (Media)</fullName>
            </value>
            <value>
                <fullName>National (Motor Vehicle Manufacturers)</fullName>
            </value>
            <value>
                <fullName>National (Other)</fullName>
            </value>
            <value>
                <fullName>National (Personal care products)</fullName>
            </value>
            <value>
                <fullName>National (Pharmaceutical / Health Products)</fullName>
            </value>
            <value>
                <fullName>National (Travel)</fullName>
            </value>
            <value>
                <fullName>Public Notices</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/External_Account__c.object-meta.xml
<CustomObject>
    <description>Object to hold external accounts such as Billing and Booking Accounts</description>
    <label>Booking System Account</label>
    <nameField>
        <label>Booking System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking System Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/External_Account__c/fields/ABN_Number__c.field-meta.xml
<CustomField>
    <fullName>ABN_Number__c</fullName>
    <description>ABN Number</description>
    <inlineHelpText>ABN Number</inlineHelpText>
    <label>ABN Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Booking/Billing Account Type</description>
    <inlineHelpText>Booking/Billing Account Type</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Established</fullName>
                <default>true</default>
                <label>Established</label>
            </value>
            <value>
                <fullName>Ad Agency</fullName>
            </value>
            <value>
                <fullName>ABN Exempt</fullName>
            </value>
            <value>
                <fullName>Casual Business</fullName>
            </value>
            <value>
                <fullName>Private Party</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Newsagent</fullName>
            </value>
            <value>
                <fullName>Overseas Agent</fullName>
            </value>
            <value>
                <fullName>Non Established</fullName>
            </value>
            <value>
                <fullName>Client of Ad Agency</fullName>
            </value>
            <value>
                <fullName>Sub corporate</fullName>
            </value>
            <value>
                <fullName>Client of Overseas Advertising Agency</fullName>
            </value>
            <value>
                <fullName>Client of Overseas Agent</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Overseas Advertising Agency</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>External Account Address Country</description>
    <inlineHelpText>External Account Address Country</inlineHelpText>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The External Account&#39;s parent Customer Account</description>
    <inlineHelpText>The External Account&#39;s parent Customer Account</inlineHelpText>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>External_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Default_Revenue_Group__c.field-meta.xml
<CustomField>
    <fullName>Default_Revenue_Group__c</fullName>
    <description>Booking Account Default Revenue Group</description>
    <inlineHelpText>Booking Account Default Revenue Group</inlineHelpText>
    <label>Default Revenue Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amusements</fullName>
            </value>
            <value>
                <fullName>Election-Political</fullName>
            </value>
            <value>
                <fullName>Employment</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>MV Dealers</fullName>
            </value>
            <value>
                <fullName>Nat - Com/Bus Equip</fullName>
            </value>
            <value>
                <fullName>Nat - Computers</fullName>
            </value>
            <value>
                <fullName>Nat - Finance</fullName>
            </value>
            <value>
                <fullName>Nat - Food &amp; Bev</fullName>
            </value>
            <value>
                <fullName>Nat - Gamb/Gaming</fullName>
            </value>
            <value>
                <fullName>Nat - Gov/Pol Part</fullName>
            </value>
            <value>
                <fullName>Nat - Media</fullName>
            </value>
            <value>
                <fullName>Nat - MV Manufact</fullName>
            </value>
            <value>
                <fullName>Nat - Other</fullName>
            </value>
            <value>
                <fullName>Nat - Pers Care Prod</fullName>
            </value>
            <value>
                <fullName>Nat - Pharm/Hth Prod</fullName>
            </value>
            <value>
                <fullName>Nat - Travel/Accom</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/DPID__c.field-meta.xml
<CustomField>
    <fullName>DPID__c</fullName>
    <description>External Account Address DPID</description>
    <inlineHelpText>External Account Address DPID</inlineHelpText>
    <label>DPID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>External Account Email Address</description>
    <inlineHelpText>The Email Address for this GBA</inlineHelpText>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Email_Confirmation_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Confirmation_Address__c</fullName>
    <description>External Account Email Confirmation Address</description>
    <inlineHelpText>External Account Email Confirmation Address</inlineHelpText>
    <label>Email Confirmation Address</label>
    <type>Email</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent External Account</description>
    <inlineHelpText>Parent External Account</inlineHelpText>
    <label>Parent Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Booking System Accounts</relationshipLabel>
    <relationshipName>External_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Booking Contact&#39;s First Name</description>
    <inlineHelpText>Booking Contact&#39;s First Name</inlineHelpText>
    <label>First Name</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/GBA_Phone__c.field-meta.xml
<CustomField>
    <fullName>GBA_Phone__c</fullName>
    <label>GBA Phone</label>
    <type>Phone</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/GBA_Phone_Area_Code__c.field-meta.xml
<CustomField>
    <fullName>GBA_Phone_Area_Code__c</fullName>
    <label>GBA Phone Area Code</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/GBA_Phone_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>GBA_Phone_Country_Code__c</fullName>
    <label>GBA Phone Country Code</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Booking Contact&#39;s Last Name</description>
    <inlineHelpText>Booking Contact&#39;s Last Name</inlineHelpText>
    <label>Last Name</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Post_Code__c.field-meta.xml
<CustomField>
    <fullName>Post_Code__c</fullName>
    <description>External Account Address Post Code</description>
    <inlineHelpText>External Account Address Post Code</inlineHelpText>
    <label>Post Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>External Account Address State</description>
    <inlineHelpText>External Account Address State</inlineHelpText>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Street Address field for External Account</description>
    <inlineHelpText>Street Address field for External Account</inlineHelpText>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Suburb__c.field-meta.xml
<CustomField>
    <fullName>Suburb__c</fullName>
    <description>External Account Address Suburb</description>
    <inlineHelpText>External Account Address Suburb</inlineHelpText>
    <label>Suburb</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Booking Title</description>
    <inlineHelpText>Booking Contact&#39;s Title</inlineHelpText>
    <label>Title</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/ExternalAccountForm_Controller_Test.cls
/*---------------------------------------------------------
 * Author: Bluewolf
 * Company: Salesforce.com
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 * 2015-12-16  Atul Gupta Updated
 // 2015-12-16 atul.gupta@bluewolfgroup.com
    // This class provides test coverage for
    //  - ExternalAccountForm_Controller 84%
 */
@isTest
private class ExternalAccountForm_Controller_Test {

	static testMethod void isAgencyFalse_NON_AdminUser() {
			
			list<Account> accountList = TestDataFactory.createAccounts(1,false);
			insert accountList;
			
			External_Account__c extAcct = TestDataFactory.createExternalAccount();

			Account acctAdvertiser = accountList[0];
			Account acctPayer = [select id, 
										Name,
										BillingPostalCode,
										BillingCountry,
										BillingState,
										BillingCity,
										BillingStreet,
										DPID_Primary_Address__c,
										AccountNumber,
										Phone,
										No_Parent_Account__c		
									from Account
									Where id=:extAcct.Customer_Account__c];
			
	        ExternalAccountForm_Controller eaf = new ExternalAccountForm_Controller();
	        eaf.isAgency = false;
	        eaf.selectedAdvertiser = acctAdvertiser;
	        eaf.selectedPayer = acctPayer;
			eaf.phoneCountryCode = '43214';
			eaf.phoneAreaCode = '123';
			eaf.phone = '9876543212';

	        //TestDataFactory.createdCyberAdUserCredentials(UserInfo.getUserId());
	        //TestDataFactory.createdCyberAdUserCredentialOne(UserInfo.getUserId());	
			TestDataFactory.createCustomSettingGeneraAccountTypeMapping();
			TestDataFactory.createCustomSettingGeneraRevenueGroups();

			User userTest = TestDataFactory.createUser('News IT Administration', 'testUser101', 'lastName101', null, true, true);
			insert userTest;

			System.runAs(userTest){
				
				TestDataFactory.createdCyberAdUserCredentialOne(userTest.id);//UserInfo.getUserId());
				
				map<String, Genera_Account_Type_Mapping__c> availableGBATypeMap = eaf.availableGBATypeMap;
				list<selectOption> gbaAccountTypeOptionsForSelectAdvertiser = eaf.gbaAccountTypeOptionsForSelectAdvertiser;
			}
			
	}

	static testMethod void isAgencyFalseTest() {
			
			list<Account> accountList = TestDataFactory.createAccounts(1,false);
			insert accountList;
			
			External_Account__c extAcct = TestDataFactory.createExternalAccount();

			Account acctAdvertiser = accountList[0];
			Account acctPayer = [select id, 
										Name,
										BillingPostalCode,
										BillingCountry,
										BillingState,
										BillingCity,
										BillingStreet,
										DPID_Primary_Address__c,
										AccountNumber,
										Phone,
										No_Parent_Account__c		
									from Account
									Where id=:extAcct.Customer_Account__c];
			
	        ExternalAccountForm_Controller eaf = new ExternalAccountForm_Controller();
	        eaf.isAgency = false;
	        eaf.selectedAdvertiser = acctAdvertiser;
	        eaf.selectedPayer = acctPayer;
			eaf.phoneCountryCode = '43214';
			eaf.phoneAreaCode = '123';
			eaf.phone = '9876543212';

	        TestDataFactory.createdCyberAdUserCredentials(UserInfo.getUserId());	
			TestDataFactory.createCustomSettingGeneraAccountTypeMapping();	
			map<String, Genera_Account_Type_Mapping__c> availableGBATypeMap = eaf.availableGBATypeMap;
	}

    static testMethod void indirectTest() { 
			
			list<Account> accountList = TestDataFactory.createAccounts(1,false);
			insert accountList;
			
			External_Account__c extAcct = TestDataFactory.createExternalAccount();
			//External_Account__c extAcct1 = TestDataFactory.createExternalAccount();

			Account acctAdvertiser = accountList[0];
			Account acctPayer = [select id, 
										Name,
										BillingPostalCode,
										BillingCountry,
										BillingState,
										BillingCity,
										BillingStreet,
										DPID_Primary_Address__c,
										AccountNumber,
										Phone,
										No_Parent_Account__c		
									from Account
									Where id=:extAcct.Customer_Account__c];
			
	        ExternalAccountForm_Controller eaf = new ExternalAccountForm_Controller();
	        eaf.isAgency = true;
	        eaf.selectedAdvertiser = acctAdvertiser;
	        eaf.selectedPayer = acctPayer;
			eaf.phoneCountryCode = '43214';
			eaf.phoneAreaCode = '123';
			eaf.phone = '9876543212';

	        TestDataFactory.createdCyberAdUserCredentials(UserInfo.getUserId());	
			TestDataFactory.createCustomSettingGeneraAccountTypeMapping();	
			map<String, Genera_Account_Type_Mapping__c> availableGBATypeMap = eaf.availableGBATypeMap;
	        list<selectOption> gbaAccountTypeOptionsForSelectAdvertiser = eaf.gbaAccountTypeOptionsForSelectAdvertiser;
			list<selectOption> gbadefaultRevenueGroupGeneraOptions = eaf.gbadefaultRevenueGroupGeneraOptions;
			list<selectOption> gbaDivisionOptions = eaf.gbaDivisionOptions;
			list<SelectOption> ParentBookingAccounts = eaf.getParentBookingAccounts();
	
			eaf.init();
			eaf.redirectToPage = false;
			system.debug('@@eaf.gbaAccount :'+ eaf.gbaAccount);
			eaf.gbaAccount.External_Account__c = extAcct.id;
			eaf.gbaAccount.GBA_Phone_Area_Code__c = 1;
			eaf.gbaAccount.Default_Revenue_Group__c = 'Amusements';
			eaf.gbaAccount.Email_Confirmation_Address__c = 'test@sfdc.com';
			eaf.onParentAccountSelection();
	
	
			eaf.gbaAccount.Account_Type__c = 'Client of Ad Agency';
			eaf.onAccountTypeSelection();
	
			PageReference pr = eaf.saveNewGBAAndRedirect();

    }
    
    static testMethod void directTest() {
			
			list<Account> accountList = TestDataFactory.createAccounts(1,false);
			insert accountList;

			External_Account__c extAcct = TestDataFactory.createExternalAccount();
			
			Account acctPayer = [select id, 
										Name,
										BillingPostalCode,
										BillingCountry,
										BillingState,
										BillingCity,
										BillingStreet,
										DPID_Primary_Address__c,
										AccountNumber,
										Phone,
										No_Parent_Account__c,
										Revenue_Group__c
									from Account
									Where id=:extAcct.Customer_Account__c];
			
			Account acctAdvertiser = acctPayer;	
			
	        ExternalAccountForm_Controller eaf = new ExternalAccountForm_Controller();
	        eaf.isAgency = true;
	        eaf.selectedAdvertiser = acctAdvertiser;
	        eaf.selectedPayer = accountList[0];
	
			eaf.init();

	        eaf.selectedPayer = acctPayer;
	        TestDataFactory.createdCyberAdUserCredentials(UserInfo.getUserId());
			TestDataFactory.createCustomSettingGeneraAccountTypeMapping();

			map<String, Genera_Account_Type_Mapping__c> availableGBATypeMap = eaf.availableGBATypeMap;
	        list<selectOption> gbaAccountTypeOptionsForSelectAdvertiser = eaf.gbaAccountTypeOptionsForSelectAdvertiser;
			list<selectOption> gbadefaultRevenueGroupGeneraOptions = eaf.gbadefaultRevenueGroupGeneraOptions;
			list<selectOption> gbaDivisionOptions = eaf.gbaDivisionOptions;
			list<SelectOption> ParentBookingAccounts = eaf.getParentBookingAccounts();
			
			eaf.init();
			
			eaf.redirectToPage = true;
			
			eaf.gbaAccount.External_Account__c = extAcct.id;
			eaf.onParentAccountSelection();
	
			eaf.gbaAccount.Account_Type__c = 'Ad Agency';
			eaf.onAccountTypeSelection();
	
			PageReference pr = eaf.saveNewGBAAndRedirect();

			eaf.cancelNewGBA();

    }
    
    //test for validation account type needs parent account
    static testMethod void testParentAccountValidation() {
			
			list<Account> accountList = TestDataFactory.createAccounts(1,false);
			insert accountList;

			External_Account__c extAcct = TestDataFactory.createExternalAccount();
			
			Account acctPayer = [select id, 
										Name,
										BillingPostalCode,
										BillingCountry,
										BillingState,
										BillingCity,
										BillingStreet,
										DPID_Primary_Address__c,
										AccountNumber,
										Phone,
										No_Parent_Account__c,
										Revenue_Group__c,
										IsPersonAccount
									from Account
									Where id=:extAcct.Customer_Account__c];
			
			Account acctAdvertiser = acctPayer;	
			
			//ExternalAccountCreateBookingAccount
			PageReference pageRef = Page.ExternalAccountCreateBookingAccount;
			Test.setCurrentPage(pageRef);
			
	        ExternalAccountForm_Controller eaf = new ExternalAccountForm_Controller();
			//atul
	        eaf.isAgency = false;
	        eaf.selectedAdvertiser = acctAdvertiser;
	        eaf.selectedPayer = accountList[0];
	
			eaf.init();

	        eaf.selectedPayer = acctPayer;
	        TestDataFactory.createdCyberAdUserCredentials(UserInfo.getUserId());
			TestDataFactory.createCustomSettingGeneraAccountTypeMapping();

			map<String, Genera_Account_Type_Mapping__c> availableGBATypeMap = eaf.availableGBATypeMap;
	        list<selectOption> gbaAccountTypeOptionsForSelectAdvertiser = eaf.gbaAccountTypeOptionsForSelectAdvertiser;
			list<selectOption> gbadefaultRevenueGroupGeneraOptions = eaf.gbadefaultRevenueGroupGeneraOptions;
			list<selectOption> gbaDivisionOptions = eaf.gbaDivisionOptions;
			list<SelectOption> ParentBookingAccounts = eaf.getParentBookingAccounts();

			eaf.redirectToPage = true;
			
			eaf.onParentAccountSelection();
	
			eaf.gbaAccount.Account_Type__c = 'Client of Ad Agency';
			
			eaf.onAccountTypeSelection();
	
			PageReference pr = eaf.saveNewGBAAndRedirect();
			List<Apexpages.Message> msgs = ApexPages.getMessages();
			system.assertEquals(msgs[0].getDetail().contains('Account Type Client of Ad Agency needs parent account'), true);

    }
    
    //test for validation account type needs parent account
    static testMethod void testPhoneNumberValidation() {
			
			list<Account> accountList = TestDataFactory.createAccounts(1,false);
			insert accountList;

			External_Account__c extAcct = TestDataFactory.createExternalAccount();
			
			Account acctPayer = [select id, 
										Name,
										BillingPostalCode,
										BillingCountry,
										BillingState,
										BillingCity,
										BillingStreet,
										DPID_Primary_Address__c,
										AccountNumber,
										Phone,
										No_Parent_Account__c,
										Revenue_Group__c,
										IsPersonAccount
									from Account
									Where id=:extAcct.Customer_Account__c];
			
			Account acctAdvertiser = acctPayer;	
			
			PageReference pageRef = Page.ExternalAccountCreateBookingAccount;
			Test.setCurrentPage(pageRef);
			
	        ExternalAccountForm_Controller eaf = new ExternalAccountForm_Controller();
			
	        eaf.isAgency = false;
	        eaf.selectedAdvertiser = acctAdvertiser;
	        eaf.selectedPayer = accountList[0];
	
			eaf.init();

	        eaf.selectedPayer = acctPayer;
	        TestDataFactory.createdCyberAdUserCredentials(UserInfo.getUserId());
			TestDataFactory.createCustomSettingGeneraAccountTypeMapping();

			map<String, Genera_Account_Type_Mapping__c> availableGBATypeMap = eaf.availableGBATypeMap;
	        list<selectOption> gbaAccountTypeOptionsForSelectAdvertiser = eaf.gbaAccountTypeOptionsForSelectAdvertiser;
			list<selectOption> gbadefaultRevenueGroupGeneraOptions = eaf.gbadefaultRevenueGroupGeneraOptions;
			list<selectOption> gbaDivisionOptions = eaf.gbaDivisionOptions;
			list<SelectOption> ParentBookingAccounts = eaf.getParentBookingAccounts();

			eaf.redirectToPage = true;
			eaf.gbaAccount.External_Account__c = extAcct.id;
			eaf.onParentAccountSelection();
			eaf.gbaAccount.Account_Type__c = 'Client of Ad Agency';
			eaf.gbaAccount.GBA_Phone__c = '9876543212345';
			
			
			PageReference prNew = eaf.saveNewGBAAndRedirect();
			List<Apexpages.Message> msgs1 = ApexPages.getMessages();
			system.assertEquals(msgs1[0].getDetail().contains('Phone number is too long'), true);
    }
    
    //test for validation account type needs parent account
    static testMethod void testAccountTypeRequiredValidation() {
			
			list<Account> accountList = TestDataFactory.createAccounts(1,false);
			insert accountList;

			External_Account__c extAcct = TestDataFactory.createExternalAccount();
			
			Account acctPayer = [select id, 
										Name,
										BillingPostalCode,
										BillingCountry,
										BillingState,
										BillingCity,
										BillingStreet,
										DPID_Primary_Address__c,
										AccountNumber,
										Phone,
										No_Parent_Account__c,
										Revenue_Group__c,
										IsPersonAccount
									from Account
									Where id=:extAcct.Customer_Account__c];
			
			Account acctAdvertiser = acctPayer;	
			
			PageReference pageRef = Page.ExternalAccountCreateBookingAccount;
			Test.setCurrentPage(pageRef);
			
	        ExternalAccountForm_Controller eaf = new ExternalAccountForm_Controller();
			
	        eaf.isAgency = false;
	        eaf.selectedAdvertiser = acctAdvertiser;
	        eaf.selectedPayer = accountList[0];
	
			eaf.init();

	        eaf.selectedPayer = acctPayer;
	        TestDataFactory.createdCyberAdUserCredentials(UserInfo.getUserId());
			TestDataFactory.createCustomSettingGeneraAccountTypeMapping();

			map<String, Genera_Account_Type_Mapping__c> availableGBATypeMap = eaf.availableGBATypeMap;
	        list<selectOption> gbaAccountTypeOptionsForSelectAdvertiser = eaf.gbaAccountTypeOptionsForSelectAdvertiser;
			list<selectOption> gbadefaultRevenueGroupGeneraOptions = eaf.gbadefaultRevenueGroupGeneraOptions;
			list<selectOption> gbaDivisionOptions = eaf.gbaDivisionOptions;
			list<SelectOption> ParentBookingAccounts = eaf.getParentBookingAccounts();

			eaf.redirectToPage = true;
			eaf.gbaAccount.External_Account__c = extAcct.id;
			eaf.onParentAccountSelection();
			eaf.gbaAccount.Account_Type__c = null;
			eaf.gbaAccount.GBA_Phone__c = '8765432123';
			
			PageReference pr = eaf.saveNewGBAAndRedirect();
			List<Apexpages.Message> msgs = ApexPages.getMessages();
			system.assertEquals(msgs[0].getDetail().contains('Account Type is required'), true);
			
    }
    
    
    //test for gbaaccount special characters in suburb field
    static testMethod void testSpecialChar_Suburb_Validation() {
			
			list<Account> accountList = TestDataFactory.createAccounts(1,false);
			insert accountList;

			External_Account__c extAcct = TestDataFactory.createExternalAccount();
			
			Account acctPayer = [select id, 
										Name,
										BillingPostalCode,
										BillingCountry,
										BillingState,
										BillingCity,
										BillingStreet,
										DPID_Primary_Address__c,
										AccountNumber,
										Phone,
										No_Parent_Account__c,
										Revenue_Group__c,
										IsPersonAccount
									from Account
									Where id=:extAcct.Customer_Account__c];
			
			Account acctAdvertiser = acctPayer;	
			
			PageReference pageRef = Page.ExternalAccountCreateBookingAccount;
			Test.setCurrentPage(pageRef);
			
	        ExternalAccountForm_Controller eaf = new ExternalAccountForm_Controller();
			
	        eaf.isAgency = false;
	        eaf.selectedAdvertiser = acctAdvertiser;
	        eaf.selectedPayer = accountList[0];
	
			eaf.init();

	        eaf.selectedPayer = acctPayer;
	        TestDataFactory.createdCyberAdUserCredentials(UserInfo.getUserId());
			TestDataFactory.createCustomSettingGeneraAccountTypeMapping();

			map<String, Genera_Account_Type_Mapping__c> availableGBATypeMap = eaf.availableGBATypeMap;
	        list<selectOption> gbaAccountTypeOptionsForSelectAdvertiser = eaf.gbaAccountTypeOptionsForSelectAdvertiser;
			list<selectOption> gbadefaultRevenueGroupGeneraOptions = eaf.gbadefaultRevenueGroupGeneraOptions;
			list<selectOption> gbaDivisionOptions = eaf.gbaDivisionOptions;
			list<SelectOption> ParentBookingAccounts = eaf.getParentBookingAccounts();

			eaf.redirectToPage = true;
			
			eaf.gbaAccount.External_Account__c = extAcct.id;
			eaf.onParentAccountSelection();
	
			eaf.gbaAccount.Account_Type__c = 'Client of Ad Agency';
			
			eaf.onAccountTypeSelection();
			
			eaf.gbaAccount.Suburb__c = 'abc%12';
			try{
				PageReference pr = eaf.saveNewGBAAndRedirect();
			}catch(Exception ex){
				system.assertEquals(ex.getMessage().contains('Please remove special characters from Suburb field'), true);
			}
    }
    
    //test for gbaaccount special characters in Name field
    static testMethod void testSpecialChar_Name_Validation() {
			
			list<Account> accountList = TestDataFactory.createAccounts(1,false);
			insert accountList;

			External_Account__c extAcct = TestDataFactory.createExternalAccount();
			
			Account acctPayer = [select id, 
										Name,
										BillingPostalCode,
										BillingCountry,
										BillingState,
										BillingCity,
										BillingStreet,
										DPID_Primary_Address__c,
										AccountNumber,
										Phone,
										No_Parent_Account__c,
										Revenue_Group__c,
										IsPersonAccount
									from Account
									Where id=:extAcct.Customer_Account__c];
			
			Account acctAdvertiser = acctPayer;	
			
			PageReference pageRef = Page.ExternalAccountCreateBookingAccount;
			Test.setCurrentPage(pageRef);
			
	        ExternalAccountForm_Controller eaf = new ExternalAccountForm_Controller();
			
	        eaf.isAgency = false;
	        eaf.selectedAdvertiser = acctAdvertiser;
	        eaf.selectedPayer = accountList[0];
	
			eaf.init();

	        eaf.selectedPayer = acctPayer;
	        TestDataFactory.createdCyberAdUserCredentials(UserInfo.getUserId());
			TestDataFactory.createCustomSettingGeneraAccountTypeMapping();

			map<String, Genera_Account_Type_Mapping__c> availableGBATypeMap = eaf.availableGBATypeMap;
	        list<selectOption> gbaAccountTypeOptionsForSelectAdvertiser = eaf.gbaAccountTypeOptionsForSelectAdvertiser;
			list<selectOption> gbadefaultRevenueGroupGeneraOptions = eaf.gbadefaultRevenueGroupGeneraOptions;
			list<selectOption> gbaDivisionOptions = eaf.gbaDivisionOptions;
			list<SelectOption> ParentBookingAccounts = eaf.getParentBookingAccounts();

			eaf.redirectToPage = true;
			
			eaf.gbaAccount.External_Account__c = extAcct.id;
			eaf.onParentAccountSelection();
	
			eaf.gbaAccount.Account_Type__c = 'Client of Ad Agency';
			
			eaf.onAccountTypeSelection();
			
			eaf.gbaAccount.Name = 'abc%12';
			eaf.gbaAccount.Suburb__c = 'test';
			try{
				PageReference pr1 = eaf.saveNewGBAAndRedirect();
			}catch(Exception ex){
				system.assertEquals(ex.getMessage().contains('Please remove special characters from Name field'), true);
			}
    }
    
    //test for gbaaccount special characters in Street field
    static testMethod void testSpecialChar_Street_Validation() {
			
			list<Account> accountList = TestDataFactory.createAccounts(1,false);
			insert accountList;

			External_Account__c extAcct = TestDataFactory.createExternalAccount();
			
			Account acctPayer = [select id, 
										Name,
										BillingPostalCode,
										BillingCountry,
										BillingState,
										BillingCity,
										BillingStreet,
										DPID_Primary_Address__c,
										AccountNumber,
										Phone,
										No_Parent_Account__c,
										Revenue_Group__c,
										IsPersonAccount
									from Account
									Where id=:extAcct.Customer_Account__c];
			
			Account acctAdvertiser = acctPayer;	
			
			PageReference pageRef = Page.ExternalAccountCreateBookingAccount;
			Test.setCurrentPage(pageRef);
			
	        ExternalAccountForm_Controller eaf = new ExternalAccountForm_Controller();
			
	        eaf.isAgency = false;
	        eaf.selectedAdvertiser = acctAdvertiser;
	        eaf.selectedPayer = accountList[0];
	
			eaf.init();

	        eaf.selectedPayer = acctPayer;
	        TestDataFactory.createdCyberAdUserCredentials(UserInfo.getUserId());
			TestDataFactory.createCustomSettingGeneraAccountTypeMapping();

			map<String, Genera_Account_Type_Mapping__c> availableGBATypeMap = eaf.availableGBATypeMap;
	        list<selectOption> gbaAccountTypeOptionsForSelectAdvertiser = eaf.gbaAccountTypeOptionsForSelectAdvertiser;
			list<selectOption> gbadefaultRevenueGroupGeneraOptions = eaf.gbadefaultRevenueGroupGeneraOptions;
			list<selectOption> gbaDivisionOptions = eaf.gbaDivisionOptions;
			list<SelectOption> ParentBookingAccounts = eaf.getParentBookingAccounts();

			eaf.redirectToPage = true;
			
			eaf.gbaAccount.External_Account__c = extAcct.id;
			eaf.onParentAccountSelection();
	
			eaf.gbaAccount.Account_Type__c = 'Client of Ad Agency';
			
			eaf.onAccountTypeSelection();
			
			eaf.gbaAccount.Name = 'test';
			eaf.gbaAccount.Street__c = 'abc%12';
			eaf.gbaAccount.Suburb__c = 'test';
			try{
				PageReference pr = eaf.saveNewGBAAndRedirect();
			}catch(Exception ex){
				system.debug('@@ex : '+ ex.getMessage());
				system.assertEquals(ex.getMessage().contains('Please remove special characters from Street field'), true);
			}
    }
    
    //test for gbaaccount special characters in Country field
    static testMethod void testSpecialChar_Country_Validation() {
			
			list<Account> accountList = TestDataFactory.createAccounts(1,false);
			insert accountList;

			External_Account__c extAcct = TestDataFactory.createExternalAccount();
			
			Account acctPayer = [select id, 
										Name,
										BillingPostalCode,
										BillingCountry,
										BillingState,
										BillingCity,
										BillingStreet,
										DPID_Primary_Address__c,
										AccountNumber,
										Phone,
										No_Parent_Account__c,
										Revenue_Group__c,
										IsPersonAccount
									from Account
									Where id=:extAcct.Customer_Account__c];
			
			Account acctAdvertiser = acctPayer;	
			
			PageReference pageRef = Page.ExternalAccountCreateBookingAccount;
			Test.setCurrentPage(pageRef);
			
	        ExternalAccountForm_Controller eaf = new ExternalAccountForm_Controller();
			
	        eaf.isAgency = false;
	        eaf.selectedAdvertiser = acctAdvertiser;
	        eaf.selectedPayer = accountList[0];
	
			eaf.init();

	        eaf.selectedPayer = acctPayer;
	        TestDataFactory.createdCyberAdUserCredentials(UserInfo.getUserId());
			TestDataFactory.createCustomSettingGeneraAccountTypeMapping();

			map<String, Genera_Account_Type_Mapping__c> availableGBATypeMap = eaf.availableGBATypeMap;
	        list<selectOption> gbaAccountTypeOptionsForSelectAdvertiser = eaf.gbaAccountTypeOptionsForSelectAdvertiser;
			list<selectOption> gbadefaultRevenueGroupGeneraOptions = eaf.gbadefaultRevenueGroupGeneraOptions;
			list<selectOption> gbaDivisionOptions = eaf.gbaDivisionOptions;
			list<SelectOption> ParentBookingAccounts = eaf.getParentBookingAccounts();

			eaf.redirectToPage = true;
			
			eaf.gbaAccount.External_Account__c = extAcct.id;
			eaf.onParentAccountSelection();
	
			eaf.gbaAccount.Account_Type__c = 'Client of Ad Agency';
			
			eaf.onAccountTypeSelection();
			
			eaf.gbaAccount.Name = 'test';
			eaf.gbaAccount.Street__c = 'streettest';
			eaf.gbaAccount.Suburb__c = 'test';
			eaf.gbaAccount.Country__c = 'abc%12';
			
			try{
				PageReference pr = eaf.saveNewGBAAndRedirect();
			}catch(Exception ex){
				system.assertEquals(ex.getMessage().contains('Please remove special characters from Country field'), true);
			}
    }
    
    //test for gbaaccount insert exception
    static testMethod void testInsertException() {
			
			list<Account> accountList = TestDataFactory.createAccounts(1,false);
			insert accountList;

			External_Account__c extAcct = TestDataFactory.createExternalAccount();
			
			Account acctPayer = [select id, 
										Name,
										BillingPostalCode,
										BillingCountry,
										BillingState,
										BillingCity,
										BillingStreet,
										DPID_Primary_Address__c,
										AccountNumber,
										Phone,
										No_Parent_Account__c,
										Revenue_Group__c,
										IsPersonAccount
									from Account
									Where id=:extAcct.Customer_Account__c];
			
			Account acctAdvertiser = acctPayer;	
			
			PageReference pageRef = Page.ExternalAccountCreateBookingAccount;
			Test.setCurrentPage(pageRef);
			
	        ExternalAccountForm_Controller eaf = new ExternalAccountForm_Controller();
			
	        eaf.isAgency = false;
	        eaf.selectedAdvertiser = acctAdvertiser;
	        eaf.selectedPayer = accountList[0];
	
			eaf.init();

	        eaf.selectedPayer = acctPayer;
	        TestDataFactory.createdCyberAdUserCredentials(UserInfo.getUserId());
			TestDataFactory.createCustomSettingGeneraAccountTypeMapping();

			map<String, Genera_Account_Type_Mapping__c> availableGBATypeMap = eaf.availableGBATypeMap;
	        list<selectOption> gbaAccountTypeOptionsForSelectAdvertiser = eaf.gbaAccountTypeOptionsForSelectAdvertiser;
			list<selectOption> gbadefaultRevenueGroupGeneraOptions = eaf.gbadefaultRevenueGroupGeneraOptions;
			list<selectOption> gbaDivisionOptions = eaf.gbaDivisionOptions;
			list<SelectOption> ParentBookingAccounts = eaf.getParentBookingAccounts();

			eaf.redirectToPage = true;
			
			eaf.gbaAccount.External_Account__c = extAcct.id;
			eaf.onParentAccountSelection();
	
			eaf.gbaAccount.Account_Type__c = 'Client of Ad Agency';
			
			eaf.onAccountTypeSelection();

	        ABNLookupMockTest fakeResponse = new ABNLookupMockTest(200,
	                                                 'Complete',
	                                                 '[{"Name": "sForceTest1"}]',
	                                                 null);
			Test.setMock(HttpCalloutMock.class, fakeResponse);
	        eaf.doABNLookup();
	       
    }
    
    
    //test for createAccount
    static testMethod void testCreateAccount() {
			
			list<Account> accountList = TestDataFactory.createAccounts(1,false);
			insert accountList;

			External_Account__c extAcct = TestDataFactory.createExternalAccount();
			
			Account acctPayer = [select id, 
										Name,
										BillingPostalCode,
										BillingCountry,
										BillingState,
										BillingCity,
										BillingStreet,
										DPID_Primary_Address__c,
										AccountNumber,
										Phone,
										No_Parent_Account__c,
										Revenue_Group__c,
										IsPersonAccount
									from Account
									Where id=:extAcct.Customer_Account__c];
			
			Account acctAdvertiser = acctPayer;	
			
			PageReference pageRef = Page.ExternalAccountCreateBookingAccount;
			Test.setCurrentPage(pageRef);
			
	        ExternalAccountForm_Controller eaf = new ExternalAccountForm_Controller();
			
	        eaf.isAgency = false;
	        eaf.selectedAdvertiser = acctAdvertiser;
	        eaf.selectedPayer = accountList[0];
	
			eaf.init();

	        eaf.selectedPayer = acctPayer;
	        TestDataFactory.createdCyberAdUserCredentials(UserInfo.getUserId());
			TestDataFactory.createCustomSettingGeneraAccountTypeMapping();

			map<String, Genera_Account_Type_Mapping__c> availableGBATypeMap = eaf.availableGBATypeMap;
	        list<selectOption> gbaAccountTypeOptionsForSelectAdvertiser = eaf.gbaAccountTypeOptionsForSelectAdvertiser;
			list<selectOption> gbadefaultRevenueGroupGeneraOptions = eaf.gbadefaultRevenueGroupGeneraOptions;
			list<selectOption> gbaDivisionOptions = eaf.gbaDivisionOptions;
			list<SelectOption> ParentBookingAccounts = eaf.getParentBookingAccounts();

			eaf.redirectToPage = true;
			
			eaf.gbaAccount.External_Account__c = extAcct.id;
			eaf.gbaAccount.GBA_Phone_Area_Code__c = 9;
			eaf.onParentAccountSelection();
	
			eaf.gbaAccount.Account_Type__c = 'Client of Ad Agency';
			
			eaf.onAccountTypeSelection();
			
			eaf.gbaAccount.Country__c = 'testCountry';
            eaf.gbaAccount.Name = 'test';
            eaf.gbaAccount.Title__c = 'test';
            eaf.gbaAccount.Email_Address__c = 'test@email.com';
            eaf.gbaAccount.Post_Code__c = '1234';
            eaf.gbaAccount.State__c = '2345';
            eaf.gbaAccount.Street__c = 'abc';
            eaf.gbaAccount.Suburb__c = 'subtest';
            eaf.gbaAccount.GBA_Phone_Country_Code__c = 12;
            eaf.gbaAccount.GBA_Phone__c = '9876543212';
            eaf.gbaAccount.Account_Type__c = 'typeTest';
            eaf.gbaAccount.ABN_Number__c = 'abnNo';
            eaf.gbaAccount.First_Name__c = 'testFirstName';
            eaf.gbaAccount.Last_Name__c = 'testLastName';
            eaf.gbaAccount.DPID__c = 'testDPID';
            eaf.gbaAccount.Default_Revenue_Group__c = 'revenueTest';
            eaf.gbaAccount.Email_Confirmation_Address__c = 'test1@email.com';
            eaf.gbaAccount.Division__c = 'testDivision';
            eaf.gbaAccount.Owning_Credit_Division__c = 'testCredit';
            
            Test.startTest();
            Test.setMock(WebServiceMock.class, new CreateAccountResponseMockTest());
            
	        string createdAccountString = eaf.createAccount();
	        Test.stopTest();
	        //system.debug('@@createdAccountString : '+ createdAccountString);
	        
    }
    
    //create general account type mapping
    public static list<Genera_Account_Type_Mapping__c> createGenAccountTypeMapping() {
    	
        list<Genera_Account_Type_Mapping__c> gatm = new list<Genera_Account_Type_Mapping__c>();
        
        gatm.add(  new Genera_Account_Type_Mapping__c ( Name = 'Client of Ad Agency',
                                                       Value__c = 'CL',
                                                       CreatedByNFSS__c = true,
                                                       CreatedBySales__c = true,
                                                       Parent__c = 'Ad Agency',
                                                       isABNrequired__c = false,
                                                       Owning_Credit_Division__c = 'N',
                                                       Request_Account_Divisions__c = 'N'));
        insert gatm;                                             
        return gatm;
    }
}