News UAT/force-app/main/default/objects/Account/fields/Account_Last_Modified__c.field-meta.xml
<CustomField>
    <fullName>Account_Last_Modified__c</fullName>
    <description>timestamp when TCS or TAS or Parent has been changed</description>
    <label>Account Last Modified</label>
    <type>DateTime</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Total_Agency_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Agency_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Agency Spend - rolled up from all Bookings where the Agency is the Payer (YTD)</description>
    <inlineHelpText>Total Agency Spend - rolled up from all Bookings where the Agency is the Payer (YTD)</inlineHelpText>
    <label>Total Agency Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Total_Customer_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Customer_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Customer Spend - rolled up from Total Cost of all Bookings related to the Customer (YTD)</description>
    <inlineHelpText>Total Customer Spend - rolled up from Total Cost of all Bookings related to the Customer (YTD)</inlineHelpText>
    <label>Total Customer Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Total_Group_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Group_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Group Spend for the Customer/Agency Hierarchy (this Customer and all below) for all Bookings (YTD)</description>
    <inlineHelpText>Total Group Spend for the Customer/Agency Hierarchy (this Customer and all below) for all Bookings (YTD)</inlineHelpText>
    <label>Total Group Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Ultimate_Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_Id__c</fullName>
    <externalId>true</externalId>
    <label>Ultimate Parent ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Exception_Record__c/Exception_Record__c.object-meta.xml
<CustomObject>
    <description>This object is to store exception records throw from batches</description>
    <label>Exception Record</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Exception Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Exception_Record__c/fields/Action_Type__c.field-meta.xml
<CustomField>
    <fullName>Action_Type__c</fullName>
    <description>This field determines what action/batch causes this record failed. It&#39;s very important for trigger/controller/batch to pickup failure records.</description>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TGS</fullName>
            </value>
            <value>
                <fullName>TCSTAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Shell Order encompassing Booking(s) - to be related to an Opportunity Product/s</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{0000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Advertiser_Account__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advertiser Account</description>
    <label>Advertiser Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders_Advertiser</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Payer_Account__c.field-meta.xml
<CustomField>
    <fullName>Payer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payer Account</description>
    <inlineHelpText>Payer – The account that pays for the advertising.</inlineHelpText>
    <label>Payer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders (Payer Account)</relationshipLabel>
    <relationshipName>Sales_Orders_Payer</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Total_Gross_Price_Ytd__c.field-meta.xml
<CustomField>
    <fullName>Total_Gross_Price_Ytd__c</fullName>
    <label>Total Gross Price YTD</label>
    <summarizedField>Booking__c.Line_Item_Gross_Price_YTD__c</summarizedField>
    <summaryForeignKey>Booking__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Total_Gross_Price_YTD_Last_Modified__c.field-meta.xml
<CustomField>
    <fullName>Total_Gross_Price_YTD_Last_Modified__c</fullName>
    <description>last modified datetime for total gross price YTD</description>
    <label>Total Gross Price YTD Last Modified</label>
    <type>DateTime</type>
</CustomField>

News UAT/force-app/main/default/classes/ExceptionRecordCleanUp_Batch.cls
/*---------------------------------------------------------
 * Author: Bohao Chen
 * Company: Bluewolf.com
 * Description: This batch will clean up exception record based on action type 
 * History:
 * 20/07/2014  Bohao Chen  Created
 ---------------------------------------------------------*/
 // TODO: covert this exception proccess class to process TCSTAS exception records
global class ExceptionRecordCleanUp_Batch implements Database.Batchable<sObject>, Database.Stateful
{
    global String query;
	global String actionType;
	
    global ExceptionRecordCleanUp_Batch(String actionType)
    {       
        this.query = 'Select Id from Exception_Record__c Where Action_Type__c = \'' + actionType + '\'';
        this.actionType = actionType;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Exception_Record__c> exceptionRecords)
    {
    	delete exceptionRecords;
    }
    
    global void finish(Database.BatchableContext BC)
    {
	        if(this.actionType == 'TGS')
	        {
	            // After cleaning up TGS (total group spending) exception records, 
	            // AccountUpdateTgs_Batch gets called to update TGS using latest TCS and TAS

                        // when TCS or TAS or parent account get updated, Account_Last_Modified__c will timestamp it.
                // Only rollup accounts' whose Account_Last_Modified__c is greater than last success batch run time.
                String query = 'Select Id, ParentId, RecordType.Name, Total_Group_Spend__c, '
                    + 'Ultimate_Parent_Id__c, Total_Customer_Spend__c, Total_Agency_Spend__c, Account_Last_Modified__c, '
                    + 'Parent.Name, Parent.Id, Parent.ParentId, Parent.RecordType.Name, Parent.Total_Group_Spend__c, ' 
                    + 'Parent.Ultimate_Parent_Id__c, Parent.Total_Customer_Spend__c, Parent.Total_Agency_Spend__c '
                    + 'From Account ' 
                    + 'Where Account_Last_Modified__c > :recordStartDatetime '
                    + 'And Ultimate_Parent_Id__c != NULL';
				
				// SFE-766 2016-01-14 atul.gupta@bluewolfgroup.com - Batch class call exempted from during test class execution
				if(!Test.isRunningTest()){
	                AccountUpdateTgs_Batch accountUpdateTgs = new AccountUpdateTgs_Batch(query);
	                ID batchProcessId; batchProcessId = Database.executeBatch(accountUpdateTgs);
	                System.debug('Account TGS Update Batch batch process ID: ' + batchProcessId);
				}
	        }
	        else if(this.actionType == 'TCSTAS')
	        {	        	
	        	String query = 'Select s.Total_Gross_Price_Ytd__c, s.Payer_Account__c, s.Payer_Account__r.RecordType.Name, '
                     + 's.Advertiser_Account__c, s.Advertiser_Account__r.RecordType.Name, s.Total_Gross_Price_YTD_Last_Modified__c ' 
                     + 'From Sales_Order__c s';
                     
                // SFE-766 2016-01-14 atul.gupta@bluewolfgroup.com - Batch class call exempted from during test class execution
	        	if(!Test.isRunningTest()){
					AccountUpdateTcsTas_Batch b = new AccountUpdateTcsTas_Batch(null, query);
					database.executeBatch(b);  
	        	} 
	        }
    }
}