News UAT/force-app/main/default/objects/Account/fields/AdPoint_Id__c.field-meta.xml
<CustomField>
    <fullName>AdPoint_Id__c</fullName>
    <externalId>true</externalId>
    <label>AdPoint Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Mark for Duplication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Campaign_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Start_Date__c</fullName>
    <label>Advertising Start Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/OpportunityGroup__c.field-meta.xml
<CustomField>
    <fullName>OpportunityGroup__c</fullName>
    <label>Opportunity Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Inserts</fullName>
            </value>
            <value>
                <fullName>NewsXtend</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Magazine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Payer_Account__c.field-meta.xml
<CustomField>
    <fullName>Payer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payer Account</relationshipLabel>
    <relationshipName>Opportunities_Payer</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>CASE(TEXT(StageName),
  &quot;Identify Prospects&quot;, &quot;Open&quot;,
  &quot;Establish Rapport&quot;, &quot;Open&quot;,
  &quot;Qualify Opportunity&quot;, &quot;Open&quot;,
  &quot;Select Product(s) and Update Stage&quot;, &quot;Open&quot;,
  &quot;Develop Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Present Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Re-affirm Value/ Negotiate&quot;, &quot;Open&quot;,
  &quot;Awaiting Bookings&quot;, &quot;Open&quot;,
  &quot;Closed Won&quot;, &quot;Closed Won&quot;,
  &quot;Closed Lost&quot;, &quot;Closed Lost&quot;,
  &quot;Err: Invalid stage name&quot;
)</formula>
    <inlineHelpText>Field to allow reporting on Win/ Lost vs Open. Do not display on page layouts.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Fulfilment Ready</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Campaign Live</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Payment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Line_Item__c/Payment_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Line Item</label>
    <nameField>
        <label>Payment Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Payment_Line_Item__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <label>Payment Schedule</label>
    <referenceTo>Payment_Schedule__c</referenceTo>
    <relationshipLabel>Payment Line Items</relationshipLabel>
    <relationshipName>Payment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Payment Schedule</label>
    <nameField>
        <label>Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Payment_Schedule__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Campaign Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/CS_SchedulePaymentsController.cls
/**
 * Controller for Salesforce Lightning action to Schedule Payments
 * Deletes old orders and payments if all payment schedules are pending or cancelled
 */
public class CS_SchedulePaymentsController {
    
    @TestVisible
    private ApexPages.StandardController ctrl;
    
    public CS_SchedulePaymentsController(ApexPages.StandardController controller) {
        this.ctrl = controller;
    }
    
    /**
     * Schedule payments Lightning action
     */
    public PageReference schedulePayments() {
        try {
            Id oppId = ctrl.getRecord().Id;
            List<Opportunity> oppList = new list<Opportunity> ([select OpportunityGroup__c, Account.AdPoint_ID__c, Payer_Account__r.AdPoint_ID__c from Opportunity where id =:oppId]);
            //**Commented for field type switch Start            
            List<csmso__Sales_Order__c> salesOrders = [
                select id,Name,csmso__Status__c,Campaign_Start_Date__c,Campaign_End_Date2__c,Campaign_Length__c,Total_GST_inclusive__c,csmso__Total_Price__c,csmso__Booking_Contact__r.Name,GST__c 
                from csmso__Sales_Order__c 
                where csmso__Opportunity__c =:oppId
                and (csmso__Status__c = 'externally approved'
                    or csmso__Status__c = 'manually approved')
            ];
            //**Commented for field type switch End 
            if (salesOrders.size() > 1) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL, 'More than one manually or externally approved Sales Order.'));
                return null;
            }
            /*
            else if (salesOrders[0].Campaign_Start_Date__c < system.today()){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL, 'Campaign start date cannot be sooner than today, please amend the start date on the Sales Order to schedule payments.'));
                return null;
            }
            */
            List<Order__c> ordersToDelete = [
                select id 
                from Order__c
                where Opportunity__c = :oppId
            ];
            List<Payment_Schedule__c> psToDelete = [
                select Id, Status__c
                from Payment_Schedule__c
                where Payment__r.Order__r.Opportunity__c = :oppId
            ];
            List<Payment__c> pToDelete = [
                select Id
                from Payment__c
                where Order__r.Opportunity__c = :oppId
            ];
            List<Payment_Line_Item__c> pliToDelete = [
                select Id
                from Payment_Line_Item__c
                where Payment_Schedule__r.Payment__r.Order__r.Opportunity__c = :oppId
            ];
            for (Payment_Schedule__c ps : psToDelete) {
                if (ps.Status__c != 'Pending' && ps.Status__c != 'Cancelled') {
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL, 'Campaign already started. Cannot reschedule payments.'));
                    return null;
                }
            }
            if (!pliToDelete.isEmpty()) {
                delete pliToDelete;
            }
            if (!psToDelete.isEmpty()) {
                delete psToDelete;
            }
            if (!pToDelete.isEmpty()) {
                delete pToDelete;
            }
            if (!ordersToDelete.isEmpty()) {
                delete ordersToDelete;
            }
            if (oppId !=null && salesOrders.size()>0){
                Order_PaymentSchedulerController.getOrder(oppId,salesOrders[0]);
                Order_PaymentSchedulerController.createPayment(salesOrders[0],oppList[0]);
                Order_PaymentSchedulerController.createPaymentSchedule(salesOrders[0]);
                Order_PaymentSchedulerController.createPaymentLineItem(salesOrders[0]);
            }
            return ctrl.view();
        } catch(Exception e) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL, e.getMessage()));
            return null;
        }
    }

}