News UAT/force-app/main/default/objects/Account/fields/AdPoint_Id__c.field-meta.xml
<CustomField>
    <fullName>AdPoint_Id__c</fullName>
    <externalId>true</externalId>
    <label>AdPoint Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/No_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>No_Parent_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to override the Parent Account required field</inlineHelpText>
    <label>No Parent Account</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <formula>Owner.UserRole.Name</formula>
    <label>Owner Role</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Account_Portfolio_Relationship__c/Account_Portfolio_Relationship__c.object-meta.xml
<CustomObject>
    <description>NextGen - Account portfolio relationship</description>
    <label>Account Portfolio Relationship</label>
    <nameField>
        <label>Account Portfolio Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Portfolio Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Account_Portfolio_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>NextGen</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Portfolio Relationships</relationshipLabel>
    <relationshipName>Account_Portfolio_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Account_Portfolio_Relationship__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <description>External ID for upserting the relationship mapping between Portfolio and Account</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique Identifier for the Portfolio and Account</inlineHelpText>
    <label>ExternalID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Account_Portfolio_Relationship__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <label>Portfolio</label>
    <referenceTo>Portfolio2__c</referenceTo>
    <relationshipLabel>Account Portfolio Relationships</relationshipLabel>
    <relationshipName>Account_Portfolio_Relationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Account_Portfolio_Relationship__c/fields/Portfolio_Code__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Code__c</fullName>
    <description>Formula field from related Master Porfolio2__c.Portfolio_Code__c</description>
    <formula>Portfolio__r.Portfolio_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Portfolio Code</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_System_Portfolio_Junction__c/Booking_System_Portfolio_Junction__c.object-meta.xml
<CustomObject>
    <label>Booking System - Portfolio Junction</label>
    <nameField>
        <label>Booking System - Portfolio Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking System - Portfolio Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking_System_Portfolio_Junction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking System - Portfolio Junctions</relationshipLabel>
    <relationshipName>Booking_System_Portfolio_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_System_Portfolio_Junction__c/fields/Booking_System_Account__c.field-meta.xml
<CustomField>
    <fullName>Booking_System_Account__c</fullName>
    <description>NextGen</description>
    <label>Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Booking System - Portfolio Junctions</relationshipLabel>
    <relationshipName>Booking_System_Portfolio_Junctions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_System_Portfolio_Junction__c/fields/BSA_Portfolio_Id__c.field-meta.xml
<CustomField>
    <fullName>BSA_Portfolio_Id__c</fullName>
    <description>External Unique Id for Booking System Account relationship to Portfolio</description>
    <externalId>true</externalId>
    <label>BSA Portfolio Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Booking_System_Portfolio_Junction__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <label>Portfolio</label>
    <referenceTo>Portfolio2__c</referenceTo>
    <relationshipLabel>Booking System - Portfolio Junctions</relationshipLabel>
    <relationshipName>Booking_System_Portfolio_Junctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_System_Portfolio_Junction__c/fields/Portfolio_Code__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Code__c</fullName>
    <formula>Portfolio__r.Portfolio_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Portfolio Code</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/External_Account__c.object-meta.xml
<CustomObject>
    <description>Object to hold external accounts such as Billing and Booking Accounts</description>
    <label>Booking System Account</label>
    <nameField>
        <label>Booking System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking System Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/External_Account__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The External Account&#39;s parent Customer Account</description>
    <inlineHelpText>The External Account&#39;s parent Customer Account</inlineHelpText>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>External_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent External Account</description>
    <inlineHelpText>Parent External Account</inlineHelpText>
    <label>Parent Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Booking System Accounts</relationshipLabel>
    <relationshipName>External_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <inlineHelpText>External Id</inlineHelpText>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Portfolio_Code__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Code__c</fullName>
    <description>Portfolio Code assigned from the Portfolio2__c object from the portfolio picker</description>
    <inlineHelpText>Selected from the Portfolio Picker</inlineHelpText>
    <label>Portfolio Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Portfolio2__c/Portfolio2__c.object-meta.xml
<CustomObject>
    <description>For use with Phoenix reports</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Portfolio2__c/fields/Conformed_Name__c.field-meta.xml
<CustomField>
    <fullName>Conformed_Name__c</fullName>
    <description>Phoenix Reporting</description>
    <label>Conformed Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Portfolio2__c/fields/Portfolio_Code__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Code__c</fullName>
    <description>NextGen - Phoenix Reporting</description>
    <externalId>true</externalId>
    <label>Portfolio Code</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <label>Portfolio Team</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Portfolio Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Portfolio__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Parent Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Portfolios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Product2/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Product2/fields/isTest__c.field-meta.xml
<CustomField>
    <fullName>isTest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field purely for testing class use. The reason behind this is that we need to turn on annotation SeeAllData in order to allow test class to get standard price book from Database. But we don&#39;t want to see existing product records in test class. This field is only visible for system administrator.</description>
    <label>Test</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/classes/PortfolioReassignment_Test.cls
/** 
 *
 * @author      Paul Kang, Bluewolf 
 * @description Update all Opened Opportunities Portfolio Codes with the updated code from the parent Account
 * @description Modified 2018-02-11 Paul Kang 
 **/
@isTest
private class PortfolioReassignment_Test {
	
	static Integer numOfRecords = 5;

	//static Portfolio2__c port {get; set;}

	private static Product2 SetupProducts() {

		Product2 prod = new Product2();
		prod.isTest__c = true;
		prod.Name = 'test Prod';

		insert prod;

		Pricebook2 pb2 = new Pricebook2();
		pb2.Name = 'sample pricebook';
		pb2.IsActive = true;
		insert pb2;


		PricebookEntry pbe = new PricebookEntry();
		pbe.UnitPrice = 10.0;
		pbe.Product2Id = prod.id;
		pbe.Pricebook2Id = pb2.id;
		pbe.UseStandardPrice = true;
		
		insert pbe;

		return prod;
	}

	@testSetup static void Setup() {
	// adpoint accounts
		List<Account> accounts = new List<Account>();
		for(Integer i = 0; i < numOfRecords; i++) {
			// create Accounts
			Account newAccount = new Account();
			newAccount.AccountNumber = '47 007 871 171';
			newAccount.AdPoint_Id__c = '100' + i;
			newAccount.Name = 'account name' + i;
			newAccount.No_Parent_Account__c = true;			
			
			accounts.add(newAccount);
		}
		insert accounts;


		Portfolio2__c oldPort = new Portfolio2__c();
		oldPort.Portfolio_Code__c = '04';
		oldPort.Conformed_Name__c = 'previous portfolio code';
		insert oldPort;


		List<Opportunity> oppts = new List<Opportunity>();
		for(Integer i=0; i < numOfRecords; i++) {
			Opportunity newOppt = new Opportunity();
			newOppt.AccountId = accounts[1].Id;
			newOppt.Name = 'randomName' + i;
			newOppt.Portfolio_Code__c = oldPort.Portfolio_Code__c;
			newOppt.StageName = 'Discover Needs';
			newOppt.CloseDate = System.today();
			oppts.add(newOppt);
		}
		insert oppts;

		//List<OpportunityLineItem> opptProds = new List<OpportunityLineItem>();
		//for(Opportunity opp : oppts) {
		
		//	for(Integer i=0; i<numOfRecords; i++) {
		//		OpportunityLineItem op = new OpportunityLineItem();
		//		op.OpportunityId = opp.id;
		//		op.TotalPrice = Math.random();
		//		op.Quantity = Math.random();
		//		//op.Product2Id = SetupProducts().Id;
		//		opptProds.add(op);
		//	}
		//}

		//insert opptProds;

	 	Portfolio2__c port = new Portfolio2__c();
		port.Portfolio_Code__c = '02';
		port.Conformed_Name__c = 'test name';
		insert port;


	}

	@isTest static void test_PortfolioCodeChange() {

		Account account = [Select Id, AdPoint_Id__c from Account where AdPoint_Id__c=:'1001'];
		Portfolio2__c oldPort = [Select Id from Portfolio2__c where Portfolio_Code__c ='04'];
		Portfolio2__c port = [Select Id from Portfolio2__c where Portfolio_Code__c ='02'];

		// Load sample account portfolios
		
		List<Account_Portfolio_Relationship__c> acctPorts = new List<Account_Portfolio_Relationship__c>();
		for(Integer i=0; i < numOfRecords; i++) {
			Account_Portfolio_Relationship__c apr = new Account_Portfolio_Relationship__c();
			apr.Account__c = account.Id;
			apr.Portfolio__c = port.Id;
			apr.ExternalID__c = '1001';
			acctPorts.add(apr);
		}
		insert acctPorts;

		External_Account__c bsaAcct = new External_Account__c();
		bsaAcct.Customer_Account__c = account.Id;
		bsaAcct.External_Id__c = 'GBA_T001';
		insert bsaAcct;


		// Load sample bsa to portfolios
		List<Booking_System_Portfolio_Junction__c> bsaPorts = new List<Booking_System_Portfolio_Junction__c>();
		for(Integer i=0; i < numOfRecords; i++) {
			Booking_System_Portfolio_Junction__c bsa = new Booking_System_Portfolio_Junction__c();
			bsa.Booking_System_Account__c = bsaAcct.Id;
			bsa.Portfolio__c = port.Id;
			bsa.BSA_Portfolio_Id__c = 'GBA_T00' + i;
			bsaPorts.add(bsa);
		}
		insert bsaPorts;


		System.assertEquals(numOfRecords, [Select count() from Opportunity where Portfolio_Code__c ='04']);


		Test.startTest();

		PortfolioReassignmentProcess process = new PortfolioReassignmentProcess();
		Database.executeBatch(process, 2000);

		Test.stopTest();

		System.assertEquals(numOfRecords, [Select count() from Opportunity where Portfolio_Code__c ='02']);
		
	}


	
	@isTest static void test_SendReminder() {
		Integer invocations = 0;

		List<Opportunity> oppts = [Select Id, OwnerId, Portfolio_Code__c from Opportunity];

		Test.startTest();
		PortfolioReassignmentProcess process = new PortfolioReassignmentProcess();

		process.SendReminder(oppts);	

		invocations = Limits.getEmailInvocations();	

		Test.stopTest();

		System.assertEquals(1, invocations, 'One email was sent due to more than 1 portfolio to opportunity');
	}

	
}