News UAT/force-app/main/default/objects/Account/fields/AdPoint_Id__c.field-meta.xml
<CustomField>
    <fullName>AdPoint_Id__c</fullName>
    <externalId>true</externalId>
    <label>AdPoint Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Industry_Code__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Industry Codes are imported from the ANSIC standard of Industry Codes. It is periodically maintained and the information in this field will feed into Opportunities and Bookings.</inlineHelpText>
    <label>Industry</label>
    <referenceTo>Industry_Code__c</referenceTo>
    <relationshipLabel>Accounts_IndustryCodes</relationshipLabel>
    <relationshipName>Accounts_Industry</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Is_Digital__c.field-meta.xml
<CustomField>
    <fullName>Is_Digital__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Turns this Account into a Digital Account - a corresponding Account is created in the Adpoint System.</description>
    <inlineHelpText>Check to enable this as a Digital Account and perform digital Adpoint Bookings. Once turned Digital, it cannot be unchecked.</inlineHelpText>
    <label>Is this a Digital Account?</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Industry_Code__c/Industry_Code__c.object-meta.xml
<CustomObject>
    <description>ANZSIC 2006 Industry Codes.

4 levels (Division, Subdivision, Group, Class)</description>
    <label>Industry Code</label>
    <nameField>
        <label>Industry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industry Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/No_Triggers__c/No_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>No Triggers</label>
</CustomObject>

News UAT/force-app/main/default/objects/Opportunity/fields/Industry_Code__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Code</label>
    <referenceTo>Industry_Code__c</referenceTo>
    <relationshipLabel>Opportunities_IndustryCode</relationshipLabel>
    <relationshipName>Opportunities_IndustryCode</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/OpportunityGroup__c.field-meta.xml
<CustomField>
    <fullName>OpportunityGroup__c</fullName>
    <label>Opportunity Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Inserts</fullName>
            </value>
            <value>
                <fullName>NewsXtend</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Magazine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Payer_Account__c.field-meta.xml
<CustomField>
    <fullName>Payer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payer Account</relationshipLabel>
    <relationshipName>Opportunities_Payer</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/User/fields/Bypass_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Triggers__c</fullName>
    <description>List of triggers that are selected to be bypassed for this user. Allows triggers to be muted.</description>
    <label>Bypass Triggers</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BookingLineItemManagement</fullName>
            </value>
            <value>
                <fullName>SalesOrderManagement</fullName>
            </value>
            <value>
                <fullName>AccountManagement</fullName>
            </value>
            <value>
                <fullName>AccountTeam</fullName>
            </value>
            <value>
                <fullName>AgreementManagement</fullName>
            </value>
            <value>
                <fullName>BookingManagement</fullName>
            </value>
            <value>
                <fullName>CampaignMemberManagement</fullName>
            </value>
            <value>
                <fullName>CaseManagement</fullName>
            </value>
            <value>
                <fullName>CleanUpAccountTeam</fullName>
            </value>
            <value>
                <fullName>ContactManagement</fullName>
            </value>
            <value>
                <fullName>emailAttachmentReassigner</fullName>
            </value>
            <value>
                <fullName>LeadManagement</fullName>
            </value>
            <value>
                <fullName>OpportunityLineItemManagement</fullName>
            </value>
            <value>
                <fullName>OpportunityManagement</fullName>
            </value>
            <value>
                <fullName>PublicationProductManagement</fullName>
            </value>
            <value>
                <fullName>TaskManagement</fullName>
            </value>
            <value>
                <fullName>ActionTask</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/User/fields/Sales_Team__c.field-meta.xml
<CustomField>
    <fullName>Sales_Team__c</fullName>
    <label>Sales Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Community Newspaper Group - CWA</fullName>
            </value>
            <value>
                <fullName>NewsAdds - Facebook NSW</fullName>
            </value>
            <value>
                <fullName>NewsAdds - Facebook NT</fullName>
            </value>
            <value>
                <fullName>NewsAdds - Facebook QLD</fullName>
            </value>
            <value>
                <fullName>NewsAdds - Facebook SA</fullName>
            </value>
            <value>
                <fullName>NewsAdds - Facebook TAS</fullName>
            </value>
            <value>
                <fullName>NewsAdds - Facebook VIC</fullName>
            </value>
            <value>
                <fullName>NewsAdds - Facebook VIC Geelong</fullName>
            </value>
            <value>
                <fullName>NewsAdds - Facebook WA</fullName>
            </value>
            <value>
                <fullName>NRM</fullName>
            </value>
            <value>
                <fullName>NSW Community</fullName>
            </value>
            <value>
                <fullName>NSW Metro</fullName>
            </value>
            <value>
                <fullName>NT Northern Territory</fullName>
            </value>
            <value>
                <fullName>QLD Cairns</fullName>
            </value>
            <value>
                <fullName>QLD Community</fullName>
            </value>
            <value>
                <fullName>QLD Gold Coast</fullName>
            </value>
            <value>
                <fullName>QLD Metro</fullName>
            </value>
            <value>
                <fullName>QLD Townsville</fullName>
            </value>
            <value>
                <fullName>SA Community</fullName>
            </value>
            <value>
                <fullName>TAS Hobart</fullName>
            </value>
            <value>
                <fullName>The Weekly Times</fullName>
            </value>
            <value>
                <fullName>VIC Community</fullName>
            </value>
            <value>
                <fullName>VIC Geelong</fullName>
            </value>
            <value>
                <fullName>VIC Metro</fullName>
            </value>
            <value>
                <fullName>SA Metro</fullName>
                <isActive>false</isActive>
                <label>SA Metro</label>
            </value>
            <value>
                <fullName>WA CNG</fullName>
                <isActive>false</isActive>
                <label>WA CNG</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/SalesOrderCalloutTest.cls
/*
 * 2017-06-15 Existing class
 * 2017-06-15 Item-00299 louis.wang@bluewolf.com - Added IndustryCode to accomodate new validaiton rule
 *
 *      This class provides test coverage for
 *          - GBALookupService.cls             100% 
 --------------------------------------------------------- */
@isTest
public class SalesOrderCalloutTest {
    /*@isTest static void testCallout_oppGrp() {              
        // This causes a fake response to be generated
        //Test.setMock(WebServiceMock.class, new SalesOrderCalloutMock());
        // Call the method that invokes a callout
        Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        acc.AdPoint_ID__c = null;
        acc.Is_Digital__c = false;
        insert acc;
        
        Account payerAcc = TestDataSetupClass.createAccount();
        RecordType payerAccrtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        payerAcc.RecordTypeId = payerAccrtypes.Id;
        payerAcc.AdPoint_ID__c = null;
        payerAcc.Is_Digital__c = false;
        insert payerAcc;
        
        Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today(),
                                          OpportunityGroup__c = 'Digital',  Payer_Account__c = payerAcc.Id);
        insert opp;
        
        csmso__Sales_Order__c so = TestDataSetupClass.createSalesOrder(acc, opp);
        so.csmso__Status__c = 'externally approved';
        insert so;
        
        List<csmso__Sales_Order__c> soList = new List<csmso__Sales_Order__c>();
        soList.add(so);
        Test.startTest();
        	Test.setMock(WebServiceMock.class, new SalesOrderCalloutMock());
            PageReference pageRef = Page.NewSalesOrder;
            Test.setCurrentPage(pageRef);
            ApexPages.StandardSetcontroller sc = new ApexPages.StandardSetcontroller(soList);
            ApexPages.currentPage().getParameters().put('Id',opp.id);
            NewSalesOrderController  testcontroller = new NewSalesOrderController(sc);        
            pagereference result = testcontroller.opptyValidation();
        Test.stopTest();
        
    }
    
    @isTest static void testCallout_AccAdPointID() {              
        // This causes a fake response to be generated
        Test.setMock(WebServiceMock.class, new SalesOrderCalloutMock());
        // Call the method that invokes a callout
        Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        acc.AdPoint_ID__c = null;
        acc.Is_Digital__c = false;
        insert acc;
        
        Account payerAcc = TestDataSetupClass.createAccount();
        RecordType payerAccrtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        payerAcc.RecordTypeId = payerAccrtypes.Id;
        payerAcc.AdPoint_ID__c = null;
        payerAcc.Is_Digital__c = false;
        insert payerAcc;
        
        Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today(),
                                          OpportunityGroup__c = 'NewsXtend',  Payer_Account__c = payerAcc.Id);
        insert opp;
        
        csmso__Sales_Order__c so = TestDataSetupClass.createSalesOrder(acc, opp);
        so.csmso__Status__c = 'externally approved';
        insert so;
        
        List<csmso__Sales_Order__c> soList = new List<csmso__Sales_Order__c>();
        soList.add(so);
        Test.startTest();
            PageReference pageRef = Page.NewSalesOrder;
            Test.setCurrentPage(pageRef);
            ApexPages.StandardSetcontroller sc = new ApexPages.StandardSetcontroller(soList);
            ApexPages.currentPage().getParameters().put('Id',opp.id);
            NewSalesOrderController  testcontroller = new NewSalesOrderController(sc); 
            pagereference result = testcontroller.opptyValidation();
        Test.stopTest();
    }
    
        @isTest static void testCallout_PayerAccAdPointID() {              
        // This causes a fake response to be generated
        Test.setMock(WebServiceMock.class, new SalesOrderCalloutMock());
        // Call the method that invokes a callout
        Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        acc.AdPoint_ID__c = '12345';
        acc.Is_Digital__c = false;
        insert acc;
        
        Account payerAcc = TestDataSetupClass.createAccount();
        RecordType payerAccrtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        payerAcc.RecordTypeId = payerAccrtypes.Id;
        payerAcc.AdPoint_ID__c = null;
        payerAcc.Is_Digital__c = false;
        insert payerAcc;
        
        Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today(),
                                          OpportunityGroup__c = 'NewsXtend',  Payer_Account__c = payerAcc.Id);
        insert opp;
        
        csmso__Sales_Order__c so = TestDataSetupClass.createSalesOrder(acc, opp);
        so.csmso__Status__c = 'externally approved';
        insert so;
        
        List<csmso__Sales_Order__c> soList = new List<csmso__Sales_Order__c>();
        soList.add(so);
        
        Test.startTest();
            PageReference pageRef = Page.NewSalesOrder;
            Test.setCurrentPage(pageRef);
            ApexPages.StandardSetcontroller sc = new ApexPages.StandardSetcontroller(soList);
            ApexPages.currentPage().getParameters().put('Id',opp.id);
            NewSalesOrderController  testcontroller = new NewSalesOrderController(sc);
            pagereference result = testcontroller.opptyValidation();
        Test.stopTest();
    }
    
    @isTest static void testCallout_AccIsDigi() {              
        // This causes a fake response to be generated
        Test.setMock(WebServiceMock.class, new SalesOrderCalloutMock());
        // Call the method that invokes a callout
        Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        acc.AdPoint_ID__c = '12345';
        acc.Is_Digital__c = false;
        insert acc;
        
        Account payerAcc = TestDataSetupClass.createAccount();
        RecordType payerAccrtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        payerAcc.RecordTypeId = payerAccrtypes.Id;
        payerAcc.AdPoint_ID__c = '6789';
        payerAcc.Is_Digital__c = false;
        insert payerAcc;
        
        Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today(),
                                          OpportunityGroup__c = 'NewsXtend',  Payer_Account__c = payerAcc.Id);
        insert opp;
        csmso__Sales_Order__c so = TestDataSetupClass.createSalesOrder(acc, opp);
        so.csmso__Status__c = 'externally approved';
        insert so;
        
        List<csmso__Sales_Order__c> soList = new List<csmso__Sales_Order__c>();
        soList.add(so);
        
        Test.startTest();
            PageReference pageRef = Page.NewSalesOrder;
            Test.setCurrentPage(pageRef);
            ApexPages.StandardSetcontroller sc = new ApexPages.StandardSetcontroller(soList);
            ApexPages.currentPage().getParameters().put('Id',opp.id);
            NewSalesOrderController  testcontroller = new NewSalesOrderController(sc);       
            pagereference result = testcontroller.opptyValidation();
        Test.stopTest();
        
    }
    
    @isTest static void testCallout_PayerAccIsDigi() {              
        // This causes a fake response to be generated
        Test.setMock(WebServiceMock.class, new SalesOrderCalloutMock());
        // Call the method that invokes a callout
        Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        acc.AdPoint_ID__c = '12345';
        acc.Is_Digital__c = true;
        insert acc;
        
        Account payerAcc = TestDataSetupClass.createAccount();
        RecordType payerAccrtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        payerAcc.RecordTypeId = payerAccrtypes.Id;
        payerAcc.AdPoint_ID__c = '6789';
        payerAcc.Is_Digital__c = false;
        insert payerAcc;
        
        Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today(),
                                          OpportunityGroup__c = 'NewsXtend',  Payer_Account__c = payerAcc.Id);
        insert opp;

        csmso__Sales_Order__c so = TestDataSetupClass.createSalesOrder(acc, opp);
        so.csmso__Status__c = 'externally approved';
        insert so;
        
        List<csmso__Sales_Order__c> soList = new List<csmso__Sales_Order__c>();
        soList.add(so);
        
        Test.startTest();
            PageReference pageRef = Page.NewSalesOrder;
            Test.setCurrentPage(pageRef);
            ApexPages.StandardSetcontroller sc = new ApexPages.StandardSetcontroller(soList);
            ApexPages.currentPage().getParameters().put('Id',opp.id);
            NewSalesOrderController  testcontroller = new NewSalesOrderController(sc);
            pagereference result = testcontroller.opptyValidation();
        Test.stopTest();
    }*/
    
    @isTest static void testCallout_webService() {              
        // This causes a fake response to be generated
        //Test.setMock(WebServiceMock.class, new SalesOrderCalloutMock());
        // Call the method that invokes a callout
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u2 = new User(Alias = 'newUser', Email='newuser@testorg.com', 
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                           LocaleSidKey='en_US', ProfileId = p.Id, 
                           TimeZoneSidKey='Australia/Sydney', UserName='testuserforcallout@testorg.com',
                           Sales_Team__c = 'QLD Metro',
                           Bypass_Triggers__c = 'AccountManagement;AccountTeam;CaseManagement;OpportunityManagement;SalesOrder_Helper_Trigger');
        System.runAs(u2){
            // 2017-06-15 Item-00299 louis.wang@bluewolf.com - Added IndustryCode to accomodate new validaiton rule
            Industry_Code__c indCode = TestDataFactory.createIndustryCode();
            insert indCode;

            Account acc = TestDataSetupClass.createAccount();
            RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
            acc.RecordTypeId = rtypes.Id;
            acc.AdPoint_ID__c = '234';
            acc.Is_Digital__c = true;
            acc.Industry_Code__c = indCode.Id;
            insert acc;
            
            Account payerAcc = TestDataSetupClass.createAccount();
            RecordType payerAccrtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
            payerAcc.RecordTypeId = payerAccrtypes.Id;
            payerAcc.AdPoint_ID__c = '7010';
            payerAcc.Is_Digital__c = true;
            payerAcc.Industry_Code__c = indCode.Id;
            insert payerAcc;
            
            Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today(),
                                              OpportunityGroup__c = 'NewsXtend',  Payer_Account__c = payerAcc.Id);
            insert opp;
            
            csmso__Sales_Order__c so = TestDataSetupClass.createSalesOrder(acc, opp);
            so.csmso__Status__c = 'externally approved';
            //insert so;
            
            list<csmso__Sales_Order__c> soList = new list<csmso__Sales_Order__c>();     
            //soList.add(so);
            
            No_Triggers__c setting = new No_Triggers__c();
            setting.SetupOwnerId = UserInfo.getUserId();
            setting.Flag__c = true;
            insert setting;
            
            Test.startTest();
                Test.setMock(WebServiceMock.class, new SalesOrderCalloutMock());
                PageReference pageRef = Page.NewSalesOrder;
                Test.setCurrentPage(pageRef);
                ApexPages.StandardSetcontroller sc = new ApexPages.StandardSetcontroller(soList);
                ApexPages.currentPage().getParameters().put('Id',opp.id);
                NewSalesOrderController  testcontroller = new NewSalesOrderController(sc);
                pagereference result = testcontroller.opptyValidation();
            	testcontroller.responseMapping(opp);
            Test.stopTest();
        }
    }
    
    @isTest static void testCallout_webServiceElse() {              
        // This causes a fake response to be generated
        //Test.setMock(WebServiceMock.class, new SalesOrderCalloutMock());
        // Call the method that invokes a callout
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u2 = new User(Alias = 'newUser', Email='newuser@testorg.com', 
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                           LocaleSidKey='en_US', ProfileId = p.Id, 
                           TimeZoneSidKey='Australia/Sydney', UserName='testuserforcallout@testorg.com',
                           Sales_Team__c = 'QLD Metro',
                           Bypass_Triggers__c = 'AccountManagement;AccountTeam;CaseManagement;OpportunityManagement;SalesOrder_Helper_Trigger');
        System.runAs(u2){
            // 2017-06-15 Item-00299 louis.wang@bluewolf.com - Added IndustryCode to accomodate new validaiton rule
            Industry_Code__c indCode = TestDataFactory.createIndustryCode();
            insert indCode;

            Account acc = TestDataSetupClass.createAccount();
            RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
            acc.RecordTypeId = rtypes.Id;
            acc.AdPoint_ID__c = '234';
            acc.Is_Digital__c = true;
            acc.Industry_Code__c = indCode.Id;
            insert acc;
            
            Account payerAcc = TestDataSetupClass.createAccount();
            RecordType payerAccrtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
            payerAcc.RecordTypeId = payerAccrtypes.Id;
            payerAcc.AdPoint_ID__c = '7010';
            payerAcc.Is_Digital__c = true;
            payerAcc.Industry_Code__c = indCode.Id;
            insert payerAcc;
            
            Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today(),
                                              OpportunityGroup__c = 'NewsXtend',  Payer_Account__c = payerAcc.Id);
            insert opp;
            
            csmso__Sales_Order__c so = TestDataSetupClass.createSalesOrder(acc, opp);
            so.csmso__Status__c = 'externally approved';
            //insert so;
            
            list<csmso__Sales_Order__c> soList = new list<csmso__Sales_Order__c>();     
            //soList.add(so);
            
            No_Triggers__c setting = new No_Triggers__c();
            setting.SetupOwnerId = UserInfo.getUserId();
            setting.Flag__c = true;
            insert setting;
            
            Test.startTest();
                Test.setMock(WebServiceMock.class, new SalesOrderCalloutMock());
                PageReference pageRef = Page.NewSalesOrder;
                Test.setCurrentPage(pageRef);
                ApexPages.StandardSetcontroller sc = new ApexPages.StandardSetcontroller(soList);
                ApexPages.currentPage().getParameters().put('Id',opp.id);
                NewSalesOrderController  testcontroller = new NewSalesOrderController(sc);
                pagereference result = testcontroller.opptyValidation();
            	//testcontroller.responseMapping(opp);
            Test.stopTest();
        }
    }
    
      
}