News UAT/force-app/main/default/objects/Account/fields/AdPoint_User_Id__c.field-meta.xml
<CustomField>
    <fullName>AdPoint_User_Id__c</fullName>
    <inlineHelpText>Identify who the owner should be in Adpoint from CRM. This uses the ESUC and updated on Account owner change. 5/3/14 - Webservice will send the owner of Adpoint accounts in Adpoint to be owned by Integration User due to Adpoint license issue.</inlineHelpText>
    <label>AdPoint User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (PrimaryContact)</relationshipLabel>
    <relationshipName>Accounts_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Print_Customer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Print_Customer_Tier__c</fullName>
    <defaultValue>(&quot;New Client&quot;)</defaultValue>
    <description>NextGen - For use with Print pricing discounts</description>
    <label>Print Customer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAA</fullName>
            </value>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>New Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Rolling_12_Months_Print__c.field-meta.xml
<CustomField>
    <fullName>Rolling_12_Months_Print__c</fullName>
    <description>Created by Rollup Helper</description>
    <label>Rolling 12 Months Print</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Xtend Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
                <default>true</default>
                <label>Tier 3</label>
            </value>
            <value>
                <fullName>Tier 0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account_Portfolio_Relationship__c/Account_Portfolio_Relationship__c.object-meta.xml
<CustomObject>
    <description>NextGen - Account portfolio relationship</description>
    <label>Account Portfolio Relationship</label>
    <nameField>
        <label>Account Portfolio Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Portfolio Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Account_Portfolio_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>NextGen</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Portfolio Relationships</relationshipLabel>
    <relationshipName>Account_Portfolio_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_System_Portfolio_Junction__c/Booking_System_Portfolio_Junction__c.object-meta.xml
<CustomObject>
    <label>Booking System - Portfolio Junction</label>
    <nameField>
        <label>Booking System - Portfolio Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking System - Portfolio Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking_System_Portfolio_Junction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking System - Portfolio Junctions</relationshipLabel>
    <relationshipName>Booking_System_Portfolio_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_System_Portfolio_Junction__c/fields/Booking_System_Account__c.field-meta.xml
<CustomField>
    <fullName>Booking_System_Account__c</fullName>
    <description>NextGen</description>
    <label>Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Booking System - Portfolio Junctions</relationshipLabel>
    <relationshipName>Booking_System_Portfolio_Junctions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/Booking_System_Account__c.field-meta.xml
<CustomField>
    <fullName>Booking_System_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Booking System Account for successful Credit Application</description>
    <label>Booking System Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>External_Account__c.Customer_Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/CyberAd_User_Credential__c/CyberAd_User_Credential__c.object-meta.xml
<CustomObject>
    <description>External System User Credentials</description>
    <label>External System User Credential</label>
    <nameField>
        <displayFormat>CyberAdCredential-{00000}</displayFormat>
        <label>CyberAd User Credential Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External System User Credentials</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/CyberAd_User_Credential__c/fields/AdPoint_User_Id__c.field-meta.xml
<CustomField>
    <fullName>AdPoint_User_Id__c</fullName>
    <externalId>true</externalId>
    <label>AdPoint User Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/CyberAd_User_Credential__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CyberAd_User_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/CyberAd_User_Credential__c/recordTypes/AdPoint.recordType-meta.xml
<RecordType>
    <fullName>AdPoint</fullName>
    <active>true</active>
    <description>AdPoint User Credentials</description>
    <label>AdPoint</label>
</RecordType>

News UAT/force-app/main/default/objects/External_Account__c/External_Account__c.object-meta.xml
<CustomObject>
    <description>Object to hold external accounts such as Billing and Booking Accounts</description>
    <label>Booking System Account</label>
    <nameField>
        <label>Booking System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking System Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/External_Account__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The External Account&#39;s parent Customer Account</description>
    <inlineHelpText>The External Account&#39;s parent Customer Account</inlineHelpText>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>External_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Rolling_12_Months_Print__c.field-meta.xml
<CustomField>
    <fullName>Rolling_12_Months_Print__c</fullName>
    <label>Rolling 12 Months Print</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/NextGen_User_Profile__mdt/NextGen_User_Profile__mdt.object-meta.xml
<CustomObject>
    <description>List of profile names for NextGen users</description>
    <label>NextGen User Profile</label>
    <pluralLabel>NextGen User Profiles</pluralLabel>
</CustomObject>

News UAT/force-app/main/default/objects/Opportunity/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <inlineHelpText>Who they are</inlineHelpText>
    <label>Segment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

News UAT/force-app/main/default/objects/Spend_Tier_Mapping__c/Spend_Tier_Mapping__c.object-meta.xml
<CustomObject>
    <label>Spend to Tier Mapping</label>
    <nameField>
        <displayFormat>STM-{000}</displayFormat>
        <label>Mapping</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spend to Tier Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Spend_Tier_Mapping__c/fields/Max_Spend__c.field-meta.xml
<CustomField>
    <fullName>Max_Spend__c</fullName>
    <defaultValue>999999999999999999</defaultValue>
    <description>To define a tier with no maximum spend use the value 999999999999999999 (i.e. 18 nines)</description>
    <inlineHelpText>To define a tier with no maximum spend use the value 999999999999999999 (i.e. 18 nines)</inlineHelpText>
    <label>Max Spend</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/Spend_Tier_Mapping__c/fields/Min_Spend__c.field-meta.xml
<CustomField>
    <fullName>Min_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Min Spend</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/Spend_Tier_Mapping__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Spend_Tier_Mapping__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Spend_Tier_Mapping__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/AccountManagement_Trigger_Helper.cls
/*---------------------------------------------------------
 * Author: Bohao Chen
 * Company: Salesforce.com
 * Description: This is helper class for trigger AccountManagement
 * History:
 * 20/12/2013  Bohao Chen  Created
 * 21/08/2018  Pratyush Chalasani (Ativa) - Updated to include Segment+Spend mapping to customer Tier
 * 30/10/2018  Pratyush Chalasani (Ativa) - Updated to prevent owner chang
 * Making Print as Case Insensitive. Changing tier.Platform__c == 'Print' to tier.Platform__c.equalsIgnoreCase('Print'): Refer to Jira: NR-1201.
 */
public class AccountManagement_Trigger_Helper
{

    // AdSales-121 2016-08-04 darshan.gosar@bluewolfgroup.com
        // Added new bypass flag to bypass account trigger execute while updating person account in after trigger
    public static boolean byPassAccountTrigger = false;
    
    // this function takes list of account owner ids in order to retrieve mapping 
    // between salesforce owner and adpoint user id
    public static Map<Id, String> findAdPointUserIdByAccountOwner(Set<Id> ownerIds)
    {
        system.debug('@AccountManagement_Trigger_Helper ownerIds: ' + ownerIds);
        
        
        Map<Id, String> adPointUserIdByOwnerId = new Map<Id, String>();
        
        for(CyberAd_User_Credential__c cred : [Select c.User__c, c.AdPoint_User_Id__c 
                                                From CyberAd_User_Credential__c c 
                                                Where c.User__c IN: ownerIds
                                                And c.RecordType.DeveloperName = 'AdPoint'])
        {
            adPointUserIdByOwnerId.put(cred.User__c, cred.AdPoint_User_Id__c);
        }
        
        system.debug('@AccountManagement_Trigger_Test findAdPointUserIdByAccountOwner: ' + adPointUserIdByOwnerId);
        
        return adPointUserIdByOwnerId;
    }
    
    // AdSales-121 2016-08-04 darshan.gosar@bluewolfgroup.com
        // Added new method to populate Person Contact Id on Primary Account field
    public static void updatePersonAccountPrimaryContact(List<Account> newTriggerList){
        List<Account> updateAccountList = new List<Account>();
         
        for(Account a : newTriggerList){
            if(a.IsPersonAccount != null && a.IsPersonAccount && a.Primary_Contact__c == null){
                Account tempAccount = a.clone(true,true,true);
                tempAccount.Primary_Contact__c = tempAccount.PersonContactId;
                updateAccountList.add(tempAccount);
            }   
        }
        
        if(updateAccountList.size() > 0){
            byPassAccountTrigger = true;            
            update updateAccountList;
            byPassAccountTrigger = false;
        }       
    }
    
    //NR-1679: When a portfolio is attached to a account record the account owner should be locked
    public static void preventOwnerChangeWhenPortfolioAttached(List<Account> accounts, Map<Id, Account> oldMap) {
       	Set<Account> ownerChangedAccounts = new Set<Account>();
        
        System.debug('Checking for owner change');
        
        for (Account acc: accounts) {
            Account old = oldMap.get(acc.Id);
            
            if (old != null && (acc.OwnerId != old.OwnerId)) ownerChangedAccounts.add(acc);
        }
        
        System.debug('Accounts with changed owners: ' + ownerChangedAccounts);
        
        if (!ownerChangedAccounts.isEmpty()) {
            Set<String> nextgenProfileNames = new Set<String>();
            
            for (NextGen_User_Profile__mdt prof: [SELECT Label FROM NextGen_User_Profile__mdt]) nextgenProfileNames.add(prof.Label);
            
            System.debug('NextGen profiles: ' + nextgenProfileNames);
            
            nextgenProfileNames.remove('System Administrator');
            nextgenProfileNames.remove('~System Administrator');
            nextgenProfileNames.remove('News Sales Operations');
            
            String userProfileName = [SELECT Name FROM Profile WHERE Id = :UserInfo.getProfileId()].Name;
            
            if (nextgenProfileNames.contains(userProfileName)) {
                Set<Id> accountsWithPortfolios = new Set<Id>();
                
                for (Account_Portfolio_Relationship__c rel: [SELECT Account__c FROM Account_Portfolio_Relationship__c WHERE Account__c IN :ownerChangedAccounts]) {
                    accountsWithPortfolios.add(rel.Account__c);
                }
                
                for (Booking_System_Portfolio_Junction__c rel: [SELECT Booking_System_Account__r.Customer_Account__c FROM Booking_System_Portfolio_Junction__c WHERE Booking_System_Account__r.Customer_Account__c IN :ownerChangedAccounts]) {
                    accountsWithPortfolios.add(rel.Booking_System_Account__r.Customer_Account__c);
                }
                
                for (Account acc: ownerChangedAccounts) {
                    if (accountsWithPortfolios.contains(acc.Id)) {
                    	acc.addError('Cannot change owner for an Account with an attached Opportunity. Please speak to your Ops manager.');
                    }
                }
            }
        }
    }
    
    /* NR-390: Customer Tier for Print includes Segment variation
     * 
     * Use an account's segment and rolling 12 months spend to determine it's tier
     * Making it case insensitive NR-1201
     */
    public static void setCustomerTier(List<Account> accounts) {
        Map<String, List<Spend_Tier_Mapping__c>> segmentTiers = new Map<String, List<Spend_Tier_Mapping__c>>();
        
        for (Spend_Tier_Mapping__c tier: [SELECT Segment__c, Platform__c, Min_Spend__c, Max_Spend__c, Tier__c FROM Spend_Tier_Mapping__c ORDER BY Min_Spend__c ASC, Max_Spend__c ASC]) {
            //addToMap(segmentTiers, tier.Segment__c, tier);
            addToMap(segmentTiers, tier.Segment__c.toLowerCase(), tier);
        }
        
        for (Account acc: accounts) {
            if (acc.Customer_Segment__c != null) {
                List<Spend_Tier_Mapping__c> tiers = segmentTiers.get(acc.Customer_Segment__c.toLowerCase());
                
                if (tiers != null) {
                    Decimal printSpend = acc.Rolling_12_Months_Print__c != null ? acc.Rolling_12_Months_Print__c : 0 ;
                    
                    for (Spend_Tier_Mapping__c tier: tiers) {
                        if (tier.Platform__c.equalsIgnoreCase('Print') && (printSpend >= tier.Min_Spend__c) && (printSpend <= tier.Max_Spend__c)) {
                            acc.Print_Customer_Tier__c = tier.Tier__c;
                        }
                    }
                }
            }
        }
    }
    
   private static void addToMap(Map<String, List<Spend_Tier_Mapping__c>> mapList, String key, Spend_Tier_Mapping__c value) {
        List<Spend_Tier_Mapping__c> values = mapList.get(key);
        
        if (values == null) values = new List<Spend_Tier_Mapping__c>();
        
        values.add(value);
        
        mapList.put(key, values);
    }
}