News UAT/force-app/main/default/objects/Account/fields/DPID_Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>DPID_Primary_Address__c</fullName>
    <label>DPID - Primary Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/No_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>No_Parent_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to override the Parent Account required field</inlineHelpText>
    <label>No Parent Account</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Revenue_Group__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Group__c</fullName>
    <inlineHelpText>Revenue Groups are based on the News Corp categorisations that are defined for budget and forecasting reporting. This field will feed into Opportunity and Booking information.</inlineHelpText>
    <label>Revenue Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amusements</fullName>
            </value>
            <value>
                <fullName>Employment</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle Dealers</fullName>
            </value>
            <value>
                <fullName>National (Communications/business equipment)</fullName>
            </value>
            <value>
                <fullName>National (Computers)</fullName>
            </value>
            <value>
                <fullName>National (Finance)</fullName>
            </value>
            <value>
                <fullName>National (Food and beverages)</fullName>
            </value>
            <value>
                <fullName>National (Gambling/gaming)</fullName>
            </value>
            <value>
                <fullName>National (Government/political)</fullName>
            </value>
            <value>
                <fullName>National (Media)</fullName>
            </value>
            <value>
                <fullName>National (Motor Vehicle Manufacturers)</fullName>
            </value>
            <value>
                <fullName>National (Other)</fullName>
            </value>
            <value>
                <fullName>National (Personal care products)</fullName>
            </value>
            <value>
                <fullName>National (Pharmaceutical / Health Products)</fullName>
            </value>
            <value>
                <fullName>National (Travel)</fullName>
            </value>
            <value>
                <fullName>Public Notices</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Total_Agency_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Agency_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Agency Spend - rolled up from all Bookings where the Agency is the Payer (YTD)</description>
    <inlineHelpText>Total Agency Spend - rolled up from all Bookings where the Agency is the Payer (YTD)</inlineHelpText>
    <label>Total Agency Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Total_Customer_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Customer_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Customer Spend - rolled up from Total Cost of all Bookings related to the Customer (YTD)</description>
    <inlineHelpText>Total Customer Spend - rolled up from Total Cost of all Bookings related to the Customer (YTD)</inlineHelpText>
    <label>Total Customer Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Total_Group_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Group_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Group Spend for the Customer/Agency Hierarchy (this Customer and all below) for all Bookings (YTD)</description>
    <inlineHelpText>Total Group Spend for the Customer/Agency Hierarchy (this Customer and all below) for all Bookings (YTD)</inlineHelpText>
    <label>Total Group Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Contact/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Created in Error</fullName>
            </value>
            <value>
                <fullName>Marked for Deletion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Contact/fields/DPID_Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>DPID_Primary_Address__c</fullName>
    <label>DPID Primary Address</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/NXX2_AccountListController_Test.cls
@isTest
private class NXX2_AccountListController_Test {
	
	@isTest static void test_method_one() {
        NXX2_TestUtility.disableAllTriggerDuringTesting();
		User currentUser = TestDataFactory.createUser('System Administrator','Test','Demo',null,false,false);
		System.runAs(currentUser){
			//Create portal account owner
			UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
			Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
			User portalAccountOwner1 = new User(
				UserRoleId = portalRole.Id,
				ProfileId = profile1.Id,
				Username = System.now().millisecond() + 'test2@test.com',
				Alias = 'batman',
				Email='bruce.wayne@wayneenterprises.com',
				EmailEncodingKey='UTF-8',
				Firstname='Bruce',
				Lastname='Wayne',
				LanguageLocaleKey='en_US',
				LocaleSidKey='en_US',
				TimeZoneSidKey='America/Chicago'
			);
			Database.insert(portalAccountOwner1);

			//Create account
			Account portalAccount1 = new Account(
				Name = 'TestAccount',
				OwnerId = portalAccountOwner1.Id,
				BillingPostalCode='2000',
				BillingCountry = 'Australia',
				BillingState = 'NSW',
				BillingCity = 'Sydney',
				BillingStreet = 'George Street',
				DPID_Primary_Address__c = '555',
				AccountNumber = '12345678901',
				Phone = '61021234567',
				Revenue_Group__c = 'Classified - Marketplace',
				No_Parent_Account__c = true,
				Total_Customer_Spend__c = 0,
				Total_Agency_Spend__c = 0,
				Total_Group_Spend__c = 0            
			);
			Database.insert(portalAccount1);
					
			//Create contact
			Contact contact1 = new Contact(
				FirstName = 'Test',
					Lastname = 'McTesty',
				AccountId = portalAccount1.Id,
					Email = System.now().millisecond() + 'test@test.com',
                Title = 'Test title',
                Contact_Status__c = 'Active'
			);
			Database.insert(contact1);
					
			//Create user
			Profile portalProfile = [SELECT Id FROM Profile WHERE Name LIKE '%NewsXtend My Account Community Read Only%' Limit 1];
			User user1 = new User(
				Username = System.now().millisecond() + 'test12345@test.com',
				ContactId = contact1.Id,
				ProfileId = portalProfile.Id,
				Alias = 'test123',
				Email = 'test12345@test.com',
				EmailEncodingKey = 'UTF-8',
				LastName = 'McTesty',
				CommunityNickname = 'test12345',
				TimeZoneSidKey = 'America/Los_Angeles',
				LocaleSidKey = 'en_US',
				LanguageLocaleKey = 'en_US'
			);
			insert(user1);

         system.debug('insert user1' +user1);
        
		AccountShare accountShare = new AccountShare();
		accountShare.AccountId = portalAccount1.Id;
		accountShare.UserOrGroupId=user1.Id;
		accountShare.OpportunityAccessLevel='Edit';
		accountShare.AccountAccessLevel='Edit';
		accountShare.CaseAccessLevel='Edit';
		insert accountShare;
		system.debug('insert accountShare' +accountShare);

		Test.startTest();
        NXX2_AccountListController.getAllAccessibleAccount(contact1.Id); 
		NXX2_AccountListController.getLoggedInUserContact();
		NXX2_AccountListController.getIconName('Account');
		NXX2_AccountListController.getAccountsListAccessibleToCustomer();
        Test.stopTest();
		}
	}
	
	
	
}