News UAT/force-app/main/default/objects/Account/fields/DPID_Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>DPID_Primary_Address__c</fullName>
    <label>DPID - Primary Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/No_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>No_Parent_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to override the Parent Account required field</inlineHelpText>
    <label>No Parent Account</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Revenue_Group__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Group__c</fullName>
    <inlineHelpText>Revenue Groups are based on the News Corp categorisations that are defined for budget and forecasting reporting. This field will feed into Opportunity and Booking information.</inlineHelpText>
    <label>Revenue Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amusements</fullName>
            </value>
            <value>
                <fullName>Employment</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle Dealers</fullName>
            </value>
            <value>
                <fullName>National (Communications/business equipment)</fullName>
            </value>
            <value>
                <fullName>National (Computers)</fullName>
            </value>
            <value>
                <fullName>National (Finance)</fullName>
            </value>
            <value>
                <fullName>National (Food and beverages)</fullName>
            </value>
            <value>
                <fullName>National (Gambling/gaming)</fullName>
            </value>
            <value>
                <fullName>National (Government/political)</fullName>
            </value>
            <value>
                <fullName>National (Media)</fullName>
            </value>
            <value>
                <fullName>National (Motor Vehicle Manufacturers)</fullName>
            </value>
            <value>
                <fullName>National (Other)</fullName>
            </value>
            <value>
                <fullName>National (Personal care products)</fullName>
            </value>
            <value>
                <fullName>National (Pharmaceutical / Health Products)</fullName>
            </value>
            <value>
                <fullName>National (Travel)</fullName>
            </value>
            <value>
                <fullName>Public Notices</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Mark for Duplication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Total_Agency_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Agency_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Agency Spend - rolled up from all Bookings where the Agency is the Payer (YTD)</description>
    <inlineHelpText>Total Agency Spend - rolled up from all Bookings where the Agency is the Payer (YTD)</inlineHelpText>
    <label>Total Agency Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Total_Customer_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Customer_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Customer Spend - rolled up from Total Cost of all Bookings related to the Customer (YTD)</description>
    <inlineHelpText>Total Customer Spend - rolled up from Total Cost of all Bookings related to the Customer (YTD)</inlineHelpText>
    <label>Total Customer Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Total_Group_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Group_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Group Spend for the Customer/Agency Hierarchy (this Customer and all below) for all Bookings (YTD)</description>
    <inlineHelpText>Total Group Spend for the Customer/Agency Hierarchy (this Customer and all below) for all Bookings (YTD)</inlineHelpText>
    <label>Total Group Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Contact/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Created in Error</fullName>
            </value>
            <value>
                <fullName>Marked for Deletion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Contact/fields/DPID_Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>DPID_Primary_Address__c</fullName>
    <label>DPID Primary Address</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/Customer_Task__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Customer Activity</label>
    <nameField>
        <displayFormat>CAN-{YYMMDD}-{0000}</displayFormat>
        <label>Customer Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Activities</relationshipLabel>
    <relationshipName>Customer_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>With Client</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
                <isActive>false</isActive>
                <label>In Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Revenue_Group__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Group__c</fullName>
    <description>Revenue Group for the Opportunity - defaulted to the Account&#39;s Revenue Group.
If Revenue Group options change - also update the &#39;Revenue Group L1&#39; dependant formula field.</description>
    <label>Revenue Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amusements</fullName>
            </value>
            <value>
                <fullName>Employment</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle Dealers</fullName>
            </value>
            <value>
                <fullName>National (Communications/business equipment)</fullName>
            </value>
            <value>
                <fullName>National (Computers)</fullName>
            </value>
            <value>
                <fullName>National (Finance)</fullName>
            </value>
            <value>
                <fullName>National (Food and beverages)</fullName>
            </value>
            <value>
                <fullName>National (Gambling/gaming)</fullName>
            </value>
            <value>
                <fullName>National (Government/political)</fullName>
            </value>
            <value>
                <fullName>National (Media)</fullName>
            </value>
            <value>
                <fullName>National (Motor Vehicle Manufacturers)</fullName>
            </value>
            <value>
                <fullName>National (Other)</fullName>
            </value>
            <value>
                <fullName>National (Personal care products)</fullName>
            </value>
            <value>
                <fullName>National (Pharmaceutical / Health Products)</fullName>
            </value>
            <value>
                <fullName>National (Travel)</fullName>
            </value>
            <value>
                <fullName>Public Notices</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>CASE(TEXT(StageName),
  &quot;Identify Prospects&quot;, &quot;Open&quot;,
  &quot;Establish Rapport&quot;, &quot;Open&quot;,
  &quot;Qualify Opportunity&quot;, &quot;Open&quot;,
  &quot;Select Product(s) and Update Stage&quot;, &quot;Open&quot;,
  &quot;Develop Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Present Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Re-affirm Value/ Negotiate&quot;, &quot;Open&quot;,
  &quot;Awaiting Bookings&quot;, &quot;Open&quot;,
  &quot;Closed Won&quot;, &quot;Closed Won&quot;,
  &quot;Closed Lost&quot;, &quot;Closed Lost&quot;,
  &quot;Err: Invalid stage name&quot;
)</formula>
    <inlineHelpText>Field to allow reporting on Win/ Lost vs Open. Do not display on page layouts.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Fulfilment Ready</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Campaign Live</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Order__r.Account__r.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/SocialCampaign__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Proof</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proofs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/SocialCampaign__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Social_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/classes/NXX2_CustomerActivitiesListCntrl_Test.cls
@isTest
private class NXX2_CustomerActivitiesListCntrl_Test {
	
	static testMethod void testcCustomerActivitiesList(){
        NXX2_TestUtility.disableAllTriggerDuringTesting();
		User currentUser = TestDataFactory.createUser('System Administrator','Test','Demo',null,false,false);
		System.runAs(currentUser){
			UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
			Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
			User portalAccountOwner1 = new User(
				UserRoleId = portalRole.Id,
				ProfileId = profile1.Id,
				Username = System.now().millisecond() + 'test2@test.com',
				Alias = 'batman',
				Email='test@testSalesforce.com',
				EmailEncodingKey='UTF-8',
				Firstname='Bruce',
				Lastname='Wayne',
				LanguageLocaleKey='en_US',
				LocaleSidKey='en_US',
				TimeZoneSidKey='America/Chicago'
			);
			Database.insert(portalAccountOwner1);
			Account portalAccount1 = new Account(
				Name = 'TestAccount',
				OwnerId = portalAccountOwner1.Id,
				BillingPostalCode='2000',
				BillingCountry = 'Australia',
				BillingState = 'NSW',
				BillingCity = 'Sydney',
				BillingStreet = 'George Street',
				DPID_Primary_Address__c = '555',
				AccountNumber = '12345678901',
				Phone = '61021234567',
				Revenue_Group__c = 'Classified - Marketplace',
				No_Parent_Account__c = true,
				Total_Customer_Spend__c = 0,
				Total_Agency_Spend__c = 0,
				Total_Group_Spend__c = 0            
			);
			Database.insert(portalAccount1);
			Account portalAccount2 = new Account(
				Name = 'TestAccount',
				OwnerId = portalAccountOwner1.Id,
				BillingPostalCode='2000',
				BillingCountry = 'Australia',
				BillingState = 'NSW',
				BillingCity = 'Sydney',
				BillingStreet = 'George Street',
				DPID_Primary_Address__c = '555',
				AccountNumber = '12345678901',
				Phone = '61021234567',
				Revenue_Group__c = 'Classified - Marketplace',
				No_Parent_Account__c = true,
				Total_Customer_Spend__c = 0,
				Total_Agency_Spend__c = 0,
				Total_Group_Spend__c = 0            
			);
			Database.insert(portalAccount2);
			Contact contact1 = new Contact(
				FirstName = 'Test',
				Lastname = 'McTesty',
				AccountId = portalAccount1.Id,
				Email = System.now().millisecond() + 'test@test.com',
                Title = 'Test title',
                Contact_Status__c = 'Active',
				NewsXtend_My_Account_Access__c=true
			);
			Database.insert(contact1);
			Profile portalProfile = [SELECT Id FROM Profile WHERE Name LIKE '%NewsXtend My Account Community Read Only%' Limit 1];
            User user1 = new User(
				Username = System.now().millisecond() + 'test12345@test.com',
				ContactId = contact1.Id,
				ProfileId = portalProfile.Id,
				Alias = 'test123',
				Email = 'test12345@test.com',
				EmailEncodingKey = 'UTF-8',
				LastName = 'McTesty',
				CommunityNickname = 'test12345',
				TimeZoneSidKey = 'America/Los_Angeles',
				LocaleSidKey = 'en_US',
				LanguageLocaleKey = 'en_US'
			);
			insert(user1);
			AccountShare accountShare = new AccountShare();
			accountShare.AccountId = portalAccount1.Id;
			accountShare.UserOrGroupId=user1.Id;
			accountShare.OpportunityAccessLevel='Edit';
			accountShare.AccountAccessLevel='Edit';
			accountShare.CaseAccessLevel='Edit';
			insert accountShare;
			List<Opportunity> opportunities = TestDataFactory.createOpportunities_withContact(1,Test.getStandardPricebookId(),portalAccount1,contact1);
            opportunities.get(0).Payer_Account__c = portalAccount2.Id;
			insert opportunities;
			Order__c campaignOrder = new Order__c();
			campaignOrder.Opportunity__c = opportunities[0].Id;
			campaignOrder.Campaign_Customer_Contact__c = contact1.id; 
			campaignOrder.Account__c = portalAccount1.id; 
			insert campaignOrder;
			Product_Order__c productOrder;
			List<Product_Order__c> orders = new List<Product_Order__c>();
			for(Integer i = 0; i < 2; i++){
				productOrder = new Product_Order__c();
				productOrder.Order__c = campaignOrder.id;
				productOrder.Status__c = 'In Progress';
				orders.add(productOrder);
			}
			insert orders;
            SocialCampaign__c socialCampaignForApproved = NXX2_TestUtility.createProof(orders[0].Id);
            SocialCampaign__c socialCampaignForRequestChange = NXX2_TestUtility.createProof(orders[1].Id); 
			SocialCampaign__c socialCampaignForWithCustomer = NXX2_TestUtility.createProof(orders[1].Id); 
            List<SocialCampaign__c> proofsForSocial = new List<SocialCampaign__c>();
            proofsForSocial.add(socialCampaignForApproved);
            proofsForSocial.add(socialCampaignForRequestChange);
            proofsForSocial.add(socialCampaignForWithCustomer);
            List<Customer_Task__c> customerActivity = NXX2_TestUtility.createCustomerActivity(proofsForSocial);
			List<Order__c> campaignOrderList= new List<Order__c>();
			campaignOrderList.add(campaignOrder);
            Test.startTest();
            NXX2_CustomerActivitiesListController.fetchCustomerTask(proofsForSocial.get(0).Id,'SocialCampaign__c',true);
			NXX2_CustomerActivitiesListController.fetchCustomerTask(orders.get(0).Id,'Product_Order__c',true);
			NXX2_CustomerActivitiesListController.fetchCustomerTask(campaignOrderList.get(0).Id,'Order__c',true);
			NXX2_CustomerActivitiesListController.updateCustomerTaskStatus(customerActivity.get(0).Id);
			NXX2_CustomerActivitiesListController.getIconName('Customer_Task__c');
			NXX2_CustomerActivitiesListController.fetchLoggedInUsersDetails();
			NXX2_CustomerActivitiesListController.getCustomerActivityRecordTypeForProof();
			NXX2_CustomerActivitiesListController.getAllCommentsLinkedToType();
			NXX2_CustomerActivitiesListController.getAllAccessibleAccountCustomerTask(contact1.id);
            
            Test.stopTest();  
		}
	}
}