News UAT/force-app/main/default/objects/Account/fields/DPID_Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>DPID_Primary_Address__c</fullName>
    <label>DPID - Primary Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Last_Client_Engagement__c.field-meta.xml
<CustomField>
    <fullName>Last_Client_Engagement__c</fullName>
    <description>Indicates the last interaction (call or appointment) with this customer</description>
    <inlineHelpText>Indicates the last interaction (call or appointment) with this customer</inlineHelpText>
    <label>Last Client Engagement</label>
    <type>DateTime</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/No_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>No_Parent_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to override the Parent Account required field</inlineHelpText>
    <label>No Parent Account</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Revenue_Group__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Group__c</fullName>
    <inlineHelpText>Revenue Groups are based on the News Corp categorisations that are defined for budget and forecasting reporting. This field will feed into Opportunity and Booking information.</inlineHelpText>
    <label>Revenue Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amusements</fullName>
            </value>
            <value>
                <fullName>Employment</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle Dealers</fullName>
            </value>
            <value>
                <fullName>National (Communications/business equipment)</fullName>
            </value>
            <value>
                <fullName>National (Computers)</fullName>
            </value>
            <value>
                <fullName>National (Finance)</fullName>
            </value>
            <value>
                <fullName>National (Food and beverages)</fullName>
            </value>
            <value>
                <fullName>National (Gambling/gaming)</fullName>
            </value>
            <value>
                <fullName>National (Government/political)</fullName>
            </value>
            <value>
                <fullName>National (Media)</fullName>
            </value>
            <value>
                <fullName>National (Motor Vehicle Manufacturers)</fullName>
            </value>
            <value>
                <fullName>National (Other)</fullName>
            </value>
            <value>
                <fullName>National (Personal care products)</fullName>
            </value>
            <value>
                <fullName>National (Pharmaceutical / Health Products)</fullName>
            </value>
            <value>
                <fullName>National (Travel)</fullName>
            </value>
            <value>
                <fullName>Public Notices</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Total_Agency_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Agency_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Agency Spend - rolled up from all Bookings where the Agency is the Payer (YTD)</description>
    <inlineHelpText>Total Agency Spend - rolled up from all Bookings where the Agency is the Payer (YTD)</inlineHelpText>
    <label>Total Agency Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Total_Customer_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Customer_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Customer Spend - rolled up from Total Cost of all Bookings related to the Customer (YTD)</description>
    <inlineHelpText>Total Customer Spend - rolled up from Total Cost of all Bookings related to the Customer (YTD)</inlineHelpText>
    <label>Total Customer Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Total_Group_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Group_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Group Spend for the Customer/Agency Hierarchy (this Customer and all below) for all Bookings (YTD)</description>
    <inlineHelpText>Total Group Spend for the Customer/Agency Hierarchy (this Customer and all below) for all Bookings (YTD)</inlineHelpText>
    <label>Total Group Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/classes/AT_LastClientEngagement_Test.cls
@isTest
private class AT_LastClientEngagement_Test {
	
 private static testMethod void setupTestData(){


        Integer recordsToCreate = 20, ii=0;
        Boolean isPersonAccount = false;
                List<Account> accList = new List<Account>();
     /*Creating / Inserting Account Data*/
     
        for ( Integer i = 0 ; i < recordsToCreate ; i++ ) {
            Account tmpAccount = new Account();
                tmpAccount.Name = 'Test Account ' + String.valueOf(i);
                tmpAccount.BillingPostalCode='2000';
                tmpAccount.BillingCountry = 'Australia';
                tmpAccount.BillingState = 'NSW';
                tmpAccount.BillingCity = 'Sydney';
                tmpAccount.BillingStreet = 'George Street';
                tmpAccount.DPID_Primary_Address__c = '555' + String.valueOf(i);
                tmpAccount.AccountNumber = '12345678901';
                tmpAccount.Phone = '61021234567' + String.valueOf(i);
                tmpAccount.Revenue_Group__c = 'Classified - Marketplace';
                tmpAccount.No_Parent_Account__c = true;
            tmpAccount.Total_Customer_Spend__c = 0;
            tmpAccount.Total_Agency_Spend__c = 0;
            tmpAccount.Total_Group_Spend__c = 0;
            tmpAccount.Last_Client_Engagement__c = System.now().addDays(-10);
            
            accList.add( tmpAccount);            
        }

	    insert accList;
	    
     /*Creating / Inserting Event Data*/
	    List <Event> eve = new List <Event>();
	    for (Integer i=0; i<recordsToCreate; i++){
	    Event event_temp = new Event();
	        event_temp.Description = 'Test Description '+i;
            event_temp.ShowAs = 'Busy';
            event_temp.Subject = 'Test Subject '+i;
            event_temp.IsReminderSet = false;
            event_temp.IsPrivate = false;
            event_temp.StartDateTime = System.now().addDays(-2);
            event_temp.EndDateTime = System.now().addDays(-1);
            event_temp.whatID = accList[i].id;
            eve.add(event_temp);
	    }
	    insert eve;

     /*Starting Test*/
     	Test.startTest();
     
          /*Running Batch Process*/
        Database.executeBatch(new AT_LastClientEngagementBatchProcess());
     
          /*Stopping Test to Commit Changes Before Proceeding Further*/
     	Test.stopTest();
     
          /*Asserting Changes Post Batch Run to Compare the End Date of Event with Last Client Engagement Date*/
     	List < Account > accList_new = new List <Account>([Select id, name, Last_client_engagement__c from account order by id asc]);
        for (Account acc: accList_new){
             System.assertEquals(acc.Last_client_engagement__c, eve[ii].EndDateTime);
             ii++;
         }
     
     }
    
}