News UAT/force-app/main/default/objects/Account/fields/Industry_Code__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Industry Codes are imported from the ANSIC standard of Industry Codes. It is periodically maintained and the information in this field will feed into Opportunities and Bookings.</inlineHelpText>
    <label>Industry</label>
    <referenceTo>Industry_Code__c</referenceTo>
    <relationshipLabel>Accounts_IndustryCodes</relationshipLabel>
    <relationshipName>Accounts_Industry</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Revenue_Group__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Group__c</fullName>
    <inlineHelpText>Revenue Groups are based on the News Corp categorisations that are defined for budget and forecasting reporting. This field will feed into Opportunity and Booking information.</inlineHelpText>
    <label>Revenue Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amusements</fullName>
            </value>
            <value>
                <fullName>Employment</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle Dealers</fullName>
            </value>
            <value>
                <fullName>National (Communications/business equipment)</fullName>
            </value>
            <value>
                <fullName>National (Computers)</fullName>
            </value>
            <value>
                <fullName>National (Finance)</fullName>
            </value>
            <value>
                <fullName>National (Food and beverages)</fullName>
            </value>
            <value>
                <fullName>National (Gambling/gaming)</fullName>
            </value>
            <value>
                <fullName>National (Government/political)</fullName>
            </value>
            <value>
                <fullName>National (Media)</fullName>
            </value>
            <value>
                <fullName>National (Motor Vehicle Manufacturers)</fullName>
            </value>
            <value>
                <fullName>National (Other)</fullName>
            </value>
            <value>
                <fullName>National (Personal care products)</fullName>
            </value>
            <value>
                <fullName>National (Pharmaceutical / Health Products)</fullName>
            </value>
            <value>
                <fullName>National (Travel)</fullName>
            </value>
            <value>
                <fullName>Public Notices</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account/recordTypes/IMA.recordType-meta.xml
<RecordType>
    <fullName>IMA</fullName>
    <active>true</active>
    <description>Independent Agencies &amp; Major Accounts team</description>
    <label>IMA</label>
</RecordType>

News UAT/force-app/main/default/objects/Account/recordTypes/KAC.recordType-meta.xml
<RecordType>
    <fullName>KAC</fullName>
    <active>true</active>
    <description>Key Accounts &amp; Consortium team</description>
    <label>KAC</label>
</RecordType>

News UAT/force-app/main/default/objects/Account/recordTypes/SME.recordType-meta.xml
<RecordType>
    <fullName>SME</fullName>
    <active>true</active>
    <description>Small to Medium Enterprises team</description>
    <label>SME</label>
</RecordType>

News UAT/force-app/main/default/objects/Activity/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <description>@NXRIII-75</description>
    <formula>Campaign_Order__r.Sales_Order__r.Name_of_Sales_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/Revenue_Group__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Group__c</fullName>
    <formula>TEXT(Opportunity__r.Revenue_Group__c)</formula>
    <label>Revenue Group</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales Order related to the Case</description>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Case/recordTypes/Referral.recordType-meta.xml
<RecordType>
    <fullName>Referral</fullName>
    <active>true</active>
    <businessProcess>Referral</businessProcess>
    <description>Request to action a Customer referral between Field Sales and Direct Sales</description>
    <label>Referral</label>
</RecordType>

News UAT/force-app/main/default/objects/Opportunity/fields/Industry_Code__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Code</label>
    <referenceTo>Industry_Code__c</referenceTo>
    <relationshipLabel>Opportunities_IndustryCode</relationshipLabel>
    <relationshipName>Opportunities_IndustryCode</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agreement Negotiation</fullName>
            </value>
            <value>
                <fullName>Brief</fullName>
            </value>
            <value>
                <fullName>Historical</fullName>
            </value>
            <value>
                <fullName>Late Space</fullName>
            </value>
            <value>
                <fullName>Multi-Channel</fullName>
            </value>
            <value>
                <fullName>Proactive</fullName>
            </value>
            <value>
                <fullName>Promotions</fullName>
            </value>
            <value>
                <fullName>Self Service</fullName>
            </value>
            <value>
                <fullName>xxxxxxxxxxxxxTarget</fullName>
            </value>
            <value>
                <fullName>Walk-In</fullName>
            </value>
            <value>
                <fullName>Walk-In Forecast</fullName>
            </value>
            <value>
                <fullName>NLM Proactive</fullName>
            </value>
            <value>
                <fullName>NLM Brief</fullName>
            </value>
            <value>
                <fullName>Trade Marketing</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>NLM Trade Marketing</fullName>
            </value>
            <value>
                <fullName>NLM Management</fullName>
            </value>
            <value>
                <fullName>ADM/ASM Referral</fullName>
            </value>
            <value>
                <fullName>Existing customer - new business</fullName>
            </value>
            <value>
                <fullName>Existing customer - renewal</fullName>
            </value>
            <value>
                <fullName>New customer</fullName>
            </value>
            <value>
                <fullName>Transactional YoY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Payer_Account__c.field-meta.xml
<CustomField>
    <fullName>Payer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payer Account</relationshipLabel>
    <relationshipName>Opportunities_Payer</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Reason_Won_Lost__c.field-meta.xml
<CustomField>
    <fullName>Reason_Won_Lost__c</fullName>
    <label>Reason Won/Lost</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alternative Media</fullName>
            </value>
            <value>
                <fullName>Below the Line</fullName>
            </value>
            <value>
                <fullName>Editorial</fullName>
            </value>
            <value>
                <fullName>Inventory Limitation</fullName>
            </value>
            <value>
                <fullName>Lack of Colour</fullName>
            </value>
            <value>
                <fullName>Masthead Reputation</fullName>
            </value>
            <value>
                <fullName>No budget</fullName>
            </value>
            <value>
                <fullName>Positioning</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Product/Environment</fullName>
            </value>
            <value>
                <fullName>Reach</fullName>
            </value>
            <value>
                <fullName>Relationship</fullName>
            </value>
            <value>
                <fullName>Response Rate %</fullName>
            </value>
            <value>
                <fullName>Share of Voice</fullName>
            </value>
            <value>
                <fullName>Synergy Lost</fullName>
            </value>
            <value>
                <fullName>Target audience</fullName>
            </value>
            <value>
                <fullName>Timing</fullName>
            </value>
            <value>
                <fullName>Track Record</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Created In Error</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Client Objective</fullName>
            </value>
            <value>
                <fullName>Audience</fullName>
            </value>
            <value>
                <fullName>Connection</fullName>
            </value>
            <value>
                <fullName>Platform</fullName>
            </value>
            <value>
                <fullName>Impact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Revenue_Group__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Group__c</fullName>
    <description>Revenue Group for the Opportunity - defaulted to the Account&#39;s Revenue Group.
If Revenue Group options change - also update the &#39;Revenue Group L1&#39; dependant formula field.</description>
    <label>Revenue Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amusements</fullName>
            </value>
            <value>
                <fullName>Employment</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle Dealers</fullName>
            </value>
            <value>
                <fullName>National (Communications/business equipment)</fullName>
            </value>
            <value>
                <fullName>National (Computers)</fullName>
            </value>
            <value>
                <fullName>National (Finance)</fullName>
            </value>
            <value>
                <fullName>National (Food and beverages)</fullName>
            </value>
            <value>
                <fullName>National (Gambling/gaming)</fullName>
            </value>
            <value>
                <fullName>National (Government/political)</fullName>
            </value>
            <value>
                <fullName>National (Media)</fullName>
            </value>
            <value>
                <fullName>National (Motor Vehicle Manufacturers)</fullName>
            </value>
            <value>
                <fullName>National (Other)</fullName>
            </value>
            <value>
                <fullName>National (Personal care products)</fullName>
            </value>
            <value>
                <fullName>National (Pharmaceutical / Health Products)</fullName>
            </value>
            <value>
                <fullName>National (Travel)</fullName>
            </value>
            <value>
                <fullName>Public Notices</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/recordTypes/IMA.recordType-meta.xml
<RecordType>
    <fullName>IMA</fullName>
    <active>true</active>
    <businessProcess>NextGen</businessProcess>
    <description>Independent Agencies &amp; Major Accounts team</description>
    <label>IMA</label>
</RecordType>

News UAT/force-app/main/default/objects/Opportunity/recordTypes/KAC.recordType-meta.xml
<RecordType>
    <fullName>KAC</fullName>
    <active>true</active>
    <businessProcess>NextGen</businessProcess>
    <description>Key Accounts &amp; Consortium team</description>
    <label>KAC</label>
</RecordType>

News UAT/force-app/main/default/objects/Opportunity/recordTypes/SME.recordType-meta.xml
<RecordType>
    <fullName>SME</fullName>
    <active>true</active>
    <businessProcess>NextGen</businessProcess>
    <description>Small to Medium Enterprises team</description>
    <label>SME</label>
</RecordType>

News UAT/force-app/main/default/objects/OpportunityLineItem/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales Order</description>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Shell Order encompassing Booking(s) - to be related to an Opportunity Product/s</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{0000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Advertiser_Account__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advertiser Account</description>
    <label>Advertiser Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders_Advertiser</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Payer_Account__c.field-meta.xml
<CustomField>
    <fullName>Payer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payer Account</description>
    <inlineHelpText>Payer – The account that pays for the advertising.</inlineHelpText>
    <label>Payer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders (Payer Account)</relationshipLabel>
    <relationshipName>Sales_Orders_Payer</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>Booking Source System</description>
    <label>Booking System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cyber$ell</fullName>
                <default>true</default>
                <label>Cyber$ell</label>
            </value>
            <value>
                <fullName>CyberAd</fullName>
            </value>
            <value>
                <fullName>AdPoint</fullName>
            </value>
            <value>
                <fullName>OSCA</fullName>
            </value>
            <value>
                <fullName>NewsAdds</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/Opportunity_Helper.cls
public with sharing class Opportunity_Helper 
{
    public static Map<String, Opportunity> createOpportunitFromSalesOrder(Map<Id, Sales_Order__c> salesOrderById)
    {
        Map<String, Opportunity> opportunityBySalesOrderId = new Map<String, Opportunity>();
        
        system.debug('@ createOpportunitFromSalesOrder()');
        List<Opportunity> opportunities = new List<Opportunity>();

        for(String salesOrderId : salesOrderById.keySet())
        {
            Sales_Order__c so = salesOrderById.get(salesOrderId);
            Opportunity opportunity = new Opportunity();
            
            if(so.Source_System__c == 'OSCA' || so.Source_System__c == 'CampaignTrack') // added by Tim Fabros 18 / 07 / 2014 - SFE added CampaignTrack to logic
            {
                opportunity.Opportunity_Type__c = 'Self Service'; ///???
                opportunity.Payer_Account__c = so.Payer_Account__r.id;
                opportunity.AccountId = so.Advertiser_Account__r.id;
                opportunity.recordTypeId = getRecordTypeIdByName(opportunity.Opportunity_Type__c, 'Opportunity');
                opportunity.name = 'OSCA - ' + so.Advertiser_Account__r.Name + ' - ' + system.today().year() + system.today().month() + system.today().day();
                opportunity.type = 'Non-Core Activity';
                opportunity.Revenue_Group__c = so.Advertiser_Account__r.Revenue_Group__c;
                opportunity.Industry_Code__c = so.Advertiser_Account__r.Industry_Code__c;
                opportunity.Description = salesOrderId; // sales order id in description is to find opportunity based on sales order id
                opportunity.StageName = 'Closed Won';
                opportunity.CloseDate = Date.today();
                //ND 10/04 set amount to avoid validation on closed won opportunity
                opportunity.Amount = 0;
                opportunity.CloseDate = Date.today();
            }

            // added by Tim Fabros 18 / 07 / 2014 - SFE
            // added logic for campaign track to
            // change the opportunity type and name
            // BEGIN:
            if(so.Source_System__c == 'CampaignTrack')
            {
                opportunity.Opportunity_Type__c = 'Walk-In';
                opportunity.name = 'CampaignTrack - ' + so.Advertiser_Account__r.Name + ' - ' + system.today().year() + system.today().month() + system.today().day();
            }
            // END:
            
            if(opportunity.Opportunity_Type__c == 'Self Service')
            {
                opportunity.StageName = 'Closed Won'; 
                opportunity.Probability = 100;
                opportunity.Reason_Won_Lost__c = 'Other';
                opportunity.CloseDate = system.today();
                opportunity.Campaign_Start_Date__c = system.today();
            }

            // 2017-05-22 Item-00282 louis.wang@bluewolf.com - Opportunity created by SalesOrder trigger will skip the conditional mandatory Contact validation rule.
            opportunity.BypassContactValidation__c = true;
            
            opportunityBySalesOrderId.put(salesOrderId, opportunity);
        }
        
		try{
        	insert opportunityBySalesOrderId.values();
		}
        catch(Exception ex)
        {
            system.assert(false, ex.getMessage());
            ExLog.log(ex, 'config', opportunityBySalesOrderId.values(), 'SFE-824 Investigation');
        }
         
        system.debug('====BC: opportunityBySalesOrderId=== ' + opportunityBySalesOrderId);
        
        return opportunityBySalesOrderId;
    }
    
    private static Map<String, Map<String, RecordType>> bySobjectAndRecordTypeName
    {
        get{ return bySobjectAndRecordTypeName = bySobjectAndRecordTypeName == null ? new Map<String, Map<String, RecordType>>() : bySobjectAndRecordTypeName; }
        set;
    }
    
    private static String getRecordTypeIdByName(String recordTypeName, String sObjectType)
    {
        String recordTypeId;
        Id rtId = null; 
        if(recordTypeName != null && sObjectType != null && (!bySobjectAndRecordTypeName.containsKey(sObjectType) || !bySobjectAndRecordTypeName.get(sObjectType).containsKey(recordTypeName)))
        {
            getRecordObjectMap (sObjectType);
        }

        if(bySobjectAndRecordTypeName.get(sObjectType).containsKey(recordTypeName))
        {   
            rtId = bySobjectAndRecordTypeName.get(sObjectType).get(recordTypeName).Id;
        }

        return rtId;
    }
    
    private static void getRecordObjectMap (String s)
    {
        Map<String,RecordType> rtObj = new Map<String,RecordType>();      

        for(RecordType rt : [Select r.Id, r.Name From RecordType r where r.SobjectType =: s])
        {
            rtObj.put(rt.name, rt);
        }

        if(rtObj.size()>0)
        {
            bySobjectAndRecordTypeName.put(s, rtObj);
        }

    }
    // updated by Bohao Chen on 6/6/2014 for JIRA SFE-498
    // Begin
    public static void populateCaseWithOpportunityId(Map<Id, List<Id>> opportunityIdsByCaseId)
    {
        if(opportunityIdsByCaseId != null && !opportunityIdsByCaseId.isEmpty())
        {
            List<Case> cases = new List<Case>();
            for(Case c : [Select Id, Opportunity__c, RecordType.Name From Case Where Id IN: opportunityIdsByCaseId.keySet()])
            {
                if(c.RecordType.Name == 'Referral')
                {
                    c.Opportunity__c = opportunityIdsByCaseId.get(c.Id)[0];
                    cases.add(c);                    
                }
            }
            try{
            	update cases;
            }
            catch(Exception ex)
	        {
	            ExLog.log(ex, 'config', cases, 'SFE-824 Investigation');
	        }
        }
    }
    // End
    
    //REVENUE REPORTING 
    public static Void rollupTriggerOpportunityLineItem(Set<Id> opIds){
        List<OpportunityLineItem> oliList = new List<OpportunityLineItem>([SELECT Id, RollupTrigger__c FROM OpportunityLineItem WHERE OpportunityId IN :opIds]);
    	for(OpportunityLineItem oli :oliList){
            oli.RollupTrigger__c = true;
        }
        try{
        	update oliList;
        }
        catch(Exception ex)
        {
            ExLog.log(ex, 'config', oliList, 'SFE-824 Investigation');
        }
    }
	////END REVENUE REPORTING
    
 //   /**
 //   * @description  creates a case if the related account has not been credit checked
 //   *               (before insert)
 //   *
 //   * @date         2017-10-20
 //   * @author       Tim Fabros
 //   **/
 //   public static void createCreditCheckCase(List<Opportunity> newOpptys) {

 //       Set<Id> recordTypeIds = new Set<Id>();
 //       recordTypeIds.add(Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('SME').getRecordTypeId());
 //       recordTypeIds.add(Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('KAC').getRecordTypeId());
 //       recordTypeIds.add(Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('IMA').getRecordTypeId());
        
 //       Set<Id> accountIds = new Set<Id>();

 //       for (Opportunity newOpp : newOpptys) {
 //           if (recordTypeIds.contains(newOpp.RecordtypeId) && newOpp.StageName == 'Discover Needs') {

 //               accountIds.add(newOpp.AccountId);
 //           }
 //       }

 //       if (accountIds.isEmpty()) { return; }

 //       List<Account> accounts = [SELECT Id FROM Account WHERE Id IN :accountIds AND Has_Credit_Checked__c = false];

 //       Group financeQueue = [SELECT Id FROM Group WHERE Name = 'Finance' AND Type = 'Queue'];

 //       List<Case> creditCases = new List<Case>();

 //       for (Account account : accounts) {

 //           account.Credit_Status__c = 'Pending';

 //           Case creditCase = new Case();

 //           creditCase.AccountId = account.Id;
 //           creditCase.RecordtypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Credit Check').getRecordTypeId();
 //           creditCase.OwnerId = financeQueue.Id;

 //           creditCases.add(creditCase);
 //       }

 //       System.debug(LoggingLevel.ERROR, '@creditCases: ' + creditCases);

 //       if (creditCases.isEmpty()) { return; }
            
 //       insert creditCases;
 //       update accounts;

 //   }
}