News UAT/force-app/main/default/objects/Account/fields/Last_Booking_Number__c.field-meta.xml
<CustomField>
    <fullName>Last_Booking_Number__c</fullName>
    <description>Booking number the latest booking record rolled up to the account.</description>
    <label>Last Booking Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Mark for Duplication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Bookings related to Bookings in Cyber$ell (Genera), CyberAd, or Digital Booking Systems</description>
    <label>Booking</label>
    <nameField>
        <label>Booking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking__c/fields/Account_No__c.field-meta.xml
<CustomField>
    <fullName>Account_No__c</fullName>
    <formula>Sales_Order__r.External_Account__r.Account_No__c</formula>
    <label>Account #</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Ad_Proof_Link__c.field-meta.xml
<CustomField>
    <fullName>Ad_Proof_Link__c</fullName>
    <formula>IF( ISBLANK( Ad_Proof_Document__c ), &quot;&quot;, HYPERLINK( &quot;/servlet/servlet.FileDownload?file=&quot; &amp; Ad_Proof_Document__c , &quot;View Proof&quot; ) )</formula>
    <label>Ad Proof Link</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Advertiser_Account__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advertiser Account</description>
    <label>Advertiser Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/CyberAd_Classification__c.field-meta.xml
<CustomField>
    <fullName>CyberAd_Classification__c</fullName>
    <label>Classification</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>External Booking/Billing Account</description>
    <inlineHelpText>Select the External Booking or Billing Account related to this Booking</inlineHelpText>
    <label>Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Line_Item_Classifications__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Classifications__c</fullName>
    <description>Unique Classifications in the Booking Line Items</description>
    <inlineHelpText>Unique Classifications in the Booking Line Items</inlineHelpText>
    <label>Line Item Classifications</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Line_Item_Publications__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Publications__c</fullName>
    <description>Unique Publications in the Booking Line Items</description>
    <inlineHelpText>Unique Publications in the Booking Line Items</inlineHelpText>
    <label>Line Item Publications</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <description>Parent Sales Order</description>
    <inlineHelpText>Parent Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>Source System for Booking</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cyber$ell</fullName>
                <default>true</default>
                <label>Cyber$ell</label>
            </value>
            <value>
                <fullName>CyberAd</fullName>
            </value>
            <value>
                <fullName>AdPoint</fullName>
            </value>
            <value>
                <fullName>OSCA</fullName>
            </value>
            <value>
                <fullName>Leapfrog</fullName>
            </value>
            <value>
                <fullName>NewsAdds Booking System</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <description>2016-04-15 Item-00028 SFE-449 - Updated so CyberAd also uses Line_Item_Gross_Price__c, rather than Total_Cost_Cyber__c</description>
    <formula>Line_Item_Gross_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost GST Excl</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Booking related to Case</description>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales Order related to the Case</description>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Contact/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Created in Error</fullName>
            </value>
            <value>
                <fullName>Marked for Deletion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/External_Account__c.object-meta.xml
<CustomObject>
    <description>Object to hold external accounts such as Billing and Booking Accounts</description>
    <label>Booking System Account</label>
    <nameField>
        <label>Booking System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking System Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/External_Account__c/fields/Account_No__c.field-meta.xml
<CustomField>
    <fullName>Account_No__c</fullName>
    <description>Used to store the Billing/Booking Account Number</description>
    <inlineHelpText>Used to store the Billing/Booking Account Number</inlineHelpText>
    <label>Account #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The External Account&#39;s parent Customer Account</description>
    <inlineHelpText>The External Account&#39;s parent Customer Account</inlineHelpText>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>External_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent External Account</description>
    <inlineHelpText>Parent External Account</inlineHelpText>
    <label>Parent Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Booking System Accounts</relationshipLabel>
    <relationshipName>External_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>External Account Status</description>
    <inlineHelpText>External Account Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Marked For Deletion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Shell Order encompassing Booking(s) - to be related to an Opportunity Product/s</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{0000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Account_No__c.field-meta.xml
<CustomField>
    <fullName>Account_No__c</fullName>
    <formula>External_Account__r.Account_No__c</formula>
    <label>Account #</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Advertiser_Account__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advertiser Account</description>
    <label>Advertiser Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders_Advertiser</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Booking/Billing Account</description>
    <inlineHelpText>Select the related Booking or Billing Account</inlineHelpText>
    <label>Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Sales Orders (External Account)</relationshipLabel>
    <relationshipName>Sales_Orders_ExternalAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>Booking Source System</description>
    <label>Booking System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cyber$ell</fullName>
                <default>true</default>
                <label>Cyber$ell</label>
            </value>
            <value>
                <fullName>CyberAd</fullName>
            </value>
            <value>
                <fullName>AdPoint</fullName>
            </value>
            <value>
                <fullName>OSCA</fullName>
            </value>
            <value>
                <fullName>NewsAdds</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Booking</fullName>
                <default>true</default>
                <label>Booking</label>
            </value>
            <value>
                <fullName>KILLED</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Created in Error</fullName>
            </value>
            <value>
                <fullName>Marked for Deletion</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <description>Rollup of booking costs</description>
    <label>Cost GST Excl</label>
    <summarizedField>Booking__c.Line_Item_Gross_Price__c</summarizedField>
    <summaryForeignKey>Booking__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

News UAT/force-app/main/default/classes/Case_Sidebar_Helper.cls
/**
* @company      Bluewolf
* @author       Louis Wang (louis.wang@bluewolf.com)
* @date         2015-01-29
* @description  This class contains methods that are used for Case Sidebar pages (console) <p>
*                   - Case_AccountInfo <p>
*                   - Case_EnhancedAccountSearch <p>
*                   - Case_NewAccountContact <p>
*                   - Case_RefreshPrimaryTab <p>
*/
public with sharing class Case_Sidebar_Helper 
{
    public static final string PASS_CORRECT_INFO = 'Please pass correct information to the Url.';

    /**
    * @author       Louis Wang (louis.wang@bluewolf.com)
    * @date         2015-01-29
    * @description  This method will perform URL redirect
    * @param        PageReference - destination page
    * @param        Boolean - whether it is a redirect
    * @param        Id - record Id to pass through
    * @param        String - type param    
    * @return       PageReference
    */    
    public static PageReference gotoPage(PageReference pageName, Boolean isRedirect, Id recordId, String typeParam)
    {
        PageReference output = pageName;
        if(recordId!=null) output.getParameters().put('id', recordId);
        if(typeParam!=null) output.getParameters().put('type', typeParam);
        output.setRedirect(isRedirect);
        return output;
    }

    /**
    * @author       Louis Wang (louis.wang@bluewolf.com)
    * @date         2015-10-28
    * @description  This method will perform URL redirect, with additional param "keyword" (SFE-739)
    * @param        PageReference - destination page
    * @param        Boolean - whether it is a redirect
    * @param        Id - record Id to pass through
    * @param        String - type param    
    * @param        String - type param
    * @return       PageReference
    */    
    public static PageReference gotoPage(PageReference pageName, Boolean isRedirect, Id recordId, String typeParam, String keywordParam)
    {
        PageReference output = pageName;
        if(recordId!=null) output.getParameters().put('id', recordId);
        if(typeParam!=null) output.getParameters().put('type', typeParam);
        if(keywordParam!=null) output.getParameters().put('keyword', EncodingUtil.urlEncode(keywordParam, 'UTF-8'));        
        output.setRedirect(isRedirect);
        return output;
    }

    /**
    * @author       Louis Wang (louis.wang@bluewolf.com)
    * @date         2015-01-29
    * @description  This method will fetch Case record based on a ID String
    * @param        String - case Id
    * @return       Case
    */    
    public static Case fetchCaseRecord(string caseRecordId)
    {
        Case output = null;

        if(caseRecordId!=null)
        {
            list<Case> caseList = [SELECT Id, CaseNumber, AccountId 
                                    FROM Case
                                    WHERE Id =: caseRecordId];
            if(!caseList.isEmpty())
            {
                output = caseList[0];
            }
        }
        return output;
    }

    /**
    * @author       Louis Wang (louis.wang@bluewolf.com)
    * @date         2015-01-29
    * @description  This method will fetch Contact Id based on few params. <p>
    *                   If the selected Account is a person account, fetch it. <p>
    *                   If the selected Account only has 1 contact, fetch it. <p>
    * @param        String - account Id
    * @param        boolean - whether account is Person Account
    * @param        Id - Contact Id from the Person Account
    * @return       Case
    */    
    public static Id fetchContactId_FromChosenAccount(string selectedAccount_Id, boolean selectedAccount_IsPersonAccount, string selectedAccount_ContactId)
    {
        // This function will fetch a ContactId. 
        Id output_ContactId;

        if(selectedAccount_Id!=null)
        {    
            if(selectedAccount_IsPersonAccount)
            {
                // if the Account is a Private Party (ie. PersonAccount), then fetch contactId
                output_ContactId = selectedAccount_ContactId;
            }
            else
            {
                // if not Person Account (ie. Business Account etc), and there is only 1 contact, then fetch contactId
                list<Contact> cList = [SELECT Id, AccountId 
                                        FROM Contact 
                                        WHERE AccountId = : selectedAccount_Id];
                if(cList.size()==1)
                {
                    output_ContactId = cList[0].Id;
                }                                
            }
        }    
        return output_ContactId;
    }

    /**
    * @author       Louis Wang (louis.wang@bluewolf.com)
    * @date         2015-07-29
    * @description  This method will transform the search string to acceptable format
    * @param        String
    * @param        boolean
    * @return       String
    */    
    public static String format_SearchString(String keywordString, Boolean isExactMatch)
    {
        String output = '';
        if(keywordString!=null && keywordString.trim().length()>0)
        {
            if(isExactMatch)
            {
                output = '\'' + string.escapeSingleQuotes(keywordString) + '\'';
            }
            else
            {
                output = '\'' + string.escapeSingleQuotes(keywordString) + '%\'';    
            }
        }
        return output;           
    }   

    /**
    * @author       Louis Wang (louis.wang@bluewolf.com)
    * @date         2015-07-29
    * @description  This method will generate SOQL string for booking
    * @param        String
    * @param        String
    * @return       String
    */    
    public static String generate_bookingSoql(string searchString, string limitString)
    {
        string output = 'SELECT Id, Name, Advertiser_Account__r.Name, Status__c, ' +
                        '       Source_System__c, Total_Cost__c, Sales_Order__r.Owner.Name, LastModifiedDate, ' +
                        '       Advertiser_Account__r.IsPersonAccount, Advertiser_Account__r.PersonContactId, ' +
                        '       CyberAd_Classification__c, Line_Item_Publications__c ' +
                        'FROM Booking__c ' +
                        'WHERE Name LIKE ' + searchString + ' ' +
                        'ORDER BY LastModifiedDate DESC ' + 
                        'LIMIT ' + limitString;
        return output;
    }

    /**
    * @author       Louis Wang (louis.wang@bluewolf.com)
    * @date         2015-07-29
    * @description  This method will generate SOQL string for case
    * @param        String
    * @param        String
    * @return       String
    */    
    public static String generate_caseSoql(string searchString, string limitString)
    {
        string output = 'SELECT Id, CaseNumber, Account.Name, RecordType.Name, ' + 
                        '       Status, Subject, Owner.Name, LastModifiedDate, ' +
                        '       Account.IsPersonAccount, Account.PersonContactId, ' +
                        '       Type ' +
                        'FROM Case ' +
                        'WHERE CaseNumber LIKE ' + searchString + ' ' +
                        'ORDER BY LastModifiedDate DESC ' + 
                        'LIMIT ' + limitString;
        return output;
    }

    /**
    * @author       Louis Wang (louis.wang@bluewolf.com)
    * @date         2015-07-29
    * @description  This method will generate SOQL string for account
    * @param        String
    * @param        String
    * @return       String
    */    
    public static String generate_accountSoql(string searchString, string limitString, string bsaSetName)
    {
        string output = 'SELECT Id, Name, RecordType.Name, Phone, PersonHomePhone, PersonMobilePhone, ' + 
                        '       PersonOtherPhone, IsPersonAccount, PersonContactId, ' +
                        '       AccountNumber, Owner.Name, BillingCity, PersonMailingCity ' +
                        'FROM Account ' +
                        'WHERE (Name LIKE ' + searchString + ' ' +
                        '       OR FirstName LIKE ' + searchString + ' ' +
                        '       OR LastName LIKE ' + searchString + ' ' +
                        '       OR Phone LIKE ' + searchString + ' ' +
                        '       OR PersonHomePhone LIKE ' + searchString + ' ' +
                        '       OR PersonMobilePhone LIKE ' + searchString + ' ' +
                        '       OR PersonOtherPhone LIKE ' + searchString + ') ';
            //Item-00182 DD Added parameters for searching with a set of account ids generated from related BSA
        	if(bsaSetName != null){
                output += '      OR Id IN :' + bsaSetName + ' ';
            }
        output += 'ORDER BY LastModifiedDate DESC ' + 
                         'LIMIT ' + limitString;
        return output;
    }
    
    /**
    * @author       David Dawson (david.dawson@bluewolf.com)
    * @date         2016-11-25
    * @description  This method will generate SOQL string for booking system account
    * @param        String
    * @param        String
    * @return       String
    */    
    public static String generate_bsaSoql(string searchString, string limitString)
    {
        string output = 'SELECT Id, Customer_Account__c ' +
                        'FROM External_Account__c ' +
                        'WHERE Account_No__c LIKE ' + searchString + ' ' +
                        'ORDER BY LastModifiedDate DESC ' + 
                        'LIMIT ' + limitString;
        return output;
    }

    /**
    * @author       Louis Wang (louis.wang@bluewolf.com)
    * @date         2015-07-29
    * @description  This method will generate SOQL string for contact
    * @param        String
    * @param        String
    * @return       String
    */    
    public static String generate_contactSoql(string searchString, string limitString)
    {
        string output = 'SELECT Id, Name, Account.Name, Email, Phone, HomePhone, MobilePhone, OtherPhone, AccountId ' +
                        'FROM Contact ' +
                        'WHERE (Name LIKE ' + searchString + ' ' +
                        '       OR FirstName LIKE ' + searchString + ' ' +
                        '       OR LastName LIKE ' + searchString + ' ' +
                        '       OR Phone LIKE ' + searchString + ' ' +
                        '       OR HomePhone LIKE ' + searchString + ' ' +
                        '       OR MobilePhone LIKE ' + searchString + ' ' +
                        '       OR OtherPhone LIKE ' + searchString + ' ' +  
                        '       OR Email LIKE ' + searchString + ') ' +
                        'AND IsPersonAccount=false ' + 
                        'AND Contact_Status__c=\'Active\'' +
                        'ORDER BY LastModifiedDate DESC ' + 
                        'LIMIT ' + limitString;
        return output;
    }  

    /**
    * @author       Louis Wang (louis.wang@bluewolf.com)
    * @date         2015-08-14
    * @description  This method will generate SOQL string for Account (for Case_AccountInfo)
    *               (This method is relocated from Case_AccountInfo)
    * @param        String
    * @param        String
    * @param        String    
    * @return       String
    */    
    public static string generate_accountSoql_for_Case_AccountInfo(string acctId, string limitString, string limitString_Contacts)
    {
        string output = '';
        if(acctId!=null && limitString!=null && limitString_Contacts!=null)
        {
            output = 'SELECT Id, Name, RecordType.Name, Status__c, AccountNumber, Last_Booking_Number__c, Owner.Name, IsPersonAccount, ' +
                        '(SELECT Id, Name, Status__c, Source_System__c, Total_Cost__c, Sales_Order__r.Owner.Name, LastModifiedDate, Line_Item_Classifications__c, Ad_Proof_Link__c FROM Bookings__r ORDER BY LastModifiedDate DESC LIMIT ' + limitString + '), ' + 
                        '(SELECT Id, CaseNumber, RecordType.Name, Status, Subject, Owner.Name, LastModifiedDate FROM Cases ORDER BY LastModifiedDate DESC LIMIT ' + limitString + '), ' + 
                        '(SELECT Id, Subject, ActivityType, IsTask, Owner.Name, LastModifiedDate FROM ActivityHistories ORDER BY ActivityDate DESC, LastModifiedDate DESC LIMIT ' + limitString + '), ' + 
                        '(SELECT Id, Subject, ActivityType, IsTask, Owner.Name, LastModifiedDate FROM OpenActivities ORDER BY ActivityDate ASC, LastModifiedDate DESC LIMIT ' + limitString + '), ' + 
                        '(SELECT Id, FirstName, LastName, Email, Phone, LastModifiedDate, AccountId, Name FROM Contacts ORDER BY LastModifiedDate DESC LIMIT ' + limitString_Contacts + ') ' + 
                        'FROM Account ' +
                        'WHERE Id = \'' + acctId + '\'';
        }
        return output;

        /* sample output string
        SELECT Id, Name, RecordType.Name, 
                (SELECT Id, Name FROM Bookings__r LIMIT 4), 
                (SELECT Id, CaseNumber FROM Cases LIMIT 4), 
                (SELECT Id FROM ActivityHistories LIMIT 4), 
                (SELECT Id FROM OpenActivities LIMIT 4),
                (SELECT Id FROM Contacts LIMIT 4)
        FROM Account 
        WHERE Id = '001N000000N2Duv'
        */        
    }

    /**
    * @author       Louis Wang (louis.wang@bluewolf.com)
    * @date         2015-08-14
    * @description  This method will fetch campaignMember list for Account (for Case_AccountInfo)
    * @param        Id
    * @param        String
    * @return       List<CampaignMember>
    */    
    public static List<CampaignMember> fetch_cmList_for_Case_AccountInfo(Id acctId, String limitString)
    {
        List<CampaignMember> output = new List<CampaignMember>();
        if(acctId!=null && limitString!=null)
        {
            output = [SELECT Id, Response_Type__c, Response_Sub_Type__c, LastModifiedDate,
                                Campaign.Name, Campaign.Status,
                                Contact.Name
                        FROM CampaignMember 
                        WHERE Contact.AccountId =: acctId
                        AND Campaign.IsActive = true
                        ORDER BY LastModifiedDate DESC
                        LIMIT : integer.valueOf(limitString)];
        }
        return output;
    }


}