News UAT/force-app/main/default/objects/Account/fields/Last_Booking_Number__c.field-meta.xml
<CustomField>
    <fullName>Last_Booking_Number__c</fullName>
    <description>Booking number the latest booking record rolled up to the account.</description>
    <label>Last Booking Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Bookings related to Bookings in Cyber$ell (Genera), CyberAd, or Digital Booking Systems</description>
    <label>Booking</label>
    <nameField>
        <label>Booking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking__c/fields/Ad_Taker__c.field-meta.xml
<CustomField>
    <fullName>Ad_Taker__c</fullName>
    <label>Ad Taker</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/AdProof_Required__c.field-meta.xml
<CustomField>
    <fullName>AdProof_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate whether AdProof is required.</description>
    <label>AdProof Required</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Advertiser_Account__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advertiser Account</description>
    <label>Advertiser Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cancelled Status</description>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/External_Sales_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Sales_Order_Id__c</fullName>
    <label>External Sales Order Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Integration_Date__c.field-meta.xml
<CustomField>
    <fullName>Integration_Date__c</fullName>
    <description>Integration Date/Time for when WebMethods have finished Booking updates.</description>
    <label>Integration Date</label>
    <type>DateTime</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Quote_Confirmation_waiting_msg_sent__c.field-meta.xml
<CustomField>
    <fullName>Quote_Confirmation_waiting_msg_sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote/Confirmation waiting msg sent</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Quote_or_Confirmation_Flag_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_or_Confirmation_Flag_Send_Date__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To set Send Date for Quote/Confirmation</description>
    <label>Quote or Confirmation Flag Send Date</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Quote_or_Confirmation_User__c.field-meta.xml
<CustomField>
    <fullName>Quote_or_Confirmation_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup is used to populate the From information for the outbound booking Quote/Confirmation visualforce template.</description>
    <label>Quote or Confirmation User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <description>Parent Sales Order</description>
    <inlineHelpText>Parent Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <label>Sales Rep</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Send_Channel__c.field-meta.xml
<CustomField>
    <fullName>Send_Channel__c</fullName>
    <label>Send Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/Booking_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Booking Line Items</description>
    <label>Booking Line Item</label>
    <nameField>
        <displayFormat>BKL{00000000}</displayFormat>
        <label>Booking Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cancelled</description>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/fields/Run_Date__c.field-meta.xml
<CustomField>
    <fullName>Run_Date__c</fullName>
    <description>Run Date</description>
    <label>Run Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Booking related to Case</description>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Case/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales Order related to the Case</description>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product2/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Shell Order encompassing Booking(s) - to be related to an Opportunity Product/s</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{0000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Ad_Taker__c.field-meta.xml
<CustomField>
    <fullName>Ad_Taker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ad Taker</description>
    <label>Ad Taker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Orders_AdTaker</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Advertiser_Account__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advertiser Account</description>
    <label>Advertiser Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders_Advertiser</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/SystemParameters__c/SystemParameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>System parameter is to improve the application customisation in the sense that it can be adapted as required.</description>
    <label>System parameters</label>
</CustomObject>

News UAT/force-app/main/default/objects/SystemParameters__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>Value of a key-value pair, where name is the key</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/User/fields/Network_Username__c.field-meta.xml
<CustomField>
    <fullName>Network_Username__c</fullName>
    <description>Windows network username, for correlation with other systems (e.g. Genera, Global Viewpoint).</description>
    <externalId>true</externalId>
    <label>Network Username</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/BookingManagement_Trigger_Test.cls
/*---------------------------------------------------------
 * Author: Bohao Chen
 * Company: Salesforce.com
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 * 28/08/2013  Bohao Chen  Created
 * 16/01/2014  Bohao Chen  Created
 * 2016-01-14  Atul Gupta  Updated 
 // 2016-01-14 atul.gupta@bluewolfgroup.com
    // This class provides test coverage for
    //  - BookingManagement Trigger        91%
    //  - BookingLineItemManagement_Helper 86%
    //  - BookingLineItemManagement        20%
 ---------------------------------------------------------*/
@isTest
public class BookingManagement_Trigger_Test 
{
    static testMethod void updateSalesOrderOwnerTest() 
    {
    	// create account
    	Account acct = TestDataFactory.createSingleAccount(null, 0, null, 0, 0);
    	insert acct;
    	
    	// create contact
    	List<Contact> contacts = TestDataFactory.createContacts(1, acct);
    	insert contacts;
    	
    	// create users
    	List<User> users = TestDataFactory.createUsers(51, 'News Direct Sales Inbound', null, null, false);
        insert users;
        
    	// set default sales rep
    	// treat last user in the list as default sales rep
    	SystemParameters__c salesRep = new SystemParameters__c(Name = 'Default Sales Rep', Value__c = users[50].Id, External_Id__c = '1234');
    	insert salesRep;
    	
    	system.debug('@default sales rep user id: ' + users[50].Id);
    	
    	// create sales orders
    	List<Sales_Order__c> salesOrders = new List<Sales_Order__c>();
    	
    	List<Sales_Order__c> salesOrdersBatch1 = TestDataFactory.createSalesOrders(10, acct, acct, acct, contacts[0], null);
    	List<Sales_Order__c> salesOrdersBatch2 = TestDataFactory.createSalesOrders(10, acct, acct, acct, contacts[0], null);
    	

    	salesOrders.addAll(salesOrdersBatch1);
    	salesOrders.addAll(salesOrdersBatch2);
        
    	insert salesOrders;
    	
    	List<Case> cases=TestDataFactory.createCases(1,null,null);
    	cases[0].Sales_Order__c=salesOrdersBatch1[0].Id;
    	insert cases[0];
    	
    	Test.startTest();
    	
    	system.debug('====salesOrders1=== ' + salesOrders);
    	system.debug('====salesOrdersBatch1=== ' + salesOrdersBatch1);
    	system.debug('====salesOrdersBatch2=== ' + salesOrdersBatch2);
    	
    	// create bookings
    	List<Booking__c> bookings = new List<Booking__c>();
    	
    	Integer i = 0;
    	
    	List<User> usersBatch1 = new List<User>();
    	List<User> usersBatch2 = new List<User>();
    	List<User> usersBatch3 = new List<User>();
    	
    	for(; i < 10; i++)
    	{
    		usersBatch1.add(users.get(i));
    	}
    	
    	for(; i < 20; i++)
    	{
    		usersBatch2.add(users.get(i));
    	}
    	
        for(; i < 30; i++)
        {
            usersBatch3.add(users.get(i));
        }
        
    	List<Booking__c> bookingWithNetworkUser1 = TestDataFactory.createBookings(10, salesOrdersBatch1, usersBatch1);
        List<Booking__c> bookingWithNetworkUser2 = TestDataFactory.createBookings(10, salesOrdersBatch2, usersBatch2);
    	bookings.addAll(bookingWithNetworkUser1);
    	bookings.addAll(bookingWithNetworkUser2);
    	insert bookings;

        Product2 prod = new Product2(name='prod');
        insert prod;
        list<Booking_line_Item__c> blis = TestDataFactory.createBookingLineItems(5,bookingWithNetworkUser1[0], prod, null);
        insert blis;
    	
        system.debug('====bookings=== ' + bookings);
        system.debug('====bookingWithNetworkUser1=== ' + bookingWithNetworkUser1);
    	system.debug('====bookingWithNetworkUser2 1=== ' + bookingWithNetworkUser2);
    	
    	// verify owner on sales order
    	i = 0;
    	
    	for(Sales_Order__c so : [Select OwnerId, Ad_Taker__c From Sales_Order__c Where Id IN: salesOrdersBatch1])
    	{
    		system.assertEquals(users[i].Id, so.OwnerId);
    		system.assertEquals(users[i].Id, so.Ad_Taker__c);
    		i++;
    	}
    	
        for(Sales_Order__c so : [Select OwnerId, Ad_Taker__c From Sales_Order__c Where Id IN: salesOrdersBatch2])
        {
            system.debug('1. @users[i].Id: ' + users[i].Id + ' so.OwnerId: ' + so.OwnerId);
        	
            system.assertEquals(users[i].Id, so.OwnerId);
            system.assertEquals(users[i].Id, so.Ad_Taker__c);
            i++;
        }
    	
    	// update sales rep field on bookings
    	bookingWithNetworkUser2 = BookingManagement_Trigger_Test.updateBookings(bookingWithNetworkUser2, usersBatch3);
    	update bookingWithNetworkUser2;
    	
        system.debug('====bookingWithNetworkUser2 2=== ' + bookingWithNetworkUser2);
    	
    	
    	// verify sales order owner when booking has sales rep updated
        for(Sales_Order__c so : [Select OwnerId, Ad_Taker__c From Sales_Order__c Where Id IN: salesOrdersBatch2])
        {
            system.debug('2. @users[i].Id: ' + users[i].Id + ' so.OwnerId: ' + so.OwnerId);
        	
            system.assertEquals(users[i].Id, so.OwnerId);
            system.assertEquals(users[i].Id, so.Ad_Taker__c);
            i++;
        }
        

        bookingWithNetworkUser1[0].Integration_Date__c = System.now();
        update bookingWithNetworkUser1[0];

    	Test.stopTest(); 
    }
    
    static testMethod void updateBookingSendDateFlagTest() 
    {
        // create users
        List<User> users = TestDataFactory.createUsers(1, 'News Direct Sales Inbound', null, null, false);
        insert users;
            	
        // set default sales rep
        // treat last user in the list as default sales rep
        SystemParameters__c salesRep = new SystemParameters__c(Name = 'Default Sales Rep', Value__c = users[0].Id, External_Id__c = '1234');
        insert salesRep;
        
    	// create booking
    	Sales_Order__c so = TestDataFactory.createSalesOrder('Cyber$ell');
    	List<Booking__c> bookings = TestDataFactory.createBookings(10, so);
    	insert bookings;
    	
    	Set<Id> bookingIds = new Set<Id>();

    	Test.startTest();
	
        system.debug('@bookingmanagement_trigger_helper_test bookingIds: ' + bookingIds);
        
    	//BookingManagement_Trigger_Helper.updateBookingSendDateFlag(bookingIds);
    	
    	BookingManagement_Trigger_Helper.updateBookingSendDateFlagNonFuture(bookingIds);
    	
    	// verify that all booking's send date flag has been set to true
    	bookings = [Select Quote_or_Confirmation_Flag_Send_Date__c 
                                      From Booking__c 
                                      Where Id IN: bookingIds];
                                          
    	Test.stopTest();
    }
    
    public static List<Booking__c> updateBookings(List<Booking__c> bookings, List<User> users)
    {
    	Integer i = 0;
    	
    	for(Booking__c b : bookings)
    	{
    	   b.Sales_Rep__c = users[i].Network_Username__c;
    	   b.Ad_Taker__c = users[i].Network_Username__c;
    	   i++;
    	}
    	
    	return bookings;
    }

    static testMethod void updateBookingLastExpiry(){
		
		// create users
        List<User> users = TestDataFactory.createUsers(1, 'News Direct Sales Inbound', null, null, false);
        insert users;
            	
        // set default sales rep
        // treat last user in the list as default sales rep
        SystemParameters__c salesRep = new SystemParameters__c(Name = 'Default Sales Rep', Value__c = users[0].Id, External_Id__c = '1234');
        insert salesRep;
        
    	// create booking
    	Sales_Order__c so = TestDataFactory.createSalesOrder('Cyber$ell');
    	List<Booking__c> bookings = TestDataFactory.createBookings(10, so);
    	insert bookings;
		
		List<Booking_line_Item__c> booklineItems = new List<Booking_line_Item__c>();
		
		Product2 prod = new Product2(name='prod', Family='Digital');
        insert prod;
        list<Booking_line_Item__c> blis = TestDataFactory.createBookingLineItems(5,bookings[0], prod, null);
        
        Product2 prod1 = new Product2(name='prod1', Family='Magazine');
        insert prod1;
        list<Booking_line_Item__c> blis1 = TestDataFactory.createBookingLineItems(5,bookings[1], prod1, null);
        
        booklineItems.addAll(blis);
        booklineItems.addAll(blis1);
        insert booklineItems;
		
		for(Booking_line_Item__c bitem : blis){
			bitem.Cancelled__c = false;
			bitem.Run_Date__c = date.today() +1;
		}
		update blis;
		
		List<Account> acctList = [select id,Last_Booking_Number__c from Account where id =: bookings[0].Advertiser_Account__c];
		system.assertEquals(acctList[0].Last_Booking_Number__c, bookings[0].Name);
	}
	
	static testMethod void updateBooking_CheckQuote(){
		
		// create users
        List<User> users = TestDataFactory.createUsers(1, 'News Integration', null, null, false);
        insert users;
            	
        // set default sales rep
        // treat last user in the list as default sales rep
        SystemParameters__c salesRep = new SystemParameters__c(Name = 'Default Sales Rep', Value__c = users[0].Id, External_Id__c = '1234');
        insert salesRep;
        
    	// create booking
    	Sales_Order__c so = TestDataFactory.createSalesOrder('Cyber$ell');
    	so.External_Id__c = 'orderId';
    	update so;
    	
    	List<Booking__c> bookings = TestDataFactory.createBookings(10, so);
    	for(Booking__c book : bookings){
    		book.External_Sales_Order_Id__c = 'orderId';
    	}
    	insert bookings;
		
		system.assertEquals(bookings[0].Sales_Order__c, so.id);
		
		for(Booking__c book : bookings){
			book.Send_Channel__c = 'Email';
			book.AdProof_Required__c = true;
			book.Quote_Confirmation_waiting_msg_sent__c = false;
		}
		update bookings;

	}
	
	static testMethod void updateBooking_CheckAdProof(){
		
		// create users
        List<User> users = TestDataFactory.createUsers(1, 'News Integration', null, null, false);
        insert users;
            	
        // set default sales rep
        // treat last user in the list as default sales rep
        SystemParameters__c salesRep = new SystemParameters__c(Name = 'Default Sales Rep', Value__c = users[0].Id, External_Id__c = '1234');
        insert salesRep;
        
    	// create booking
    	Sales_Order__c so = TestDataFactory.createSalesOrder('Cyber$ell');
    	
    	List<Booking__c> bookings = TestDataFactory.createBookings(10, so);
    	insert bookings;
		
		for(Booking__c book : bookings){
			book.Send_Channel__c = 'Email';
			book.AdProof_Required__c = true;
			book.Quote_Confirmation_waiting_msg_sent__c = false;
			book.Quote_or_Confirmation_User__c = users[0].Id;
		}
		update bookings;

	}
    
}