News UAT/force-app/main/default/objects/Account/fields/No_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>No_Parent_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to override the Parent Account required field</inlineHelpText>
    <label>No Parent Account</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/recordTypes/SME.recordType-meta.xml
<RecordType>
    <fullName>SME</fullName>
    <active>true</active>
    <description>Small to Medium Enterprises team</description>
    <label>SME</label>
</RecordType>

News UAT/force-app/main/default/objects/Opportunity/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Existing Business</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Lapsed Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <label>Competitor</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B Mag</fullName>
            </value>
            <value>
                <fullName>Cinema</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Letterbox</fullName>
            </value>
            <value>
                <fullName>Magazines - Bauer</fullName>
            </value>
            <value>
                <fullName>Magazines - EMAP</fullName>
            </value>
            <value>
                <fullName>Magazines - Fairfax Magazines</fullName>
            </value>
            <value>
                <fullName>Magazines - Other</fullName>
            </value>
            <value>
                <fullName>Magazines – Pacific Magazines</fullName>
            </value>
            <value>
                <fullName>Map Magazine</fullName>
            </value>
            <value>
                <fullName>No Competitor</fullName>
            </value>
            <value>
                <fullName>Online - Fairfax Digital</fullName>
            </value>
            <value>
                <fullName>Online - News Digital Media</fullName>
            </value>
            <value>
                <fullName>Online - NineMSN</fullName>
            </value>
            <value>
                <fullName>Online - Other</fullName>
            </value>
            <value>
                <fullName>Online - Sensis</fullName>
            </value>
            <value>
                <fullName>Online - Yahoo</fullName>
            </value>
            <value>
                <fullName>Outdoor - APN</fullName>
            </value>
            <value>
                <fullName>Outdoor - Adshel</fullName>
            </value>
            <value>
                <fullName>Outdoor - Australia Outdoor Network</fullName>
            </value>
            <value>
                <fullName>Outdoor - Eyecorp</fullName>
            </value>
            <value>
                <fullName>Press - APN</fullName>
            </value>
            <value>
                <fullName>Press - Fairfax Community</fullName>
            </value>
            <value>
                <fullName>Press - Fairfax Metro</fullName>
            </value>
            <value>
                <fullName>Press - News Communitities</fullName>
            </value>
            <value>
                <fullName>Press - News Metro</fullName>
            </value>
            <value>
                <fullName>Press - Other</fullName>
            </value>
            <value>
                <fullName>Press - Trading Post</fullName>
            </value>
            <value>
                <fullName>Press - Yellow Pages</fullName>
            </value>
            <value>
                <fullName>Radio - Austereo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/recordTypes/SME.recordType-meta.xml
<RecordType>
    <fullName>SME</fullName>
    <active>true</active>
    <businessProcess>NextGen</businessProcess>
    <description>Small to Medium Enterprises team</description>
    <label>SME</label>
</RecordType>

News UAT/force-app/main/default/classes/AT_LowSpendCustomers_Test.cls
@isTest
public class AT_LowSpendCustomers_Test {
    @isTest
    static void testLowSpendCustomer() {
        RecordType accountRT = [SELECT Id FROM RecordType WHERE (SObjectType = 'Account') AND (DeveloperName = 'SME') LIMIT 1];
        
        Account acc1 = new Account(Name = 'Test', No_Parent_Account__c = true, RecordTypeId = accountRT.Id);
        
        insert acc1;
        
        Contact cont1 = new Contact(AccountId = acc1.Id, LastName = 'test', FirstName = 'test', Email = 'test@example.com');
        
        insert cont1;
        
        Date thisFY = System.today();
        
        Date lastFY = Date.newInstance(thisFY.year() - 1, thisFY.month(), thisFY.day());
        
        Opportunity oppOld = new Opportunity(Name = 'Last FY Opp', Description = 'test', Contact__c = cont1.Id, StageName = 'Establish Rapport', Competitor__c = 'No Competitor', Classification__c = 'Existing Business', AccountId = acc1.Id, CloseDate = lastFY, Amount = 1000);
        Opportunity oppNew = new Opportunity(Name = 'Current FY Opp', Description = 'test', Contact__c = cont1.Id, StageName = 'Establish Rapport',Competitor__c = 'No Competitor',Classification__c = 'Existing Business',  AccountId = acc1.Id, CloseDate = thisFY, Amount = 500);
        
        insert oppOld;
        insert oppNew;
        
        Test.startTest();
        
        List<AT_LowSpendCustomers.AccountSpend> lowSpend = AT_LowSpendCustomers.getSpending(UserInfo.getUserId(), 5);
        
        System.assertEquals(1, lowSpend.size());
        
        Test.stopTest();
    }
    
    @isTest
    static void testSorting() {
        AT_LowSpendCustomers.AccountSpend less = new AT_LowSpendCustomers.AccountSpend();
        AT_LowSpendCustomers.AccountSpend more = new AT_LowSpendCustomers.AccountSpend();
        
        List<AT_LowSpendCustomers.AccountSpend> spends = new List<AT_LowSpendCustomers.AccountSpend>();
        
        less.Difference = 10;
        more.Difference = 20;
        
        spends.add(less);
        spends.add(more);
        
        spends.sort();
        
        System.assertEquals(spends[0].Difference, more.Difference);
        System.assertEquals(spends[1].Difference, less.Difference);
        
        spends = new List<AT_LowSpendCustomers.AccountSpend>();
        
        less.Difference = 15;
        more.Difference = 25;
        
        spends.add(more);
        spends.add(less);
        
        spends.sort();
        
        System.assertEquals(spends[0].Difference, more.Difference);
        System.assertEquals(spends[1].Difference, less.Difference);
        
        spends = new List<AT_LowSpendCustomers.AccountSpend>();
        
        spends.add(more);
        spends.add(more);
        
        spends.sort();
        
        System.assertEquals(spends[0].Difference, more.Difference);
        System.assertEquals(spends[1].Difference, more.Difference);
    }
}