News UAT/force-app/main/default/objects/Account/fields/No_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>No_Parent_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to override the Parent Account required field</inlineHelpText>
    <label>No Parent Account</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/External_Account__c.object-meta.xml
<CustomObject>
    <description>Object to hold external accounts such as Billing and Booking Accounts</description>
    <label>Booking System Account</label>
    <nameField>
        <label>Booking System Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking System Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/External_Account__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The External Account&#39;s parent Customer Account</description>
    <inlineHelpText>The External Account&#39;s parent Customer Account</inlineHelpText>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>External_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/External_Account__c.field-meta.xml
<CustomField>
    <fullName>External_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent External Account</description>
    <inlineHelpText>Parent External Account</inlineHelpText>
    <label>Parent Booking System Account</label>
    <referenceTo>External_Account__c</referenceTo>
    <relationshipLabel>Booking System Accounts</relationshipLabel>
    <relationshipName>External_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id</description>
    <externalId>true</externalId>
    <inlineHelpText>External Id</inlineHelpText>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

News UAT/force-app/main/default/objects/External_Account__c/fields/JDE_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>JDE_Account_Number__c</fullName>
    <description>External Account JDE Number</description>
    <inlineHelpText>External Account JDE Number</inlineHelpText>
    <label>JDE Account Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/classes/GetStatementsController_Test.cls
/**
* @description  test class for GetStatementsController.cls
* 
* @author       Paul Kang
* @date         2017-11-08
**/
@isTest
private class GetStatementsController_Test {
    
    @isTest static void accessComputershare() {

        Account newAct = new Account();
        newAct.Name = 'testAccount';
        newAct.No_Parent_Account__c = True;
        insert newAct;

        // insert a sample External_Account__c record
        External_Account__c ext = new External_Account__c();
        ext.JDE_Account_Number__c = '3423706';
        ext.Customer_Account__c = newAct.Id;
        ext.External_Id__c = '1234'; // sample external id value

        insert ext;

        string id = ext.Id;

        List<User> users = TestDataFactory.createUsers(1, 'System Administrator', null, null, false);
        insert users;
        
        Test.startTest();
        
        Test.setMock(WebServiceMock.class, new svc_GvpWebServiceGenerateTokenMock());

        String resultToken = GetStatementsController.accessComputershare(id);

        Test.stopTest();

        System.assert(resultToken != null);
    }
    
    
    
}