News UAT/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Mark for Duplication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Billing_File__c/Billing_File__c.object-meta.xml
<CustomObject>
    <label>Billing File</label>
    <nameField>
        <label>Billing File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Billing_File__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Sent To Billing</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>CASE(TEXT(StageName),
  &quot;Identify Prospects&quot;, &quot;Open&quot;,
  &quot;Establish Rapport&quot;, &quot;Open&quot;,
  &quot;Qualify Opportunity&quot;, &quot;Open&quot;,
  &quot;Select Product(s) and Update Stage&quot;, &quot;Open&quot;,
  &quot;Develop Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Present Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Re-affirm Value/ Negotiate&quot;, &quot;Open&quot;,
  &quot;Awaiting Bookings&quot;, &quot;Open&quot;,
  &quot;Closed Won&quot;, &quot;Closed Won&quot;,
  &quot;Closed Lost&quot;, &quot;Closed Lost&quot;,
  &quot;Err: Invalid stage name&quot;
)</formula>
    <inlineHelpText>Field to allow reporting on Win/ Lost vs Open. Do not display on page layouts.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Fulfilment Ready</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Campaign Live</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Payment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Payment Schedule</label>
    <nameField>
        <label>Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Payment_Schedule__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Schedule__c/fields/Schedule_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_End_Date__c</fullName>
    <label>Schedule End Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Schedule__c/fields/Schedule_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Start_Date__c</fullName>
    <label>Schedule Start Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Campaign Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/PS_Billing_File_Association__c/PS_Billing_File_Association__c.object-meta.xml
<CustomObject>
    <label>PS Billing File Association</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>PS Billing File Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Billing File Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/PS_Billing_File_Association__c/fields/Billing_File__c.field-meta.xml
<CustomField>
    <fullName>Billing_File__c</fullName>
    <label>Billing File</label>
    <referenceTo>Billing_File__c</referenceTo>
    <relationshipLabel>PS Billing File Associations</relationshipLabel>
    <relationshipName>PS_Billing_File_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/PS_Billing_File_Association__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <label>Payment Schedule</label>
    <referenceTo>Payment_Schedule__c</referenceTo>
    <relationshipLabel>PS Billing File Associations</relationshipLabel>
    <relationshipName>PS_Billing_File_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/classes/CS_BillingFileHelperTest.cls
@isTest(seeAllData=false)
public class CS_BillingFileHelperTest {
    
    @isTest
    public static void createBillingFile()
    {
        //create a Billing file record
        Billing_File__c testBillingFile = new Billing_File__c(name = 'September 2016', Billing_Date__c = System.today(), Status__c='Pending' );
        insert testBillingFile;
        
        Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        insert acc;
        
        Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today());
        insert opp;
        
        Order__c order = TestDataSetupClass.createOrder(opp);
        insert order;
        
        Payment__c payment = TestDataSetupClass.createPayment(order);
        insert payment;
        
        Payment_Schedule__c paymentSch = TestDataSetupClass.createPaymentSch(payment);
        paymentSch.Schedule_Start_Date__c = System.today();
        paymentSch.Schedule_End_Date__c = System.today().addMonths(4);
        paymentSch.Status__c = 'Pending';
        paymentSch.Billing_Date__c = System.now().date().addMonths(1).toStartofMonth().addDays(-1);
        insert paymentSch;
        system.debug('paymentSch-->'+paymentSch);
        
        PS_Billing_File_Association__c pbfa = new PS_Billing_File_Association__c(Billing_File__c = testBillingFile.id, Payment_Schedule__c = paymentSch.id);
        insert pbfa;
        
        CS_BillingFileHelper billingFileHelper = new CS_BillingFileHelper();
        Datetime dt = System.now();
        String filename = dt.format('MMMMM') + ' ' + dt.year();
        Date dateFilter = dt.date().addMonths(1).toStartofMonth().addDays(-1);
        system.debug('dateFilter-->'+dateFilter);
        system.debug('paymentSch.Billing_Date__cTC-->'+paymentSch.Billing_Date__c);
       // system.assertEquals(dateFilter,paymentSch.Billing_Date__c);
        CS_BillingFileHelper.createBillingFile(dt);
        CS_BillingFileHelper.associatePaymentSchedulesToBillingFile(dt);
		List<Payment_Schedule__c> psList = [
				select id, name, Status__c
				from Payment_Schedule__c
				where Billing_Date__c = :dateFilter
				and (Status__c = 'Pending' or Status__c = 'In Progress')
			]; 
        system.debug('psListTC-->'+psList);    
        system.debug('Billing_Date__cTC-->'+paymentSch.Billing_Date__c); 
        List<Billing_File__c> bfList = [
			select id, name, Status__c
			from Billing_File__c
			where name = :fileName
		];
        system.debug('bfListTC-->'+bfList);
        
    }
    
    @isTest
    public static void bflist_empty()
    {
        //create a Billing file record
        Billing_File__c testBillingFile = new Billing_File__c(name = 'testbf', Billing_Date__c = System.today(), Status__c='Pending' );
        insert testBillingFile;
        
        Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        insert acc;
        
        Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today());
        insert opp;
        
        Order__c order = TestDataSetupClass.createOrder(opp);
        insert order;
        
        Payment__c payment = TestDataSetupClass.createPayment(order);
        insert payment;
        
        Payment_Schedule__c paymentSch = TestDataSetupClass.createPaymentSch(payment);
        paymentSch.Schedule_Start_Date__c = System.today().addMonths(1);
        paymentSch.Schedule_End_Date__c = System.today().addMonths(4);
        paymentSch.Status__c = 'Pending';
        paymentSch.Billing_Date__c = System.now().date().addMonths(1).toStartofMonth().addDays(-1);
        insert paymentSch;
        system.debug('paymentSch-->'+paymentSch);
        
        PS_Billing_File_Association__c pbfa = new PS_Billing_File_Association__c(Billing_File__c = testBillingFile.id, Payment_Schedule__c = paymentSch.id);
        insert pbfa;
        
        CS_BillingFileHelper billingFileHelper = new CS_BillingFileHelper();
        Datetime dt = System.now();
        String filename = dt.format('MMMMM') + ' ' + dt.year();
        Date dateFilter = dt.date().addMonths(1).toStartofMonth().addDays(-1);
        system.debug('dateFilter-->'+dateFilter);
        system.debug('paymentSch.Billing_Date__cTC-->'+paymentSch.Billing_Date__c);
       // system.assertEquals(dateFilter,paymentSch.Billing_Date__c);
        CS_BillingFileHelper.createBillingFile(dt);
        CS_BillingFileHelper.associatePaymentSchedulesToBillingFile(dt);
		List<Payment_Schedule__c> psList = [
				select id, name, Status__c
				from Payment_Schedule__c
				where Billing_Date__c = :dateFilter
				and (Status__c = 'Pending' or Status__c = 'In Progress')
			]; 
        system.debug('psListTC-->'+psList);    
        List<Billing_File__c> bfList = [
			select id, name, Status__c
			from Billing_File__c
			where name = :fileName
		];
        system.debug('bfListTC-->'+bfList);
        
    }
  

}