News UAT/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Mark for Duplication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/Customer_Task__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Customer Activity</label>
    <nameField>
        <displayFormat>CAN-{YYMMDD}-{0000}</displayFormat>
        <label>Customer Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Activities</relationshipLabel>
    <relationshipName>Customer_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will contain the reference of Product Order for Approve Display Ad Proof Task</description>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Social_Ad__c.field-meta.xml
<CustomField>
    <fullName>Social_Ad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This relationship is to link Social Ad with the customer tasks to get &quot;Social Ad Tasks&quot;</description>
    <label>Social Ad</label>
    <referenceTo>SocialAd__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Social_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Social_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This relationship to link social campaign to a customer task to get &quot;Campaign Tasks&quot;</description>
    <label>Social Campaign</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipName>Customer_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Customer_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>With Client</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
                <isActive>false</isActive>
                <label>In Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Campaign_Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The customer contact you are dealing with about this Campaign. The value in this field will default from the Opportunity, but you can edit it to select the most appropriate contact.</inlineHelpText>
    <label>Campaign Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Orders (Campaign Customer Contact)</relationshipLabel>
    <relationshipName>Campaign_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Fulfilment Ready</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Campaign Live</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Order__r.Account__r.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Product Orders</relationshipLabel>
    <relationshipName>Product_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Returned to CM</fullName>
            </value>
            <value>
                <fullName>Initial QA</fullName>
            </value>
            <value>
                <fullName>Peer review</fullName>
            </value>
            <value>
                <fullName>Peer review failed</fullName>
            </value>
            <value>
                <fullName>Ready to go live</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
            <value>
                <fullName>Cancellation Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/recordTypes/Content.recordType-meta.xml
<RecordType>
    <fullName>Content</fullName>
    <active>true</active>
    <label>Content</label>
</RecordType>

News UAT/force-app/main/default/objects/Product_Order__c/recordTypes/Social.recordType-meta.xml
<RecordType>
    <fullName>Social</fullName>
    <active>true</active>
    <label>Social</label>
</RecordType>

News UAT/force-app/main/default/objects/Social_Ad_Content__c/Social_Ad_Content__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Proof Ad Content</label>
    <nameField>
        <displayFormat>PAC-{000000}</displayFormat>
        <label>Proof Ad Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proof Ad Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Social_Ad_Content__c/fields/Ad_Headline__c.field-meta.xml
<CustomField>
    <fullName>Ad_Headline__c</fullName>
    <description>This will contain tHeadline for facebook ad</description>
    <inlineHelpText>This will contain tHeadline for facebook ad</inlineHelpText>
    <label>Ad Headline</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Social_Ad_Content__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <description>This will contain the name of file uploaded for ad</description>
    <inlineHelpText>This will contain the name of file uploaded for ad</inlineHelpText>
    <label>File Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Social_Ad_Content__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <description>This will contain the type of file uploaded for ad</description>
    <inlineHelpText>This will contain the type of file uploaded for ad</inlineHelpText>
    <label>File Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/SocialAd__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Proof Ad</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>ProofAd Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proof Ads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Ad_Headline__c.field-meta.xml
<CustomField>
    <fullName>Ad_Headline__c</fullName>
    <description>This field will have headline for facebook ad</description>
    <inlineHelpText>This field will have headline for facebook ad</inlineHelpText>
    <label>Ad Headline</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Social_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Social_Campaign__c</fullName>
    <description>Parent Proof</description>
    <inlineHelpText>Parent Proof</inlineHelpText>
    <label>Proof</label>
    <referenceTo>SocialCampaign__c</referenceTo>
    <relationshipLabel>Proff Ads</relationshipLabel>
    <relationshipName>Social_Ads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialAd__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Internal QA</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>With Customer</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
                <isActive>false</isActive>
                <label>In-Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/SocialCampaign__c.object-meta.xml
<CustomObject>
    <description>This object is for NewsXtend Customers who access My-Account community</description>
    <label>Proof</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proofs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/SocialCampaign__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Social_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipName>Social_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Internal QA</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>With Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/SocialCampaign__c/recordTypes/Social.recordType-meta.xml
<RecordType>
    <fullName>Social</fullName>
    <active>true</active>
    <description>Record with social ad</description>
    <label>Social</label>
</RecordType>

News UAT/force-app/main/default/classes/NXX2_SocialAdPageControllerTest.cls
/**
* @author       Kamal Sharma
* @date         2018-09-24
* @className	NXX2_SocialAdPageControllerTest
* @description  This is a test class for NXX2_SocialAdPageController.
*/
@isTest
public class NXX2_SocialAdPageControllerTest
{
	 /**
    * @author       Kamal Sharma
    * @date         2018-09-24
    * @description  This method will test saveSingleFile.
    * @param        NA
    * @return       void
    */
    static testMethod void testMethodsWithoutAPICall(){
        NXX2_TestUtility.disableAllTriggerDuringTesting();
        Contact con = new Contact(Firstname = 'Test',Lastname = 'Test',Email = 'Test@gmail.com');
        insert con;
        List<Account> accounts = TestDataFactory.createAccounts(3,false);
        insert accounts;
        Order__c order = new Order__c(Campaign_Customer_Contact__c = con.Id,Account__c = accounts[0].Id);
        insert order;
        Product_Order__c po = new Product_Order__c(order__c = order.Id);
        insert po;
        SocialCampaign__c proof = new SocialCampaign__c(Product_Order__c = po.Id,Status__c = 'New');
        insert proof;
        SocialAd__c socialAd = new SocialAd__c(Social_Campaign__c = proof.Id);
        insert socialAd;
        
		Test.startTest();
        List<NXX2_ConfigModel.SocialAdType> socialAdTypes = NXX2_SocialAdPageController.getCreateAdConfigData();
        socialAd = new SocialAd__c(Ad_Headline__c = 'Test', Social_Campaign__c = proof.Id);
        socialAd = NXX2_SocialAdPageController.saveAdDetails(socialAd,'Social Ad');
        Social_Ad_Content__c content = new Social_Ad_Content__c(
        	File_Name__c = 'Test1',
            File_Type__c = 'Text',
            Social_Ad__c = socialAd.Id
        );
        List<Social_Ad_Content__c> contents = new List<Social_Ad_Content__c>();
        contents.add(content);
        contents = NXX2_SocialAdPageController.saveAdContent(JSON.serialize(contents),socialAd.Id,'Edit');
        content = new Social_Ad_Content__c(
        	File_Name__c = 'Test2',
            File_Type__c = 'Text2',
            GoogleDrive_File_Id__c = 'Test2',
            Social_Ad__c = socialAd.Id
        );
        contents = new List<Social_Ad_Content__c>();
        contents.add(content);
        contents = NXX2_SocialAdPageController.saveAdContent(JSON.serialize(contents),socialAd.Id,'CreateNewVersion');
        String initial = NXX2_SocialAdPageController.getInitialForUser();
        NXX2_SocialAdPageController.markAdAsDeleted(socialAd.Id);
        NXX2_SocialAdPageController.updateProofStatus(proof.Id,'In Review',null);
        List<Customer_Task__c> activities = NXX2_TestUtility.createCustomerActivity(new List<SocialCampaign__c>{proof});
        NXX2_SocialAdPageController.getCommunityBaseUrl();
        NXX2_SocialAdPageController.isExternalUser();
        NXX2_SocialAdPageController.getProofsForAccount(accounts[0].Id);
        NXX2_SocialAdPageController.getIconName('Account');
        Test.stopTest();
	}
     /**
    * @author       Kamal Sharma
    * @date         2018-09-24
    * @description  This method will test saveSingleFile.
    * @param        NA
    * @return       void
    */
    static testMethod void testMethodsWithAPICall(){
        NXX2_TestUtility.disableAllTriggerDuringTesting();
        Contact con = new Contact(Firstname = 'Test',Lastname = 'Test',Email = 'Test@gmail.com');
        insert con;
        List<Account> accounts = TestDataFactory.createAccounts(3,false);
        insert accounts;
        Order__c order = new Order__c(Campaign_Customer_Contact__c = con.Id,Account__c = accounts[0].Id);
        insert order;
        Product_Order__c po = new Product_Order__c(order__c = order.Id);
        insert po;
        SocialCampaign__c proof = new SocialCampaign__c(Product_Order__c = po.Id,Status__c = 'New');
        insert proof;
        SocialAd__c socialAd = new SocialAd__c(Social_Campaign__c = proof.Id);
        insert socialAd;
        Social_Ad_Content__c content = new Social_Ad_Content__c(
        	File_Name__c = 'Test1',
            File_Type__c = 'Text1',
            Social_Ad__c = socialAd.Id,
            GoogleDrive_File_Id__c = 'Test'
        );
        insert content;
		Test.startTest();
        Test.setMock(HttpCalloutMock.class, new NXX2_GoogleDriveAPIMockUp());
        NXX2_LightningReqRespModel.SocialAdWithContent adWithContent = NXX2_SocialAdPageController.getAdDetails(socialAd.Id);
        List<NXX2_LightningReqRespModel.SocialAdWithContent> allAds = NXX2_SocialAdPageController.getAllAds(proof.Id);
        List<NXX2_LightningReqRespModel.SocialAdWithContent> allAdVersions = NXX2_SocialAdPageController.getAllVersionForSocialAd(socialAd.Id);
        List<NXX2_LightningReqRespModel.SocialAdContent> socialAdContents = NXX2_SocialAdPageController.getContentForSocialAd(socialAd.Id,null);
        Test.stopTest();
	}
}