News UAT/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Mark for Duplication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>CASE(TEXT(StageName),
  &quot;Identify Prospects&quot;, &quot;Open&quot;,
  &quot;Establish Rapport&quot;, &quot;Open&quot;,
  &quot;Qualify Opportunity&quot;, &quot;Open&quot;,
  &quot;Select Product(s) and Update Stage&quot;, &quot;Open&quot;,
  &quot;Develop Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Present Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Re-affirm Value/ Negotiate&quot;, &quot;Open&quot;,
  &quot;Awaiting Bookings&quot;, &quot;Open&quot;,
  &quot;Closed Won&quot;, &quot;Closed Won&quot;,
  &quot;Closed Lost&quot;, &quot;Closed Lost&quot;,
  &quot;Err: Invalid stage name&quot;
)</formula>
    <inlineHelpText>Field to allow reporting on Win/ Lost vs Open. Do not display on page layouts.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/recordTypes/Brief.recordType-meta.xml
<RecordType>
    <fullName>Brief</fullName>
    <active>true</active>
    <businessProcess>Brief%2F Reactive</businessProcess>
    <description>By request of a client brief.</description>
    <label>Brief</label>
</RecordType>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Proposed_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Start_Date__c</fullName>
    <label>Proposed Start Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Fulfilment Ready</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Campaign Live</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Assigned_Fulfilment_Owner__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Fulfilment_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Fulfilment Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Cost_Model__c.field-meta.xml
<CustomField>
    <fullName>Cost_Model__c</fullName>
    <description>Same value is in Product Configuration Attribute with Name of Cost Model. Required for Buy Sheet Extract. Populated by a trigger</description>
    <inlineHelpText>Same value is in Product Configuration Attribute with Name of Cost Model.</inlineHelpText>
    <label>Cost Model</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Same value is in Product Configuration Attribute with Name of Discount. Required for Buy Sheet Extract. Populated by a trigger</description>
    <inlineHelpText>Same value is in Product Configuration Attribute with Name of Discount.</inlineHelpText>
    <label>Discount</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Network_Name__c.field-meta.xml
<CustomField>
    <fullName>Network_Name__c</fullName>
    <description>Same value is in Product Configuration Attribute  with Name of Network Name. Required for Buy Sheet Extract. Populated by a trigger.</description>
    <inlineHelpText>Same value is in Product Configuration Attribute  with Name of Network Name</inlineHelpText>
    <label>Network Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Product Orders</relationshipLabel>
    <relationshipName>Product_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Configuration</label>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipLabel>Product Orders</relationshipLabel>
    <relationshipName>Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Same value is in Product Configuration Attribute with Name of Product Name. Required for Buy Sheet Extract. Populated by a trigger</description>
    <inlineHelpText>Same value is in Product Configuration Attribute with Name of Product Name.</inlineHelpText>
    <label>Product Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Product_Node__c.field-meta.xml
<CustomField>
    <fullName>Product_Node__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup for Product Node record product.</description>
    <label>Product Node</label>
    <referenceTo>csmso__Product_Node__c</referenceTo>
    <relationshipLabel>Product Orders</relationshipLabel>
    <relationshipName>Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Product_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Type_Name__c</fullName>
    <description>Same value is in Product Configuration Attribute with Name of Product Type Name. Required for Buy Sheet Extract. Populated by a trigger</description>
    <inlineHelpText>Same value is in Product Configuration Attribute with Name of Product Type Name.</inlineHelpText>
    <label>Product Type Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Proposed_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Start_Date__c</fullName>
    <formula>Order__r.Proposed_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field will display the Proposed Start Date from the Campaign Order. It cannot be edited on the Product Order; if a change to this field is needed, it must be updated on the Campaign Order.</inlineHelpText>
    <label>Proposed Start Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Returned to CM</fullName>
            </value>
            <value>
                <fullName>Initial QA</fullName>
            </value>
            <value>
                <fullName>Peer review</fullName>
            </value>
            <value>
                <fullName>Peer review failed</fullName>
            </value>
            <value>
                <fullName>Ready to go live</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
            <value>
                <fullName>Cancellation Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Shell Order encompassing Booking(s) - to be related to an Opportunity Product/s</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{0000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Order Number</description>
    <label>Siebel Order #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Booking</fullName>
                <default>true</default>
                <label>Booking</label>
            </value>
            <value>
                <fullName>KILLED</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Created in Error</fullName>
            </value>
            <value>
                <fullName>Marked for Deletion</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/NXX2_Buy_Sheet_Test.cls
/*------------------------------------------------------------
Author:        Rinaldo Clucher
Company:       Salesforce
Description:   Test Class to test NXX2_Buy_Sheet which populates
			    BuySheet specific fields in the Product Order Object.

History
<Date>      <Authors Name>     <Brief Description of Change>
13/11/2018  Rinaldo Clucher        Created
------------------------------------------------------------*/

@isTest(seeAllData=false)
public class NXX2_Buy_Sheet_Test  {

    // Setup all the objects to enable the operation of Reset Busy SHeet Extracted Flag process
    // This will in turn execute NXX2 Buy SHeet class. 
    @testSetup static void buySheetDataSetup()
    {
        System.debug('*** Create List bhs');

        List<BusinessHours> bhs = [select id from BusinessHours where IsDefault=true];
        System.assert(bhs.size() == 1);

        System.debug('*** Create Sales Order API');

        csmso__SalesOrderAPI__c soApi = TestDataSetupClass.createSalesOrderAPI();
        insert soApi;

        System.debug('*** Inserted Sales Order API');

        Account acc = TestDataSetupClass.createAccount();
        insert acc;

        Contact con = TestDataSetupClass.createContact(acc);
        insert con;

        Opportunity opp = TestDataSetupClass.createOpportunity(acc, con);
        insert opp;

        csmso__Business_Unit__c bu = TestDataSetupClass.createBusinessUnit();
        insert bu;

        csmso__Product_Node__c pn = TestDataSetupClass.createProductNode('TestPNName', bu);
        insert pn;

        csmso__Sales_Order__c so = TestDataSetupClass.createSalesOrder(acc, opp);
        so.csmso__Status__c = 'Externally Approved';
        insert so;

        Order__c order = TestDataSetupClass.createOrder(opp);
        order.Proposed_Start_Date__c = Date.Today();
        order.Sales_Order__c = so.Id;
        insert order;

        cscfga__Product_Basket__c prodBasket = TestDataSetupClass.createProdBasket(so);
        insert prodBasket;
        
        cscfga__Product_Configuration__c prodConfig = TestDataSetupClass.createProdConfig(prodBasket);
        prodConfig.Platform__c = 'Xtend';
        insert prodConfig;

        Product_Order__c pOrd = new Product_Order__c(Assigned_Fulfilment_Owner__c = UserInfo.getUserId(),
                                                     Order__c = order.Id,
                                                     Product_Configuration__c = prodConfig.id,
                                                     Product_Node__c = pn.id,
                                                     Status__c = 'In Progress');
        insert pOrd;
        
        cscfga__Product_Category__c testProdCateg = TestDataSetupClass.createProdCateg();
        insert testProdCateg;
        
        cscfga__Product_Definition__c testProDef = TestDataSetupClass.createProDef(testProdCateg);
        insert testProDef;
        
        cscfga__Attribute_Definition__c testAttrDef1 = TestDataSetupClass.createAttrDef(testProDef);
        testAttrDef1.Name= 'Product Groups For IO';
        insert testAttrDef1;
        
        cscfga__Attribute_Definition__c testAttrDef2 = TestDataSetupClass.createAttrDef(testProDef);
        testAttrDef2.Name= 'Product Type Name';
        insert testAttrDef2;
        
        cscfga__Attribute_Definition__c testAttrDef3 = TestDataSetupClass.createAttrDef(testProDef);
        testAttrDef3.Name= 'Network Name';
        insert testAttrDef3;
        
        cscfga__Attribute_Definition__c testAttrDef4 = TestDataSetupClass.createAttrDef(testProDef);
        testAttrDef4.Name= 'Discount';
        insert testAttrDef4;
        
        cscfga__Attribute__c testAttr1 = new cscfga__Attribute__c(name = 'Product Groups For IO', cscfga__Product_Configuration__c= prodConfig.Id, cscfga__Attribute_Definition__c = testAttrDef1.Id, cscfga__Value__c = '1000');
        insert testAttr1;
        
        cscfga__Attribute__c testAttr2 = new cscfga__Attribute__c(name = 'Product Type Name', cscfga__Product_Configuration__c= prodConfig.Id, cscfga__Attribute_Definition__c = testAttrDef2.Id, cscfga__Value__c = 'Catch Up TV');
        insert testAttr2;
        
        cscfga__Attribute__c testAttr3 = new cscfga__Attribute__c(name = 'Network Name', cscfga__Product_Configuration__c= prodConfig.Id, cscfga__Attribute_Definition__c = testAttrDef3.Id, cscfga__Value__c = 'The Trade Desk');
        insert testAttr3;
        
        cscfga__Attribute__c testAttr4 =new cscfga__Attribute__c(name = 'Discount', cscfga__Product_Configuration__c= prodConfig.Id, cscfga__Attribute_Definition__c = testAttrDef4.Id, cscfga__Value__c = '0.00');
        insert testAttr4;
        
        cscfga__Product_Basket__c prodBasketUpdate = [Select Id, csmso__Sales_Order__c from cscfga__Product_Basket__c];
        prodBasketUpdate.csmso__Sales_Order__c = so.Id;
        update prodBasketUpdate;
        

}

    // Tests operation of NXX2 Buy Sheet Class
    @isTest
    public static void processBuysheet() {
        
        
        System.debug('*** Product Orders Before Setup');                
        
        // Set campaign to Live

        Order__c order = [SELECT Id FROM Order__c LIMIT 1];

        list <Id> poIds = new list <Id> ();
        for (Product_Order__c po : [SELECT Id FROM Product_Order__c ]){
            poIds.add(po.id);
        }
        
        Test.startTest();
        
        NXX2_Buy_Sheet.SetProductFields(poIds);

        Test.stopTest();

        List <Product_Order__c> poOutput = [Select Id, status__c, Product_Node__c, Proposed_Start_Date__c, 
                                     Discount__c, Product_Type_Name__c, Product_Name__c, Network_Name__c,
                                     Cost_Model__c, Product_Configuration__c from Product_Order__c];
        System.debug('*** Number of Product Orders : ' + poOutput.size());
        System.debug('*** Product Order Details : ' + poOutput);
        
        System.assert(poOutput[0].Product_Type_Name__c == 'Catch Up TV'); 
        System.assert(poOutput[0].Network_Name__c == 'The Trade Desk'); 
        System.assert(poOutput[0].Discount__c == '0.00'); 

     }     
   
}