News UAT/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Mark for Duplication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Bookings related to Bookings in Cyber$ell (Genera), CyberAd, or Digital Booking Systems</description>
    <label>Booking</label>
    <nameField>
        <label>Booking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking__c/fields/Advertiser_Account__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advertiser Account</description>
    <label>Advertiser Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cancelled Status</description>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Payer_Account__c.field-meta.xml
<CustomField>
    <fullName>Payer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payer Account</description>
    <label>Payer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Payer Account)</relationshipLabel>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <description>Parent Sales Order</description>
    <inlineHelpText>Parent Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/Booking_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Booking Line Items</description>
    <label>Booking Line Item</label>
    <nameField>
        <displayFormat>BKL{00000000}</displayFormat>
        <label>Booking Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/fields/Ad_Type__c.field-meta.xml
<CustomField>
    <fullName>Ad_Type__c</fullName>
    <description>Ad Type</description>
    <label>Ad Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cancelled</description>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/fields/Gross_Price__c.field-meta.xml
<CustomField>
    <fullName>Gross_Price__c</fullName>
    <description>Gross Price of Booking Line Item</description>
    <label>Gross Price GST Excl</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/fields/Gross_Price_Change_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Gross_Price_Change_Datetime__c</fullName>
    <description>workflow rule will timestamp this field when gross price is updated</description>
    <label>Gross Price Change Datetime</label>
    <type>DateTime</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/fields/Gross_Price_YTD__c.field-meta.xml
<CustomField>
    <fullName>Gross_Price_YTD__c</fullName>
    <label>Gross Price YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/fields/Run_Date__c.field-meta.xml
<CustomField>
    <fullName>Run_Date__c</fullName>
    <description>Run Date</description>
    <label>Run Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Booking_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Payer_Account__c.field-meta.xml
<CustomField>
    <fullName>Payer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payer Account</relationshipLabel>
    <relationshipName>Opportunities_Payer</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>CASE(TEXT(StageName),
  &quot;Identify Prospects&quot;, &quot;Open&quot;,
  &quot;Establish Rapport&quot;, &quot;Open&quot;,
  &quot;Qualify Opportunity&quot;, &quot;Open&quot;,
  &quot;Select Product(s) and Update Stage&quot;, &quot;Open&quot;,
  &quot;Develop Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Present Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Re-affirm Value/ Negotiate&quot;, &quot;Open&quot;,
  &quot;Awaiting Bookings&quot;, &quot;Open&quot;,
  &quot;Closed Won&quot;, &quot;Closed Won&quot;,
  &quot;Closed Lost&quot;, &quot;Closed Lost&quot;,
  &quot;Err: Invalid stage name&quot;
)</formula>
    <inlineHelpText>Field to allow reporting on Win/ Lost vs Open. Do not display on page layouts.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Shell Order encompassing Booking(s) - to be related to an Opportunity Product/s</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{0000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Advertiser_Account__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advertiser Account</description>
    <label>Advertiser Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders_Advertiser</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Payer_Account__c.field-meta.xml
<CustomField>
    <fullName>Payer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payer Account</description>
    <inlineHelpText>Payer – The account that pays for the advertising.</inlineHelpText>
    <label>Payer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders (Payer Account)</relationshipLabel>
    <relationshipName>Sales_Orders_Payer</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Booking</fullName>
                <default>true</default>
                <label>Booking</label>
            </value>
            <value>
                <fullName>KILLED</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Created in Error</fullName>
            </value>
            <value>
                <fullName>Marked for Deletion</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Total_Gross_Price_Ytd__c.field-meta.xml
<CustomField>
    <fullName>Total_Gross_Price_Ytd__c</fullName>
    <label>Total Gross Price YTD</label>
    <summarizedField>Booking__c.Line_Item_Gross_Price_YTD__c</summarizedField>
    <summaryForeignKey>Booking__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Total_Gross_Price_YTD_Last_Modified__c.field-meta.xml
<CustomField>
    <fullName>Total_Gross_Price_YTD_Last_Modified__c</fullName>
    <description>last modified datetime for total gross price YTD</description>
    <label>Total Gross Price YTD Last Modified</label>
    <type>DateTime</type>
</CustomField>

News UAT/force-app/main/default/classes/Booking_Refresh_YTD_Revenue_Batch.cls
/* History
2016-01-05   Darshan G   Updated
-----------------------------------------*/
global class Booking_Refresh_YTD_Revenue_Batch implements Database.Batchable<sObject>, Database.Stateful { // Updated By Bohao Chen on 30/05/2014 to keep values in sales order set
    
    global String query;
    global final List<Booking_Line_Item__c> bookingLineItemIds;
    global final Set<Id> salesOrderIds; // Updated By Bohao Chen on 30/05/2014 passing salesOrder only for testing purpose

    global Booking_Refresh_YTD_Revenue_Batch(List<Booking_Line_Item__c> bookingLineItemIds) 
    {    
        this.query = 'SELECT Id, Ad_Type__c, Cancelled__c, Gross_Price__c, Gross_Price_Change_Datetime__c, Gross_Price_YTD__c, Run_Date__c, Status__c ' +
                     'FROM Booking_Line_Item__c ' +
                     'ORDER BY Booking__c';
        
        if(Test.isRunningTest() && bookingLineItemIds != null)
        {
            this.bookingLineItemIds = bookingLineItemIds;
            this.salesOrderIds = new Set<Id>();
            this.query = 'SELECT Id, Ad_Type__c, Cancelled__c, Gross_Price__c, Gross_Price_Change_Datetime__c, ' + 
                         'Gross_Price_YTD__c, Run_Date__c, Status__c, Booking__r.Sales_Order__c ' +
                         'FROM Booking_Line_Item__c ' +
                         'Where Id IN: bookingLineItemIds ' + 
                         'ORDER BY Booking__c limit 200';
        }
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        system.debug('## Start Booking_Refresh_YTD_Revenue_Batch query: ' + query); 
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        // create the opportunity line item schedules

        system.debug('## Execute Booking_Refresh_YTD_Revenue_Batch ##'); 

        List<Booking_Line_Item__c> bookingItems = (List<Booking_Line_Item__c>)scope;
        List<Booking_Line_Item__c> bookingItemsUpdate = new List<Booking_Line_Item__c>();

        for (Booking_Line_Item__c bi : bookingItems) {

            if (bi.Run_Date__c != null && bi.Run_Date__c.year() == date.today().year()) {
                // Revenue falls this year
                // Ensure Gross Price YTD = Gross Price 
                if ((bi.Gross_Price__c == null && bi.Gross_Price_YTD__c != null) ||
                    (bi.Gross_Price__c != null && bi.Gross_Price_YTD__c == null) ||
                    (bi.Gross_Price__c != bi.Gross_Price_YTD__c)) 
                {
                    bi.Gross_Price_YTD__c = bi.Gross_Price__c;
                    bookingItemsUpdate.add(bi);
                }
            } else {
                // Revenue is not this year
                // Ensure Gross Price YTD is null
                if (bi.Gross_Price_YTD__c != null && bi.Gross_Price_YTD__c != 0) {
                    bi.Gross_Price_YTD__c = null;
                    bookingItemsUpdate.add(bi);
                }
            }

            // Updated by Bohao Chen on 30/05/2014
            if(Test.isRunningTest())
                salesOrderIds.add(bi.Booking__r.Sales_Order__c);
        }
        Database.update(bookingItemsUpdate, false); 
    }
    
    global void finish(Database.BatchableContext BC) 
    {
        system.debug('## Finish Booking_Refresh_YTD_Revenue_Batch ##');
        
       // Get the ID of the AsyncApexJob representing this batch job
       // from Database.BatchableContext.
       // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
                        FROM AsyncApexJob WHERE Id = :BC.getJobId()];                        
        
        // SFE-766 2016-01-05 darshan.gosar@bluewolfgroup.com 
            // Consolidate common function in Batch Utility class
        Batch_Utility.errorHandling(a, 'Booking Refresh YTD Revenue Batch');
                        
        // Roll-up revenue to Accounts
        AccountUpdateTcsTas_Batch att;

        this.query = 'Select s.Total_Gross_Price_Ytd__c, s.Payer_Account__c, s.Payer_Account__r.RecordType.Name, '
                     + 's.Advertiser_Account__c, s.Advertiser_Account__r.RecordType.Name, s.Total_Gross_Price_YTD_Last_Modified__c ' 
                     + 'From Sales_Order__c s';
        
        if(Test.isRunningTest())
            att = new AccountUpdateTcsTas_Batch(salesOrderIds, query);
        else
            att = new AccountUpdateTcsTas_Batch(null, query);

        Id batchProcessId = Database.executeBatch(att);

    }
}