News UAT/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Mark for Duplication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>CASE(TEXT(StageName),
  &quot;Identify Prospects&quot;, &quot;Open&quot;,
  &quot;Establish Rapport&quot;, &quot;Open&quot;,
  &quot;Qualify Opportunity&quot;, &quot;Open&quot;,
  &quot;Select Product(s) and Update Stage&quot;, &quot;Open&quot;,
  &quot;Develop Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Present Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Re-affirm Value/ Negotiate&quot;, &quot;Open&quot;,
  &quot;Awaiting Bookings&quot;, &quot;Open&quot;,
  &quot;Closed Won&quot;, &quot;Closed Won&quot;,
  &quot;Closed Lost&quot;, &quot;Closed Lost&quot;,
  &quot;Err: Invalid stage name&quot;
)</formula>
    <inlineHelpText>Field to allow reporting on Win/ Lost vs Open. Do not display on page layouts.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Fulfilment Ready</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Campaign Live</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Payment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Assigned_Fulfilment_Owner__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Fulfilment_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Fulfilment Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Product Orders</relationshipLabel>
    <relationshipName>Product_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Returned to CM</fullName>
            </value>
            <value>
                <fullName>Initial QA</fullName>
            </value>
            <value>
                <fullName>Peer review</fullName>
            </value>
            <value>
                <fullName>Peer review failed</fullName>
            </value>
            <value>
                <fullName>Ready to go live</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
            <value>
                <fullName>Cancellation Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/CS_LightningTransitionTest.cls
@isTest
private class CS_LightningTransitionTest {
    
    @testSetup static void setup() {
        // Set up test data
        Account sAccount = TestDataSetupClass.createAccount();
        insert sAccount;
        
        Contact sContact = TestDataSetupClass.createContact(sAccount);
        insert sContact;
        
        Opportunity sOpportunity = TestDataSetupClass.createOpportunity(sAccount, sContact);
        insert sOpportunity;
        
        Order__c sOrder = TestDataSetupClass.createOrder(sOpportunity);
        insert sOrder;
        
        Product_Order__c sProductOrder = new Product_Order__c(
            Assigned_Fulfilment_Owner__c = UserInfo.getUserId(),
            Order__c = sOrder.Id,
            Status__c = 'In Progress');
        insert sProductOrder;
		
		Payment__c sPayment = new Payment__c(
			Name = 'Test Payment',
			Order__c = sOrder.Id);
		insert sPayment;
    }
    
    
    @isTest
    static void testStartPOFulfilment() {
        Product_Order__c sProductOrder = [SELECT ID From Product_Order__c LIMIT 1];
        
        //test start fulfilment PO
        Boolean startFulfilmentResult = Start_Fulfilment_Product_Order.updateOrder(String.valueOf(sProductOrder.Id));
    }
    
    
    
    @isTest
    static void testPauseProductOrder() {
        Product_Order__c sProductOrder = [SELECT ID From Product_Order__c LIMIT 1];
        
        Boolean result = Pause_Product_Order_modalbox.updateOrder(String.valueOf(sProductOrder.Id));
    }
    
    @isTest
    static void testStartCancel_Product_Order_modalbox() {
        Product_Order__c sProductOrder = [SELECT ID From Product_Order__c LIMIT 1];
        
        Boolean result = Cancel_Product_Order_modalbox.updateOrder(String.valueOf(sProductOrder.Id));
    }

    
    @isTest
    static void testPause_Campaign_modalbox() {
        Order__c sOrder = [SELECT ID From Order__c LIMIT 1];
        
        Boolean result = Pause_Campaign_modalbox.updateOrder(String.valueOf(sOrder.Id));
    }
    @isTest
    static void testReturn_Campaign_to_Sales_ctrl() {
        Order__c sOrder = [SELECT ID From Order__c LIMIT 1];
        
        Boolean result = Return_Campaign_to_Sales_ctrl.updateOrder(String.valueOf(sOrder.Id));
        string strResult = Return_Campaign_to_Sales_ctrl.initClass(String.valueOf(sOrder.Id)); 
    }    
    @isTest
    static void testCancel_Order_modalbox() {
        //Order__c sOrder = [SELECT ID From Order__c LIMIT 1];
		Payment__c sPayment = [SELECT ID FROM Payment__c LIMIT 1];
        
        Boolean result = Cancel_Order_modalbox.updateOrder(String.valueOf(sPayment.Id));
    }
    
    
    @isTest
    static void testStart_Fulfilment() {
        Order__c sOrder = [SELECT ID From Order__c LIMIT 1];
        
        String result = Start_Fulfilment.Start_Fulfilment_mtd(String.valueOf(sOrder.Id));
    }
    

    
    @isTest
    static void testSchedule_payment_ctrl() {
        Opportunity sOpportunity = [SELECT ID From Opportunity LIMIT 1];
        
        String result = Schedule_payment_ctrl.schedulePayment(sOpportunity.Id);
    }
    
    @isTest
    static void testPriorityextension() {
        
        Order__c sOrder = [SELECT ID From Order__c LIMIT 1];
        Product_Order__c sProductOrder = [SELECT ID From Product_Order__c LIMIT 1];
        Opportunity sOpportunity = [SELECT ID From Opportunity LIMIT 1];
        
        
        Test.starttest();
        ApexPages.StandardController ctrl = new ApexPages.StandardController(sOrder);
        CS_CampaignPriorityExtension priority = new CS_CampaignPriorityExtension(ctrl);
        
        
        ApexPages.StandardController ctrlr = new ApexPages.StandardController(sProductOrder);
        CS_CampaignPriorityExtension prioritys = new CS_CampaignPriorityExtension(ctrlr);
        
        
        
        prioritys.executePriorityLogic('2 - Normal');
        prioritys.executePriorityLogic('3 - High');
        priority.executePriorityLogic('2 - Normal');
        priority.executePriorityLogic('3 - High');
        priority.executeHighPriorityLogic();
        priority.executeNormalPriorityLogic();
        
        Test.stoptest();
        
        
    } 
    
    @isTest
    static void testrecreate_tag() {
        
        Order__c sOrder = [SELECT ID From Order__c LIMIT 1];
        
        
        Test.starttest();
        
        ApexPages.StandardController controller = new ApexPages.StandardController(sOrder);
        recreate_tag rtag = new recreate_tag(controller);
        rtag.executeRecreateLogic();
        
        Test.stoptest();
    }
    @isTest
    static void TestCS_CampaignBriefFormExtension() {
        
        Order__c sOrder = [SELECT ID From Order__c LIMIT 1];
        
        Test.starttest();
        
        ApexPages.StandardController controller = new ApexPages.StandardController(sOrder);
        CS_CampaignBriefFormExtension rtag = new CS_CampaignBriefFormExtension(controller);
        rtag.creatOrViewBriefForm();
        
        Test.stoptest();
    }
}