News UAT/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Mark for Duplication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/NLM_Opportunity_Team_Member_1__c.field-meta.xml
<CustomField>
    <fullName>NLM_Opportunity_Team_Member_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used as approver by NLM Opportunity approval process</description>
    <label>NLM Opportunity Team Member 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunitiesTeam1</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/NLM_Opportunity_Team_Member_2__c.field-meta.xml
<CustomField>
    <fullName>NLM_Opportunity_Team_Member_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used as approver by NLM Opportunity approval process</description>
    <label>NLM Opportunity Team Member 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunitiesTeam2</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/NLM_Opportunity_Team_Member_3__c.field-meta.xml
<CustomField>
    <fullName>NLM_Opportunity_Team_Member_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used as approver by NLM Opportunity approval process</description>
    <label>NLM Opportunity Team Member 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunitiesTeam3</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>CASE(TEXT(StageName),
  &quot;Identify Prospects&quot;, &quot;Open&quot;,
  &quot;Establish Rapport&quot;, &quot;Open&quot;,
  &quot;Qualify Opportunity&quot;, &quot;Open&quot;,
  &quot;Select Product(s) and Update Stage&quot;, &quot;Open&quot;,
  &quot;Develop Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Present Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Re-affirm Value/ Negotiate&quot;, &quot;Open&quot;,
  &quot;Awaiting Bookings&quot;, &quot;Open&quot;,
  &quot;Closed Won&quot;, &quot;Closed Won&quot;,
  &quot;Closed Lost&quot;, &quot;Closed Lost&quot;,
  &quot;Err: Invalid stage name&quot;
)</formula>
    <inlineHelpText>Field to allow reporting on Win/ Lost vs Open. Do not display on page layouts.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Optimisation_Log__c/Optimisation_Log__c.object-meta.xml
<CustomObject>
    <label>Optimisation Log</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Optimisation Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Optimisation Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Optimisation_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Campaign_Order__r.Account__c</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Optimisation_Log__c/fields/Campaign_Order__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Optimisation Logs</relationshipLabel>
    <relationshipName>Optimisation_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Optimisation_Log__c/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Order</label>
    <referenceTo>Product_Order__c</referenceTo>
    <relationshipLabel>Optimisation Logs</relationshipLabel>
    <relationshipName>Optimisation_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Optimisation_Log__c/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>false</active>
    <label>Campaign</label>
</RecordType>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Assigned_Campaign_Manager__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Campaign_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Campaign Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Assigned_Campaign_Manager_For_QA__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Campaign_Manager_For_QA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Campaign Manager For QA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Assigned_Setup_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Setup_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Setup Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaign_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Optimisation_Log__c.field-meta.xml
<CustomField>
    <fullName>Optimisation_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Optimisation Log</label>
    <referenceTo>Optimisation_Log__c</referenceTo>
    <relationshipLabel>Campaign Orders</relationshipLabel>
    <relationshipName>Campaign_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Sales_Representative__c.field-meta.xml
<CustomField>
    <fullName>Sales_Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Representative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Fulfilment Ready</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Campaign Live</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/Product_Order__c.object-meta.xml
<CustomObject>
    <label>Product Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Product Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Order__r.Account__r.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Assigned_Campaign_Manager__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Campaign_Manager__c</fullName>
    <formula>IF( Order__r.Assigned_Campaign_Manager__c  &lt;&gt; null ,  Order__r.Assigned_Campaign_Manager__r.LastName &amp; &quot;, &quot; &amp; Order__r.Assigned_Campaign_Manager__r.FirstName , &#39;&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned Campaign Manager</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Assigned_Fulfilment_Owner__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Fulfilment_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Fulfilment Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Assigned_Fulfilment_Owner_For_QA__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Fulfilment_Owner_For_QA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Fulfilment Owner For QA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Assigned_Social_Owner__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Social_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Social Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Assigned_Social_Owner_For_QA__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Social_Owner_For_QA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Social Owner For QA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Orders3</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>Order__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Optimisation_Log__c.field-meta.xml
<CustomField>
    <fullName>Optimisation_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Optimisation Log</label>
    <referenceTo>Optimisation_Log__c</referenceTo>
    <relationshipLabel>Product Orders</relationshipLabel>
    <relationshipName>Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Product Orders</relationshipLabel>
    <relationshipName>Product_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Product_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Returned to CM</fullName>
            </value>
            <value>
                <fullName>Initial QA</fullName>
            </value>
            <value>
                <fullName>Peer review</fullName>
            </value>
            <value>
                <fullName>Peer review failed</fullName>
            </value>
            <value>
                <fullName>Ready to go live</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
            <value>
                <fullName>Cancellation Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/CS_OptimisationLogEntries_Test.cls
@isTest
private class CS_OptimisationLogEntries_Test {
	
	@isTest static void test_method_one() {

		Account acct = TestDataFactory.createSingleAccount(null, 0, null, 0, 0);
		insert acct;
		
		// create contact
		List<Contact> contacts = TestDataFactory.createContacts(1, acct);
		insert contacts;

		// create users
		List<User> users = TestDataFactory.createUsers(1, 'News Direct Sales Inbound', null, null, false);
		insert users;

		CSPOFA__Orchestration_Process_Template__c orchestrationProcessTemplate = new CSPOFA__Orchestration_Process_Template__c (
								Name = 'Campaign Setup'
			);
		insert orchestrationProcessTemplate;

		CSPOFA__Orchestration_Process__c orchestrationProcess = new CSPOFA__Orchestration_Process__c(
								Name = 'orchestrationProcess1',
								CSPOFA__Orchestration_Process_Template__c = orchestrationProcessTemplate.Id
							);
		insert orchestrationProcess;

		Opportunity opp = new Opportunity(
								Name = 'Test', 
								OwnerId = users[0].Id,
								AccountId = acct.Id, 
								StageName = 'Prospecting', 
								CloseDate = Date.today() + 5,
								NLM_Opportunity_Team_Member_1__c = users[0].Id,
								NLM_Opportunity_Team_Member_2__c = users[0].Id,
								NLM_Opportunity_Team_Member_3__c = users[0].Id
							);
		insert opp;

		Order__c campaignOrder = new Order__c (
								Account__c = acct.Id,
								OwnerId = users[0].Id,
								Assigned_Campaign_Manager__c = users[0].Id,
								Assigned_Campaign_Manager_For_QA__c = users[0].Id,
								Assigned_Setup_Coordinator__c = users[0].Id,
								Sales_Representative__c = users[0].Id,
								Opportunity__c = opp.Id
							);
		insert campaignOrder;


	/*	csmso__Product_Node__c prodNode = new csmso__Product_Node__c (
								Name = 'Product Node'
							);
		insert prodNode;
*/

		Product_Order__c prodOrder = new Product_Order__c(
								Status__c = 'Live',
								Order__c = campaignOrder.Id,
								Assigned_Fulfilment_Owner__c = users[0].Id,
								Assigned_Fulfilment_Owner_For_QA__c = users[0].Id,
								Assigned_Social_Owner__c = users[0].Id,
								Assigned_Social_Owner_For_QA__c = users[0].Id
						);
		insert prodOrder;


		Task task = new Task (	Subject = 'Compile Summary Of Optimisations',
								Item_Proposed_Start_Date__c = Date.today().AddDays(1),
								Status = 'Not Started',
								Completed_Date_Time__c = Date.today().AddDays(10),
								Campaign_Order__c = campaignOrder.Id,
								Product_Order__c = prodOrder.Id,
								ActivityDate = Date.today().addDays(-1)
							);
		insert task;


		CSPOFA__Orchestration_Step__c orchestrationStep = new CSPOFA__Orchestration_Step__c (
								Name = 'Opportunity Check',
								CSPOFA__Orchestration_Process__c = orchestrationProcess.Id,
								CSPOFA__Related_Object_ID__c = ''+task.Id,
								CSPOFA__Status__c = 'Initializing',
								CSPOFA__Message__c = 'orchestrationStep message'
							);
		insert orchestrationStep;


		task.CSPOFA__Orchestration_Step__c = orchestrationStep.Id;
		update task;

		Optimisation_Log__c optimisationLog = new Optimisation_Log__c(
								Goal_Of_Change__c = 'Margin Management',
								Comments__c = 'Test Data Comment'
							);
		insert optimisationLog;

		List<String> mentionList = new List<String>();
		mentionList.add(users[0].Id);


		Test.startTest();

		CS_OptimisationLogEntries_Controller ctrl = new CS_OptimisationLogEntries_Controller();
		ctrl.optimisationIdTaskMap.put(task.Id,task);
		ctrl.submitLogTaskId = task.Id;
		ctrl.submitLogMentions=users[0].Id;
		ctrl.onChangeUpdateLogEntry = '';
		ctrl.onChangeUpdateTaskId = task.Id;
		ctrl.onChangeUpdateActionGoal = '';
		ctrl.submitLogEntry = 'Test Comment';
		ctrl.submitActionGoal = 'Test submitActionGoal';


		ctrl.getOptimisationTaskWrapperList();
		ctrl.getOptimisationTaskWrapperList();
		ctrl.getActionGoalItems();
		ctrl.submitLog();
		ctrl.UpdateMentionsInnWrapper();
		ctrl.UpdateLogEntryInWrapper();
		ctrl.UpdateActionGoalInWrapper();


		Test.stopTest();



	}
}