News UAT/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Mark for Duplication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Account/recordTypes/IMA.recordType-meta.xml
<RecordType>
    <fullName>IMA</fullName>
    <active>true</active>
    <description>Independent Agencies &amp; Major Accounts team</description>
    <label>IMA</label>
</RecordType>

News UAT/force-app/main/default/objects/Account/recordTypes/IMA_Independent_Agencies.recordType-meta.xml
<RecordType>
    <fullName>IMA_Independent_Agencies</fullName>
    <active>false</active>
    <description>Independent Agencies</description>
    <label>IMA - Independent Agencies</label>
</RecordType>

News UAT/force-app/main/default/objects/Account/recordTypes/IMA_Major_Account.recordType-meta.xml
<RecordType>
    <fullName>IMA_Major_Account</fullName>
    <active>false</active>
    <description>Major Account</description>
    <label>IMA - Major Account</label>
</RecordType>

News UAT/force-app/main/default/objects/Account/recordTypes/KAC.recordType-meta.xml
<RecordType>
    <fullName>KAC</fullName>
    <active>true</active>
    <description>Key Accounts &amp; Consortium team</description>
    <label>KAC</label>
</RecordType>

News UAT/force-app/main/default/objects/Account/recordTypes/KAC_Consortium.recordType-meta.xml
<RecordType>
    <fullName>KAC_Consortium</fullName>
    <active>false</active>
    <description>Consortium</description>
    <label>KAC - Consortium</label>
</RecordType>

News UAT/force-app/main/default/objects/Account/recordTypes/KAC_Key_Account.recordType-meta.xml
<RecordType>
    <fullName>KAC_Key_Account</fullName>
    <active>false</active>
    <description>Key Account</description>
    <label>KAC - Key Account</label>
</RecordType>

News UAT/force-app/main/default/objects/Account/recordTypes/Real_Estate.recordType-meta.xml
<RecordType>
    <fullName>Real_Estate</fullName>
    <active>true</active>
    <description>Real Estate team</description>
    <label>Real Estate</label>
</RecordType>

News UAT/force-app/main/default/objects/Account/recordTypes/SME.recordType-meta.xml
<RecordType>
    <fullName>SME</fullName>
    <active>true</active>
    <description>Small to Medium Enterprises team</description>
    <label>SME</label>
</RecordType>

News UAT/force-app/main/default/objects/Account/recordTypes/The_Aus_Regional.recordType-meta.xml
<RecordType>
    <fullName>The_Aus_Regional</fullName>
    <active>true</active>
    <description>The Australian or Regional teams</description>
    <label>The Aus/Regional</label>
</RecordType>

News UAT/force-app/main/default/objects/NextGen_Account_Type__mdt/NextGen_Account_Type__mdt.object-meta.xml
<CustomObject>
    <label>NextGen Account Type</label>
    <pluralLabel>NextGen Account Types</pluralLabel>
</CustomObject>

News UAT/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>CASE(TEXT(StageName),
  &quot;Identify Prospects&quot;, &quot;Open&quot;,
  &quot;Establish Rapport&quot;, &quot;Open&quot;,
  &quot;Qualify Opportunity&quot;, &quot;Open&quot;,
  &quot;Select Product(s) and Update Stage&quot;, &quot;Open&quot;,
  &quot;Develop Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Present Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Re-affirm Value/ Negotiate&quot;, &quot;Open&quot;,
  &quot;Awaiting Bookings&quot;, &quot;Open&quot;,
  &quot;Closed Won&quot;, &quot;Closed Won&quot;,
  &quot;Closed Lost&quot;, &quot;Closed Lost&quot;,
  &quot;Err: Invalid stage name&quot;
)</formula>
    <inlineHelpText>Field to allow reporting on Win/ Lost vs Open. Do not display on page layouts.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/recordTypes/IMA.recordType-meta.xml
<RecordType>
    <fullName>IMA</fullName>
    <active>true</active>
    <businessProcess>NextGen</businessProcess>
    <description>Independent Agencies &amp; Major Accounts team</description>
    <label>IMA</label>
</RecordType>

News UAT/force-app/main/default/objects/Opportunity/recordTypes/KAC.recordType-meta.xml
<RecordType>
    <fullName>KAC</fullName>
    <active>true</active>
    <businessProcess>NextGen</businessProcess>
    <description>Key Accounts &amp; Consortium team</description>
    <label>KAC</label>
</RecordType>

News UAT/force-app/main/default/objects/Opportunity/recordTypes/Real_Estate.recordType-meta.xml
<RecordType>
    <fullName>Real_Estate</fullName>
    <active>true</active>
    <businessProcess>NextGen</businessProcess>
    <description>Real Estate team</description>
    <label>Real Estate</label>
</RecordType>

News UAT/force-app/main/default/objects/Opportunity/recordTypes/SME.recordType-meta.xml
<RecordType>
    <fullName>SME</fullName>
    <active>true</active>
    <businessProcess>NextGen</businessProcess>
    <description>Small to Medium Enterprises team</description>
    <label>SME</label>
</RecordType>

News UAT/force-app/main/default/objects/Opportunity/recordTypes/The_Aus_Regional.recordType-meta.xml
<RecordType>
    <fullName>The_Aus_Regional</fullName>
    <active>true</active>
    <businessProcess>NextGen</businessProcess>
    <description>The Australian or Regional teams</description>
    <label>The Aus/Regional</label>
</RecordType>

News UAT/force-app/main/default/classes/AT_LowSpendCustomers.cls
public class AT_LowSpendCustomers {
    public class AccountSpend implements Comparable {
        @AuraEnabled
        public Id Id {get; set;}
        @AuraEnabled
        public String Name {get; set;}
        @AuraEnabled
        public String Link {get; set;}
        @AuraEnabled
        public Decimal CurrentFY {get; set;}
        @AuraEnabled
        public Decimal PreviousFY {get; set;}
        @AuraEnabled
        public Decimal Difference {get; set;}
        
        public Integer compareTo(Object to) {
            AccountSpend other = (AccountSpend)to;
            
            if (this.Difference > other.Difference) {
                return -1;
            } else if (this.Difference < other.Difference) {
                return 1;
            } else {
                return 0;
            }
        }
    }    
    
    @AuraEnabled
    public static List<AccountSpend> getSpending(Id ownerID, Integer count) {
        Integer max = Integer.valueOf(count);
        
        //List<String> recordTypeNames = new List<String>{'IMA_Independent_Agencies','IMA_Major_Account','KAC_Consortium','KAC_Key_Account','IMA','KAC','Real_Estate','SME','The_Aus_Regional'};
        Set<String> accountTypes =  new Set<String>();
        
        for (NextGen_Account_Type__mdt accType: [SELECT DeveloperName FROM NextGen_Account_Type__mdt]) {
            accountTypes.add(accType.DeveloperName);
        }
        
        List<RecordType> accountRTs = [SELECT Id FROM RecordType WHERE (SObjectType = 'Account') AND (DeveloperName IN :accountTypes)];
            
        Set<Id> roleIDs = AT_AccessUtil.getCurrentUserRoleAndSubordinates();
        
        //List<Account> accs = [SELECT Id, Name FROM Account WHERE (OwnerId = :ownerID) OR (Owner.UserRoleId IN :roleIDs)];

        Integer currentMonth = System.today().month();
        
        List<AggregateResult> lastOpps;
        
        List<AggregateResult> currentOpps;
        
        //System.debug('Current month: ' + currentMonth);
        
        Set<Id> accountIDs = new Set<Id>();
        
        if (currentMonth >= 7) {
            currentOpps = [SELECT AccountId, SUM(Amount) total FROM Opportunity WHERE (CloseDate = THIS_FISCAL_YEAR) AND (CALENDAR_MONTH(CloseDate) <= :currentMonth) AND (AccountId IN (SELECT Id FROM Account WHERE (RecordTypeId IN :accountRTs) AND (Status__c = 'Active') AND ((OwnerId = :ownerID) OR (Owner.UserRoleId IN :roleIDs)))) GROUP BY AccountId];
            
            //System.debug('Current FY Opps: ' + currentOpps.size());
            
            for (AggregateResult agg: currentOpps) accountIDs.add((Id)agg.get('AccountId'));
        	
            lastOpps = [SELECT AccountId, SUM(Amount) total FROM Opportunity WHERE (AccountId IN :accountIDs) AND (CloseDate = LAST_FISCAL_YEAR) AND (CALENDAR_MONTH(CloseDate) <= :currentMonth) GROUP BY AccountId];
            
            //System.debug('Last FY Opps: ' + lastOpps.size());
        } else {
            currentOpps = [SELECT AccountId, SUM(Amount) total FROM Opportunity WHERE (AccountId IN (SELECT Id FROM Account WHERE (RecordTypeId IN :accountRTs) AND (Status__c = 'Active') AND ((OwnerId = :ownerID) OR (Owner.UserRoleId IN :roleIDs)))) AND (CloseDate = THIS_FISCAL_YEAR) AND ((CALENDAR_MONTH(CloseDate) >= 7) OR (CALENDAR_MONTH(CloseDate) <= :currentMonth)) GROUP BY AccountId];
            
            //System.debug('Current FY Opps: ' + currentOpps.size());
            
            for (AggregateResult agg: currentOpps) accountIDs.add((Id)agg.get('AccountId'));
            
            lastOpps = [SELECT AccountId, SUM(Amount) total FROM Opportunity WHERE (AccountId IN :accountIDs) AND (CloseDate = LAST_FISCAL_YEAR) AND ((CALENDAR_MONTH(CloseDate) >= 7) OR (CALENDAR_MONTH(CloseDate) <= :currentMonth)) GROUP BY AccountId];
            
            //System.debug('Last FY Opps: ' + lastOpps.size());
        }
        
        //if ((lastOpps != null) && !lastOpps.isEmpty()) for (AggregateResult agg: lastOpps) https://newscorpaustralia--adsalesuat.cs58.my.salesforce.com/_ui/common/apex/debug/ApexCSIPage#
        
        //if ((currentOpps != null) && !currentOpps.isEmpty()) for (AggregateResult agg: currentOpps) accountIDs.add((Id)opp.get('AccountId'));
        
        /*if (currentMonth >= 7) {
            lastOpps = [SELECT AccountId, Account.Name, SUM(Amount) total FROM Opportunity WHERE (AccountId IN :accs) AND (CloseDate = LAST_FISCAL_YEAR) AND (CALENDAR_MONTH(CloseDate) <= :currentMonth) GROUP BY AccountId];
            currentOpps = [SELECT AccountId, Account.Name, SUM(Amount) total FROM Opportunity WHERE (AccountId IN :accs) AND (CloseDate = THIS_FISCAL_YEAR) AND (CALENDAR_MONTH(CloseDate) <= :currentMonth) GROUP BY AccountId];
        } else {
            lastOpps = [SELECT AccountId, Account.Name, SUM(Amount) total FROM Opportunity WHERE (AccountId IN :accs) AND (CloseDate = LAST_FISCAL_YEAR) AND ((CALENDAR_MONTH(CloseDate) >= 7) OR (CALENDAR_MONTH(CloseDate) <= :currentMonth)) GROUP BY AccountId];
            currentOpps = [SELECT AccountId, Account.Name, SUM(Amount) total FROM Opportunity WHERE (AccountId IN :accs) AND (CloseDate = THIS_FISCAL_YEAR) AND ((CALENDAR_MONTH(CloseDate) >= 7) OR (CALENDAR_MONTH(CloseDate) <= :currentMonth)) GROUP BY AccountId];
        }*/

		//
        
        Map<Id, Decimal> lastSpend = new Map<Id, Decimal>();
        Map<Id, Decimal> currentSpend = new Map<Id, Decimal>();
        
        for (AggregateResult agg: lastOpps) {
            lastSpend.put((Id)agg.get('AccountId'), (Decimal)agg.get('total'));
            //accountIDs.add((Id)agg.get('AccountId'));
        }
        
        for (AggregateResult agg: currentOpps) {
            currentSpend.put((Id)agg.get('AccountId'), (Decimal)agg.get('total'));
            //accountIDs.add((Id)agg.get('AccountId'));
        }
        
        List<AccountSpend> spending = new List<AccountSpend>();
        
        for (Account acc: [SELECT Id, Name FROM Account WHERE (Id IN :accountIDs)]) {
            Decimal last = lastSpend.get(acc.Id);
            Decimal current = currentSpend.get(acc.Id);

            if (last == null) last = 0.0;
            if (current == null) current = 0.0;
            
            if (last > current) {
                AccountSpend spend = new AccountSpend();
                    
                spend.Id    = acc.Id;
                spend.Name  = acc.Name;
                spend.Link  = '/' + acc.Id;
                spend.Difference = last - current;
                spend.PreviousFY = last;
                spend.CurrentFY = current;
                    
                spending.add(spend);
            }
        }
        
        spending.sort();
        
        List<AccountSpend> selected = new List<AccountSpend>();
        
        Integer total = (spending.size() > max) ? max : spending.size();
        
        for (Integer i = 0; i < total; i++) selected.add(spending[i]);

        return selected;
    }
}