News UAT/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Mark for Duplication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>CASE(TEXT(StageName),
  &quot;Identify Prospects&quot;, &quot;Open&quot;,
  &quot;Establish Rapport&quot;, &quot;Open&quot;,
  &quot;Qualify Opportunity&quot;, &quot;Open&quot;,
  &quot;Select Product(s) and Update Stage&quot;, &quot;Open&quot;,
  &quot;Develop Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Present Solution/ Proposal&quot;, &quot;Open&quot;,
  &quot;Re-affirm Value/ Negotiate&quot;, &quot;Open&quot;,
  &quot;Awaiting Bookings&quot;, &quot;Open&quot;,
  &quot;Closed Won&quot;, &quot;Closed Won&quot;,
  &quot;Closed Lost&quot;, &quot;Closed Lost&quot;,
  &quot;Err: Invalid stage name&quot;
)</formula>
    <inlineHelpText>Field to allow reporting on Win/ Lost vs Open. Do not display on page layouts.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Orders related to sales order</description>
    <label>Campaign Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Order__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Change In Business</fullName>
            </value>
            <value>
                <fullName>Client Perceived ROI</fullName>
            </value>
            <value>
                <fullName>Customer Service Issue</fullName>
            </value>
            <value>
                <fullName>Moving to Another Provider (specify below)</fullName>
            </value>
            <value>
                <fullName>Package Adjustment</fullName>
            </value>
            <value>
                <fullName>Seasonal Campaign Booked as Evergreen</fullName>
            </value>
            <value>
                <fullName>Upsell</fullName>
            </value>
            <value>
                <fullName>Downsell</fullName>
            </value>
            <value>
                <fullName>Financial Difficulty</fullName>
            </value>
            <value>
                <fullName>Achieved Desired Outcome</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Billing Period End Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Fulfilment Started</fullName>
            </value>
            <value>
                <fullName>Fulfilment Ready</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Campaign Live</fullName>
            </value>
            <value>
                <fullName>Pending For Pause</fullName>
            </value>
            <value>
                <fullName>Pending For Cancel</fullName>
            </value>
            <value>
                <fullName>Campaign Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Payment__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Change in Business</fullName>
            </value>
            <value>
                <fullName>Client perceived ROI</fullName>
            </value>
            <value>
                <fullName>Customer Service Issue</fullName>
            </value>
            <value>
                <fullName>Moving to Another Provider (specify below)</fullName>
            </value>
            <value>
                <fullName>Package Adjustment</fullName>
            </value>
            <value>
                <fullName>Seasonal Campaign booked as Evergreen</fullName>
            </value>
            <value>
                <fullName>Upsell</fullName>
            </value>
            <value>
                <fullName>Downsell</fullName>
            </value>
            <value>
                <fullName>Financial Difficulty</fullName>
            </value>
            <value>
                <fullName>Achieved Desired Outcome</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/fields/Last_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_End_Date__c</fullName>
    <label>Last End Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/fields/Last_Scheduled_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Scheduled_End_Date__c</fullName>
    <description>Populated when latest Payment Schedule status = scheduled. Used to determine if there is an overpayment and needs to be refunded.</description>
    <label>Last Scheduled End Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/fields/Last_Scheduled_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Scheduled_Start_Date__c</fullName>
    <label>Last Scheduled Start Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Line_Item__c/Payment_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Line Item</label>
    <nameField>
        <label>Payment Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Payment_Line_Item__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Line_Item__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <label>Payment Schedule</label>
    <referenceTo>Payment_Schedule__c</referenceTo>
    <relationshipLabel>Payment Line Items</relationshipLabel>
    <relationshipName>Payment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Credit Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Payment Schedule</label>
    <nameField>
        <label>Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Payment_Schedule__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Schedule__c/fields/Schedule_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_End_Date__c</fullName>
    <label>Schedule End Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Schedule__c/fields/Schedule_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Start_Date__c</fullName>
    <label>Schedule Start Date</label>
    <type>Date</type>
</CustomField>

News UAT/force-app/main/default/objects/Payment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Campaign Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

News UAT/force-app/main/default/classes/CS_PaymentCancellationHelperTest.cls
@isTest
public class CS_PaymentCancellationHelperTest {
    
    @isTest
    public static void paymentCancellation()
    {
    	Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        insert acc;
        
        Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today());
        insert opp;
        
        Order__c order = TestDataSetupClass.createOrder(opp);
        insert order;
        
        Payment__c payment = TestDataSetupClass.createPayment(order);
        payment.End_Date__c = System.today().addMonths(3);
        payment.Last_End_Date__c = System.today().addMonths(2).addDays(-1);
        payment.Cancellation_Reason__c='Client perceived ROI';
        insert payment;
        system.debug('payment-->'+payment);
        
        Payment_Schedule__c paymentSch1 = TestDataSetupClass.createPaymentSch(payment);
		Date myStartDate = Date.newInstance(2019, 1, 1);
		Date myEndDate = Date.newInstance(2019, 2, 17);
		Date myStartDate1 = Date.newInstance(2019, 2, 1);
		Date myEndDate1 = Date.newInstance(2019, 2, 26);
        //paymentSch1.Schedule_Start_Date__c = System.today();
        //paymentSch1.Schedule_End_Date__c = System.today().addMonths(4);
		paymentSch1.Schedule_Start_Date__c = myStartDate;
        paymentSch1.Schedule_End_Date__c = myEndDate;
        paymentSch1.Status__c = 'Pending';
        paymentSch1.Billing_Date__c = System.now().date().addMonths(1).toStartofMonth().addDays(-1);
        insert paymentSch1;
        
        Map<Id, Date> testmap = new Map<Id, Date>();
        testmap.put(payment.id,System.today());
        List<Payment__c> paymentList = new List<Payment__c>();
        List<Payment_Schedule__c> paymentSchList = new List<Payment_Schedule__c>();
        paymentList.add(payment);
        paymentSchList.add(paymentSch1);
        
        Test.startTest();
        CS_PaymentCancellationHelper payCancel = new CS_PaymentCancellationHelper();
        CS_PaymentCancellationHelper.calculateNumberOfPaymentSchedulesRequired(paymentList,paymentSchList);
        CS_PaymentCancellationHelper.getLastPaymentSchedule(paymentList,paymentSchList);
        CS_PaymentCancellationHelper.createPaymentSchedulesForPaymentCancellation(paymentList);
        CS_PaymentCancellationHelper.getPaymentScheduleForPayments(paymentList);
        CS_PaymentCancellationHelper.activateAndCancelPaymentSchedules(paymentList);
        CS_PaymentCancellationHelper.proRatePaymentSchedules(paymentList,paymentSchList,testmap);
		paymentSch1.Schedule_Start_Date__c = myStartDate1;
        paymentSch1.Schedule_End_Date__c = myEndDate1;
		CS_PaymentCancellationHelper.createPaymentSchedulesForPaymentCancellation(paymentList);
        Test.stopTest();  
    }
    
    @isTest
    public static void endDate_2()
    {
    	Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        insert acc;
        
        Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today());
        insert opp;
        
        Order__c order = TestDataSetupClass.createOrder(opp);
        insert order;
        
        Payment__c payment = TestDataSetupClass.createPayment(order);
        payment.End_Date__c = System.today().addMonths(3);
        payment.Last_End_Date__c = System.today().addMonths(2).addDays(-1);
        payment.Cancellation_Reason__c='Client perceived ROI';
        insert payment;
        system.debug('payment-->'+payment);
        
        Payment_Schedule__c paymentSch1 = TestDataSetupClass.createPaymentSch(payment);
        paymentSch1.Schedule_Start_Date__c = System.today();
        paymentSch1.Schedule_End_Date__c = System.today().addMonths(5);
        paymentSch1.Status__c = 'Pending';
		paymentSch1.Billing_Date__c = System.now().date().addMonths(1).toStartofMonth().addDays(-1);
        insert paymentSch1;
        
        Payment_Line_Item__c paymentLI = TestDataSetupClass.createPaymentLineItem(paymentSch1);
		insert paymentLI;
        
        Map<Id, Date> testmap = new Map<Id, Date>();
        testmap.put(payment.id,System.today());
        List<Payment__c> paymentList = new List<Payment__c>();
        List<Payment_Schedule__c> paymentSchList = new List<Payment_Schedule__c>();
        paymentList.add(payment);
        paymentSchList.add(paymentSch1);
        
        Test.startTest();
        CS_PaymentCancellationHelper payCancel = new CS_PaymentCancellationHelper();
        CS_PaymentCancellationHelper.calculateNumberOfPaymentSchedulesRequired(paymentList,paymentSchList);
        CS_PaymentCancellationHelper.getLastPaymentSchedule(paymentList,paymentSchList);
        CS_PaymentCancellationHelper.createPaymentSchedulesForPaymentCancellation(paymentList);
        CS_PaymentCancellationHelper.getPaymentScheduleForPayments(paymentList);
        //CS_PaymentCancellationHelper.activateAndCancelPaymentSchedules(paymentList);
        CS_PaymentCancellationHelper.proRatePaymentSchedules(paymentList,paymentSchList,testmap);
        Test.stopTest();  
    }
    
    @isTest
    public static void startDate_2()
    {
    	Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        insert acc;
        
        Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today());
        insert opp;
        
        Order__c order = TestDataSetupClass.createOrder(opp);
        insert order;
        
        Payment__c payment = TestDataSetupClass.createPayment(order);
        payment.End_Date__c = System.today().addMonths(3);
        payment.Last_End_Date__c = System.today().addMonths(2).addDays(-1);
        payment.Cancellation_Reason__c='Client perceived ROI';
        insert payment;
        system.debug('payment-->'+payment);
        
        Payment_Schedule__c paymentSch1 = TestDataSetupClass.createPaymentSch(payment);
        paymentSch1.Schedule_Start_Date__c = System.today().addMonths(5);
        paymentSch1.Schedule_End_Date__c = System.today().addMonths(7);
        paymentSch1.Status__c = 'Pending';
        paymentSch1.Billing_Date__c = System.now().date().addMonths(1).toStartofMonth().addDays(-1);
        insert paymentSch1;
        
        Payment_Line_Item__c paymentLI = TestDataSetupClass.createPaymentLineItem(paymentSch1);
        insert paymentLI;
        
        Map<Id, Date> testmap = new Map<Id, Date>();
        testmap.put(payment.id,System.today());
        List<Payment__c> paymentList = new List<Payment__c>();
        List<Payment_Schedule__c> paymentSchList = new List<Payment_Schedule__c>();
        paymentList.add(payment);
        paymentSchList.add(paymentSch1);
        
        Test.startTest();
        CS_PaymentCancellationHelper payCancel = new CS_PaymentCancellationHelper();
        CS_PaymentCancellationHelper.calculateNumberOfPaymentSchedulesRequired(paymentList,paymentSchList);
        CS_PaymentCancellationHelper.getLastPaymentSchedule(paymentList,paymentSchList);
        CS_PaymentCancellationHelper.createPaymentSchedulesForPaymentCancellation(paymentList);
        CS_PaymentCancellationHelper.getPaymentScheduleForPayments(paymentList);
        //CS_PaymentCancellationHelper.activateAndCancelPaymentSchedules(paymentList);
        CS_PaymentCancellationHelper.proRatePaymentSchedules(paymentList,paymentSchList,testmap);
        Test.stopTest();  
    }

   /* @isTest
    public static void startDateGreater()
    {
    	Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        insert acc;
        
        Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today());
        insert opp;
        
        Order__c order = TestDataSetupClass.createOrder(opp);
        insert order;
        
        Payment__c payment = TestDataSetupClass.createPayment(order);
        payment.End_Date__c = System.today().addMonths(3);
        payment.Last_End_Date__c = System.today().addMonths(2).addDays(-1);
        insert payment;
        system.debug('payment-->'+payment);
        
        Payment_Schedule__c paymentSch1 = TestDataSetupClass.createPaymentSch(payment);
        paymentSch1.Schedule_Start_Date__c = System.today().addMonths(5);
        paymentSch1.Schedule_End_Date__c = System.today().addMonths(7);
        paymentSch1.Status__c = 'Pending';
        paymentSch1.Billing_Date__c = System.now().date().addMonths(1).toStartofMonth().addDays(-1);
        insert paymentSch1;
        
        Payment_Line_Item__c paymentLI = TestDataSetupClass.createPaymentLineItem(paymentSch1);
        insert paymentLI;
        
        Map<Id, Date> testmap = new Map<Id, Date>();
        testmap.put(payment.id,System.today());
        List<Payment__c> paymentList = new List<Payment__c>();
        List<Payment_Schedule__c> paymentSchList = new List<Payment_Schedule__c>();
        paymentList.add(payment);
        paymentSchList.add(paymentSch1);
        
        Test.startTest();
        CS_PaymentCancellationHelper payCancel = new CS_PaymentCancellationHelper();
        CS_PaymentCancellationHelper.calculateNumberOfPaymentSchedulesRequired(paymentList,paymentSchList);
        CS_PaymentCancellationHelper.getLastPaymentSchedule(paymentList,paymentSchList);
        CS_PaymentCancellationHelper.createPaymentSchedulesForPaymentCancellation(paymentList);
        CS_PaymentCancellationHelper.getPaymentScheduleForPayments(paymentList);
        CS_PaymentCancellationHelper.activateAndCancelPaymentSchedules(paymentList);
        CS_PaymentCancellationHelper.proRatePaymentSchedules(paymentList,paymentSchList,testmap);
        Test.stopTest();  
    }*/

    @isTest
    public static void endDate_LastSchDate()
    {
    	Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        insert acc;
        
        Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today());
        insert opp;
        
        Order__c order = TestDataSetupClass.createOrder(opp);
        insert order;
        
        Payment__c payment = TestDataSetupClass.createPayment(order);
        payment.End_Date__c = System.today().addMonths(3);
        payment.Last_End_Date__c = System.today().addMonths(2);
        payment.Last_Scheduled_End_Date__c = System.today().addMonths(7);
        payment.Cancellation_Reason__c='Client perceived ROI';
        insert payment;
        system.debug('payment-->'+payment);
        
        Payment_Schedule__c paymentSch1 = TestDataSetupClass.createPaymentSch(payment);
        paymentSch1.Schedule_Start_Date__c = System.today().addMonths(4);
        paymentSch1.Schedule_End_Date__c = System.today().addMonths(7);
        paymentSch1.Status__c = 'Pending';
        paymentSch1.Billing_Date__c = System.now().date().addMonths(1).toStartofMonth().addDays(-1);
        insert paymentSch1;
        
        Payment_Line_Item__c paymentLI = TestDataSetupClass.createPaymentLineItem(paymentSch1);
        paymentLI.List_Price__c = 200.50;
        insert paymentLI;
        
        Map<Id, Date> testmap = new Map<Id, Date>();
        testmap.put(payment.id,System.today().addMonths(5));
        List<Payment__c> paymentList = new List<Payment__c>();
        List<Payment_Schedule__c> paymentSchList = new List<Payment_Schedule__c>();
        paymentList.add(payment);
        paymentSchList.add(paymentSch1);
        
        Test.startTest();
        CS_PaymentCancellationHelper payCancel = new CS_PaymentCancellationHelper();
        CS_PaymentCancellationHelper.calculateNumberOfPaymentSchedulesRequired(paymentList,paymentSchList);
        CS_PaymentCancellationHelper.getLastPaymentSchedule(paymentList,paymentSchList);
        CS_PaymentCancellationHelper.createPaymentSchedulesForPaymentCancellation(paymentList);
        CS_PaymentCancellationHelper.getPaymentScheduleForPayments(paymentList);
       // CS_PaymentCancellationHelper.activateAndCancelPaymentSchedules(paymentList);
        CS_PaymentCancellationHelper.proRatePaymentSchedules(paymentList,paymentSchList,testmap);
        Test.stopTest();  
    }
    
    @isTest
    public static void lastPsFound_False()
    {
    	Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        insert acc;
        
        Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today());
        insert opp;
        
        Order__c order = TestDataSetupClass.createOrder(opp);
        insert order;
        
        Payment__c payment = TestDataSetupClass.createPayment(order);
        payment.End_Date__c = System.today().addMonths(3);
        payment.Last_End_Date__c = System.today().addMonths(2);
        payment.Last_Scheduled_End_Date__c = System.today().addMonths(5);
        payment.Last_Scheduled_Start_Date__c = System.today().addMonths(2);
        payment.Cancellation_Reason__c='Client perceived ROI';
        insert payment;
        system.debug('payment-->'+payment);
        
        Payment_Schedule__c paymentSch1 = TestDataSetupClass.createPaymentSch(payment);
        //paymentSch1.Schedule_Start_Date__c = System.today();
       // paymentSch1.Schedule_End_Date__c = System.today().addMonths(7);
        paymentSch1.Status__c = 'Pending';
        paymentSch1.Billing_Date__c = System.now().date().addMonths(1).toStartofMonth().addDays(-1);
        insert paymentSch1;
        
        Payment_Line_Item__c paymentLI = TestDataSetupClass.createPaymentLineItem(paymentSch1);
        paymentLI.List_Price__c = 200.50;
        insert paymentLI;
        
        Map<Id, Date> testmap = new Map<Id, Date>();
        testmap.put(payment.id,System.today().addMonths(5));
        List<Payment__c> paymentList = new List<Payment__c>();
        List<Payment_Schedule__c> paymentSchList = new List<Payment_Schedule__c>();
        paymentList.add(payment);
        paymentSchList.add(paymentSch1);
        
        Test.startTest();
        CS_PaymentCancellationHelper payCancel = new CS_PaymentCancellationHelper();
        CS_PaymentCancellationHelper.calculateNumberOfPaymentSchedulesRequired(paymentList,paymentSchList);
        CS_PaymentCancellationHelper.getLastPaymentSchedule(paymentList,paymentSchList);
        //CS_PaymentCancellationHelper.createPaymentSchedulesForPaymentCancellation(paymentList);
        CS_PaymentCancellationHelper.getPaymentScheduleForPayments(paymentList);
       // CS_PaymentCancellationHelper.activateAndCancelPaymentSchedules(paymentList);
        CS_PaymentCancellationHelper.proRatePaymentSchedules(paymentList,paymentSchList,testmap);
        Test.stopTest();  
    }
    
    @isTest
    public static void lastSchStartDate_2()
    {
    	Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        insert acc;
        
        Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today());
        insert opp;
        
        Order__c order = TestDataSetupClass.createOrder(opp);
        insert order;
        
        Payment__c payment = TestDataSetupClass.createPayment(order);
        payment.End_Date__c = System.today().addMonths(3);
        payment.Last_End_Date__c = System.today().addMonths(2);
        payment.Last_Scheduled_End_Date__c = System.today().addMonths(7);
        payment.Last_Scheduled_Start_Date__c = System.today().addMonths(5);
        payment.Cancellation_Reason__c='Client perceived ROI';
        insert payment;
        system.debug('payment-->'+payment);
        
        Payment_Schedule__c paymentSch1 = TestDataSetupClass.createPaymentSch(payment);
        //paymentSch1.Schedule_Start_Date__c = System.today();
        //paymentSch1.Schedule_End_Date__c = System.today().addMonths(7);
        paymentSch1.Status__c = 'Pending';
        paymentSch1.Billing_Date__c = System.now().date().addMonths(1).toStartofMonth().addDays(-1);
        insert paymentSch1;
        
        Payment_Line_Item__c paymentLI = TestDataSetupClass.createPaymentLineItem(paymentSch1);
        paymentLI.List_Price__c = 200.50;
        insert paymentLI;
        
        Map<Id, Date> testmap = new Map<Id, Date>();
        testmap.put(payment.id,System.today().addMonths(5));
        List<Payment__c> paymentList = new List<Payment__c>();
        List<Payment_Schedule__c> paymentSchList = new List<Payment_Schedule__c>();
        paymentList.add(payment);
        paymentSchList.add(paymentSch1);
        
        Test.startTest();
        CS_PaymentCancellationHelper payCancel = new CS_PaymentCancellationHelper();
        CS_PaymentCancellationHelper.calculateNumberOfPaymentSchedulesRequired(paymentList,paymentSchList);
        CS_PaymentCancellationHelper.getLastPaymentSchedule(paymentList,paymentSchList);
        //CS_PaymentCancellationHelper.createPaymentSchedulesForPaymentCancellation(paymentList);
        CS_PaymentCancellationHelper.getPaymentScheduleForPayments(paymentList);
       // CS_PaymentCancellationHelper.activateAndCancelPaymentSchedules(paymentList);
        CS_PaymentCancellationHelper.proRatePaymentSchedules(paymentList,paymentSchList,testmap);
        Test.stopTest();  
    }

    @isTest
    public static void lastSchStartDate_not2()
    {
    	Account acc = TestDataSetupClass.createAccount();
        RecordType rtypes = [Select Name, Id From RecordType where sObjectType='Account' and Name = 'Prospecting Account' and isActive=true];
        acc.RecordTypeId = rtypes.Id;
        insert acc;
        
        Opportunity opp = new Opportunity(name = 'testOpportunityForSalesOrderSupportTest', AccountId = acc.Id, StageName = 'testStage', CloseDate = System.today());
        insert opp;
        
        Order__c order = TestDataSetupClass.createOrder(opp);
        insert order;
        
        Payment__c payment = TestDataSetupClass.createPayment(order);
        payment.End_Date__c = System.today().addMonths(3);
        payment.Last_End_Date__c = System.today().addMonths(2);
        payment.Last_Scheduled_End_Date__c = System.today().addMonths(7);
        payment.Last_Scheduled_Start_Date__c = System.today().addMonths(6);
        payment.Cancellation_Reason__c='Client perceived ROI';
        insert payment;
        system.debug('payment-->'+payment);
        
        Payment_Schedule__c paymentSch1 = TestDataSetupClass.createPaymentSch(payment);
        paymentSch1.Schedule_Start_Date__c = System.today();
        paymentSch1.Schedule_End_Date__c = System.today().addMonths(7);
        paymentSch1.Status__c = 'Pending';
        paymentSch1.Billing_Date__c = System.now().date().addMonths(1).toStartofMonth().addDays(-1);
        insert paymentSch1;
        
        Payment_Line_Item__c paymentLI = TestDataSetupClass.createPaymentLineItem(paymentSch1);
        paymentLI.List_Price__c = 200.50;
        paymentLI.Type__c = 'Normal';
        insert paymentLI;
        
        Map<Id, Date> testmap = new Map<Id, Date>();
        testmap.put(payment.id,System.today().addMonths(5));
        List<Payment__c> paymentList = new List<Payment__c>();
        List<Payment_Schedule__c> paymentSchList = new List<Payment_Schedule__c>();
        paymentList.add(payment);
        paymentSchList.add(paymentSch1);
        
        Test.startTest();
        CS_PaymentCancellationHelper payCancel = new CS_PaymentCancellationHelper();
        CS_PaymentCancellationHelper.calculateNumberOfPaymentSchedulesRequired(paymentList,paymentSchList);
        CS_PaymentCancellationHelper.getLastPaymentSchedule(paymentList,paymentSchList);
        //CS_PaymentCancellationHelper.createPaymentSchedulesForPaymentCancellation(paymentList);
        CS_PaymentCancellationHelper.getPaymentScheduleForPayments(paymentList);
       // CS_PaymentCancellationHelper.activateAndCancelPaymentSchedules(paymentList);
        CS_PaymentCancellationHelper.proRatePaymentSchedules(paymentList,paymentSchList,testmap);
        Test.stopTest();  
    }

}