News UAT/force-app/main/default/objects/Account/fields/Total_Agency_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Agency_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Agency Spend - rolled up from all Bookings where the Agency is the Payer (YTD)</description>
    <inlineHelpText>Total Agency Spend - rolled up from all Bookings where the Agency is the Payer (YTD)</inlineHelpText>
    <label>Total Agency Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Total_Customer_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Customer_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Customer Spend - rolled up from Total Cost of all Bookings related to the Customer (YTD)</description>
    <inlineHelpText>Total Customer Spend - rolled up from Total Cost of all Bookings related to the Customer (YTD)</inlineHelpText>
    <label>Total Customer Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Account/fields/Total_Group_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Group_Spend__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Group Spend for the Customer/Agency Hierarchy (this Customer and all below) for all Bookings (YTD)</description>
    <inlineHelpText>Total Group Spend for the Customer/Agency Hierarchy (this Customer and all below) for all Bookings (YTD)</inlineHelpText>
    <label>Total Group Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Shell Order encompassing Booking(s) - to be related to an Opportunity Product/s</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{0000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Advertiser_Account__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advertiser Account</description>
    <label>Advertiser Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders_Advertiser</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Payer_Account__c.field-meta.xml
<CustomField>
    <fullName>Payer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payer Account</description>
    <inlineHelpText>Payer – The account that pays for the advertising.</inlineHelpText>
    <label>Payer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders (Payer Account)</relationshipLabel>
    <relationshipName>Sales_Orders_Payer</relationshipName>
    <type>Lookup</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Total_Gross_Price_Ytd__c.field-meta.xml
<CustomField>
    <fullName>Total_Gross_Price_Ytd__c</fullName>
    <label>Total Gross Price YTD</label>
    <summarizedField>Booking__c.Line_Item_Gross_Price_YTD__c</summarizedField>
    <summaryForeignKey>Booking__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

News UAT/force-app/main/default/objects/Sales_Order__c/fields/Total_Gross_Price_YTD_Last_Modified__c.field-meta.xml
<CustomField>
    <fullName>Total_Gross_Price_YTD_Last_Modified__c</fullName>
    <description>last modified datetime for total gross price YTD</description>
    <label>Total Gross Price YTD Last Modified</label>
    <type>DateTime</type>
</CustomField>

News UAT/force-app/main/default/classes/AccountSpendingReset_Batch.cls
/*---------------------------------------------------------
* Author: Bohao Chen
* Company: Bluewolf
* Description: This batch is to reset total customer/agency/group spendings for accounts. 
*				It's part of solution for JIRA SFE-4. We need to reset spendings before any calculation for all accounts
* History:
* 26/05/2014   Bohao Chen  Created
---------------------------------------------------------*/
global class AccountSpendingReset_Batch implements Database.Batchable<sObject>, Database.Stateful {
    
    String query;
    Map<String, List<String>> errorMessageByFailedAccountId;
    
    global AccountSpendingReset_Batch() 
    {		
        this.query = 'Select Total_Agency_Spend__c, Total_Customer_Spend__c, Total_Group_Spend__c '
            + 'From Account '
            + 'Where Total_Agency_Spend__c > 0'
            + 'OR Total_Customer_Spend__c > 0 '
            + 'OR Total_Group_Spend__c > 0';
        
        errorMessageByFailedAccountId = new Map<String, List<String>>();
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope) 
    {
        List<Account> accounts = (List<Account>)scope;
        
        // reset spendings if they are greater than 0
        for(Account a : accounts)
        {
            if(a.Total_Agency_Spend__c > 0)
                a.Total_Agency_Spend__c = 0;
            
            if(a.Total_Customer_Spend__c > 0)
                a.Total_Customer_Spend__c = 0;
            
            if(a.Total_Group_Spend__c > 0)
                a.Total_Group_Spend__c = 0;
        }
        
        // update accounts
        List<Database.SaveResult> saveResults = Database.update(accounts, false);
        
        // generate detail error messages if there is a failure
        errorMessageByFailedAccountId = AccountBatch_Helper.generateErrorMessagesForAccounts(saveResults, accounts, errorMessageByFailedAccountId);
    }
    
    global void finish(Database.BatchableContext BC) 
    {
        if(errorMessageByFailedAccountId.size() > 0)
        {
            // Send an email to admin to notify this issue
            AccountBatch_Helper.sendBatchErrorMessages(errorMessageByFailedAccountId, 'AccountSpendingReset_Batch');
        }
        else
        {
            // run batch to populate TCS and TAS on accounts
            String query = 'Select s.Total_Gross_Price_Ytd__c, s.Payer_Account__c, s.Payer_Account__r.RecordType.Name, '
                + 's.Advertiser_Account__c, s.Advertiser_Account__r.RecordType.Name, s.Total_Gross_Price_YTD_Last_Modified__c ' 
                + 'From Sales_Order__c s';
            
            AccountUpdateTcsTas_Batch accountUpdateTcsTas = new AccountUpdateTcsTas_Batch(null, query);
            ID batchProcessId = Database.executeBatch(accountUpdateTcsTas);
            System.debug(logginglevel.error, 'Returned batch process ID: ' + batchProcessId);
        }
        
    }
    
}